### PR TITLE
Fixes #20960 - update activerecord-session_store to 1.1.0

### PR DESCRIPTION
**Pull request by mmoll**
this should be built into:

* [x] Nightly

### CODE REVIEW

**Comment by mmoll** [comment]
see https://github.com/theforeman/foreman/pull/4848

**Comment by mmoll** [comment]
this would need to go in soon, as the core PR got merged

**Comment by ekohl** [comment]
Do you know why the test failed?

**Comment by mmoll** [comment]
I guess activerecord-session_store is only in SCL

**Comment by ehelms** [comment]
Based on the Koji failure, this line may no longer be needed?

https://github.com/theforeman/foreman-packaging/pull/1812/files#diff-cb4b08197c5adf7761c2bb38deb2c10bR67

**Comment by mmoll** [comment]
thanks, should be better now

**Comment by ekohl** [comment]
Looks like a build still failed.

**Comment by mmoll** [comment]
removed 4ddd60a, which is perfectly fine, but fails in the testbuild, because the dependency is not there while building the foreman package... all green now.

**Comment by dLobatog** [comment]
Thanks @mmoll , do you want to update the foreman.spec or I do it?

**Comment by dLobatog** [comment]
Build for nightly http://koji.katello.org/koji/buildinfo?buildID=17055

**Comment by mmoll** [comment]
GH-1830

**Pull request merged**
