### PR TITLE
Update foreman-tasks to 0.7.2 into foreman 1.9 (RPM)

### PR DESCRIPTION
**Pull request by iNecas**
(cherry picked from commit 79886c465df0c4c512043be2e43783790d7aaa45)

### CODE REVIEW

**Comment by iNecas** [comment]
I will tag the dependencies (dynflow, concurrent-ruby, concurrent-ruby-edge) after this get merged

**Comment by iNecas** [comment]
Deb PR on its way

**Comment by domcleal** [comment]
:+1: if green.

http://ci.theforeman.org/job/packaging_plugin_retag/ may be useful to retag, else remember to do all three OSes.

**Comment by iNecas** [comment]
It was useful indeed, thanks!

**Pull request merged**
