### PR TITLE
Update foreman_fog_proxmox to 0.6.0

### PR DESCRIPTION
**Pull request by tristanrobert**
For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [x] 1.21
* [ ] 1.20

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by tristanrobert** [comment]
Build error log is not detailed. I unchecked nigthly because it should work only with 1.21, but build does not start again.

**Comment by dgoetz** [comment]
[test deb]

**Comment by mmoll** [comment]
```
Bundler could not find compatible versions for gem "fog-core":
  In snapshot (Gemfile.lock):
    fog-core (= 2.1.0)

  In Gemfile:
    fog-core (= 2.1.0)

    fog-proxmox (= 0.6.0) was resolved to 0.6.0, which depends on
      fog-core (~> 1.45)
```

**Comment by mmoll** [comment]
If this is for 1.21 only, the PR should be branched from (and directed to) `deb/1.21`.

**Comment by tristanrobert** [comment]
Ok thanks. I will fix it.

**Pull request closed without merging**
