### PR TITLE
Update fog-vsphere to 2.4.0

### PR DESCRIPTION
**Pull request by timogoebel**
This is only for nightly (Foreman 1.21).

### CODE REVIEW

**Comment by dLobatog** [comment]
http://koji.katello.org/koji/taskinfo?taskID=143512

**Comment by ekohl** [comment]
@dLobatog for `rpm/develop` you no longer need to release packages. We have https://ci.theforeman.org/job/foreman-packaging-release/ for that.

**Comment by timogoebel** [comment]
> why is this only for nightly though?

To reduce the risk of breaking stable versions. :-)
We can make a point release for 2.3.1 that contains fixes if you want.

**Comment by ekohl** [comment]
@timogoebel if it's a breaking release, shouldn't that have been a `3.0.0` with semver?

**Comment by timogoebel** [comment]
@ekohl: Well, it's not a breaking release, but it contains new features and not only bugfixes. The version bump was chosen wisely.

**Pull request merged**
