### PR TITLE
Update hammer_cli_foreman_virt_who_configure to 0.0.8

### PR DESCRIPTION
**Pull request by Odilhao**
(cherry picked from commit 5d436a85318d6c66b7c7179ff258625097c653d8)

### CODE REVIEW

**Review by evgeni — APPROVED** [review]
This will need tagging!

**Comment by Odilhao** [comment]
> This will need tagging!

I still don't have access to Koji :cry:

**Comment by Odilhao** [comment]
Now I have, the tag is done.

```
Created task 436714
Watching tasks (this may be safely interrupted)...
436714 tagBuild (noarch): open (kojibuilder1)
436714 tagBuild (noarch): open (kojibuilder1) -> closed
  0 free  0 open  1 done  0 failed

436714 tagBuild (noarch) completed successfully
```

**Comment by evgeni** [comment]
You need to tag both el7 and el8 versions ;)

(You only did el7)

**Comment by evgeni** [comment]
```console
% koji tag-build katello-4.1-el8 rubygem-hammer_cli_foreman_virt_who_configure-0.0.8-1.el8
Created task 436755
Watching tasks (this may be safely interrupted)...
436755 tagBuild (noarch): free
436755 tagBuild (noarch): free -> closed
  0 free  0 open  1 done  0 failed

436755 tagBuild (noarch) completed successfully
```

**Pull request merged**
