### PR TITLE
Update foreman_ansible and foreman_ansible_core

### PR DESCRIPTION
**Pull request by ares**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.20
* [ ] 1.19
* [ ] 1.18

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by mmoll** [comment]
@ares I cherry-picked the dependency update of _core, for ansible itself:
```
16:25:00 LoadError: cannot load such file -- foreman_ansible_core
16:25:00 /usr/share/foreman/vendor/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
16:25:00 /usr/share/foreman/vendor/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
16:25:00 /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
16:25:00 /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
16:25:00 /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
16:25:00 /usr/share/foreman/vendor/ruby/2.3.0/gems/foreman_ansible-2.3.0/lib/foreman_ansible/engine.rb:6:in `<top (required)>'
16:25:00 /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
16:25:00 /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
16:25:00 /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
16:25:00 /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
16:25:00 /usr/share/foreman/vendor/ruby/2.3.0/gems/foreman_ansible-2.3.0/lib/foreman_ansible.rb:4:in `<top (required)>'
16:25:00 /usr/share/foreman/config/application.rb:37:in `<top (required)>'
16:25:00 /usr/share/foreman/Rakefile:1:in `require'
16:25:00 /usr/share/foreman/Rakefile:1:in `<top (required)>'
16:25:00 /usr/share/foreman/vendor/ruby/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
```

Somehow the _core dependency in the plugin itself seems to to be gone 100%...

**Comment by ares** [comment]
I think that was intentional after changes @dlobatog made. Daniel, am I missing something?

**Comment by ares** [comment]
here's the link to the PR that drops the dependency https://github.com/theforeman/foreman_ansible/pull/213/

**Comment by mmoll** [comment]
any movement here?

**Comment by ares** [comment]
I looked at that again and it seems as forgotten require in foreman_ansible code. I opened https://github.com/theforeman/foreman_ansible/pull/229 and we'll need to build 2.3.1 with this

**Comment by mmoll** [comment]
@ares GH-3320 would probably work until a new release... Is this also 1.20 compatible? And what's the status of the proxy plugin (especially without the _core dependency)?

**Comment by ares** [comment]
It is 1.20 compatible but I'd keep it in nightlies until we test it all works after these changes. I need to fix tests and then new release will happen. What status of smart proxy plugin do you refer to? I think it has been released already?

**Comment by mmoll** [comment]
> What status of smart proxy plugin do you refer to? I think it has been released already?

Yes, but there was no DEB update... So I'll update it in nightly today.

**Comment by ares** [comment]
Ah, sorry. I must have forgotten to open the PR. It was not intentional.

**Pull request closed without merging**
