### PR TITLE
candlepin44 fixes

### PR DESCRIPTION
**Pull request by evgeni**
- **Use Candlepin 4.4 key**
- **Use Candlepin 4.4 for repoclosure**

### CODE REVIEW

**Review by ekohl — APPROVED** [review]

**Comment by ekohl** [comment]
Is this because it ran on some EL9 node?
```
[2024-06-03T06:40:35.012Z] + python3.11 -m obal lint katello-repos
[2024-06-03T06:40:35.213Z] Traceback (most recent call last):
[2024-06-03T06:40:35.213Z]   File "<frozen runpy>", line 198, in _run_module_as_main
[2024-06-03T06:40:35.213Z]   File "<frozen runpy>", line 88, in _run_code
[2024-06-03T06:40:35.213Z]   File "/home/jenkins/workspace/foreman-packaging-rpm-copr-pr-test/obal/obal/__main__.py", line 5, in <module>
[2024-06-03T06:40:35.213Z]     main()
[2024-06-03T06:40:35.213Z]   File "/home/jenkins/workspace/foreman-packaging-rpm-copr-pr-test/obal/obal/__init__.py", line 70, in main
[2024-06-03T06:40:35.213Z]     obsah.main(cliargs=cliargs, application_config=application_config)
[2024-06-03T06:40:35.213Z]   File "/home/jenkins/workspace/foreman-packaging-rpm-copr-pr-test/obsah/obsah/__init__.py", line 360, in main
[2024-06-03T06:40:35.213Z]     from ansible.utils.display import Display # pylint: disable=all
[2024-06-03T06:40:35.213Z]     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-06-03T06:40:35.213Z] ModuleNotFoundError: No module named 'ansible'
```

**Comment by evgeni** [comment]
> Is this because it ran on some EL9 node?

no, el8, but ansible got upgraded to use python3.12: https://github.com/theforeman/jenkins-jobs/pull/473

**Comment by evgeni** [comment]
[test rpm-copr]

**Comment by evgeni** [comment]
[test rpm-copr]

**Pull request merged**
