### PR TITLE
update foreman npm and gem dependencies

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
@ekohl this slightly conflicts with your #4420, but only does NPM as there seem to be an ongoing discussion in your PR?

**Comment by evgeni** [comment]
[test rpm]

**Comment by ekohl** [comment]
Ideally we'd just have one to sync up all dependencies. I've updated #4420 to correct the group so feel free to squash it into yours.

**Comment by evgeni** [comment]
Pulled in the changes from #4420 into this PR, thanks Ewoud!

**Comment by ekohl** [comment]
It's still failing now
```
Module build failed: Error: Cannot find module '/builddir/build/BUILD/foreman-1.25.0-develop/node_modules/babel-plugin-transform-class-properties' from '/builddir/build/BUILD/foreman-1.25.0-develop'
```

**Comment by evgeni** [comment]
@ekohl that's because https://ci.theforeman.org/job/foreman-develop-source-release didn't manage to build a new source yet.

and that's because of https://projects.theforeman.org/issues/28406

(feels like monday)

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
@ekohl @ehelms this now built fine, can I have an ack pls?

**Pull request merged**
