### PR TITLE
Don't install optional npm dependencies

### PR DESCRIPTION
**Pull request by tbrisker**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.13
* [ ] 1.12
* [ ] 1.11

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by domcleal** [comment]
[test]

**Comment by dLobatog** [comment]
@tbrisker After deb5e338ef5b546f24b180ff19846f34bbfa0833 , I think you may want to pass `--no-optional` to `npm install npm` too

**Comment by domcleal** [comment]
At least on 0.10.x (which is the version used to install the second npm) I can't see any difference in the installed modules when using --no-optional to install npm, so that can be left out for now.

**Comment by domcleal** [comment]
Merged, thanks @tbrisker.

**Pull request merged**
