### PR TITLE
New package ruby-server-sent-events (DEB)

### PR DESCRIPTION
**Pull request by lzap**
For plugin updates, please indicate which repos this should be built into:

* Nightly

This is my attempt to create new Debian package after many years. It will likely not work.

I used gem2deb package, then I reviewed the license and added the generates stuff into debian directory. After review I think I need to make copies in ubuntu releaes.

### CODE REVIEW

**Comment by lzap** [comment]
I guess I need to upload the gem somewhere? Where to?

```
16:33:27 ERROR:  Could not find a valid gem 'server-sent-events' (= 0.1.2) in any repository
16:33:39 ERROR:  Possible alternatives: server_sent_events
16:33:40 + ../../gem2deb server-sent-events-0.1.2.gem --debian-subdir ../server-sent-events --only-source-dir
16:33:40 ../../gem2deb:82: warning: File.exists? is a deprecated name, use File.exist? instead
16:33:40 -- Creating source tarball from server-sent-events-0.1.2.gem ...
16:33:40 tar xfm /home/jenkins/workspace/packaging_build_deb_dependency/arch/x86/label/debian/os/buster/dependencies/buster/build-server-sent-events/server-sent-events-0.1.2.gem
16:33:40 tar: /home/jenkins/workspace/packaging_build_deb_dependency/arch/x86/label/debian/os/buster/dependencies/buster/build-server-sent-events/server-sent-events-0.1.2.gem: Cannot open: No such file or directory
16:33:40 tar: Error is not recoverable: exiting now
16:33:40 /usr/lib/ruby/vendor_ruby/gem2deb.rb:56:in `run': tar xfm /home/jenkins/workspace/packaging_build_deb_dependency/arch/x86/label/debian/os/buster/dependencies/buster/build-server-sent-events/server-sent-events-0.1.2.gem (Gem2Deb::CommandFailed)
```

**Comment by evgeni** [comment]
The gem is called [server_sent_events](https://rubygems.org/gems/server_sent_events), not server-sent-events.

**Comment by evgeni** [comment]
Please rename the folder to `server_sent_events` and retry.

**Comment by lzap** [comment]
Thanks, rebased.

**Comment by lzap** [comment]
Should I also do something like this:

```diff

diff --git a/dependencies/buster/server_sent_events/control b/dependencies/buster/server_sent_events/control
index bd438023c..d3b9f2fca 100644
--- a/dependencies/buster/server_sent_events/control
+++ b/dependencies/buster/server_sent_events/control
@@ -1,4 +1,4 @@
-Source: ruby-server-sent-events
+Source: ruby-server_sent_events
 Section: ruby
 Priority: optional
 Maintainer: Debian Ruby Extras Maintainers <pkg-ruby-extras-maintainers@lists.alioth.debian.org>
```

**Comment by ekohl** [comment]
> Should I also do something like this:

No, Debian doesn't use underscores in the package name.

Looks like some UTF-8 issue?
```
10:43:25 /usr/lib/ruby/vendor_ruby/gem2deb/metadata.rb:145:in `gsub!': invalid byte sequence in US-ASCII (ArgumentError)
```

**Comment by lzap** [comment]
Hmmm I see `10:43:25 Invalid gemspec in [server_sent_events.gemspec]: No such file or directory - git` so it expect gemspec to be named differently. I am renaming the directory back to dash characters to see the original error.

**Comment by lzap** [comment]
Any hint? Anyone?

**Comment by lzap** [comment]
> No, Debian doesn't use underscores in the package name.

Ok renamed it back.

> Looks like some UTF-8 issue?

Could not find anything, I though `Lukáš` would trigger this but there's `Lukas` everywhere. Weird.

**Comment by evgeni** [comment]
a few notes:
* the *folder* needs to be named like the gem, so `server_sent_events`
* it was missing `git` as a build dependency, as they use `git ls-files` in their gemspec

after I did the above, it got me building: #6028

**Comment by lzap** [comment]
Thanks, closing. I am adding all my knowledge to https://github.com/theforeman/foreman-packaging/pull/6031 please review and let's complete the instructions.

**Pull request closed without merging**
