### PR TITLE
Update foreman_openscap to 0.9.2

### PR DESCRIPTION
**Pull request by ares**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.17
* [ ] 1.16
* [ ] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ares** [comment]
pushed fixed version

**Comment by ares** [comment]
ping

**Comment by ekohl** [comment]
I now realize that I forgot to ask about a changelog entry and already released nightly in http://koji.katello.org/koji/taskinfo?taskID=93001
1.17 should be good in http://koji.katello.org/koji/taskinfo?taskID=93003

**Comment by ares** [comment]
is there a value in changelog? it would be "version bump" only anyway

**Comment by ekohl** [comment]
So nightly failed to release because foreman is currently broken. Will need https://github.com/theforeman/foreman-packaging/pull/2333 but I'm stuck on that.

**Comment by ares** [comment]
I wonder how much "nice to have" stuff we spend time on, while this PR was sitting here 3 weeks without merge :-) anyway I didn't know about that script existence, thanks, I'll use it next time!

**Pull request merged**
