### PR TITLE
Set foreman dependencies to 1.18-stable versions

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ekohl** [comment]
Blocked on the deployment of updated repoclosures

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ekohl** [comment]
Now it fails because it's not getting the source from Jenkins - I removed that but if we set up a test_1.18_stable job it could use that.

**Comment by ehelms** [comment]
[test rpm]

**Comment by ekohl** [comment]
Rebased on the scratch build commit so the test is now running.

**Comment by ekohl** [comment]
Issues:
* dotenv either needs a downgrade or we need to cherry pick https://github.com/theforeman/foreman/commit/3505d7370ce00ae673c6c5b6f9323c8fcc17c35a
* rails 5.1.6 isn't available.

**Comment by ehelms** [comment]
[test rpm]

**Comment by ekohl** [comment]
Needs 2 cherry-picks to build since we have newer packages:
* https://github.com/theforeman/foreman/pull/5643 [nodejs-dotenv]
* https://github.com/theforeman/foreman/pull/5645 [rubygem-secure_headers]

cc @xprazak2

**Comment by xprazak2** [comment]
cherry-picks are merged now

[test rpm]

**Comment by ekohl** [comment]
I think the test_1_18_stable wasn't ready yet so it built with the old tarball.
[test rpm]

**Comment by ekohl** [comment]
I forgot that I need to modify the spec file to match ... Updated now.

**Pull request merged**
