### PR TITLE
foreman 2.1.0-rc1

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by tbrisker** [comment]
repoclosure failed, but that is expected

**Comment by evgeni** [comment]
> repoclosure failed, but that is expected
> 

Actually, it's not. Or not like this. This is similar to #4789

**Comment by pcreech** [comment]
[test]

**Comment by pcreech** [comment]
[test rpm]

**Comment by evgeni** [comment]
@pcreech did you change anything so that's supposed to pass now?

**Comment by pcreech** [comment]
@evgeni I had not, just figured it was the easiest way to see if it had gotten taken care of yet without bothering anyone

**Comment by evgeni** [comment]
okay, the closure *is* expected, it runs it for the client config for all rpms in this PR, but it also contains scl'ed things. merging.

**Comment by pcreech** [comment]
Looks like there's some interesting matrix issues at play here w/r to repoclosure.....
running repoclosure manually adding in the el7-scl repo resolves the scl repoclosures.....

what he said

**Pull request merged**
