### PR TITLE
Remote execution iteration 3 (RPM)

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by stbenjam** [comment]
Don't merge yet, found a pretty big bug while testing

**Comment by domcleal** [comment]
The proxy plugin requires should pin net-ssh to `<= 2.10.0` to match the gemspec.  I'd also say that in future the pinning should be done in development deps only (probably in the Gemfile) so packages can be more flexible - inevitably some OS will package 3.x at some point.

**Comment by stbenjam** [comment]
Updated, and will look at how we manage dependencies in the next release, thanks

**Comment by stbenjam** [comment]
This is for nightly and 1.10, btw

**Comment by domcleal** [comment]
Thanks @stbenjam, building for both versions.

**Pull request merged**
