### PR TITLE
Update foreman_discovery to 2.0.0.rc2

### PR DESCRIPTION
**Pull request by lzap**

### CODE REVIEW

**Comment by domcleal** [comment]
Please run http://ci.theforeman.org/job/packaging_build_deb_plugin/ against the branch to check it builds.

**Comment by mmoll** [comment]
the branch also need a "deb/" prefix for ci. to work

**Comment by lzap** [comment]
http://ci.theforeman.org/job/packaging_build_deb_plugin/384/

**Comment by lzap** [comment]
For the record I pushed this branch under a different name and filed that job with it.

**Comment by mmoll** [comment]
this is 1.7 only, right?

**Comment by lzap** [comment]
Yes

**Comment by domcleal** [comment]
I'll merge it to deb/develop too (optionally build it), just so the changelog and history stays accurate.

**Comment by domcleal** [comment]
Merged to both, building for 1.7.  Thanks @lzap!

**Comment by lzap** [comment]
Thank you very much.

**Pull request merged**
