### PR TITLE
Bump yggdrasil to 0.2.3

### PR DESCRIPTION
**Pull request by adamruzicka**
- Patch yggdrasil to pass FOREMAN_REX_WORKDIR env var to the workers
- Bump yggdrasil to 0.2.3

### CODE REVIEW

**Comment by ekohl** [comment]
There's now a merge conflict and https://github.com/theforeman/foreman-packaging/pull/9897 was merged, so can this be closed?

**Comment by adamruzicka** [comment]
#9897 was against rpm/develop, this one is against rpm/3.7. Unless I'm missing something then I'd say I should resolve the conflicts so that this can get in

**Comment by ekohl** [comment]
Ah yes. Fine by me. Just going over open PRs against 3.7 since we're releasing 3.7.1.

**Comment by adamruzicka** [comment]
Looks like epel doesn't have the version of go we want/expect?
```
DEBUG util.py:598:  https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/g/golang-1.19.10-1.el7.x86_64.rpm: [Errno 14] HTTPS Error 404 - Not Found
DEBUG util.py:598:  Trying other mirror.
DEBUG util.py:598:  To address this issue please refer to the below wiki article 
DEBUG util.py:598:  https://wiki.centos.org/yum-errors
DEBUG util.py:598:  If above article doesn't help to resolve this issue please use https://bugs.centos.org/.
DEBUG util.py:598:  https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/g/golang-bin-1.19.10-1.el7.x86_64.rpm: [Errno 14] HTTPS Error 404 - Not Found
DEBUG util.py:598:  Trying other mirror.
DEBUG util.py:598:  https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/g/golang-src-1.19.10-1.el7.noarch.rpm: [Errno 14] HTTPS Error 404 - Not Found
DEBUG util.py:598:  Trying other mirror.
DEBUG util.py:598:  Error downloading packages:
DEBUG util.py:598:    golang-bin-1.19.10-1.el7.x86_64: failed to retrieve Packages/g/golang-bin-1.19.10-1.el7.x86_64.rpm from build
DEBUG util.py:598:  error was [Errno 14] HTTPS Error 404 - Not Found
DEBUG util.py:598:    golang-1.19.10-1.el7.x86_64: failed to retrieve Packages/g/golang-1.19.10-1.el7.x86_64.rpm from build
DEBUG util.py:598:  error was [Errno 14] HTTPS Error 404 - Not Found
DEBUG util.py:598:    golang-src-1.19.10-1.el7.noarch: failed to retrieve Packages/g/golang-src-1.19.10-1.el7.noarch.rpm from build
DEBUG util.py:598:  error was [Errno 14] HTTPS Error 404 - Not Found
DEBUG util.py:744:  Child return code was: 1
```

**Comment by ekohl** [comment]
IIRC EPEL has 1.20 now so probably an outdated repo cache.
```console
$ koji -p katello regen-repo foreman-client-3.7-rhel7-build
Regenerating repo for tag: foreman-client-3.7-rhel7-build
Created task: 571647
Task info: http://koji.katello.org/koji/taskinfo?taskID=571647
Watching tasks (this may be safely interrupted)...
571647 newRepo (foreman-client-3.7-rhel7-build): free
571647 newRepo (foreman-client-3.7-rhel7-build): free -> open (koji-centos-stream-9)
  571648 createrepo (x86_64): free
  571648 createrepo (x86_64): free -> open (koji-centos-stream-9)
  571648 createrepo (x86_64): open (koji-centos-stream-9) -> closed
  0 free  1 open  1 done  0 failed
571647 newRepo (foreman-client-3.7-rhel7-build): open (koji-centos-stream-9) -> closed
  0 free  0 open  2 done  0 failed

571647 newRepo (foreman-client-3.7-rhel7-build) completed successfully
```

[test rpm]

**Comment by ekohl** [comment]
Repoclosure is unrelated.

**Pull request merged**
