### PR TITLE
Add Ansible dependency for Ansible proxy plugin (DEB)

### PR DESCRIPTION
**Pull request by tbrisker**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.14
* [ ] 1.13
* [ ] 1.12

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by mmoll** [comment]
That version requirement is probably only satisfiable by using the the Ansible repo/PPA, what's the background of this?

**Comment by tbrisker** [comment]
@mmoll That's the version that ships with the foreman plugin.

**Comment by mmoll** [comment]
@tbrisker I think that's OK then. If we get too many issues about this, that callback plugin should get shipped in a package. Please add a changelog entry and bump the Debian version to -2.

**Comment by tbrisker** [comment]
@mmoll thanks, updated the changelog

**Comment by mmoll** [comment]
merged, thanks @tbrisker!

**Pull request merged**
