### PR TITLE
pulp-container and dependencies

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by ekohl** [comment]
Looks like you need to split it up since cffi is a build dependency.

**Comment by evgeni** [comment]
damn, forgot that!

**Comment by evgeni** [comment]
@ekohl split out cffi to https://github.com/theforeman/foreman-packaging/pull/4365, will rebase once that is merged.

**Comment by evgeni** [comment]
repoclosure fails due to missing mashing, merging as is

**Pull request merged**
