### PR TITLE
Patch yggdrasil to pass FOREMAN_REX_WORKDIR env var to the workers

### PR DESCRIPTION
**Pull request by adamruzicka**
(cherry picked from commit 1534c0d176b225b512c26a909a783842a5e6064a)

### CODE REVIEW

**Comment by ekohl** [comment]
I think the repo needs to be regenerated:
```
DEBUG util.py:444:    kernel-headers-5.14.0-325.el9.x86_64: Download failed: Status code: 404 for https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/Packages/kernel-headers-5.14.0-325.el9.x86_64.rpm (IP: 18.160.41.75)
```

**Comment by ekohl** [comment]
http://koji.katello.org/koji/taskinfo?taskID=568169 is done
[test rpm]

**Comment by ekohl** [comment]
Now RHEL 7 fails:

```
DEBUG util.py:598:  https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/g/golang-1.19.9-1.el7.x86_64.rpm: [Errno 14] HTTPS Error 404 - Not Found
DEBUG util.py:598:  Trying other mirror.
DEBUG util.py:598:  To address this issue please refer to the below wiki article 
DEBUG util.py:598:  https://wiki.centos.org/yum-errors
DEBUG util.py:598:  If above article doesn't help to resolve this issue please use https://bugs.centos.org/.
DEBUG util.py:598:  https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/g/golang-bin-1.19.9-1.el7.x86_64.rpm: [Errno 14] HTTPS Error 404 - Not Found
DEBUG util.py:598:  Trying other mirror.
DEBUG util.py:598:  https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/g/golang-src-1.19.9-1.el7.noarch.rpm: [Errno 14] HTTPS Error 404 - Not Found
DEBUG util.py:598:  Trying other mirror.
DEBUG util.py:598:  Error downloading packages:
DEBUG util.py:598:    golang-src-1.19.9-1.el7.noarch: failed to retrieve Packages/g/golang-src-1.19.9-1.el7.noarch.rpm from build
DEBUG util.py:598:  error was [Errno 14] HTTPS Error 404 - Not Found
DEBUG util.py:598:    golang-bin-1.19.9-1.el7.x86_64: failed to retrieve Packages/g/golang-bin-1.19.9-1.el7.x86_64.rpm from build
DEBUG util.py:598:  error was [Errno 14] HTTPS Error 404 - Not Found
DEBUG util.py:598:    golang-1.19.9-1.el7.x86_64: failed to retrieve Packages/g/golang-1.19.9-1.el7.x86_64.rpm from build
DEBUG util.py:598:  error was [Errno 14] HTTPS Error 404 - Not Found
```

http://koji.katello.org/koji/taskinfo?taskID=568233 running now.

**Comment by ekohl** [comment]
[test rpm]

**Comment by adamruzicka** [comment]
The failure should be unrelated

**Review by ekohl — APPROVED** [review]
This is weird, but indeed unrelated.
```
[2023-10-11T12:18:53.319Z] fatal: [yggdrasil]: FAILED! => changed=false 
[2023-10-11T12:18:53.319Z]   command: dnf repoclosure --refresh --newest --config /tmp/ansible.g1z7kveurepoclosure/yum.conf --check el7-foreman-client-3.7 --check downloaded_rpms --repofrompath downloaded_rpms,/home/jenkins/workspace/foreman-packaging-rpm-pr-test/downloaded_rpms/rhel7 --repo el7-base --repo el7-updates --repo el7-epel --repo el7-extras --repo el7-puppet-7
[2023-10-11T12:18:53.319Z]   msg: Repoclosure failed
[2023-10-11T12:18:53.319Z]   output: |-
[2023-10-11T12:18:53.319Z]     Added downloaded_rpms repo from /home/jenkins/workspace/foreman-packaging-rpm-pr-test/downloaded_rpms/rhel7
[2023-10-11T12:18:53.319Z]     Error: Repoclosure ended with unresolved dependencies.
[2023-10-11T12:18:53.319Z]     package: rubygem-foreman_scap_client-0.5.1-1.el7.noarch from el7-foreman-client-3.7
[2023-10-11T12:18:53.319Z]       unresolved deps:
[2023-10-11T12:18:53.319Z]         /usr/bin/ruby
[2023-10-11T12:18:53.319Z]         ruby(release)
[2023-10-11T12:18:53.319Z]         ruby(rubygems)
```

**Pull request merged**
