### PR TITLE
create foreman-telemetry package

### PR DESCRIPTION
**Pull request by mmoll**
this should be built into:

* [x] Nightly

### CODE REVIEW

**Comment by ekohl** [comment]
I prefer https://github.com/theforeman/foreman/pull/5275 so it's an optional package.

**Comment by lzap** [comment]
I will let you decide guys, will test the core change, sorry!

**Comment by mmoll** [comment]
I'd rather go for telemetry to be optional, if possible.

**Comment by lzap** [comment]
That's what we aim for in core, this is a bug indeed. For packaging, should be definitely a separate package.

**Pull request merged**
