### PR TITLE
Release rubygem-bastion 5.0.10

### PR DESCRIPTION
**Pull request by ehelms**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.15
* [ ] 1.14
* [ ] 1.13

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by mmoll** [comment]
`Requires: foreman >= 1.11.0` isn't correct anymore, I presume? ;)

**Comment by ehelms** [comment]
Modified

**Comment by ehelms** [comment]
Merging and building to fix broken 1.15/3.4 installs.

**Comment by Klaas-** [comment]
@ehelms this is still broken:
http://koji.katello.org/koji/buildinfo?buildID=16589

`DEBUG util.py:439:  Error: No Package found for tfm-rubygem(angular-rails-templates) >= 1.0.2`

https://github.com/theforeman/foreman-packaging/pull/1769 thats only in nightly I'd guess

**Pull request merged**
