### PR TITLE
Bump up rubygem-ruby_parser to version 3.10.1

### PR DESCRIPTION
**Pull request by witlessbird**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.17
* [x] 1.16
* [ ] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by witlessbird** [comment]
This requires rubygem-sexp_processor v.4.10.0

**Comment by ekohl** [comment]
[test]

**Comment by ekohl** [comment]
Looks like it's not dealing well with some files:
```
error: Installed (but unpackaged) file(s) found:
   /opt/theforeman/tfm/root/usr/share/gems/gems/ruby_parser-3.10.1/compare/normalize.rb
    Installed (but unpackaged) file(s) found:
   /opt/theforeman/tfm/root/usr/share/gems/gems/ruby_parser-3.10.1/compare/normalize.rb
```

**Comment by witlessbird** [comment]
* added compare/ dir to the list of files

^ This should fix the build

**Pull request merged**
