### PR TITLE
fix thor bundling also for bionic and focal

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by pcreech** [comment]
Looks like focal is still borked.

**Comment by evgeni** [comment]
really? ;-)

I have no clue why tho.

**Comment by evgeni** [comment]
:woman_shrugging:

**Comment by evgeni** [comment]
welp, that built

@pcreech @ekohl @ehelms @upadhyeammit this essentially syncs the changes we did in 3.1+ for packaging into 3.0. I am rather confident that this "just works" (as it does in 3.1+) and wonder if we should do this for focal only (where we *need* it) or for all 3.0 supported releases (buster, bionic, focal)? 3.1 doesn't support bionic, so that's the only "risky" part.

**Comment by ekohl** [comment]
If we would keep the branch alive longer, consistency would be important but given 3.0.2 is the last 3.0 release, I'd say apply it only for focal. That keeps the potential impact small.

**Review by pcreech — APPROVED** [review]

**Pull request merged**
