### PR TITLE
Add hammer-cli-foreman-puppet

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by tbrisker** [comment]
Looks like it failed with: 15:36:20 File does not exist: simplecov

**Comment by ekohl** [comment]
Updated so it doesn't run the testsuite.

**Comment by tbrisker** [comment]
hmm, looks like now it isn't finding 3.0.0 for some reason: 
```
16:58:02 /usr/lib/ruby/2.7.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'hammer_cli_foreman' (< 4.0.0, > 2.6.0) among 56 total gem(s) (Gem::MissingSpecError)

**Comment by ekohl** [comment]
Oh, we probably didn't promote it yet? It may be stuck in staging.

**Comment by tbrisker** [comment]
@ekohl could it be because you dropped it from the build deps? maybe it needs to be present in both?

**Comment by pcreech** [comment]
ACK

**Pull request merged**
