### PR TITLE
Add nodejs-gridster package

### PR DESCRIPTION
**Pull request by ohadlevy**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.22
* [ ] 1.21
* [ ] 1.20

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by mmoll** [comment]
build fails :broken_heart:

**Comment by ohadlevy** [comment]
:green: now :)

**Comment by mmoll** [comment]
core PR got merged.

**Comment by ekohl** [comment]
@tbrisker FYI, adding packages always involves some manual work. I've now whitelisted the package and created https://github.com/theforeman/foreman-packaging/pull/3694 to update the Foreman side.

**Pull request merged**
