### PR TITLE
Update foreman_remote_execution to 0.0.10 (RPM)

### PR DESCRIPTION
**Pull request by iNecas**

### CODE REVIEW

**Comment by domcleal** [comment]
Looks like this will fail due to new files being added into the gem.  They'll need to be excluded or added as appropriate.  (Consider an exclude on `%{gem_instdir}/.*` etc.)

**Comment by iNecas** [comment]
Updated (waiting for CI if it helped) but not sure there is a better way to do so. Also, similarly as #834, we will ask for tagging into 1.9 repos eventually

**Comment by iNecas** [comment]
Damn, bad gemspec :) I already have a weekend, again and better (hopefully)

**Comment by domcleal** [comment]
Thanks @iNecas, building for nightlies.  Let me know when you want it in 1.9.  We'll need to update 1.10 as well once RC1 is available - for now we can't build in that tag.

**Comment by iNecas** [comment]
Tested with 1.9 production: good to go to 1.9! + 1.10 RC1 as well

**Comment by domcleal** [comment]
Cherry picked over to rpm/1.9 and building now.  I'll do 1.10 once we've got RC1 available.

**Pull request merged**
