### PR TITLE
Deb/develop foreman service

### PR DESCRIPTION
**Pull request by evgeni**
testing, ignore

### CODE REVIEW

**Comment by mmoll** [comment]
@evgeni this seems to work fine, thanks! However, I think until puma is becoming the default, the -service package should not be recommended.

**Comment by evgeni** [comment]
> @evgeni this seems to work fine, thanks! However, I think until puma is becoming the default, the -service package should not be recommended.

I agree, but then we also should not ship `foreman.init` as enabled-by-default :)

**Comment by ekohl** [comment]
Because the sysvinit script and the systemd unit work in a very different way I'd prefer to drop the sysvinit script. If there's demand from users we can add it again, but I don't expect any interest.

**Comment by evgeni** [comment]
[test packaging]

**Comment by evgeni** [comment]
it's green :green_heart: 

@ekohl I think I agree, but I'd do it in a separate PR

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
