### PR TITLE
Added rubygem-newt

### PR DESCRIPTION
**Pull request by lzap**
This is NONSCL, for discovery image to introduce TUI feature. If possible
please include in 1.9.

F19: http://koji.katello.org/koji/taskinfo?taskID=285900
EL6: http://koji.katello.org/koji/taskinfo?taskID=285902
EL7: http://koji.katello.org/koji/taskinfo?taskID=285903

Tests on RHEL:

```
[root@fsix ~]# rpm -ql rubygem-newt
/usr/lib/ruby/gems/1.8/gems/newt-0.9.4
/usr/lib/ruby/gems/1.8/gems/newt-0.9.4/lib
/usr/lib/ruby/gems/1.8/gems/newt-0.9.4/lib/newt.rb
/usr/lib/ruby/gems/1.8/gems/newt-0.9.4/lib/ruby_newt
/usr/lib/ruby/gems/1.8/gems/newt-0.9.4/lib/version.rb
/usr/lib/ruby/gems/1.8/specifications/newt-0.9.4.gemspec
/usr/lib64/ruby/site_ruby/1.8/x86_64-linux
/usr/lib64/ruby/site_ruby/1.8/x86_64-linux/ruby_newt
/usr/lib64/ruby/site_ruby/1.8/x86_64-linux/ruby_newt/ruby_newt.so
[root@fsix ~]# irb
irb(main):001:0> require "rubygems"
=> true
irb(main):002:0> require "newt"
=> true
```

```
[root@fseven ~]# rpm -ql rubygem-newt
/usr/lib64/gems/ruby/newt-0.9.4
/usr/lib64/gems/ruby/newt-0.9.4/lib
/usr/lib64/gems/ruby/newt-0.9.4/lib/ruby_newt
/usr/lib64/gems/ruby/newt-0.9.4/lib/ruby_newt/ruby_newt.so
/usr/share/gems/gems/newt-0.9.4
/usr/share/gems/gems/newt-0.9.4/lib
/usr/share/gems/gems/newt-0.9.4/lib/newt.rb
/usr/share/gems/gems/newt-0.9.4/lib/ruby_newt
/usr/share/gems/gems/newt-0.9.4/lib/version.rb
/usr/share/gems/specifications/newt-0.9.4.gemspec
[root@fseven ~]# irb
irb(main):001:0> require "newt"
=> true
```

### CODE REVIEW

**Comment by domcleal** [comment]
Should this be in the plugins tags/repo then, if it's going to be part of Discovery?  Does it get downloaded and baked into an image during a build process?

**Comment by lzap** [comment]
It is baked into the image together with `foreman-proxy` yes. I don't think this belongs to discovery plugin repo.

**Comment by lzap** [comment]
To clarify - we simply add the foreman-proxy repo in the kickstart during image build to fetch the proxy and few other gems from there.

**Comment by lzap** [comment]
Note for myself: Filed from develop, need to do new PR if rebase needed.

**Comment by domcleal** [comment]
> It is baked into the image together with foreman-proxy yes. I don't think this belongs to discovery plugin repo.

Yeah, so as it's not a dependency of foreman/foreman-proxy, it should be in the plugins repo as it's only used in relation to Discovery.  Could you update tito/comps?

**Comment by lzap** [comment]
Sure. In https://github.com/theforeman/foreman-packaging/pull/692

**Pull request closed without merging**
