### PR TITLE
Updated ruby-puppetdb-foreman to 3.0.1 [deb]

### PR DESCRIPTION
**Pull request by timogoebel**
Please build for:

* [x] Nightly
* [x] 1.15
* [x] 1.14
* [x] 1.13

⚠️ Fair warning: I have no clue about debian packaging. The changes for apipie cache are just copy-pasted.

### CODE REVIEW

**Comment by domcleal** [comment]
The `rules` file is missing some lines to install the plugin and copy out the results - it should match https://github.com/theforeman/foreman-packaging/blob/deb/develop/plugins/ruby-foreman-discovery/debian/rules#L14-L24 exactly. Also ensure that hard tabs are used, as it's a Makefile.

**Comment by timogoebel** [comment]
@domcleal : Thanks. That did the trick.

Now we're finally at

```
NoMethodError: undefined method `reloader' for #<Foreman::Application:0x00000004379ae8>
```

**Comment by domcleal** [comment]
I've re-triggered the nightly build job to rebuild Foreman with apipie-rails 0.5.1, please try testing it again tomorrow after 08:30 UTC (once the updated packages are available).

**Comment by timogoebel** [comment]
@domcleal : Thanks for your invaluable help with this. Tests pass now. I've found an issue in 3.0.1 I want to fix before packaging this. I'll open a separate PR for this and close this for the time being.

**Pull request closed without merging**
