### PR TITLE
Bump nodejs-theforeman-{vendor,builder} to 10.1.0

### PR DESCRIPTION
**Pull request by ofedoren**
Supported Versions:

 * Nightly
 * 3.3

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
Should go in with https://github.com/theforeman/foreman/pull/9110

**Review by zjhuntin — APPROVED** [review]

**Comment by zjhuntin** [comment]
ACK, @ezr-ondrej hey, good to merge or should it be merged with that PR?

**Comment by ezr-ondrej** [comment]
Good to merge, it is the other way around, this PR should go in first :) if you can give us an ack on the related PR, it would be awesome! :)

**Comment by adamruzicka** [comment]
Is this waiting for something?

**Comment by ezr-ondrej** [comment]
@zjhuntin pls? :)

**Comment by evgeni** [comment]
going to pretend I am still doing packaging :roll_eyes:

**Pull request merged**
