### PR TITLE
Update foreman_openscap for 2.0-stable

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by ehelms** [comment]
[test rpm]

**Comment by zjhuntin** [comment]
[test rpm]

**Comment by xprazak2** [comment]
[test rpm]

**Comment by tbrisker** [comment]
[test rpm]

**Comment by tbrisker** [comment]
odd, repoclosure is failing to find ruby:
```
[2020-05-18T15:19:37.946Z]       unresolved deps:
[2020-05-18T15:19:37.946Z]         rh-ruby25-ruby(release)
[2020-05-18T15:19:37.946Z]         rh-ruby25-ruby(rubygems)
[2020-05-18T15:19:37.946Z]         rh-ruby25-ruby
```
pretty sure it's unrelated to this PR but not 100% certain, can someone from @theforeman/packaging please take a look?

**Comment by evgeni** [comment]
this PR contains scl and non-scl packages, which confuses our repoclosure check, that's fine :)

**Pull request merged**
