### PR TITLE
Add foreman statistics plugin (CP 2.1)

### PR DESCRIPTION
**Pull request by ezr-ondrej**
(cherry picked from commit fa4b02ae06b0f035661e22de637d64f5fd128270)
Backport of #5391

### CODE REVIEW

**Comment by mmoll** [comment]
Is there already related statistics code missing in 2.1 from core?

**Comment by ezr-ondrej** [comment]
There is a related warning that statistics are gonna get removed. There's
not much point, but for people who are irritated by the warning. And for
people who wants to help testing the plugin.

Dne čt 11. 6. 2020 20:46 uživatel Michael Moll <notifications@github.com>
napsal:

**Comment by ezr-ondrej** [comment]
Closing the CP for now, will reopen once the develop are in

**Comment by ezr-ondrej** [comment]
Reopening with the proper CP, as we have the plugin in `develop` now

**Comment by tbrisker** [comment]
https://ci.theforeman.org/job/packaging_build_deb_plugin/517/

**Pull request merged**
