### PR TITLE
Update rubygem-foreman_scc_manager to 1.8.4

### PR DESCRIPTION
**Pull request by m-bucher**
see https://github.com/ATIX-AG/foreman_scc_manager/pull/39

### CODE REVIEW

**Comment by ekohl** [comment]
Looks like it's failing to build:
`I18n::InvalidLocale: :en is not a valid locale`

**Comment by tbrisker** [comment]
Looks like this is caused by the upgrade to the i18n gem to version 1.8.2 as part of the rails upgrade. Not sure why this is failing here but not elsewhere, but we might be seeing this in other plugins if they are rebuilt on top of rails 6

**Comment by m-bucher** [comment]
@tbrisker, anything I can do to fix this?

**Comment by ehelms** [comment]
Katello rebuilt a few times since the upgrade. I tested another plugin `foreman_virt_who_configure` as well which makes this even more odd.

**Comment by tbrisker** [comment]
[test rpm] just to make sure we aren't chasing a wild goose here...

**Comment by ehelms** [comment]
I'm wondering if we are seeing something related to this bit of code:

https://github.com/ATIX-AG/foreman_scc_manager/blob/master/lib/foreman_scc_manager/engine.rb#L102

**Comment by tbrisker** [comment]
> I'm wondering if we are seeing something related to this bit of code:
> 
> https://github.com/ATIX-AG/foreman_scc_manager/blob/master/lib/foreman_scc_manager/engine.rb#L102

That's common to all plugins - e.g. https://github.com/theforeman/foreman_virt_who_configure/blob/master/lib/foreman_virt_who_configure/engine.rb#L114-L119

**Comment by tbrisker** [comment]
for the record, the failure now is on repoclosure, which is looking at the previous version of the rpm for some reason.

**Pull request merged**
