### PR TITLE
Update foreman requirements

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ekohl** [comment]
Updated - had an old git checkout without rails 5.1.6

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman-infra/pull/657 will need to propagate before this passes.

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
I've had to re-engineer Koji setup to use the new repos which is the cause of some of these errors.

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
@ekohl passing now, I'll let you handle this, but the new Koji external repository is working

**Pull request merged**
