### PR TITLE
Update apipie-rails to 0.5.4

### PR DESCRIPTION
**Pull request by ares**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.16
* [x] 1.15
* [ ] 1.14

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ares** [comment]
Updated to 0.5.3, since this issue is planned for Katello 3.4, we should build it down to 1.15. I checked with @iNecas  and there are no incompatible changes since 0.4, which is the version we currently have in 1.15

**Comment by ares** [comment]
getting
```
error: File not found: /builddir/build/BUILDROOT/tfm-rubygem-apipie-rails-0.5.3-1.git.255.773df2a.el7.noarch/opt/theforeman/tfm/root/usr/share/gems/gems/apipie-rails-0.5.3/Gemfile
RPM build errors:
    File not found: /builddir/build/BUILDROOT/tfm-rubygem-apipie-rails-0.5.3-1.git.255.773df2a.el7.noarch/opt/theforeman/tfm/root/usr/share/gems/gems/apipie-rails-0.5.3/Gemfile
```

but I don't see any change and the Gemfile is present in the gem, any ideas?

**Comment by ares** [comment]
removing the Gemfile seems to work, other gems don't list it either, perhaps some exclude macro change the way it works after we built last apipie-rails. Squashing into single commit.

**Comment by iNecas** [comment]
Please update to 0.5.4, as apipie community found and fixed some issue that was introduced in 0.5.3.

**Comment by ares** [comment]
updated to 0.5.4

**Comment by iNecas** [comment]
👍

**Comment by dLobatog** [comment]
Merged, tagged and built for:

nightly - http://koji.katello.org/koji/taskinfo?taskID=27737
1.16 - not ready yet
1.15 - http://koji.katello.org/koji/buildinfo?buildID=16801

**Pull request merged**
