### PR TITLE
Accept python3-requests for the callback too.

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
Just checking what uses what for Ansible:
* Debian Buster uses Python 3 (https://packages.debian.org/buster/ansible)
* Ubuntu Bionic uses Python 2 (https://packages.ubuntu.com/bionic/ansible)
* Ubuntu Focal uses Python 3 (https://packages.ubuntu.com/focal/ansible)

Given that, should it prefer the 3 version over 2?

**Comment by evgeni** [comment]
Well… That'll pull in the wrong requests on Bionic then, while the current one pulls in the wrong one on Buster…

**Comment by ekohl** [comment]
I also thought about that. Here is an example where a common plugins repository does break down.

**Comment by evgeni** [comment]
Yes.

**Comment by ekohl** [comment]
In control files, can you specify `(ansible >= 2.6 && python3-requests) || (ansible >= 2.2 && python-requests)`? This would rely on the fact that Bionic ships Ansible 2.5 while Buster ships 2.7. Still a hack, but if that works ...

**Comment by evgeni** [comment]
No you can't. You could do `python-requests | ansible (>= 2.6), python3-requests` which is similar-ish. But that'd "break" (as in not force pulling what we want it to) with backports which people probably do for Ansible heavily.

**Comment by ekohl** [comment]
I was afraid of that. This also has the problem that on a Bionic system where `python3-requests` is already installed that the dependency will be missing. Prior to https://github.com/theforeman/puppet-foreman_proxy/commit/d1954c714a912af0c098357c3684d8635fb234a3#diff-490f5830bc142ccd235c22d610cdedc2ac99eef2bc8dde306912f3c5b366ae8f it could have been handled in the installer.

**Comment by ekohl** [comment]
Sounds good to me.

**Comment by evgeni** [comment]
Updated!

**Review by ekohl — APPROVED** [review]
Might be nice to explain this in a commit message, but otherwise :+1:

**Comment by evgeni** [comment]
Updated the commit message.

**Review by ekohl — APPROVED** [review]
Thanks!

**Pull request merged**
