### PR TITLE
Update foreman_azure to 1.3.0 [rpm]

### PR DESCRIPTION
**Pull request by dLobatog**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.14
* [x] 1.13
* [ ] 1.12

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

Thanks!

### CODE REVIEW

**Comment by dLobatog** [comment]
"15:27:33 Command output: Kerberos authentication failed: No credentials cache found (-1765328189)" is the error?

**Comment by domcleal** [comment]
[test] Koji client config fixed.

**Comment by dLobatog** [comment]
db/seeds.d missing - will address this shortly

**Comment by domcleal** [comment]
[test] with an override in place.

**Comment by domcleal** [comment]
[test] override fixed.

**Comment by domcleal** [comment]
Merged and building, thanks @dLobatog.

**Pull request merged**
