### PR TITLE
add satellite collections to packaging

### PR DESCRIPTION
**Pull request by evgeni**
this is mostly so that we can use packit for those collections

### CODE REVIEW

**Comment by ehelms** [comment]
Why do these need packit?

**Comment by evgeni** [comment]
Because I want to be able to test changes via PRT

**Comment by evgeni** [comment]
I talked to Zach and he said that no changes are needed on the downstream side.

**Comment by ehelms** [comment]
> Because I want to be able to test changes via PRT

I was hopeful the tests could just use the collection more directly and avoid all of this setup.

**Comment by evgeni** [comment]
Nope. They assume a prod system, which obtains things via RPM.

**Pull request merged**
