### PR TITLE
Update to dynflow 0.7.6

### PR DESCRIPTION
**Pull request by iNecas**

### CODE REVIEW

**Comment by domcleal** [comment]
The uuidtools dep has been removed from the gem, could you remove it from the spec file please?

**Comment by ares** [comment]
just out of curiosity, required ruby version changed in gemspec? otherwise seems good

**Comment by domcleal** [comment]
@ares yeah, I did that when replacing uuidtools with SecureRandom (1.9 only)

**Comment by ares** [comment]
I see, thanks

**Comment by iNecas** [comment]
Ah, you're right. Updated

**Comment by domcleal** [comment]
Thanks for the PR @iNecas, building now.

**Pull request merged**
