### PR TITLE
Update foreman_expire_hosts to 5.1.0

### PR DESCRIPTION
**Pull request by timogoebel**
Please build for:

* [x] Nightly
* [x] 1.17
* [ ] 1.16
* [ ] 1.15

### CODE REVIEW

**Comment by timogoebel** [comment]
> we also need a changelog entry since we're no longer tagging (which previously generated the entry).

Ah, I must have missed the announcement that a changelog entry os not required.
Have you already automated that somehow? If not I need to make my own script for this.

**Comment by timogoebel** [comment]
@ekohl: Sed to the rescue, done. :-)

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm]
We should allow a few more builds to be kept. This is a short lifetime.

**Comment by timogoebel** [comment]
> It looks like there's some webpack compilation going on but this plugin doesn't contain webpack.

Is there something I can do about that?

**Comment by ekohl** [comment]
Testing https://github.com/theforeman/foreman-packaging/pull/2449 now with this package and a webpack pkg.

**Comment by ekohl** [comment]
[test rpm]

**Pull request merged**
