### PR TITLE
Update fast_gettext to 1.4.1 (RPM)

### PR DESCRIPTION
**Pull request by tbrisker**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.15
* [ ] 1.14
* [ ] 1.13

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by mmoll** [comment]
[test] again

**Comment by mmoll** [comment]
the git-annexing seems still to be broken?

**Comment by mmoll** [comment]
@tbrisker the spec file also needed an update. in the meanwhile 1.4.1 got released, feel free to squash my stuff into your commit.

**Comment by tbrisker** [comment]
@mmoll thanks, squashed

**Comment by mmoll** [comment]
yes :)

**Comment by tbrisker** [comment]
@mmoll @ehelms ping?

**Comment by mmoll** [comment]
IMHO this is ready to :ship: it! 🚀

**Pull request merged**
