### PR TITLE
katello dep updates for pulpcore 3.4 backport

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
build will fail until https://github.com/theforeman/foreman-packaging/pull/5505 is merged

**Comment by pcreech** [comment]
[test rpm]

**Comment by pcreech** [comment]
[test rpm]

**Comment by pcreech** [comment]
[test rpm]

**Comment by pcreech** [comment]
```
Log file /builddir/build/BUILD/katello-3.16.0.rc3.1/usr/share/foreman/log/production.log cannot be opened. Falling back to STDOUT
Gem loading error: Could not find 'pulpcore_client' (< 3.4.0, >= 3.3.0) - did find: [pulpcore_client-3.4.1]
```

**Comment by pcreech** [comment]
looks like we need a new katello release with an updated gemspec

**Comment by pcreech** [comment]
This was merged as part of https://github.com/theforeman/foreman-packaging/pull/5511

**Pull request closed without merging**
