### PR TITLE
Update foreman_expire_hosts to 2.1.2 [rpm]

### PR DESCRIPTION
**Pull request by timogoebel**
Please build for:

* [x] Nightly
* [x] 1.14
* [x] 1.13
* [ ] 1.12

### CODE REVIEW

**Comment by timogoebel** [comment]
Test results look unrelated.

**Comment by domcleal** [comment]
[test] with an override in place.

**Comment by domcleal** [comment]
[test] override fixed.

**Comment by timogoebel** [comment]
That looks to have done the trick. Thanks for taking care of this, @domcleal . Great job.

**Comment by domcleal** [comment]
Merged and building, thanks @timogoebel.

**Pull request merged**
