### PR TITLE
Discovery 4.1.0

### PR DESCRIPTION
**Pull request by lzap**
FYI the extra locale files were released as a mistake in 4.0.0.

```
Wrote: /tmp/tito/rubygem-foreman_discovery-4.1.0-1.fm1_10.git.56.4fb06b2.fc19.src.rpm



Submitting build with: koji -c ~/.koji/katello-config build --nowait --scratch foreman-plugins-nightly-fedora19 /tmp/tito/rubygem-foreman_discovery-4.1.0-1.fm1_10.git.56.4fb06b2.fc19.src.rpm
Uploading srpm: /tmp/tito/rubygem-foreman_discovery-4.1.0-1.fm1_10.git.56.4fb06b2.fc19.src.rpm
[                                    ]  00% 00:00:00     0.00 B        - B/sec
[====================================] 100% 00:00:01  83.88 KiB  71.43 KiB/sec
Created task: 347361
Task info: http://koji.katello.org/koji/taskinfo?taskID=347361
Wrote: /tmp/tito/tfm-rubygem-foreman_discovery-4.1.0-1.fm1_10.git.56.4fb06b2.git.56.4fb06b2.el6.src.rpm



Submitting build with: koji -c ~/.koji/katello-config build --nowait --scratch foreman-plugins-nightly-rhel6 /tmp/tito/tfm-rubygem-foreman_discovery-4.1.0-1.fm1_10.git.56.4fb06b2.git.56.4fb06b2.el6.src.rpm
Uploading srpm: /tmp/tito/tfm-rubygem-foreman_discovery-4.1.0-1.fm1_10.git.56.4fb06b2.git.56.4fb06b2.el6.src.rpm
[                                    ]  00% 00:00:00     0.00 B        - B/sec
[====================================] 100% 00:00:01  83.93 KiB  68.09 KiB/sec
Created task: 347362
Task info: http://koji.katello.org/koji/taskinfo?taskID=347362
Wrote: /tmp/tito/tfm-rubygem-foreman_discovery-4.1.0-1.fm1_10.git.56.4fb06b2.git.56.4fb06b2.git.56.4fb06b2.el7.src.rpm



Submitting build with: koji -c ~/.koji/katello-config build --nowait --scratch foreman-plugins-nightly-rhel7 /tmp/tito/tfm-rubygem-foreman_discovery-4.1.0-1.fm1_10.git.56.4fb06b2.git.56.4fb06b2.git.56.4fb06b2.el7.src.rpm
Uploading srpm: /tmp/tito/tfm-rubygem-foreman_discovery-4.1.0-1.fm1_10.git.56.4fb06b2.git.56.4fb06b2.git.56.4fb06b2.el7.src.rpm
[                                    ]  00% 00:00:00     0.00 B        - B/sec
[====================================] 100% 00:00:01  83.94 KiB  78.38 KiB/sec
Created task: 347363
Task info: http://koji.katello.org/koji/taskinfo?taskID=347363

[lzap@lzapx rubygem-foreman_discovery]$ gem compare -b foreman_discovery 4.0.0 4.1.0
Fetching: foreman_discovery-4.0.0.gem (100%)
Fetching: foreman_discovery-4.1.0.gem (100%)
Compared versions: ["4.0.0", "4.1.0"]
  DIFFERENT authors:
    4.0.0: ["Greg Sutcliffe"]
    4.1.0: ["Greg Sutcliffe", "Lukas Zapletal", "Ori Rabin"]
  DIFFERENT files:
    4.0.0->4.1.0:
      * Deleted:
            locale/ru/LC_MESSAGES/
            locale/de/LC_MESSAGES/
            locale/pt_BR/LC_MESSAGES/
            locale/en_GB/LC_MESSAGES/
            locale/zh_TW/LC_MESSAGES/
            locale/es/LC_MESSAGES/
            locale/fr/LC_MESSAGES/
            locale/it/LC_MESSAGES/
            locale/ja/LC_MESSAGES/
            locale/ko/LC_MESSAGES/
            locale/zh_CN/LC_MESSAGES/
            locale/gl/LC_MESSAGES/
            locale/sv_SE/LC_MESSAGES/
      * Added:
            app/services/foreman_discovery/node_api/
            app/views/foreman_discovery/
            app/services/foreman_discovery/node_api/node_resource.rb
              (!) Unexpected permissions: 100664
            app/services/foreman_discovery/node_api/power.rb
              (!) Unexpected permissions: 100664
            app/services/foreman_discovery/proxy_operations.rb
              (!) Unexpected permissions: 100664
            app/views/foreman_discovery/redhat_kexec.erb
              (!) Unexpected permissions: 100664
            db/seeds.d/50_discovery_templates.rb
              (!) Unexpected permissions: 100664
```

### CODE REVIEW

**Comment by domcleal** [comment]
> FYI the extra locale files were released as a mistake in 4.0.0.

I think 4.0.0 was correct - the .gem *should* contain .mo files, as they're used in production mode.  The .po files in the gem are only used in development.

**Comment by domcleal** [comment]
I should add - there's no step in the package build process for plugins to build .mo files from .po files.  We could add it, but that would only be useful for RPMs as that's the only place we distribute an unpacked gem.  Both source and Debian installations use packed gem files, so having the .mo is needed.

**Comment by domcleal** [comment]
And lastly, the .gem has been added in this PR as a binary and not using `git annex add`.

**Comment by domcleal** [comment]
Please note that what to do about the locales issue is entirely up to you, whether you want to fix it and simply package 4.1.1 or to ship it as-is without them, I meant it only for your information.

**Comment by lzap** [comment]
Yeah good point, I thought we agreed in not shipping MO files for GEMs as it will fallback to read PO files by default. It's the extra step in packaging process we don't have in Discovery now. Anyway, fixed the annex file, Debian package on the way.

**Comment by lzap** [comment]
http://koji.katello.org/koji/taskinfo?taskID=347710
http://koji.katello.org/koji/taskinfo?taskID=347711
http://koji.katello.org/koji/taskinfo?taskID=347712

**Comment by domcleal** [comment]
Thanks, I'll build for nightly.  If you'd like it for 1.9 too then cherry pick over to rpm/1.9, scratch build, tag and build, or open a PR or ask - though I'd suggest fixing locales first so it's not a regression for those users.

**Comment by domcleal** [comment]
I filed http://projects.theforeman.org/issues/11915 for you to track it.

**Comment by lzap** [comment]
Thanks

**Pull request merged**
