### PR TITLE
Update rubygem-foreman_ansible to 4.0.2

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by adamruzicka** [comment]
If I understand correctly this version cannot be released to develop/1.25 because the plugin depends on vendor <v2. Keeping this as a placeholder until develop/1.25-compatible version gets released

**Comment by evgeni** [comment]
that's correct. thanks!

**Comment by pcreech** [comment]
[test rpm]

**Comment by tbrisker** [comment]
This won't build, we need a new ansible release with https://github.com/theforeman/foreman_ansible/commit/2b0e1bd10175617fa0789e0ddd43bed2e450d0ba in it.

**Comment by ares** [comment]
This is replaced by https://github.com/theforeman/foreman-packaging/pull/4587, closing

**Pull request closed without merging**
