### PR TITLE
Add rubygem-qpid_proton gem package

### PR DESCRIPTION
**Pull request by jturel**

### CODE REVIEW

**Comment by jturel** [comment]
Looks like koji node doesn't have access to qpid-proton-cpp-devel: http://koji.katello.org/kojifiles/work/tasks/4230/394230/mock_output.log

**Comment by pcreech** [comment]
[test]

**Comment by pcreech** [comment]
[test rpm]

**Comment by evgeni** [comment]
#6231 contained a rubygem-qpid_proton, so is this obsolete then?

**Comment by ehelms** [comment]
Ha, I didnt even notice. I think we still need this in order to produce an SCL version of it for EL7. We just need to restrict this to only build on EL7.

**Comment by jturel** [comment]
@ehelms updated!

**Review by ehelms — APPROVED** [review]

**Pull request merged**
