### PR TITLE
Fix debian log rotation

### PR DESCRIPTION
**Pull request by mark-wagner**
Based on https://community.theforeman.org/t/smart-proxy-log-rotate-not-working/9904

### CODE REVIEW

**Comment by ekohl** [comment]
I'm not 100% sure how Debian's handled but I think we still maintain support for both systemd and sysvinit. We should prefer systemd but otherwise fall back to the current code.

**Comment by mark-wagner** [comment]
systemd has been the default init for Debian since jessie (8). Stretch is 9. It has been the default for Ubuntu since 15.04. Xenial is 16.04.

According to http://without-systemd.org/wiki/index.php/How_to_remove_systemd_from_a_Debian_Stretch_installation Debian still officially supports sysvinit. I was unable to find Ubuntu's support status but apparently it is possible: http://without-systemd.org/wiki/index.php/How_to_remove_systemd_from_an_Ubuntu_Xenial_installation

I don't want to get involved in an init war but IMHO it is time to drop support for sysvinit and eliminate the complications involved in supporting two init  systems.

**Comment by mmoll** [comment]
I'm quite sure that (almost?) all our DEB users are using the default, which is systemd these days.

However, adding a check (`test -d /run/systemd/system`) here doesn't cost much and will make potential systemd haters happy, so I'm kindly asking to add that check and continue to also support init as long as it's that cheap.

**Comment by ekohl** [comment]
It does sound like it's still easy to support non-systemd for now.

**Pull request closed without merging**
