### PR TITLE
Discovery hammer 1.0.1 update

### PR DESCRIPTION
**Pull request by lzap**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly

---

### CODE REVIEW

**Comment by lzap** [comment]
No updates for debian @mmoll because it is a dependency, correct?

**Comment by lzap** [comment]
Getting 404 on jenkins? [test]

**Comment by mmoll** [comment]
@lzap this also needs updating on the DEB side, a simple `./scripts/update_package.rb --name=hammer_cli_foreman_discovery --version=1.0.1` should do it there. :package:

**Comment by lzap** [comment]
Thanks pushed to rubygems, [test] [test rpm]

**Comment by lzap** [comment]
https://github.com/theforeman/foreman-packaging/pull/3968 for debian.

**Comment by ekohl** [comment]
I noticed this spec is pretty old so I regenerated it based on the current template: https://github.com/theforeman/foreman-packaging/pull/3969

**Comment by lzap** [comment]
Thanks closing than.

**Pull request closed without merging**
