### PR TITLE
Bump nodejs-patternfly-react to 2.17.3

### PR DESCRIPTION
**Pull request by ohadlevy**

### CODE REVIEW

**Comment by ekohl** [comment]
[test rpm]

**Comment by ohadlevy** [comment]
@ekohl there seems to be a bug in the script, as it generate lines in the SPEC such as 
```
Provides: bundled-npm() = babel/runtime-corejs2
```

I was able to workaround it manually, e.g.
```
Provides: bundled-npm(babel/runtime-corejs2) = 2.2.5
```

but for others (such as types/c3) I am not really sure where this comes from....

How to suggest I continue? thanks.

**Comment by ohadlevy** [comment]
also, maybe I'm looking it at it the wrong way? I added the package as bundled as I thought it should be, but I saw it originally wasn't so I'm uncertain if this was done before we had the script or some other reasoning ?

**Comment by ohadlevy** [comment]
[test]

**Comment by ohadlevy** [comment]
@ekohl thanks, updated, can you please have another look?

**Comment by ekohl** [comment]
It looks like there's some issue with the subdirectory support for sources. It looks like that's not really working well. Perhaps I need to rethink that. Hopefully I'll have time for it tomorrow so I can give an answer before my vacation starting Wednesday but I might not.

**Comment by ohadlevy** [comment]
closing in favor of #3024

**Pull request closed without merging**
