### PR TITLE
Pulpcore 3.16 update

### PR DESCRIPTION
**Pull request by ianballou**
Bumps the pulpcore pulp_rpm, and pulp_deb clients for Pulpcore 3.16.

### CODE REVIEW

**Review by jlsherrill — APPROVED** [review]
ack from me once the 3.16 repos are available

**Comment by Odilhao** [comment]
@jlsherrill Pulpcore 3.16 is now live, should I cherry-pick this into rpm/3.1?

**Comment by ianballou** [comment]
[test rpm]

**Comment by ianballou** [comment]
@Odilhao we should be good to cherry-pick these into 3.1.

**Comment by ianballou** [comment]
Does `foreman_max_version` in `rubygem-katello.spec` need to be bumped up to fix the build error?

I have this related PR: https://github.com/theforeman/foreman-packaging/pull/7297

**Comment by jlsherrill** [comment]
@ianballou thats being done here: https://github.com/theforeman/foreman-packaging/pull/7296/files

**Comment by jlsherrill** [comment]
@Odilhao lets wait till 3.16 is stable in master/nightly before we backport it to rpm/3.1

**Comment by Odilhao** [comment]
@jlsherrill ack

**Comment by ianballou** [comment]
[test rpm]

**Pull request merged**
