### PR TITLE
Fixes #17280 - Update dep in scap spec file

### PR DESCRIPTION
**Pull request by chris1984**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.13
* [ ] 1.12
* [ ] 1.11

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by domcleal** [comment]
1. This doesn't "update" the dep, it's removing it. It should be replaced by `openscap-scanner` according to the bug report.
1. EL6 is no longer supported, please close the PR or resubmit to an older branch (rpm/1.12).

**Comment by timspeetjens** [comment]
@domcleal
This package is required on the client to run openscap scans, did we stop supporting EL6 as target platform too?

**Comment by domcleal** [comment]
Yes, EL6 support was deprecated in Foreman 1.12, and not provided in 1.13.

**Comment by chris1984** [comment]
@domcleal ack closing and redoing for rpm/1.12 and changing dep instead of remvoing

**Pull request closed without merging**
