### PR TITLE
Fix katello-agent upgrades from old versions

### PR DESCRIPTION
**Pull request by jturel**
For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [x] 1.20
* [ ] 1.19
* [ ] 1.18

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by jturel** [comment]
Looking into the el5 failure..

**Comment by jturel** [comment]
I could work around the el5 failure but curious about it. There has not been much change to the spec, and the PR for 1.19 (#3190) is passing fine. Here's the diff b/t the two specs less the changelog section

```
17,18c17,18
< Version: 3.3.5
< Release: 4%{?dist}
---
> Version: 3.3.2
> Release: 2%{?dist}
80,82d79
< Obsoletes: python-pulp-agent-lib < 3.0
< Obsoletes: pulp-rpm-handlers < 3.0
< Obsoletes: python-pulp-rpm-common < 2.16.4
362c359
```

Could something be different in the el5 build environment between 1.20 and 1.19?

**Comment by evgeni** [comment]
It seems like it didn't process the assignments of `%{katello_libdir}` and `%{plugins_dir}`, which is weird.

**Comment by evgeni** [comment]
The difference from a Koji perspective is the Build Target: katello-3.8-rhel5 for 1.19 and foreman-client-1.20-rhel5-build for 1.20.

**Comment by evgeni** [comment]
looking at `koji list-groups katello-3.8-rhel5-build` vs `koji list-groups foreman-client-1.20-rhel5-build`, the latter is missing `buildsys-macros{,-rhel}`, so I did:

```
% koji add-group foreman-client-1.20-rhel5-build buildsys-macros
% koji add-group foreman-client-1.20-rhel5-build buildsys-macros-rhel
% koji regen-repo foreman-client-1.20-rhel5-build
```

Let's see if that fixes it!

[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
And it works if you tell Koji to do what you meant to do:

```
% koji add-group-pkg foreman-client-1.20-rhel5-build build buildsys-macros
% koji add-group-pkg foreman-client-1.20-rhel5-build srpm-build buildsys-macros
% koji regen-repo foreman-client-1.20-rhel5-build
```

fix for our toolbelt setup: https://github.com/theforeman/tool_belt/pull/125

@ehelms please tell me I did the right thing ;)

**Comment by evgeni** [comment]
EL5: http://koji.katello.org/koji/taskinfo?taskID=149933
EL6: http://koji.katello.org/koji/taskinfo?taskID=149936
EL7: http://koji.katello.org/koji/taskinfo?taskID=149937
F27: http://koji.katello.org/koji/taskinfo?taskID=149938
F28: http://koji.katello.org/koji/taskinfo?taskID=149940

**Pull request merged**
