### PR TITLE
Updated foreman-fog-proxmox to 0.8.2

### PR DESCRIPTION
**Pull request by tristanrobert**
Nightly

### CODE REVIEW

**Comment by mmoll** [comment]
@tristanrobert this version is for nightly all the way down to 1.22, I presume?

**Comment by tristanrobert** [comment]
Yes it is for nightly. The PR one for 1.22 is asked in #4311.

**Comment by mmoll** [comment]
@tristanrobert I'm asking because in this case usually we just "want"" the PR for nightly and then cherry-pick that change into the otehr brnaches, as 1.23 and 1.24 would get missed with a per-version approach.

So my real question is: Can the change in this PR be used for all versions from nightly to 1.22?

**Comment by tristanrobert** [comment]
Sorry I didn't understand your question. Yes this change can be used to 1.22. I have tried cherry-pick but the number of diff commits were to high between the two branches.

**Comment by mmoll** [comment]
merged, merci @tristanrobert!

**Comment by mmoll** [comment]
- 1.24: a2172bf
- 1.23: 57bd189
- 1.22: 5a96940

**Pull request merged**
