### PR TITLE
Add rubygem-vault package

### PR DESCRIPTION
**Pull request by timogoebel**
(cherry picked from commit 15d99e5a63619155e79e7c801811b7abcd20512b)

### CODE REVIEW

**Comment by timogoebel** [comment]
It looks like `tfm-rubygem(aws-sigv4)` is missing, but why?

**Comment by timogoebel** [comment]
[test rpm]

**Comment by timogoebel** [comment]
It still reports `tfm-rubygem(aws-sigv4)` as missing, but the package was added in #3612.

@ekohl or @evgeni: Mind taking a look?

**Comment by evgeni** [comment]
i dont see it in the .21 tag: http://koji.katello.org/koji/buildinfo?buildID=40511

**Comment by timogoebel** [comment]
@evgeni: Is there anything _I_ can do about that?

**Comment by ekohl** [comment]
No, it was my bad. I merged it but failed to release it. I've written a verification script to find mismatches.

[test rpm]

**Comment by timogoebel** [comment]
[test rpm]

**Comment by ekohl** [comment]
I've also kicked off the plugins pipeline so repoclosure can actually see the builds.
[test rpm]

**Comment by timogoebel** [comment]
💚

**Pull request merged**
