### PR TITLE
Release 3.0.0

### PR DESCRIPTION
**Pull request by pcreech**

### CODE REVIEW

**Comment by ekohl** [comment]
Looks like a CI failure in the Jenkins job rewrite. @ehelms @evgeni are you working on this already?

**Comment by evgeni** [comment]
Let me look into this.

**Comment by evgeni** [comment]
[test deb]

**Comment by ehelms** [comment]
[test deb]

**Review by evgeni — APPROVED** [review]
the builds failed at different stages, but that is due to the changes to the jobs

the release builds will happen on the old infra, so it should be safe

**Pull request merged**
