### PR TITLE
Update rubygem-foreman_vault to 0.1.0

### PR DESCRIPTION
**Pull request by UXabre**

### CODE REVIEW

**Comment by timogoebel** [comment]
@UXabre: Thanks!

This is my little "script" to bump the version of a rpm. I hope it shows all the necessary steps. You definitely need to remove the old gem and add the new gem via git-annex.

```bash
git checkout rpm/develop
gpull
git checkout -b ${FOREMAN_PLUGIN_NAME}_${FOREMAN_PLUGIN_RELEASE}

cd packages/plugins/rubygem-${FOREMAN_PLUGIN_NAME}/
git rm ${FOREMAN_PLUGIN_NAME}-*.gem

Change the version in the spec, set "Release" to 1

gsed -i -e "s/%changelog/%changelog\n* $(date +"%a %b %d %Y") Timo Goebel <mail@timogoebel.name> - ${FOREMAN_PLUGIN_RELEASE}-1\n- Update ${FOREMAN_PLUGIN_NAME} to ${FOREMAN_PLUGIN_RELEASE}\n/g" *.spec

wget https://rubygems.org/downloads/${FOREMAN_PLUGIN_NAME}-${FOREMAN_PLUGIN_RELEASE}.gem

git annex add ${FOREMAN_PLUGIN_NAME}-*.gem

git add -A
git commit -m "Update ${FOREMAN_PLUGIN_NAME} to ${FOREMAN_PLUGIN_RELEASE}"

git push -u fork ${FOREMAN_PLUGIN_NAME}_${FOREMAN_PLUGIN_RELEASE}

hub pull-request -m "Update ${FOREMAN_PLUGIN_NAME} to ${FOREMAN_PLUGIN_RELEASE}" -b 'theforeman:rpm/develop' -h ${FOREMAN_PLUGIN_NAME}_${FOREMAN_PLUGIN_RELEASE} -o

```

**Comment by ekohl** [comment]
For the record, https://github.com/theforeman/foreman-packaging/blob/rpm/develop/bump_rpm.sh should take care of this. It does need various RPM tools which can be challenging on a non-RH OS.

It doesn't do git push + hub, but big :+1: for those. I personally have an alias `git phr`. From `~/.gitconfig`
```ini
[alias]
        ph = "!git push $(whoami) HEAD --set-upstream --quiet"
        pr = "!hub pull-request"
        phr = "!git ph && git pr"
```

This does rely on my convention that I always have a remote `$(whoami)` that points to my fork.

**Comment by UXabre** [comment]
Hi! Thanks for your input guys, sorry, I didn't know what I was doing but I think I understand now.... (however, only one way to find out and that's...Waiting!)

Thanks for your input!

**Comment by timogoebel** [comment]
Looks good!

**Comment by timogoebel** [comment]
@UXabre: If you want to have the package in a specific version you need to cherry-pick the commit against a stable branch and open a PR.

```
git checkout rpm/1.24
git pull --ff-only
git checkout -b my-new-branch
git cherry-pick 0d043b6
git push ...
when opening the PR, select rpm/1.24 as the target branch.
```

**Comment by ekohl** [comment]
Please use `-x` when doing a cherry pick.

**Pull request merged**
