### PR TITLE
Update rubygem-foreman_virt_who_configure to 0.5.6

### PR DESCRIPTION
**Pull request by jturel**

### CODE REVIEW

**Comment by jturel** [comment]
@jeremylenz FYI - you can update the release config to this version

**Comment by jturel** [comment]
> @jturel It's already `0.5.6`, I think I must have gotten too excited speak_no_evil

Perfect! :lobster:

**Comment by jturel** [comment]
Hmm..

```
Getting requirements for tfm-rubygem-foreman_virt_who_configure-0.5.6-1.fm2_6.el7.src
 --> Already installed : scl-utils-build-20130529-19.el7.x86_64
 --> foreman-assets-2.6.0-0.1.develop.20210510142733gitbf9220a.el7.noarch
 --> foreman-plugin-2.6.0-0.1.develop.20210510142733gitbf9220a.el7.noarch
 --> tfm-rubygem-katello-4.2.0-0.1.pre.master.20210506231032git5d9a25d.el7.noarch
 --> rh-ruby27-ruby-libs-2.7.1-128.el7.x86_64
 --> rh-ruby27-ruby-2.7.1-128.el7.x86_64
 --> rh-ruby27-rubygems-devel-3.1.2-128.el7.noarch
Error: Package: tfm-rubygem-activestorage-6.0.3.7-1.el7.noarch (build)
           Requires: tfm-rubygem(marcel) >= 1.0.0
           Installing: tfm-rubygem-marcel-0.3.3-2.el7.noarch (build)
               tfm-rubygem(marcel) = 0.3.3
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by jturel** [comment]
@evgeni merge pls? :)

**Comment by evgeni** [comment]
@jturel it's @theforeman/packaging aka @pcreech this week, but I can make an exception ;)

**Review by evgeni — APPROVED** [review]

**Pull request merged**
