### PR TITLE
Update rubygem-hammer_cli_foreman_scc_manager to 0.3.0 rpm develop

### PR DESCRIPTION
**Pull request by nadjaheitmann**

### CODE REVIEW

**Comment by evgeni** [comment]
I wanted to complain about the hammer_cli dep, but you already fixed it in https://github.com/ATIX-AG/hammer-cli-foreman-scc-manager/commit/6ce836eca135f40a6c0cb7662ba794c02ff6088f 
♥

**Review by ekohl — CHANGES_REQUESTED** [review]
Repoclosure is still complaining about that:
> [2024-08-21T10:01:38.195Z]             (rubygem(hammer_cli_foreman) >= 3.10.0 with rubygem(hammer_cli_foreman) < 3.11)

We'll need to fix that in packaging or release 0.2.2 with that fix. Given you already merge that to master, I'd prefer a 0.2.2 release.

**Comment by nadjaheitmann** [comment]
I am going to bump a new version today. The hammer_cli depenency somehow slipped through the first fix we did yesterday :roll_eyes:

**Review by ekohl — APPROVED** [review]
:+1: when CI agrees

**Comment by nadjaheitmann** [comment]
I think the new translation files are causing the build to fail. I need to figure out how to fix that.

**Comment by nadjaheitmann** [comment]
New failure:
[2024-08-22T11:40:43.132Z] fatal: [rubygem-hammer_cli_foreman_scc_manager]: FAILED! => 
[2024-08-22T11:40:43.132Z]     changed: false
[2024-08-22T11:40:43.132Z]     command: dnf repoclosure --refresh --newest --config /tmp/ansible.ien9jhmlrepoclosure/yum.conf
[2024-08-22T11:40:43.132Z]         --arch noarch --arch x86_64 --check repo0 --repo repo0 --check el8-katello-nightly-staging
[2024-08-22T11:40:43.132Z]         --repo el8-katello-nightly-staging --repofrompath repo0,https://download.copr.fedorainfracloud.org/results/@theforeman/katello-nightly-staging-scratch-529e7de2-1f37-5c51-9fe5-3acb74df37ee/rhel-8-x86_64
[2024-08-22T11:40:43.132Z]         --repo el8-baseos --repo el8-appstream --repo el8-powertools --repo el8-extras
[2024-08-22T11:40:43.132Z]         --repo el8-puppet-7 --repo el8-foreman-nightly-staging --repo el8-foreman-plugins-nightly-staging
[2024-08-22T11:40:43.132Z]         --repo el8-candlepin-4.4-staging
[2024-08-22T11:40:43.132Z]     msg: Repoclosure failed
[2024-08-22T11:40:43.132Z]     output: |-
[2024-08-22T11:40:43.132Z]         Unable to detect release version (use '--releasever' to specify release version)
[2024-08-22T11:40:43.132Z]         Added repo0 repo from https://download.copr.fedorainfracloud.org/results/@theforeman/katello-nightly-staging-scratch-529e7de2-1f37-5c51-9fe5-3acb74df37ee/rhel-8-x86_64
[2024-08-22T11:40:43.132Z]         Error: Repoclosure ended with unresolved dependencies (1) across 1 packages.
[2024-08-22T11:40:43.132Z]         package: rubygem-katello-4.14.0-0.4.pre.master.20240819231915gite50aca7.el8.noarch from el8-katello-nightly-staging
[2024-08-22T11:40:43.132Z]           unresolved deps (1):
[2024-08-22T11:40:43.132Z]             foreman < 3.13

**Comment by nadjaheitmann** [comment]
As far as I can tell, Katello needs to be updated to a new version in foreman-packaging for this PR to get a green CI.

**Comment by evgeni** [comment]
[test rpm-copr]

**Pull request merged**
