### PR TITLE
Update puppet-agent-oauth to 0.5.5

### PR DESCRIPTION
**Pull request by antaflos**

### CODE REVIEW

**Comment by ekohl** [comment]
ok to test

**Comment by antaflos** [comment]
@ekohl I just updated the commit message to include the line you specified.

**Comment by ekohl** [comment]
I meant with `$current` the current message. So write `Fixes #34681 - Update puppet-agent-oauth to 0.5.5`

**Review by ekohl — APPROVED** [review]
Thanks! I'll try to be more explicit next time. You probably already noticed https://projects.theforeman.org/issues/34681#note-2 which tells you that linking worked. Once I merge it you should see more, like setting the Fixed in version field and setting the state to closed. The latter is on a cronjob so there's some delay in that.

**Pull request merged**
