### PR TITLE
Update dynflow to 0.7.8

### PR DESCRIPTION
**Pull request by iNecas**
The deb PR on its way

### CODE REVIEW

**Comment by domcleal** [comment]
Thanks @iNecas!

**Comment by domcleal** [comment]
Building for nightly plugin repo, let me know if you'd like it in older releases too.

**Comment by iNecas** [comment]
Just nightly AFAIK, thanks!

**Comment by ehelms** [comment]
I'd like to request this version in the 1.8 repos so that we can provide users a fix in Katello 2.2

**Comment by domcleal** [comment]
Sure, in progress.

**Pull request merged**
