### PR TITLE
[rpm/3.1] - Update rubygem-foreman_openscap to 5.1.1

### PR DESCRIPTION
**Pull request by Ron-Lavi**

### CODE REVIEW

**Comment by Ron-Lavi** [comment]
@theforeman/packaging could you take a look at this one?
the version on develop branch couldn't be cherry-picked, mostly because of https://github.com/theforeman/foreman_openscap/commit/22f3c43185ec036744f8b37f01da7b92e451734c
so I created this release (5.1.1) which includes the commit before that and cherry-picked 2 important fixes:
-  [Fixes #33972 - Fix tailoring file selection](https://github.com/theforeman/foreman_openscap/commit/086f7af001a587f711aeaf04b5045d3446e18099)
- [Fixes #34134 - removing the increment on the day of the week](https://github.com/theforeman/foreman_openscap/commit/808e8c3769e1601736c5e74d1d1eaaf4cb531a93)

**Comment by pcreech** [comment]
[test rpm]

**Comment by pcreech** [comment]
[test]

**Comment by evgeni** [comment]
[test rpm]

**Review by evgeni — APPROVED** [review]

**Pull request merged**
