### PR TITLE
Remove babel-preset-es2015

### PR DESCRIPTION
**Pull request by dLobatog**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.16
* [ ] 1.15
* [ ] 1.14

Follows https://github.com/theforeman/foreman-packaging/pull/1897

### CODE REVIEW

**Comment by dLobatog** [comment]
This is clearly not going to be able to build Foreman if nodejs-babel-preset-env isn't available, so if you want to ensure tests are green - https://github.com/theforeman/foreman-packaging/pull/1897 has to be merged first

**Comment by ares** [comment]
the build seems to fail

from http://koji.katello.org/kojifiles/work/tasks/5032/45032/build.log
```
ERROR in ./webpack/assets/javascripts/bundle.js
Module build failed: Error: Couldn't find preset "env" relative to directory "/builddir/build/BUILD/foreman-1.17.0"
    at /usr/lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:372:17
    at Array.map (native)
    at OptionManager.resolvePresets (/usr/lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
    at OptionManager.mergePresets (/usr/lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
    at OptionManager.mergeOptions (/usr/lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
    at OptionManager.addConfig (/usr/lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:207:10)
    at OptionManager.findConfigs (/usr/lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:413:16)
    at OptionManager.init (/usr/lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:461:12)
    at File.initOptions (/usr/lib/node_modules/babel-core/lib/transformation/file/index.js:194:75)
    at new File (/usr/lib/node_modules/babel-core/lib/transformation/file/index.js:123:22)
    at Pipeline.transform (/usr/lib/node_modules/babel-core/lib/transformation/pipeline.js:45:16)
    at transpile (/usr/lib/node_modules/babel-loader/lib/index.js:49:20)
    at Object.module.exports (/usr/lib/node_modules/babel-loader/lib/index.js:174:20)
RPM build errors:
```

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman-packaging/pull/1893 will be needed to fix the build but I don't know why it's failing.

**Comment by ehelms** [comment]
This needs a rebase please.

**Comment by ekohl** [comment]
Looks like the jenkins build can't handle removals but I think this is good now.

**Comment by ares** [comment]
what's the status here? the PR seems to be approved, perhaps [test] will help

the error from jenkins now
```
08:08:47 Can't open 'nodejs-babel-preset-es2015/*.spec': No such file or directory at /usr/bin/spectool line 314.
```

**Comment by ekohl** [comment]
@ares I think that jenkins can't handle deletions and we can merge this. Do we also untag a package when it's removed?

**Comment by ares** [comment]
that sounds reasonable but I defer to @theforeman/packaging maintainers :-)

**Comment by ekohl** [comment]
There's now a merge conflict. I think you should also remove ```rel-eng/packages/nodejs-babel-preset-es2015```

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
