### PR TITLE
foreman_datacenter 1.20.4

### PR DESCRIPTION
**Pull request by Zenya**

### CODE REVIEW

**Comment by mmoll** [comment]
Please release a new gem of this plugin, which is compatible with the newer Foreman versions. The 1.20.4 version of this plugin (at least on rubygems.org, no idea about the git repo as tehre are tags missing) has db-migrations without Rails version, which is fixed in the git repo.

**Comment by mmoll** [comment]
Especially https://github.com/theforeman/foreman_datacenter/commit/392993109e59ec82d1a9812d63241cd4b70046fc#diff-7de49e9208dab5a185ab6ef5080a53cc is missing for the released gem.

**Comment by mmoll** [comment]
[test packaging]

**Comment by mmoll** [comment]
looking again, this is not missing, but different:
```
mmoll@snow:/tmp/ruby-foreman-datacenter-1.20.4$ head -n1 db/migrate/20180725201545_add_location_id_and_organization_id_columns_to_devices.rb 
class AddLocationIdAndOrganizationIdColumnsToDevices < ActiveRecord::Migration
```

**Comment by ehelms** [comment]
@Zenya this is waiting on you for updates

**Pull request closed without merging**
