### PR TITLE
Update katello to 4.6.0

### PR DESCRIPTION
**Pull request by pcreech**

### CODE REVIEW

**Comment by evgeni** [comment]
@pcreech can you please pick the following change? https://github.com/theforeman/foreman-packaging/pull/8377/files

**Review by ekohl — CHANGES_REQUESTED** [review]
The faraday dependency needs to be dropped to reflect the cherry pick in rc2: https://github.com/Katello/katello/commit/91030e17480f3bb5ec15cd1f0cfd4e9494dcb6d1#diff-21cb8426e694930953a1fb66d2f1e4c0c4021bcadd760d9582423094a4dcaace

**Comment by ekohl** [comment]
I'd also like to get https://github.com/theforeman/foreman-packaging/pull/8429 in, but also wait for https://ci.theforeman.org/job/katello-nightly-rpm-pipeline/1421/ to complete so we at least know it works.

**Comment by pcreech** [comment]
> I'd also like to get #8429 in, but also wait for https://ci.theforeman.org/job/katello-nightly-rpm-pipeline/1421/ to complete so we at least know it works.

Ack.  @sjha4 for awareness.  will wait.

Previous two comments have been addressed.

**Pull request merged**
