### PR TITLE
Bumped smart_proxy_discovery to 1.0.2

### PR DESCRIPTION
**Pull request by lzap**
CC https://github.com/theforeman/foreman-packaging/pull/556

### CODE REVIEW

**Comment by domcleal** [comment]
If you can link a scratch build with your PRs, it'd be much appreciated.

http://ci.theforeman.org/job/packaging_build_deb_plugin/

**Comment by lzap** [comment]
Do you know what can be wrong?

http://ci.theforeman.org/job/packaging_build_deb_plugin/405/

```
Branch local set up to track remote branch deb/develop-smart-proxy-discovery-1-0-2 from origin.
+ cd plugins
+ mkdir build-smart_proxy_discovery
+ cd build-smart_proxy_discovery
+ cp -r ../smart_proxy_discovery ./
+ cd smart_proxy_discovery
+ ../../download_gems
../../download_gems: line 7: debian/gem.list: No such file or directory

wget: missing URL
Usage: wget [OPTION]... [URL]...
Try `wget --help' for more options.

mv: cannot stat `*gem': No such file or directory
Build step 'Execute shell' marked build as failure
```

**Comment by domcleal** [comment]
Apologies, I meant http://ci.theforeman.org/job/packaging_build_deb_proxy_plugin/ for proxy plugins.

**Comment by lzap** [comment]
http://ci.theforeman.org/job/packaging_build_deb_proxy_plugin/25/

**Comment by domcleal** [comment]
Thanks @lzap!  Building now.

**Pull request merged**
