### PR TITLE
Updated foreman_discovery to 6.0.0

### PR DESCRIPTION
**Pull request by lzap**
Received warning about incorrect GPL-3 licence, fixing that in develop branch.

I am holding off pushing the gem until I see this passing builds.

### CODE REVIEW

**Comment by lzap** [comment]
For the record:

```
WARNING:  WARNING: license value 'GPL-3' is invalid.  Use a license identifier from
http://spdx.org/licenses or 'Nonstandard' for a nonstandard license.
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
```

**Comment by lzap** [comment]
FYI

```
[lzap@lzapx foreman_discovery]$ gem compare -b foreman_discovery 5.0.2 6.0.0 -k
Fetching: foreman_discovery-5.0.2.gem (100%)
Compared versions: ["5.0.2", "6.0.0"]
  DIFFERENT files:
    5.0.2->6.0.0:
      * Deleted:
            app/helpers/concerns/foreman_discovery/
      * Added:
            locale/en/LC_MESSAGES/
            locale/en/
            app/controllers/api/v2/fact_values_controller_extensions.rb
              (!) Unexpected permissions: 100664
            app/models/concerns/discovery_taxonomy_extensions.rb
              (!) Unexpected permissions: 100664
            app/models/concerns/fact_value_extensions.rb
              (!) Unexpected permissions: 100664
            app/views/discovery_rules/_template_inline.erb
              (!) Unexpected permissions: 100664
            app/views/foreman_discovery/debian_kexec.erb
              (!) Unexpected permissions: 100664
            db/migrate/20160719124942_add_missing_view_permissions.rb
              (!) Unexpected permissions: 100664
            locale/en/LC_MESSAGES/foreman_discovery.mo
              (!) Unexpected permissions: 100664
            locale/en/foreman_discovery.edit.po
              (!) Unexpected permissions: 100664
            locale/en/foreman_discovery.po
              (!) Unexpected permissions: 100664
            test/functional/api/v2/fact_value_extensions_test.rb
              (!) Unexpected permissions: 100664
            test/unit/discovery_taxonomy_extensions_test.rb
              (!) Unexpected permissions: 100664
  DIFFERENT test_files:
    5.0.2->6.0.0:
      * Added:
            test/functional/api/v2/fact_value_extensions_test.rb
              (!) Unexpected permissions: 100664
            test/unit/discovery_taxonomy_extensions_test.rb
              (!) Unexpected permissions: 100664
```

**Comment by lzap** [comment]
https://rubygems.org/gems/foreman_discovery/versions/6.0.0

**Comment by lzap** [comment]
Working on Debian package, please build into 1.12 as well, thanks. Doco updates next week.

**Comment by domcleal** [comment]
1. Please use git-annex for the binary file, don't commit it directly to git.
2. Minimum Foreman version appears to be 1.12.0, update the requirements
3. It's a good idea to push git tags to the upstream repositories.

**Comment by lzap** [comment]
OMG all done. I was hoping to do this release properly ;-)

**Comment by domcleal** [comment]
Merging to rpm/develop, but since #3917 (strong params) was merged, it won't build here. Tests pass on rpm/1.12, so I'll build it there only for now.  Thanks @lzap.

**Comment by lzap** [comment]
Thanks, so the easy way out is to release 6.1 nightly only once I fix it.

**Comment by domcleal** [comment]
Yes, that's right.

**Pull request merged**
