### PR TITLE
Update foreman_bootdisk to 16.0.0

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by evgeni** [comment]
@mmoll remind me what needs to be done here now? just merge, or do I need to kick some job

**Comment by mmoll** [comment]
Merge and kick https://ci.theforeman.org/job/packaging_build_deb_plugin/ with the correct parameters (especially disabling gitrelease).

**Comment by mmoll** [comment]
This is also for 1.24, I presume?

**Comment by ekohl** [comment]
Sounds like we should spend time to improve the Debian release pipelines and automate it.

**Comment by ares** [comment]
yes

**Comment by evgeni** [comment]
well, let's see if I break debian stuff then :D

**Comment by evgeni** [comment]
https://ci.theforeman.org/job/packaging_build_deb_plugin/198 is running

**Pull request merged**
