### PR TITLE
Handle foreman-compute package on updates

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by evgeni** [comment]
Oh god, I hate replacing packages.

Should the replaces/breaks be versioned?
Should we also provide compute for anything depending on that name? (Is there anything?)

**Comment by mmoll** [comment]
> Oh god, I hate replacing packages.

It was only a deletion. ;)

> Should the replaces/breaks be versioned?

I hope not. 1.21 has foreman-compute, while 1.22 has not, so if one does add the 1.22 repo, any foreman-compute should get deinstalled.

>  Should we also provide compute for anything depending on that name? (Is there anything?)

There is nothing left. :scissors:

**Comment by evgeni** [comment]
Jenkins error is unrelated. :ship:

**Comment by evgeni** [comment]
@ekohl unrelated to the PR itself, but why was the `DEB` label only added now, and not when the PR was opened?

**Pull request merged**
