### PR TITLE
Add react-intl package

### PR DESCRIPTION
**Pull request by xprazak2**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.16
* [ ] 1.15
* [ ] 1.14

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

Second part of #1981

### CODE REVIEW

**Comment by ekohl** [comment]
There is now a merge conflict

**Comment by xprazak2** [comment]
Rebased.

**Comment by ekohl** [comment]
[test]

**Comment by ekohl** [comment]
Going to close this until it's actually needed by core.

**Pull request closed without merging**
