### PR TITLE
Update foreman-tasks to 0.7.2 into Foreman 1.9 (DEB)

### PR DESCRIPTION
**Pull request by iNecas**
Hey Mr. Jenkins, how do you like this branch, ha?

### CODE REVIEW

**Comment by iNecas** [comment]
[test]

**Comment by iNecas** [comment]
Jenkins, go home, you are drunk.

**Comment by domcleal** [comment]
There it goes.  GitHub statuses are per SHA rather than per SHA + PR, so it was cached there until the re-test is picked up (every 30 minutes).

**Comment by iNecas** [comment]
hooray-zoidberg

**Comment by domcleal** [comment]
Thanks, building.

**Pull request merged**
