### PR TITLE
Refs #19034 - add cronjob to notifications:clean task [Deb]

### PR DESCRIPTION
**Pull request by amirfefer**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.15
* [ ] 1.14
* [ ] 1.13

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ohadlevy** [comment]
if this is going to be cherry picked into 1.15.z then I suggest to build it for 1.15 too /cc @dLobatog ?

**Comment by domcleal** [comment]
Merged, thanks @amirfefer.

**Comment by dLobatog** [comment]
@ohadlevy ack, can anyone do that? I cannot cp stuff to the 1.15 branches here

**Comment by mmoll** [comment]
cherry-picked as 3f760d33

**Pull request merged**
