### PR TITLE
Update bump_rpm to handle global version macro

### PR DESCRIPTION
**Pull request by lzap**
This is not a package, not sure what the process is.

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
:-1: discovery is the only one. Last time I suggested to get rid of it, but this hasn't been implemented. I don't see a good reason to keep it.

**Comment by lzap** [comment]
I don't understand, I was asked by @evgeni to keep the macro. What's the correct approach then?

**Comment by evgeni** [comment]
No, I asked you to either use it properly or get rid of it (preferred):
https://github.com/theforeman/foreman-packaging/pull/5809#discussion_r490765192
https://github.com/theforeman/foreman-packaging/pull/5303#issuecomment-635204901

**Comment by lzap** [comment]
I falled into thinking the macro is something we want. I can remove it easily.

**Pull request closed without merging**
