### PR TITLE
Refs #29846 - replace awesome_print with amazing_print

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
Needs the amazing_print RPM first.

**Comment by tbrisker** [comment]
@mmoll i merged the foreman core PR as well, should we update that in this PR or a separate one?

**Comment by evgeni** [comment]
[test rpm]

**Comment by tbrisker** [comment]
is it failing because koji wasn't mashed yet with amazing_print? or some missing tag?
```

[2020-05-21T10:34:14.573Z]     package: tfm-rubygem-hammer_cli-2.2.0-0.2.pre.develop.20200521103053git919dc54.el7.noarch from downloaded_rpms
[2020-05-21T10:34:14.573Z]       unresolved deps:
[2020-05-21T10:34:14.573Z]         tfm-rubygem(amazing_print)

```

**Comment by evgeni** [comment]
Correct, not mashed yet.

**Pull request merged**
