### PR TITLE
bump @theforeman/vendor and builder

### PR DESCRIPTION
**Pull request by johnpmitsch**

### CODE REVIEW

**Comment by tbrisker** [comment]
[test rpm]

**Comment by johnpmitsch** [comment]
@tbrisker are these koji failures related to my changes?

**Review by tbrisker — COMMENTED** [review]
Looks like something is wrong with the registry cache, causing koji to try downloading from npm instead of using the tarballs provided. note that `nodejs-theforeman-builder/nodejs-theforeman-builder-6.0.0-registry.npmjs.org.tgz` is only 785 bytes compared to the 4.85MB that the previous one was. 
Looking at its contents it appears that it had an error during generation:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--cache',
1 verbose cli   '/tmp/tmp.yEEBfmj0OA/cache',
1 verbose cli   '@theforeman/builder@6.0.0',
1 verbose cli   '--no-shrinkwrap',
1 verbose cli   '--no-optional',
1 verbose cli   '--production',
1 verbose cli   '--verbose' ]
2 info using npm@6.14.2
3 info using node@v10.16.3
4 verbose stack TypeError: Class constructor LRUCache cannot be invoked without 'new'
4 verbose stack     at Object.<anonymous> (/usr/lib/node_modules/npm/lib/fetch-package-metadata.js:29:35)
4 verbose stack     at Module._compile (internal/modules/cjs/loader.js:778:30)
4 verbose stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
4 verbose stack     at Module.load (internal/modules/cjs/loader.js:653:32)
4 verbose stack     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
4 verbose stack     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
4 verbose stack     at Module.require (internal/modules/cjs/loader.js:692:17)
4 verbose stack     at require (internal/modules/cjs/helpers.js:25:18)
4 verbose stack     at Object.<anonymous> (/usr/lib/node_modules/npm/lib/install/deps.js:15:28)
4 verbose stack     at Module._compile (internal/modules/cjs/loader.js:778:30)
4 verbose stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
4 verbose stack     at Module.load (internal/modules/cjs/loader.js:653:32)
4 verbose stack     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
4 verbose stack     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
4 verbose stack     at Module.require (internal/modules/cjs/loader.js:692:17)
4 verbose stack     at require (internal/modules/cjs/helpers.js:25:18)
5 verbose cwd /tmp/tmp.yEEBfmj0OA/install
6 verbose Linux 4.20.3-200.fc29.x86_64
7 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--cache" "/tmp/tmp.yEEBfmj0OA/cache" "@theforeman/builder@6.0.0" "--no-shrinkwrap" "--no-optional" "--production" "--verbose"
8 verbose node v10.16.3
9 verbose npm  v6.14.2
10 error Class constructor LRUCache cannot be invoked without 'new'
11 verbose exit [ 1, true ]

**Comment by johnpmitsch** [comment]
@tbrisker It seems to be an issue with the builder package, I updated this to just be the vendor package and it builds fine. I'm trying to build locally but running into some environmental issues.

Any ideas why the builder package would be causing this issue?

**Comment by evgeni** [comment]
no, but I'll have a look

**Comment by evgeni** [comment]
hum, no idea, I didn't do anything differently, but https://github.com/theforeman/foreman-packaging/pull/6002 passed, so I'll just take that and your vendor ;)

**Review by evgeni — APPROVED** [review]

**Pull request merged**
