### PR TITLE
Updated rubygem-rbovirt to 0.0.36

### PR DESCRIPTION
**Pull request by lzap**
```
Compared versions: ["0.0.35", "0.0.36"]
  DIFFERENT files:
    0.0.35->0.0.36:
      * Added:
            lib/client/instance_type_api.rb
              (!) Unexpected permissions: 100664
            lib/client/operating_system_api.rb
              (!) Unexpected permissions: 100664
            lib/ovirt/instance_type.rb
              (!) Unexpected permissions: 100664
            lib/ovirt/operating_system.rb
              (!) Unexpected permissions: 100664
            spec/integration/instance_type_spec.rb
              (!) Unexpected permissions: 100664
  DIFFERENT test_files:
    0.0.35->0.0.36:
      * Added:
            spec/integration/instance_type_spec.rb
              (!) Unexpected permissions: 100664
```

### CODE REVIEW

**Comment by lzap** [comment]
Hmmm where do I find Debian package? I don't see it.

**Comment by domcleal** [comment]
There's no Debian package, as for Foreman core we ship a Bundler cache of the latest gems.  It'll update automatically.

**Comment by lzap** [comment]
Thanks!

**Comment by domcleal** [comment]
Thanks @lzap, building now.

**Pull request merged**
