### PR TITLE
Add rubygem-logging-journald package

### PR DESCRIPTION
**Pull request by lzap**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly

And the third dep. All the three were created from template, no changes
other then mentioned in the PRs.

For Debian I believe I don't need to do anything. Correct?

---

### CODE REVIEW

**Comment by lzap** [comment]
I just pushed missing tags [test].

**Comment by lzap** [comment]
Tags are present in my repo, what is wrong @ehelms ?

**Comment by ekohl** [comment]
Due to the directory restructure this now needs to be updated. Could you rebase the PR?

**Comment by lzap** [comment]
Rebased.

**Comment by dLobatog** [comment]
nightly - http://koji.katello.org/koji/taskinfo?taskID=82554

**Pull request merged**
