### PR TITLE
Update rubygem-smart_proxy_container_gateway to 1.0.5

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Review by ianballou — APPROVED** [review]
ACK once errors are gone.

**Comment by jlsherrill** [comment]
they look like el7 build root issues, lets try again

[test rpm]

**Review by ehelms — APPROVED** [review]

**Comment by ehelms** [comment]
[test rpm]

**Comment by evgeni** [comment]
This needs a different build than 2.5/develop, as it's built against ruby 2.7

**Pull request merged**
