### PR TITLE
Update rubygem-foreman_virt_who_configure to 0.5.18

### PR DESCRIPTION
**Pull request by chris1984**
@ekohl here is a new release with your translation fixes

### CODE REVIEW

**Comment by ekohl** [comment]
@ehelms I think we have a problem with our new EL8 nodes:
```
[2023-09-27T18:29:10.872Z] TASK [Check for a new changelog entry] *****************************************
[2023-09-27T18:29:10.872Z] fatal: [rubygem-foreman_virt_who_configure]: FAILED! => changed=false 
[2023-09-27T18:29:10.872Z]   module_stderr: |-
[2023-09-27T18:29:10.872Z]     /usr/bin/env: ‘python’: No such file or directory
[2023-09-27T18:29:10.872Z]   module_stdout: ''
[2023-09-27T18:29:10.872Z]   msg: |-
[2023-09-27T18:29:10.872Z]     MODULE FAILURE
[2023-09-27T18:29:10.872Z]     See stdout/stderr for the exact error
[2023-09-27T18:29:10.872Z]   rc: 127
```

This line doesn't work:
https://github.com/theforeman/obal/blob/997898860b73f8c7006b7d40de7dc9dd252c40f6/obal/data/modules/rpmspec_changelog_check.py#L1

**Comment by ehelms** [comment]
To fix that issue -- https://github.com/theforeman/obal/pull/367

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm-copr]

**Comment by ehelms** [comment]
[test rpm-copr]

**Comment by ehelms** [comment]
[test rpm-copr]

**Comment by ehelms** [comment]
[test rpm-copr]

**Comment by ehelms** [comment]
[test rpm-copr]

**Comment by ehelms** [comment]
[test rpm-copr]

**Comment by ehelms** [comment]
Note this ran against this change https://github.com/theforeman/jenkins-jobs/pull/355 which fixes repoclosure checks for Copr based scratch builds.

**Review by ekohl — APPROVED** [review]
Let's see if this fixes the luna pipeline.

**Pull request merged**
