### PR TITLE
[DEB] Add net-ssh-krb

### PR DESCRIPTION
**Pull request by adamruzicka**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.15
* [ ] 1.14
* [ ] 1.13

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by mmoll** [comment]
This will be a dependency and not a smart proxy plugin, correct? Then I have a few nits, but would like to wait until the rex-proxy PR itself went in.

**Comment by adamruzicka** [comment]
@mmoll It is a package which, if installed, enables certain feature in the remote execution plugin, but rex can work without it. So optional dependency would probably be the most accurate description

**Comment by adamruzicka** [comment]
@mmoll All the code PRs went in, could you please give me some feedback on this?

**Comment by mmoll** [comment]
I'll try to redo this (for inclusion into upstream Debian) and open a PR to your repo then in the next days.

**Comment by mmoll** [comment]
I added (slightly modified for older versions) files from the stuff I'll submit for upstream. Please move back everything you want to change (Maintainer and so on), and ping back.

As this is a dependency of a proxy plugin rather than a proxy plugin itself, I think it shouldn't get loaded directly via bundler-ext?

**Comment by adamruzicka** [comment]
@mmoll ping, so I set myself as maintainer for the package and also put myself into the changelog if that's ok with you. Could you please take a look at it again?

> As this is a dependency of a proxy plugin rather than a proxy plugin itself, I think it shouldn't get loaded directly via bundler-ext?

Sounds about right

**Comment by mmoll** [comment]
all fine then, merged, díky @adamruzicka!

**Pull request merged**
