### PR TITLE
Update rubygem-foreman_remote_execution to 1.8.4

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by adamruzicka** [comment]
Oh, completely forgot about that, let me get in touch with @iNecas and we'll figure out how to move both of these forward.

**Comment by ehelms** [comment]
@adamruzicka I am gonna merge and release https://github.com/theforeman/foreman-packaging/pull/4018 and then you can update this PR?

**Comment by adamruzicka** [comment]
Sounds good to me

**Comment by ehelms** [comment]
@adamruzicka merged, feel free to rebase

**Pull request merged**
