### PR TITLE
Update foreman_remote_execution to 0.0.10 (DEB)

### PR DESCRIPTION
**Pull request by iNecas**

### CODE REVIEW

**Comment by mmoll** [comment]
working fine here, merged, díky @iNecas!

**Comment by mmoll** [comment]
also merged as 1e0a98e for 1.10

**Comment by domcleal** [comment]
The 1.10 build failed probably because there aren't any Foreman packages in the archive at the moment - once RC1's out this week, we'll have to remember to rebuild it.

**Comment by iNecas** [comment]
Tested with 1.9 production: good to go to 1.9!

**Comment by iNecas** [comment]
+ 1.10 rc1 as well

**Comment by mmoll** [comment]
I'll sort out the whole dynflow/tasks/rex stuff later for DEB 1.9... :)

**Comment by iNecas** [comment]
I expect that should be handled by https://github.com/theforeman/foreman-packaging/pull/796, right?

**Comment by mmoll** [comment]
yep, but if I have time, I might be faster ;)

**Comment by stbenjam** [comment]
Will you do it or do you want me to update that PR? I was waiting for iteration 2 to be done to revisit it, but if you want to take care of it, go for it :-)

**Comment by mmoll** [comment]
also built for 1.10 now

**Pull request merged**
