### PR TITLE
Iteration 4 Main PR - Update foreman_remote_execution to 0.1.2 (RPM)

### PR DESCRIPTION
**Pull request by stbenjam**
This is the main PR.  Have to do the package dance :dancers: again, because there's new dependencies and updates.

Core
- [x] concurrent-ruby https://github.com/theforeman/foreman-packaging/pull/928
- [x] concurrent-ruby-edge https://github.com/theforeman/foreman-packaging/pull/931
- [x] dynflow https://github.com/theforeman/foreman-packaging/pull/930
- [x] parse-cron https://github.com/theforeman/foreman-packaging/pull/933
- [x] foreman-tasks https://github.com/theforeman/foreman-packaging/pull/932
- [ ] foreman_remote_execution (~~this pr~~ https://github.com/theforeman/foreman-packaging/pull/948)

Smart Proxy
- [x] smart_proxy_remote_execution_ssh https://github.com/theforeman/foreman-packaging/pull/936

Hammer
- [x] hammer plugin https://github.com/theforeman/foreman-packaging/pull/914

### CODE REVIEW

**Comment by domcleal** [comment]
Thanks for the PRs, especially the foreman-tasks updates which are required for Rails 4 compatibility I think.

Just so you're aware, the Rails 4 changes are being built on rpm/develop at the moment so I'm going to wait until the plugins repo's buildroot is ready with the refreshed packages before reviewing and re-testing these PRs.

**Comment by domcleal** [comment]
Most of the other PRs are reviewed and merged, but this one won't be possible as it depends on Rails 3.2.8, which isn't used in rpm/develop any more.

If you want this in rpm/1.10 then we can perhaps merge it to rpm/develop and build in rpm/1.10 if all of the deps are first cherry picked and built.

That said, there is a need for a compatible version to be built in rpm/develop in the next couple of weeks or the package will have to be temporarily removed from nightlies, see https://groups.google.com/forum/#!topic/foreman-dev/m7HrOIm3vIU for details.

**Comment by stbenjam** [comment]
We don't care too much about nightlies for now, as we've only been targeting stable releases.  I have no idea what the plans are to get rails 4 working in the plugin though, I'll let @iNecas comment on that.

But I don't think we're going to have an answer until after the holidays, I'm already off and will be back Jan 4th.  I think same for everyone else.

**Comment by iNecas** [comment]
Both merging updated version to nightlies and cherry-picking, or opening a PR against stable regardless of the niglties work for me

**Comment by stbenjam** [comment]
I opened a PR against rpm/1.10... https://github.com/theforeman/foreman-packaging/pull/948

**Comment by domcleal** [comment]
Thanks @stbenjam, merged because of the merge of rpm/1.10, but it'll remain unbuilt.

I'll send a message to -dev shortly too, but I'll probably (temporarily) remove it from the nightly repos in a week's time due to the incompatibility.

**Comment by domcleal** [comment]
Everything's now in the 1.10 plugin repos, hopefully that's all!

**Comment by stbenjam** [comment]
I'll give a try this afternoon.  Thanks!!

**Pull request merged**
