### PR TITLE
Update foreman_remote_execution_core to 1.0.4 (DEB, proxy)

### PR DESCRIPTION
**Pull request by iNecas**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.15
* [ ] 1.14
* [ ] 1.13

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by mmoll** [comment]
Unfortunately, smart-proxy plugins are completely different from copre plugin in our current Debian packaging... What you need to do here is to revert this entire change and update `dependencies/*/foreman_remote_execution_core` instead.

**Comment by iNecas** [comment]
Right. I hope I got it right now.

**Comment by mmoll** [comment]
Yes, that's good. 👍

**Comment by mmoll** [comment]
merged, díky @iNecas!

**Pull request merged**
