### PR TITLE
Release 1.21.0-RC1

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by chris1984** [comment]
[test rpm]

**Comment by tbrisker** [comment]
repoclosure step seems to be failing with `http://koji.katello.org/releases/yum/foreman-1.21/RHEL/7/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found` - perhaps some step on koji is missing?

**Comment by ekohl** [comment]
We haven't mashed (published) repos on koji yet so there's nothing to compare to.

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
Now it's the issue that it tries to do non-scl repoclosure on SCL'ed RPMs so I'm going to merge this and start the pipeline.

**Pull request merged**
