### PR TITLE
Fix statedir and shebang for smart_proxy_salt

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
This repoclosure failure would indicate we need to update the Requires on python to the python from the module. The salt-master requirement appears to be a bit more problematic as I do not see it in the configmanagement repo for CentOS or in EPEL.

**Comment by m-bucher** [comment]
This fix is included in #5371, so I guess this one can be closed, @adamruzicka!?

**Comment by adamruzicka** [comment]
That's true, closing.

**Pull request closed without merging**
