### PR TITLE
Add rubygem-fog-kubevirt package

### PR DESCRIPTION
**Pull request by masayag**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.21
* [ ] 1.20

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by masayag** [comment]
@ekohl the complaint is about kubeclient (ruby client for kubernetes that is used by fog-kubevirt)
```
[2019-04-18T19:46:58.847Z]     package: tfm-rubygem-fog-kubevirt-1.2.4-1.el7.noarch from downloaded_rpms

[2019-04-18T19:46:58.847Z]       unresolved deps:

[2019-04-18T19:46:58.847Z]          tfm-rubygem(kubeclient) < 0:4.2

[2019-04-18T19:46:58.847Z]          tfm-rubygem(kubeclient) >= 0:4.1.2
```

Does [kubeclient](https://github.com/abonas/kubeclient/blob/master/kubeclient.gemspec) be packaged as well ? and if so, does it mean that any of its dependencies should be packaged as well ?

**Comment by masayag** [comment]
@ekohl also, is it possible to ask add_gem to create a packaging for an older version of a gem ?

**Comment by ekohl** [comment]
Dependencies do need to be added. Since they're build time dependencies (`BuildRequires`) they need to be a separate PR (in our process). Usually a single PR for all dependencies works since they're often at most runtime dependencies (`Requires`) of each other.

**Comment by ekohl** [comment]
And to add an older version of a gem is a bit tricky. It's not a workflow we often see so it's a bit of manual work. Your approach of add & bump is probably the easiest way, but please do squash the changelog and commits into one you at least have the illusion of a single step in our history.

**Comment by masayag** [comment]
Closing this one in favor of a unified PR for all foreman_kubevirt dependencies

**Pull request closed without merging**
