### PR TITLE
Update katello package dependencies

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by evgeni** [comment]
Seems like vendor and angular need an update

**Comment by ekohl** [comment]
I've pinged the authors of the PRs that actually changed these deps since I don't have time to update them. Anyone, feel free to pick this up.

**Comment by evgeni** [comment]
I'll pick that up as part of "make it build with pulpcore 3.2"

**Comment by ehelms** [comment]
I think some of these have made it in so this needs an update.

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman-packaging/pull/4963 is needed for this.

**Comment by ehelms** [comment]
[test rpm]

**Comment by ekohl** [comment]
I manually stripped the `b...` parts from pulp gems.

**Comment by ekohl** [comment]
I guess this is from @evgeni's change
`/var/tmp/rpm-tmp.i26CWy: line 70: [: missing `]'`

**Comment by ehelms** [comment]
[test rpm]

**Pull request merged**
