### PR TITLE
Add source_location in build_vars.sh for nightly packages

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
@ekohl want to give your thoughts? @evgeni are you good with the approach?  The CI PR https://github.com/theforeman/jenkins-jobs/pull/128 is up to date based on this PR.

**Comment by ekohl** [comment]
I think this is ok. The only consideration I have is with #7202 and merge conflicts. There's probably already a few so I'd prefer to avoid rebasing all the time.

**Comment by ehelms** [comment]
Updated and rebased on https://github.com/theforeman/foreman-packaging/pull/7202

**Review by ekohl — APPROVED** [review]
I think we can try this out.

**Review by evgeni — APPROVED** [review]

**Pull request merged**
