### PR TITLE
Update katello-pull-transport-migrate to 1.0.2

### PR DESCRIPTION
**Pull request by adamruzicka**
- Correct website for katello-pull-transport-migrate
- Update katello-pull-transport-migrate to 1.0.2

### CODE REVIEW

**Comment by ekohl** [comment]
Looks like a network issue on the EL9 build
[test rpm]

**Comment by ekohl** [comment]
I'm not sure where this comes from, but it's persistent:
```
Error: Error downloading packages:
  openssl-libs-1:3.0.1-18.el9.x86_64: Download failed: Status code: 404 for http://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/Packages/openssl-libs-3.0.1-18.el9.x86_64.rpm (IP: 34.219.42.16)
```

**Comment by ekohl** [comment]
I ran `koji regen-repo foreman-client-3.3-el9`. Let's see if that helps.
[test rpm]

**Comment by ekohl** [comment]
@pcreech any idea? did I regen the wrong tag?

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Pull request merged**
