### PR TITLE
proxy picks for 2.1

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
@lzap @adamruzicka would you mind having a brief look that this should go to 2.1 as is?

**Comment by adamruzicka** [comment]
LGTM

**Comment by evgeni** [comment]
"Version updated but release was not reset back to 1 for rubygem-smart_proxy_dns_infoblox" because this touches it twice. Meh.

**Comment by ekohl** [comment]
Sounds like one we should disable for stable branches where we might pick multiple changes (like now).

**Comment by evgeni** [comment]
dropped the infoblox bump, lzap said it's not needed

**Pull request merged**
