### PR TITLE
Update rubygem-fog-openstack to 0.1.25

### PR DESCRIPTION
**Pull request by dLobatog**
Solution for https://bugzilla.redhat.com/show_bug.cgi?id=1513932

For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.18
* [x] 1.17
* [x] 1.16

### CODE REVIEW

**Comment by ekohl** [comment]
I wonder why the build failed and I can't see the results. Probably already rotated away.
[test rpm]

**Comment by pcreech** [comment]
```
error: Installed (but unpackaged) file(s) found:
   /opt/theforeman/tfm/root/usr/share/gems/gems/fog-openstack-0.1.25/docker-compose.yml
```
It looks like a new file is installed, docker-compose.yml that isn't listed in the spec file

**Comment by ekohl** [comment]
Sounds like a candidate for `%exclude`

**Comment by pcreech** [comment]
ACK

**Comment by ehelms** [comment]
I did nightly and 1.18 so far, @mmoll mentioned updating something which I wasn't sure if would be needed for 1.17 and 1.16 so I have not done those yet

**Pull request merged**
