### PR TITLE
Bump foreman_statistics to 1.0

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Removes cron job, packages version 1.0

- [x] Merge: https://github.com/theforeman/foreman_statistics/pull/19
- [x] Relase foreman_statistics, and include it here

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
[test packaging]

**Comment by tbrisker** [comment]
I think you need to separate the core removal of the cronjob from the release to another pr for it to pass

**Comment by ezr-ondrej** [comment]
Cron job removal extracted to #5784

**Review by evgeni — APPROVED** [review]

**Comment by evgeni** [comment]
build in https://ci.theforeman.org/job/packaging_build_deb_plugin/598

**Pull request merged**
