### PR TITLE
Update rubygem-foreman-tasks-core to 0.3.3

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by adamruzicka** [comment]
[test rpm]

**Comment by adamruzicka** [comment]
```
[2019-10-18T07:55:20.740Z]     package: tfm-rubygem-foreman-tasks-core-0.3.3-1.fm1_24.el7.noarch from downloaded_rpms
[2019-10-18T07:55:20.740Z]       unresolved deps:
[2019-10-18T07:55:20.740Z]          rh-ruby25-ruby(rubygems)
[2019-10-18T07:55:20.740Z]          rh-ruby25-ruby(release)
[2019-10-18T07:55:20.740Z]          rh-ruby25-ruby
```

Any pointers what to do about this?

**Comment by adamruzicka** [comment]
@ekohl any pointers?

**Comment by adamruzicka** [comment]
[test rpm]

**Comment by adamruzicka** [comment]
[test rpm]

**Comment by ekohl** [comment]
@ehelms in 3c6439a288d21e93f02efb7481048a4d19fe52fd you moved these into the proxy plugins group, but that's non-SCL while they should be SCL. Do we need a proxy plugins scl and proxy plugins non-scl?

**Comment by evgeni** [comment]
I have opened https://github.com/theforeman/foreman-packaging/pull/4363 to try out @ekohl's suggestion, but am not sure this is really needed given we're switching to proxy-fullscl soon anyways.

@ehelms what do you say?

**Comment by evgeni** [comment]
Thanks Eric!

**Pull request merged**
