### PR TITLE
Update foreman_chef to 0.7.0

### PR DESCRIPTION
**Pull request by ares**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.18
* [x] 1.17
* [ ] 1.16

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by mmoll** [comment]
Shouldn't this go striaght to deb/1.17? (and GH-2612 to deb/develop and deb/1.18)

**Comment by mmoll** [comment]
cherry-picked to deb/1.17 as 4f801bc02f, díky @ares!

**Comment by ares** [comment]
Yes, though people using nightlies usually can choose between multiple versions as we keep all packages versions in that repo, which is why I opened it this way. Or AFAIK that's how rpms nightlies work.

**Comment by mmoll** [comment]
yes, RPM is different.

**Comment by ekohl** [comment]
Let's continue this discussion in https://community.theforeman.org/t/carrying-only-latest-plugins-in-nightly/9900 :)

**Pull request closed without merging**
