### PR TITLE
Discovery 15.0.2

### PR DESCRIPTION
**Pull request by lzap**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly

---

### CODE REVIEW

**Comment by mmoll** [comment]
@lzap Also for 1.22 and 1.23, I presume?

**Comment by mmoll** [comment]
I went ahead and cherry-picked it to those stable branches, díky @lzap!

**Comment by lzap** [comment]
Well I haven't tested 1.22 honestly, it should work but I'd rather not try my luck :-)

**Comment by lzap** [comment]
Oh wait scratch that this is 0.2 okay. sure.

**Pull request merged**
