### PR TITLE
Add nodejs-patternfly-react-catalog-view-extension package

### PR DESCRIPTION
**Pull request by evgeni**
(cherry picked from commit b2ee5e7af99d6626e7ece6245e6241359ca1ccfb)

### CODE REVIEW

**Comment by evgeni** [comment]
required for #6726

**Review by pcreech — APPROVED** [review]
ack

**Comment by Odilhao** [comment]
looks good to me

**Comment by evgeni** [comment]
koji dance:

allow new packages in the tags:
```console
% koji add-pkg foreman-plugins-2.5-rhel7  tfm-nodejs-patternfly-react-catalog-view-extension --owner=kojiadm
Adding 1 packages to tag foreman-plugins-2.5-rhel7

% koji add-pkg foreman-plugins-2.5-el8 nodejs-patternfly-react-catalog-view-extension --owner=kojiadm
Adding 1 packages to tag foreman-plugins-2.5-el8
```

tag the builds from nightly, as koji won't build a build that already exists
```console
% koji tag-build foreman-plugins-2.5-rhel7 tfm-nodejs-patternfly-react-catalog-view-extension-4.11.25-1.el7
Created task 428865
Watching tasks (this may be safely interrupted)...
428865 tagBuild (noarch): free
428865 tagBuild (noarch): free -> closed
  0 free  0 open  1 done  0 failed

428865 tagBuild (noarch) completed successfully

% koji tag-build foreman-plugins-2.5-el8 nodejs-patternfly-react-catalog-view-extension-4.11.25-1.el8 
Created task 428878
Watching tasks (this may be safely interrupted)...
428878 tagBuild (noarch): free
428878 tagBuild (noarch): free -> closed
  0 free  0 open  1 done  0 failed

428878 tagBuild (noarch) completed successfully
```

**Pull request merged**
