### PR TITLE
Bump nodejs-patternfly-react to 2.18.0

### PR DESCRIPTION
**Pull request by ohadlevy**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.19
* [ ] 1.18
* [ ] 1.17

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ohadlevy** [comment]
@ehelms do you happen to have an idea why it fails? I've noticed the scripts now made changes to the SPEC structure, could there be an issue there? thanks. sadly this is blocking currently multiple PR's that we hope to land asap to make 1.20. thanks!

**Comment by ehelms** [comment]
RPM does not handle nested sources, so format such as `nodejs-patternfly-react/@babel/runtime-corejs2-7.0.0.tgz` is failing as it not finding it in the buildroot. I think that has to be flattened.

**Comment by ohadlevy** [comment]
in that case what exactly should i do? create a single for runtime-corejs2
and bundle for pf-react?

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman-packaging/pull/3038 replaced this

**Pull request closed without merging**
