### PR TITLE
Update rubygem-foreman_ansible to 7.0.3

### PR DESCRIPTION
**Pull request by stejskalleos**

### CODE REVIEW

**Comment by stejskalleos** [comment]
[test rpm]

**Comment by zjhuntin** [comment]
[test rpm]

**Comment by stejskalleos** [comment]
Can anybody from packaging take a look why the build is failing?

**Comment by dgoetz** [comment]
In the root.log from the koji build it is complaining:

**Comment by stejskalleos** [comment]
> In the root.log from the koji build it is complaining:
> 
> ```
> DEBUG util.py:600:  No matching package to install: 'npm(@theforeman/builder) < 9.0.0'
> DEBUG util.py:600:  Not all dependencies satisfied
> DEBUG util.py:600:  Error: Some packages could not be found.
> ```

Thanks, `npm` was indeed that problem. Now it's green

**Review by zjhuntin — APPROVED** [review]

**Pull request merged**
