### PR TITLE
Remote Execution - Iteration 5 - Develop (RPM)

### PR DESCRIPTION
**Pull request by stbenjam**
Needs new foreman tasks, other than that we should be able to build everything else in one PR.

Nightly only.  Separate PR will be for 1.10.

- [x] smart_proxy_remote_execution_ssh
- [x] hammer rex
- [x] hammer tasks
- [x] smart proxy dynflow
- [x] foreman remote execution 0.2.1

### CODE REVIEW

**Comment by stbenjam** [comment]
Hm, what'd I screw up here?

```
DEBUG util.py:388:  Error: No Package found for tfm-rubygem(dynflow) >= 0.8.8
```
This is the nightly repos:

tfm-rubygem-dynflow-0.8.9-1.fm1_11.el7.noarch.rpm

**Comment by domcleal** [comment]
Add the package back to comps/ as it was removed.  It looks like the test job is defaulting to the regular Foreman tag, not the plugins tag.

**Comment by stbenjam** [comment]
It's in comps

```
./comps-foreman-plugins-rhel7.xml:      <packagereq type="default">tfm-rubygem-foreman_remote_execution</packagereq>
./comps-foreman-plugins-fedora19.xml:      <packagereq type="default">rubygem-foreman_remote_execution</packagereq>
./comps-foreman-plugins-rhel6.xml:      <packagereq type="default">tfm-rubygem-foreman_remote_execution</packagereq>
```

**Comment by stbenjam** [comment]
Oh, right, nevermind! I got it, thanks

**Comment by domcleal** [comment]
Thanks @stbenjam, merged and all building now.

**Pull request merged**
