### PR TITLE
Bindings updates for pulpcore 3.3

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by zjhuntin** [comment]
[test rpm]

**Comment by evgeni** [comment]
@zjhuntin please don't merge this, @jlsherrill and I are waiting on pulpcore 3.3.1

**Comment by zjhuntin** [comment]
@evgeni ack, sorry I just saw your message on the other one too. I'll wait till I hear more approval for it.

**Comment by evgeni** [comment]
Yeah, no worries, I talked to Justin on IRC but forgot to update here

**Pull request merged**
