### PR TITLE
fixes #7228 -  rebuild packages under ror41/ruby22 SCLs [RPM]

### PR DESCRIPTION
**Pull request by domcleal**
This is the corresponding RPM packaging PR for https://github.com/theforeman/foreman/pull/2870, to update our packages to use new software collections for Rails 4.1.  Changes fall into these categories:

1. Ruby 1.9.3 (ruby193) moved to Ruby 2.2 (rh-ruby22).  This skips a number of generations of Fedora packaging, requiring changes from ruby(abi) to ruby(release), from minitest to test-unit and package updates or fixes to tests for Ruby version compatibility.  Only EL6 non-SCL packages still use ruby(abi).  A few specs using older styles were refreshed to make them build again (particularly around native libraries and gem install commands).
1. Rails packages split from scl_ruby to scl_ror.  Dependencies on %{scl_prefix_ruby} are changed to _ror throughout for [Rails packages](https://www.softwarecollections.org/repos/rhscl/rh-ror41/epel-7-x86_64/), as only a few are left in the core Ruby SCL.
1. Foreman Rails 4 updates.  A series of new packages and package updates to match the Gemfile changes in core Foreman.  Package removals too where newer SCLs have the required versions.

Test repositories:

* EL6:
    * https://www.softwarecollections.org/en/scls/rhscl/rh-ror41/epel-6-x86_64/download/rhscl-rh-ror41-epel-6-x86_64.noarch.rpm
    * https://www.softwarecollections.org/en/scls/rhscl/rh-ruby22/epel-6-x86_64/download/rhscl-rh-ruby22-epel-6-x86_64.noarch.rpm
    * https://copr.fedoraproject.org/coprs/domcleal/foreman-ror41/repo/epel-6/domcleal-foreman-ror41-epel-6.repo
    * https://copr.fedoraproject.org/coprs/domcleal/foreman-ror41-scl/repo/epel-6/domcleal-foreman-ror41-scl-epel-6.repo
    * https://copr.fedoraproject.org/coprs/domcleal/foreman-ror41-nonscl/repo/epel-6/domcleal-foreman-ror41-nonscl-epel-6.repo
* EL7:
    * https://www.softwarecollections.org/en/scls/rhscl/rh-ror41/epel-7-x86_64/download/rhscl-rh-ror41-epel-7-x86_64.noarch.rpm
    * https://www.softwarecollections.org/en/scls/rhscl/rh-ruby22/epel-7-x86_64/download/rhscl-rh-ruby22-epel-7-x86_64.noarch.rpm
    * https://copr.fedoraproject.org/coprs/domcleal/foreman-ror41/repo/epel-7/domcleal-foreman-ror41-epel-7.repo
    * https://copr.fedoraproject.org/coprs/domcleal/foreman-ror41-scl/repo/epel-7/domcleal-foreman-ror41-scl-epel-7.repo
    * https://copr.fedoraproject.org/coprs/domcleal/foreman-ror41-nonscl/repo/epel-7/domcleal-foreman-ror41-nonscl-epel-7.repo

TODO list:

* [x] Rebase
* [x] Build test EL6 repo
* [x] Build non-SCL test repos to check for regressions
* [x] Build non-SCL plugin repos to check for regressions
* [x] Update foreman-release-scl dependencies
* [x] SCL repoclosure
* [x] non-SCL repoclosure
* [x] Obsolete removed packages
* [x] Upgrade testing
* [ ] Build plugins that depend on foreman (may require plugin releases)
    * [x] Core plugin asset compilation fixed
    * [x] rubygem-bastion: http://projects.theforeman.org/issues/12515, #924
    * [ ] rubygem-foreman_bootdisk: https://github.com/theforeman/foreman_bootdisk/pull/18
    * [x] rubygem-foreman_cockpit
    * [ ] rubygem-foreman_deployments: needs -tasks
    * [ ] rubygem-foreman_discovery: https://github.com/theforeman/foreman_discovery/pull/228
    * [ ] rubygem-foreman_docker: #923
    * [ ] rubygem-foreman_setup: https://github.com/theforeman/foreman_setup/pull/23
    * [ ] rubygem-foreman-tasks: package 0.7.8
    * [x] rubygem-foreman_openscap
    * [ ] rubygem-foreman_remote_execution: needs -tasks
    * [ ] rubygem-foreman_salt: needs -tasks
* [x] Fix rspec-rails repoclosure failure, or remove via #887
* [x] Fix Passenger startup error (extensions not built)
* [x] Fix pg ruby_thread_select error
* [x] Fix Passenger startup error (`'trap': Invalid argument - SIGKILL (Errno::EINVAL)`)
* [x] Support in Foreman core for Ruby 2.2 (http://projects.theforeman.org/issues/12219), downgrade pg to 0.15.x
* [x] Switch to jquery-rails 3.1
* [x] Removal of workarounds after core Foreman is fixed
* [x] Sync new collections to Koji
* [ ] Adopt a newer Fedora release (#7229)

PR test failures are expected, since Koji can't chainbuild all of this properly!

### CODE REVIEW

**Comment by ehelms** [comment]
I attempted to try this out myself and look into the bastion issue, when I try to build using the `mock/el6-scl.cfg` I am seeing this type of output:

```
 --> 1:tfm-rubygem-angular-rails-templates-0.1.2-3.el6.noarch
Error: Package: tfm-rubygem-secure_headers-1.4.1-2.el6.noarch (foreman)
           Requires: ruby193-ruby(abi) = 1.9.1
Error: Package: tfm-rubygem-foreigner-1.7.1-2.el6.noarch (foreman)
           Requires: ruby193-rubygem(activerecord) >= 3.0.0
```

I feel like I must be missing something simple.

**Comment by domcleal** [comment]
The mock config doesn't point to builds of all of those dependencies, it still points to nightly and a little Copr repo containing the tfm package.  If you add this repo (and maybe remove nightly temporarily), it should work to rebuild just bastion: https://copr.fedoraproject.org/coprs/domcleal/foreman-ror41-scl/repo/epel-6/domcleal-foreman-ror41-scl-epel-6.repo

**Comment by ehelms** [comment]
I switched bastion to use the default foreman_precompile_plugin (previously we used a custom one due to Rails 3.2.8 issues) and the issue you saw went away. However, a new issue arose because Bastion doesn't have any apipie configuration and precompile runs both assets and apipie caching:

```
NoMethodError: undefined method `apipie_ignored_controllers' for nil:NilClass
/builddir/build/BUILD/rubygem-bastion-2.0.3/usr/share/foreman/lib/tasks/plugin_apipie.rake:14:in `block in <top (required)>'
```

So, would you prefer that macro be split into two functionalities or patch the Rake task to ignore the caching if certain settings are not set? Alternatively, we could split the macro into two.

**Comment by domcleal** [comment]
The macro should already be split in two - it accepts flags, `-a` for API docs and `-s` for a*s*sets.  It looks like rubygem-bastion only uses the latter, so I'm puzzled as to why you'd see API docs precompiled.

**Comment by ehelms** [comment]
I completely missed those switching options. I believe this fix (https://github.com/theforeman/foreman/pull/2870#issuecomment-158463897) should in the end solve the issue you are seeing here as it will remove those source comments from the assets.

**Comment by domcleal** [comment]
I've been refreshing the repos this week, and they're up to date currently with this branch.  Foreman now works under PostgreSQL and Passenger, so it's pretty much complete with the exception of plugins (which will have to be fixed as and when they release).

**Comment by ehelms** [comment]
I've released Bastion 2.0.4 which fixes an issue that prevented it's use of the normal plugin asset precompile task during RPM build.

**Comment by domcleal** [comment]
@ehelms could you go ahead and build that on rpm/develop now if it's 3.2 compatible to save time later?

**Comment by domcleal** [comment]
Before merging this I want to check whether the pg 0.18.2 update is going to be too new or not, per @ehelms' comment at http://projects.theforeman.org/issues/12219#note-6.  If we need to pin it to 0.15 in Foreman then I'd rather update just to that to avoid having to downgrade it again.

**Comment by domcleal** [comment]
Rebuild status:

- [ ] Change external repository config to use new SCL repos
- [ ] Update buildroot groups to include new scldevel pacakges
- [ ] Build tfm (stage 1 bootstrap)
- [ ] Build core dependencies (stage 2, 101 packages)
- [ ] Build core dependencies (stage 3, 6 packages)
- [ ] Build core dependencies (stage 4, 4 packages)
- [ ] Build core Foreman package (stage 5, 1 package)
- [ ] Build plugin dependencies (stage 1, 53 packages)
- [ ] Build plugins (stage 2, 8 packages)
- [ ] Build plugins (stage 3, 3 packages)
- [ ] Push nightly repos
- [ ] Push plugin repos

**Pull request merged**
