### PR TITLE
Update rubygem-pulp_2to3_migration to 0.0.1rc1

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
Note that this will require https://github.com/Katello/katello/pull/8569/files and a packaging update for that first

**Comment by jlsherrill** [comment]
Also, reminder to myself to backport this to 2.0

**Comment by jlsherrill** [comment]
katello pr here: https://github.com/theforeman/foreman-packaging/pull/4738

**Comment by jlsherrill** [comment]
katello pkg pr is merged, repoclosure failure i think is an issue with repoclosure

**Comment by jlsherrill** [comment]
[test rpm]

**Comment by evgeni** [comment]
this lowers the version from 0.0.1a1-1 to 0.0.1-0.1.rc1, so repoclosure is not happy and so won't the clients who already have a1 installed. you might want to add an epoch?

**Comment by ekohl** [comment]
I'd avoid an epoch and just keep a `1` release instead of `0.1`.

**Comment by evgeni** [comment]
@ekohl 0.0.1a1-1 > 0.0.1-1

**Comment by ekohl** [comment]
Given they're so low in version numbers I'd prefer to release a new version rather than to start with epochs already.

**Comment by jlsherrill** [comment]
I ended up bumping epoch, i don't think asking the pulp team to bump their version is the right thing to do

**Comment by jlsherrill** [comment]
all green!

**Pull request merged**
