### PR TITLE
Updated foreman_discovery to 4.0.0

### PR DESCRIPTION
**Pull request by lzap**
RPMs: https://github.com/theforeman/foreman-packaging/pull/743

### CODE REVIEW

**Comment by mmoll** [comment]
working fine here, is ```foreman (>= 1.8.0~rc1)``` still correct?

**Comment by lzap** [comment]
> working fine here, is ```foreman (>= 1.8.0~rc1)``` still correct?

Oh right, not at all. Changed to `1.9.0~rc1`. Will that hit rc2, 3 and
the final release? I think so.

-- 
Later,
 Lukas #lzap Zapletal

**Comment by domcleal** [comment]
It will match rc2, 3 etc just fine.  You ought to fix that in engine.rb then, since the plugin still states that it's compatible with 1.8.

**Comment by domcleal** [comment]
Thanks @lzap, building for develop and 1.9.

**Pull request merged**
