### PR TITLE
Update foreman-fog-proxmox to 0.13.1

### PR DESCRIPTION
**Pull request by tristanrobert**
* Nightly

### CODE REVIEW

**Comment by evgeni** [comment]
this fails to precompile the assets, for whatever reason:

```
16:06:10 Uglifier::Error: Unexpected token: name (id). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).
16:06:10 --
16:06:10 [36m 19[0m   var id = $(item).attr('id');
16:06:10 [36m 20[0m   var pattern = /(host_compute_attributes_volumes_attributes_||compute_attribute_vm_attrs_volumes_attributes_)(\d+)[_](.*)/i;
16:06:10 [36m 21[0m   pattern_a = pattern.exec(id);
16:06:10 [36m 22[0m   var index = pattern_a[2];
16:06:10 [36m 23[0m   return index;
16:06:10 [36m 24[0m }
16:06:10 [36m 25[0m 
16:06:10 [36m 26[0m function volumeId(type,index){
16:06:10 [91m => [0m  let [91mid = '#volume_' + type + '_' + index;[0m
16:06:10 [36m 28[0m   return id;
16:06:10 [36m 29[0m }
16:06:10 [36m 30[0m 
16:06:10 [36m 31[0m function enableField(id) {
16:06:10 [36m 32[0m   $(id).show();
16:06:10 [36m 33[0m   $(id).removeAttr('disabled');
16:06:10 [36m 34[0m }
16:06:10 [36m 35[0m 
```

**Comment by evgeni** [comment]
#6344 (0.13.0) was failing in the same way already.

**Comment by tristanrobert** [comment]
> #6344 (0.13.0) was failing in the same way already.

@evgeni have you any ideas how to fix these errors ?

1. `W: GPG error: http://deb.theforeman.org plugins Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6F8600B9563278F6`
2. ` Uglifier::Error: Unexpected token: name (id). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).` I am investigating
3. `LoadError: Error loading the 'postgresql' Active Record adapter. Missing a gem it depends on? pg is not part of the bundle. Add it to your Gemfile.` My debian/rules build file contains: `DATABASE_URL=nulldb://nohost`

**Comment by evgeni** [comment]
Only nr 2 is relevant, and that's in your code, so I have little idea, sorry.

**Comment by tristanrobert** [comment]
fixed by #6454

**Pull request closed without merging**
