### PR TITLE
Update rubygem-logging to 2.3.0

### PR DESCRIPTION
**Pull request by lzap**
For plugin updates, please indicate which repos this should be built into:

* Nightly

This fixes one synchronization issue we are running into in smart proxy
and dynflow. @adamruzicka

https://github.com/TwP/logging/pull/219

### CODE REVIEW

**Comment by adamruzicka** [comment]
> This fixes one synchronization issue we are running into in smart proxy and dynflow.

Oh yes, finally :tada: Thank you

You will probably need to add rubygem-logging to package_manifest.yaml to make the build pass

**Comment by lzap** [comment]
> You will probably need to add rubygem-logging to package_manifest.yaml to make the build pass

Ok thanks for heads up.

**Comment by adamruzicka** [comment]
This is just a wild guess, but maybe `little-plugger` and `multi_json` need to be there as well?

**Comment by lzap** [comment]
Logs are gone, these are not new dependencies. Not sure what was wrong. Rebased.

**Comment by lzap** [comment]
I am not aware closing and deleting the branch myself. Reopening.

**Comment by lzap** [comment]
Rebased, hopefully I can see what's wrong now.

**Comment by lzap** [comment]
I've added little-plugger to the YAML, however I do see multi_json already there:

```
[2020-09-17T06:06:22.904Z]     Added downloaded_rpms repo from ./downloaded_rpms/rhel7
[2020-09-17T06:06:22.904Z]     package: rubygem-logging-2.3.0-1.el7.noarch from downloaded_rpms
[2020-09-17T06:06:22.904Z]       unresolved deps:
[2020-09-17T06:06:22.904Z]         rubygem(little-plugger) >= 1.1
[2020-09-17T06:06:22.904Z]         rubygem(little-plugger) < 2
[2020-09-17T06:06:22.904Z]         rubygem(multi_json) >= 1.10
```

Not sure why it appears there, it's whitelisted in tito.props as well. Anyone?

**Comment by evgeni** [comment]
@lzap that's because it still built it for non-scl, https://github.com/theforeman/foreman-packaging/pull/5835 should fix that

**Comment by evgeni** [comment]
my PR also includes your manifest change (as it was incomplete), please rebase when it's merged

**Comment by ekohl** [comment]
It was merged. Please rebase.

**Comment by lzap** [comment]
Thank you so much! Rebased.

**Review by evgeni — APPROVED** [review]

**Pull request merged**
