### PR TITLE
Pulpcore 3.63 bindings bump for Katello

### PR DESCRIPTION
**Pull request by ianballou**
Katello PR: https://github.com/Katello/katello/pull/11197
Requirements bump: https://github.com/theforeman/foreman-packaging/pull/11415

The big question is -- is it okay to merge this before Katello 4.15 branches?

### CODE REVIEW

**Comment by ekohl** [comment]
If you feel confident about this I don't mind. We already have 3.63 in nightly and if this is better, I'm ok with it. Worst case we'll revert. To me stabilization is about not introducing too much risk when blindly merging things, but I know you've carefully considered this

**Comment by ekohl** [comment]
Fyi, on my phone. Hard to review the specifics. If @Odilhao is ok with it, feel free to merge. I just wanted to make it clear that stabilization week is IMHO not a blocker

**Comment by Odilhao** [comment]
The changelogs looks good to me. We can get this merged and later this one https://github.com/theforeman/foreman-packaging/pull/11415

**Comment by ekohl** [comment]
By all means. I trust the 2 of you to move forward here. From my phone at a guick (imperfect) glance it looks ok to me. Again, it's hard to do a real review but if you think it's ok, let's get it in. The sooner, the more time we have to fix any unforeseen issues

**Pull request merged**
