### PR TITLE
Revert el6 1.13

### PR DESCRIPTION
**Pull request by ehelms**
For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [x] 1.13
* [ ] 1.12
* [ ] 1.11

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by dLobatog** [comment]
There are a few things missing from the rpm/1.13 branch - some of them critical like npm modules, and some things that are still in the comps and tito but there is no package for it and should be removed:

* Add:
nodejs-es6-promise to rhel6
nodejs-extract-text-webpack
nodejs-style-loader
nodejs-css-loader
nodejs-file-loader
nodejs-url-loader
nodejs-ipaddr.js
rubygem-infoblox 

* Remove:
rubygem-select2-rails
rubygem-ipaddrjs-rails
rubygem-foreman-mco

Should be ready to merge in 1.13 after that IMO. The foreman-1.13-nonscl-rhel6 tag doesn't exist in Koji, if you can add it I think Jenkins would be green again. Thanks @ehelms !

**Comment by dLobatog** [comment]
nodejs-ipaddr.js is missing and rubygem-ipaddrjs-rails should be removed (the package too¸ not just comps).

Also the packages you've added in the latest commit are not in rel-eng/tito.props yet

@ehelms Any idea how to fix `Unknown build target: foreman-nightly-nonscl-rhel6` on Jenkins?

**Comment by ehelms** [comment]
@dLobatog nodejs-ipaddr.js was not added in 1.13 -- https://github.com/theforeman/foreman-packaging/blob/rpm/1.13/foreman/foreman.spec#L277-L278

The foreman-nightly-nonscl-rhel6 issue has been fixed in Koji now.

I updated the tito.props for the additional packages.

**Comment by ehelms** [comment]
@dLobatog Also worth noting is that these only build a subset of packages against koji, we limit it to 5 to not overwhelm Koji or Jenkins. I have created the necessary 1.13 EL6 buildroots so they are ready to begin building and testing (I can't create any test repos on Koji until the comps are back in place).

**Comment by dLobatog** [comment]
ack for rpm/1.13

**Comment by domcleal** [comment]
Don't merge this to rpm/1.13, it's a stable (cherry pick only) branch and new functionality can't be added here before it's even tested through rpm/develop. Branching and RC1 for 1.13 happened two weeks ago, it is now too late to add this to 1.13.

**Comment by ehelms** [comment]
Sounds to me like our only recourse is:

 * fix the revert-el6 branch in rpm/develop
 * merge the revert-el6 branch
 * rebuild all the things for EL6
 * fix koji tags and koji-mash-scripts
 * test koji-repositories for installation
 * add el6 back to pipeline
 * add el6 back to wherever else its missing
 * push el6 nightly to yum.theforeman.org
 * cherry-pick all the EL6 changes to rpm/1.13 branch
 * rebuild any missing 1.13 packages in koji tags for EL6 1.13
 * update 1.13 mash scripts
 * publish repositories for 1.13
 * re-rip out all of EL6 from rpm/nightly
 * re-rip out of all of EL6 from pipeline

I've done some of those Koji related items and been building packages into 1.13 and nightly tags already to make sure they do build and because I've been in a holding pattern waiting to hear what the accepted path is.

**Comment by domcleal** [comment]
@ehelms yes, that would be the normal way to add an OS so it gets tested, but _before_ branching and the release candidates, not during the release process.

@dLobatog hypothetically builds _would_ be from rpm/develop and rpm/1.13, not in another branch or outside version control. I was trying to say that merging to a stable branch _first_ is incorrect, not that it should be in another branch altogether. As you say, it missed RC1, so is too late for 1.13.

**Comment by dLobatog** [comment]
@domcleal What would be an acceptable way to add the OS after the first release candidate for you? We could unofficially build these packages ourselves and distribute them through the katello.org repo or something but I wouldn't like to go that route, it's cumbersome for users. Merging into rpm/develop would be OK for any OS that we were to add, but for el6 this means adding packages that are never going to be used (basically everything post 1.13-branching).

**Comment by domcleal** [comment]
> What would be an acceptable way to add the OS after the first release candidate for you?

There isn't, but I can't stop you if you want to build it elsewhere.

**Comment by domcleal** [comment]
Closing, this wasn't in time for 1.13.

**Pull request closed without merging**
