### PR TITLE
Update ruby-foreman-ansible to 9.0.1

### PR DESCRIPTION
**Pull request by nofaralfasi**

### CODE REVIEW

**Comment by nofaralfasi** [comment]
Hi @theforeman/packaging, can you help me with the error I'm getting here? 
This is the first time I'm updating a package, so maybe I'm missing something.

**Comment by evgeni** [comment]
Looks like foreman-tasks (which you depend on) is currently broken in 3.4 and thus Ansible doesn't build either.

**Comment by ekohl** [comment]
Yes, I started cherry picks for that. https://github.com/theforeman/foreman-packaging/pull/8514 is the pick for Foreman itself and https://github.com/theforeman/foreman-packaging/pull/8513 should fix tasks.

**Comment by ekohl** [comment]
[test deb]

**Review by evgeni — APPROVED** [review]

**Pull request merged**
