### PR TITLE
Fix wrong rubygem wrapper script for shell script 'salt_python_wrapper'

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by sbernhard** [comment]
Ready for review

**Comment by sbernhard** [comment]
[test rpm]

**Comment by sbernhard** [comment]
Again, after rebasing ready for review.

**Comment by sbernhard** [comment]
[test rpm]

**Comment by sbernhard** [comment]
Ready to review @zjhuntin

**Comment by sbernhard** [comment]
Can someone have a look at this one, maybe @zjhuntin ?

**Review by pcreech — APPROVED** [review]

**Pull request merged**
