### PR TITLE
Refs #35409 - Include sprockets assets in rubygem-foreman_chef

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by ekohl** [comment]
I opened https://github.com/theforeman/foreman_chef/pull/99 to trigger CI, but there is no CI ...

**Comment by evgeni** [comment]
```
NameError: undefined local variable or method `belongs_to_host' for ForemanChef::CachedRunList(Table doesn't exist):Class
```

**Comment by evgeni** [comment]
I think https://github.com/theforeman/foreman_chef/pull/100 should fix it, but yeah, Ci would be cool.

**Comment by evgeni** [comment]
as far as I could gather, nobody is developing or using the Chef plugin anymore, I am going to close this PR and see that the plugin is instead removed completely.

**Pull request closed without merging**
