### PR TITLE
Update foreman_bootdisk to 19.0.0

### PR DESCRIPTION
**Pull request by ofedoren**
(cherry picked from commit f7303577fd8653263a2c33916757840fc7efad82)

@lzap, FYI this is PR for 3.1.

### CODE REVIEW

**Comment by shr-project** [comment]
After installing this upgrade in ubuntu-20.04 foreman doesn't start anymore:
```
2021-12-14T16:53:52 [I|app|2e97bf25] Rendered layouts/base.html.erb (Duration: 2.9ms | Allocations: 1640)
2021-12-14T16:53:52 [W|app|2e97bf25] Can't find entry point 'foreman_bootdisk:global' in webpack manifest
2021-12-14T16:53:52 [I|app|2e97bf25] Backtrace for 'Can't find entry point 'foreman_bootdisk:global' in webpack manifest' error (ActionView::Template::Error): Can't find entry point 'foreman_bootdisk:global' in webpack manifest
 2e97bf25 | /usr/share/foreman/vendor/ruby/2.7.0/gems/webpack-rails-0.9.11/lib/webpack/rails/manifest.rb:39:in `asset_paths'
 2e97bf25 | /usr/share/foreman/vendor/ruby/2.7.0/gems/webpack-rails-0.9.11/lib/webpack/rails/helper.rb:18:in `webpack_asset_paths'
...
```

Even fresh foreman 3.1 installation with bootdisk plugin enabled (foreman-installer --enable-foreman-plugin-{remote-execution,ansible} --enable-foreman-proxy-plugin-{ansible,remote-execution-ssh} --foreman-proxy-plugin-remote-execution-ssh-install-key=true --enable-foreman-plugin-bootdisk) fails with:
```
root@ubuntu2004:~# /usr/sbin/foreman-rake db:migrate
Apipie cache enabled but not present yet. Run apipie:cache rake task to speed up API calls.
== 20140522185700 ChangeTemplatekindToBootdisk: migrating =====================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "templates" does not exist
LINE 8:  WHERE a.attrelid = '"templates"'::regclass
                            ^
```

Downgrading to 18.0.0-2 works better.

Any idea what's missing?

**Comment by evgeni** [comment]
Thanks for the report! We'll have a look.

**Comment by lzap** [comment]
@ofedoren do you know how to debug this?

**Comment by evgeni** [comment]
Okay, I think I know what triggers this issue.

For some reason, there is no `/usr/share/foreman/vendor/ruby/2.7.0/gems/foreman_bootdisk-19.0.0/public`  folder, which is needed for the detection to work.

**Comment by evgeni** [comment]
This should fix it: https://github.com/theforeman/foreman-packaging/pull/7439

**Comment by evgeni** [comment]
@shr-project we've pushed out a 19.0.0-2 which should fix your problem, can you retry please?

`apt update && apt upgrade && systemctl restart foreman` should be sufficient.

**Comment by shr-project** [comment]
I haven't tried to use new bootdisk yet, but the new version definitely doesn't prevent foreman from starting successfully. Thanks

**Pull request merged**
