### PR TITLE
Update rubygem-foreman_maintain to 0.7.9

### PR DESCRIPTION
**Pull request by upadhyeammit**
(cherry picked from commit 7bf4ee17548c571ac837237f1f7c243bd054d4bf)

### CODE REVIEW

**Comment by upadhyeammit** [comment]
Is it sane to cherry pick 0.7.7 directly and skip 0.7.6? The 0.7.7 fixes issue with backup and restore failure due to mongo command check implemented recently?

**Comment by pcreech** [comment]
> Is it sane to cherry pick 0.7.7 directly and skip 0.7.6? The 0.7.7 fixes issue with backup and restore failure due to mongo command check implemented recently?

I would think so.

**Comment by evgeni** [comment]
@upadhyeammit are you planning to pick the changes from #6386 on top of that, based on above conversation?

**Comment by evgeni** [comment]
And I guess now it needs to be 0.7.8?

**Comment by upadhyeammit** [comment]
[test rpm]

**Review by evgeni — APPROVED** [review]

**Pull request merged**
