### PR TITLE
Update fog-vsphere to v3.3.0

### PR DESCRIPTION
**Pull request by fwdIT**
As requested in https://github.com/fog/fog-vsphere/issues/245
Cherry-pick from https://github.com/fwdIT/foreman-packaging/commit/202d4e35fa2820be7fad64cb5c444aa60c939146

(hope all is right, first time I performed these steps - next time I will first make a pr for rpm/develop and then cherry-pick for rpm/2.0)

### CODE REVIEW

**Comment by fwdIT** [comment]
will have a look at this coming days

**Comment by fwdIT** [comment]
not sure what is wrong now :/

**Comment by ehelms** [comment]
@fwdIT Looks like the PR needs a rebase

**Comment by fwdIT** [comment]
is that something for someone with rights on this repo or something I can do on my end since I don't have any merge conflicts on my end ?

**Comment by ehelms** [comment]
@fwdIT Something you would do locally. 

```
git fetch origin
git rebase origin/rpm/develop
```

Then address anything that has a conflict in the spec file

```
git add packages/foreman/rubygem-fog-vsphere/rubygem-fog-vsphere.spec
git rebase --continue
git push <your fork> develop-bump_fog-vsphere
```

**Comment by fwdIT** [comment]
@ehelms thanks for the feedback, must have missed something then. will have a look at it tomorrow

**Comment by fwdIT** [comment]
@ehelms seems to be a struggle for me :) any idea what could be wrong now ? It was probably caused by my 2 changelog entries which I first kept on 3.3.0-1 but then the lint check failed saying it expected a 3.3.0-2 so I changed my last changelog entry to that. But now I am getting this issue in the next step of the pipeline

**Comment by dgoetz** [comment]
I think it complains as there was no release 1 of 3.3.0.
I suggest to remove the changelog entry for 3.3.0-2 (or combine 3.3.0-2 and 3.3.0-1 to 3.3.0-1) and change `Release: 2%{?dist}` to `Release: 1%{?dist}`.

**Comment by fwdIT** [comment]
@dgoetz thx for the pointers, starting to understand more with each iteration :)

sadly we are stuck again further in fhe pipeline

**Comment by dgoetz** [comment]
`nodejs-react-popper` for EL8 is missing a dependency `npm(typed-styles) >= 0.0.5 with npm(typed-styles) < 0.0.6`, so this repoclosure failure is probably unrelated and will be fixed in another pull-request.

Packages have been build successfully for EL7 and EL8 and are looking fine.

**Comment by dgoetz** [comment]
[test rpm]

**Pull request merged**
