### PR TITLE
Update kafo to 0.9.6 [deb]

### PR DESCRIPTION
**Pull request by ares**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.13
* [ ] 1.12
* [ ] 1.11

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by domcleal** [comment]
Nightly only for now please, as 1.13 has been branched and needs to be stabilised. We can reconsider it for 1.13.0-RC2 or 1.13.1.

**Comment by mmoll** [comment]
merged, díky @ares!

**Comment by ares** [comment]
1.13.0-RC2 would be great, all introduced changes (mostly fixes) seemed safe to me and I tested them with 1.13 branch

**Comment by domcleal** [comment]
Cherry picked to deb/1.13 as d688204, building at http://ci.theforeman.org/job/packaging_build_deb_dependency/1376/.

**Pull request merged**
