### PR TITLE
Fixes #24919 - Remove the use of the _license macro and just hard cod…

### PR DESCRIPTION
**Pull request by bkearney**
…e it in the License line

For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.19
* [ ] 1.18
* [ ] 1.17

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ekohl** [comment]
I agree with this, but wonder if we shouldn't do a more thorough update. There's still EL6 compatibility code in there and the versions are ancient.

**Comment by ekohl** [comment]
https://github.com/theforeman/hammer-cli-foreman-tasks/pull/37 should allow updating to the newest powerbar gem. That'll allow a newer hashie as well.

**Comment by bkearney** [comment]
@ehelms add the release bumps.

**Comment by bkearney** [comment]
@ehelms fixed the commit logs.

**Comment by ehelms** [comment]
Needs a rebase

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman-packaging/pull/2990 (merged) and https://github.com/theforeman/foreman-packaging/pull/3039 make this redundant.

**Pull request closed without merging**
