### PR TITLE
Update rubygem-foreman_templates to 9.0.2

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
@pcreech this still fails to find Perl…

and http://koji.katello.org/kojifiles/releases/split/yum/koji-modules/koji/staged/x86_64/RHEL-8-001-mod/perl:5.26/ looks empty?

**Comment by evgeni** [comment]
oh ffs, the perl:2.26 module is really emty

how is this supposed to work

**Comment by evgeni** [comment]
https://github.com/theforeman/foreman-infra/pull/1602 should fix it

**Comment by zjhuntin** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
Does something need to run to execute https://github.com/theforeman/foreman-infra/pull/1602 to fix this @pcreech ?

**Comment by evgeni** [comment]
My understanding was this runs as a cronjob?

**Comment by ehelms** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
before:

```
DEBUG util.py:600:   Problem 1: package git-2.27.0-1.el8.x86_64 requires perl(Term::ReadKey), but none of the providers can be installed
DEBUG util.py:600:    - conflicting requests
DEBUG util.py:600:    - nothing provides perl(:MODULE_COMPAT_5.26.3) needed by perl-TermReadKey-2.37-7.el8.x86_64
DEBUG util.py:600:    - nothing provides libperl.so.5.26()(64bit) needed by perl-TermReadKey-2.37-7.el8.x86_64
DEBUG util.py:600:   Problem 2: package rubygem-git-1.5.0-2.el8.noarch requires git >= 1.6.0.0, but none of the providers can be installed
DEBUG util.py:600:    - package git-2.27.0-1.el8.x86_64 requires perl(Term::ReadKey), but none of the providers can be installed
DEBUG util.py:600:    - conflicting requests
DEBUG util.py:600:    - nothing provides perl(:MODULE_COMPAT_5.26.3) needed by perl-TermReadKey-2.37-7.el8.x86_64
DEBUG util.py:600:    - nothing provides libperl.so.5.26()(64bit) needed by perl-TermReadKey-2.37-7.el8.x86_64
```

now:

```
DEBUG util.py:600:   Problem 1: package git-2.27.0-1.el8.x86_64 requires perl(Getopt::Long), but none of the providers can be installed
DEBUG util.py:600:    - package perl-Getopt-Long-1:2.50-4.el8.noarch requires perl(constant), but none of the providers can be installed
DEBUG util.py:600:    - conflicting requests
DEBUG util.py:600:    - nothing provides perl(:MODULE_COMPAT_5.24.4) needed by perl-constant-1.33-1001.module_el8.1.0+229+cd132df8.noarch
DEBUG util.py:600:   Problem 2: package git-2.27.0-1.el8.x86_64 requires /usr/bin/perl, but none of the providers can be installed
DEBUG util.py:600:    - package git-2.27.0-1.el8.x86_64 requires perl(File::Basename), but none of the providers can be installed
DEBUG util.py:600:    - package git-2.27.0-1.el8.x86_64 requires perl(File::Find), but none of the providers can be installed
DEBUG util.py:600:    - package git-2.27.0-1.el8.x86_64 requires perl(lib), but none of the providers can be installed
DEBUG util.py:600:    - package git-2.27.0-1.el8.x86_64 requires perl(IPC::Open2), but none of the providers can be installed
DEBUG util.py:600:    - package rubygem-git-1.5.0-2.el8.noarch requires git >= 1.6.0.0, but none of the providers can be installed
DEBUG util.py:600:    - package perl-interpreter-4:5.26.3-416.el8.x86_64 requires perl(threads::shared), but none of the providers can be installed
DEBUG util.py:600:    - conflicting requests
DEBUG util.py:600:    - nothing provides perl(:MODULE_COMPAT_5.24.4) needed by perl-threads-shared-1.58-3.module_el8.1.0+229+cd132df8.x86_64
DEBUG util.py:600:    - nothing provides libperl.so.5.24()(64bit) needed by perl-threads-shared-1.58-3.module_el8.1.0+229+cd132df8.x86_64
```

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
PLEASE ACK IT'S GREEN

**Review by pcreech — APPROVED** [review]
ACK

**Pull request merged**
