### PR TITLE
build installer packages on el9

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
I didn't test `foreman-installer` itself, as that is the only package that has `BuildRequires`, but the others did build, so I am rather confident :)

**Comment by evgeni** [comment]
yeah, no, idk.

to nicely test the proxy, we'll need the installer to deploy it. and if stuff builds, we have packaging prepped for it to get the ruby3 fixes once they appear (if any).

so :woman_shrugging:

**Review by ehelms — APPROVED** [review]
I'm OK with this... as we fix things those fixes will propagate and arrive. If all the packages build (which I do not think is tested here in the PR) that is.

**Comment by evgeni** [comment]
> If all the packages build (which I do not think is tested here in the PR) that is.

not in the PR, no, but I tested them out-of-band :)

**Pull request merged**
