### PR TITLE
Katello 4.4 version bump for nightly

### PR DESCRIPTION
**Pull request by chris1984**

### CODE REVIEW

**Review by jturel — APPROVED** [review]
LGTM!

**Comment by jturel** [comment]
Jenkins is crying about the spec files:

```
[2021-11-17T15:50:33.736Z] fatal: [katello]: FAILED! => changed=false 

[2021-11-17T15:50:33.736Z]   changelog_epoch_version_release: 4.4.0.1.master

[2021-11-17T15:50:33.736Z]   msg: changelog entry missing for 4.4.0-0.1.master

[2021-11-17T15:50:33.736Z]   specfile_epoch_version_release: 4.4.0-0.1.master
```

**Comment by chris1984** [comment]
working on a fix

**Comment by jturel** [comment]
I think the repoclosure error is expected - that's ultimately what this PR will fix

**Comment by jturel** [comment]
@Odilhao  I think this is good for a merge - can you confirm?

**Review by jlsherrill — APPROVED** [review]
Looks good to me, merging

**Pull request merged**
