### PR TITLE
Add nodejs-reselect package

### PR DESCRIPTION
**Pull request by ohadlevy**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.19
* [ ] 1.18
* [ ] 1.17

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ohadlevy** [comment]
any idea why it fails? (what did I do wrong?)

**Comment by ekohl** [comment]
You missed the `package_manifest.yaml` step so it doesn't know how to build it.

**Comment by ohadlevy** [comment]
tests are green, anyone else can merge (as I guess @ekohl is away?)

**Comment by ohadlevy** [comment]
ping @ehelms ?

**Pull request merged**
