### PR TITLE
Rpm/1.22 hammer 0.17.0

### PR DESCRIPTION
**Pull request by mbacovsky**
For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [x] 1.22
* [ ] 1.21
* [ ] 1.20

### CODE REVIEW

**Comment by mbacovsky** [comment]
@ekohl is the missing target error something I should worry about/fix?

**Comment by ekohl** [comment]
[test rpm] It's because I was still doing the branching work. They should now exist.

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm] (you're the lucky test subject for me to fix the 1.22 build env)

**Comment by ekohl** [comment]
[test rpm]

**Pull request merged**
