### PR TITLE
Update rubygem-foreman_host_reports to 1.0.1

### PR DESCRIPTION
**Pull request by lzap**
* Nightly
* 3.2

### CODE REVIEW

**Comment by lzap** [comment]
No matching package to install: 'npm(@theforeman/builder) < 9.0.0'

**Comment by lzap** [comment]
Ok I am gonna guess here, builder is now ^10.0 in core so I am going to bump to that. As well as manually review all other dependencies I guess?

**Comment by lzap** [comment]
@ron-lavi need help:

```
** Execute plugin:assets:precompile
node --max_old_space_size=2048 /builddir/build/BUILD/foreman_host_reports-1.0.0/usr/share/foreman/node_modules/webpack/bin/webpack.js --config /builddir/build/BUILD/foreman_host_reports-1.0.0/usr/share/foreman/config/webpack.config.js --bail --env.pluginName=foreman_host_reports
ModuleNotFoundError: Module not found: Error: Can't resolve '@patternfly/react-icons/dist/esm/icons/filter-icon' in '/builddir/build/BUILDROOT/rubygem-foreman_host_reports-1.0.0-1.fm3_3.el8.noarch/usr/share/gems/gems/foreman_host_reports-1.0.0/webpack/src/Router/HostReports/ShowPage/Components/ReportLogsFilter'
    at factoryCallback (/usr/lib/node_modules/webpack/lib/Compilation.js:282:40)
    at /usr/lib/node_modules/webpack/lib/NormalModuleFactory.js:237:20
    at /usr/lib/node_modules/webpack/lib/NormalModuleFactory.js:60:20
    at /usr/lib/node_modules/webpack/lib/NormalModuleFactory.js:127:20
    at /usr/lib/node_modules/webpack/node_modules/async/dist/async.js:3888:9
    at /usr/lib/node_modules/webpack/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/usr/lib/node_modules/webpack/node_modules/async/dist/async.js:1062:13)
    at /usr/lib/node_modules/webpack/node_modules/async/dist/async.js:969:16
    at /usr/lib/node_modules/webpack/node_modules/async/dist/async.js:3885:13
    at /usr/lib/node_modules/webpack/lib/NormalModuleFactory.js:119:22
    at onError (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:65:10)
    at loggingCallbackWrapper (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/usr/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:252:11)
    at /usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/usr/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:252:11)
    at innerCallback (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:144:11)
    at loggingCallbackWrapper (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/usr/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:249:35)
    at /usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6
    at loggingCallbackWrapper (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:166:11)
    at loggingCallbackWrapper (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/usr/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:249:35)
```

**Comment by Ron-Lavi** [comment]
@lzap I'm on my phone, though looks like we need to change all imports of these icons e.g. from: 
`import SearchIcon from '@patternfly/react-icons/dist/esm/icons/search-icon';`
To
`import  { SearchIcon } from '@patternfly/react-icons';`

Then release a new gem and try packaging again..

**Comment by Ron-Lavi** [comment]
@lzap I just opened a PR to fix it https://github.com/theforeman/foreman_host_reports/pull/23

**Comment by lzap** [comment]
Looks green!

**Comment by lzap** [comment]
I just tested this and it works fine on 3.2 RC1. We can merge this.

**Pull request merged**
