### PR TITLE
Build katello-certs-tools for EL8

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by evgeni** [comment]
```
DEBUG util.py:600:  Error: 
DEBUG util.py:600:   Problem: package docbook-utils-0.6.14-44.el8.noarch requires perl(Getopt::Long) >= 2.01, but none of the providers can be installed
DEBUG util.py:600:    - package perl-Getopt-Long-1:2.50-4.el8.noarch requires perl(constant), but none of the providers can be installed
DEBUG util.py:600:    - conflicting requests
DEBUG util.py:600:    - nothing provides perl(:MODULE_COMPAT_5.24.4) needed by perl-constant-1.33-1001.module_el8.1.0+229+cd132df8.noarch
```

not sure this is an issue with Koji or this package, but it clearly does not biold :)

**Comment by ehelms** [comment]
@evgeni Koji issue, something to do with the modular perl and the builtin perl, @pcreech is going to take a look

**Comment by ehelms** [comment]
[test rpm]

**Comment by evgeni** [comment]
leaving open as review from Zach is explicitly requested

**Pull request merged**
