### PR TITLE
Update foreman.spec to restart if in passenger mode [rpm]

### PR DESCRIPTION
**Pull request by Klaas-**
Previously this was not actually restarting foreman. I broke the rhel6 compatibility.

For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.15
* [ ] 1.14
* [ ] 1.13

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by Klaas-** [comment]
@ehelms I think this could be the appropriate PR to discuss if you really want to restart httpd on plugin install :)

**Comment by Klaas-** [comment]
also a question if you want to keep restarting foreman: is a ```touch ~foreman/tmp/restart.txt``` enough on plugin install?

**Comment by ehelms** [comment]
I feel like I should know this but, what are the other modes with RPM install? 

To your question, I wouldn't think that would cause an Apache restart to just touch that file.

**Comment by Klaas-** [comment]
I'm not 100% sure an apache restart is actually needed, I know the restart.txt should reload the foreman application; that could be enough after a plugin install but someone with more rails knowledge should answer that; and other modes I think this is from waay back when you still started it with ```rails s``` via /etc/init.d/foreman

**Comment by timogoebel** [comment]
How about restarting `foreman-tasks` service as well? It can cause strange errors if you forget to do that.

**Comment by ekohl** [comment]
So at least in [foreman.init](https://github.com/theforeman/foreman-packaging/blob/rpm/develop/foreman/foreman.init) if ```FOREMAN_USE_PASSENGER``` is set to ```1``` it will restart passenger using ```restart.txt``` which is sufficient to restart the app. puppet-foreman sets that value for you so in a properly configured foreman install this shouldn't be needed.

**Comment by Klaas-** [comment]
@ekohl the service restart is not reached atm because /sbin/service foreman status doesn't exit with 0; so I thought we should update it to use systemctl or just create the restart.txt directly if that is sufficient after a plugin install

**Comment by Klaas-** [comment]
I tested it and ```touch ~foreman/tmp/restart.txt``` is enough after a plugin install, I'll replace the service restart with a call to that directly. I think we should also consider cleaning up that old init script :) This doesn't break rhel6 anymore if that is relevant downstream

**Comment by Klaas-** [comment]
okay, this should work I'd say :) if there is consensus about adding foreman-tasks I can do that aswell

**Comment by ekohl** [comment]
I don't have an install at hand right now, but does ```systemctl try-restart foreman``` work when running in Passenger mode or does it suffer from the same problem? At home I have a WIP patch to remove all use of ```service``` in this file and use the systemd macro's instead.

**Comment by ehelms** [comment]
Given foreman-tasks is optional, and the service is moving to dynflow I'd say not to include that.

**Comment by Klaas-** [comment]
@ekohl ```systemctl try-restart foreman``` doesn't work because foreman is not actually started by systemd. So try-restart does nothing :) I'd say the direct touch of the restart.txt is the best option as of now so this PR should be good to test @ehelms :)

**Comment by ekohl** [comment]
@Klaas- In that case I actually think we should do both: in case a user runs it as a (local) service or through passenger.

**Comment by Klaas-** [comment]
@ekohl okay, this should work then :)

**Comment by ehelms** [comment]
[test]

**Comment by Klaas-** [comment]
http://koji.katello.org/kojifiles/work/tasks/2170/22170/root.log 
`Error: No Package found for tfm-rubygem(fog-core) = 1.44.2`
is there something wrong with the foreman repositories?

**Comment by ekohl** [comment]
@Klaas- you're right that nightlies are still not building. It's being worked on.

**Comment by Klaas-** [comment]
this is not needed anymore with https://github.com/theforeman/foreman-packaging/commit/114dd478c6e4ea55ee579b85032a158cc4f76842

**Pull request closed without merging**
