### PR TITLE
Relax rubygem-katello Ruby requirements

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by evgeni** [comment]
You rev-bumped the wrong rpm ;)

**Comment by ehelms** [comment]
Dang. Fixed.

**Comment by evgeni** [comment]
```
+ %gem_install
/var/tmp/rpm-tmp.kFu2Xk: line 42: fg: no job control
```

something you removed removed the rpm macros for gems…

**Comment by ehelms** [comment]
Heh, I took it a little too far in my removing. I think it's good now.

**Review by evgeni — APPROVED** [review]

**Pull request merged**
