### PR TITLE
Drop version macros from discovery plugin

### PR DESCRIPTION
**Pull request by lzap**
For plugin updates, please indicate which repos this should be built into:

* Nightly

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by evgeni** [comment]
can you bump release to 2 and add a changelog, so it actually builds? but otherwise this looks correct.

**Comment by lzap** [comment]
Damn, sure.

**Comment by ekohl** [comment]
Looks like it fails because we've updated the builder:
```
DEBUG util.py:600:  No matching package to install: 'npm(@theforeman/builder) < 5.0.0'
```

**Comment by lzap** [comment]
Thanks, rebased.

**Review by ekohl — APPROVED** [review]
:+1: if the build passes

**Comment by lzap** [comment]
Looks very green to me :-)

**Comment by ekohl** [comment]
@evgeni this is good now, right?

**Review by evgeni — APPROVED** [review]

**Pull request merged**
