### PR TITLE
Update to discovery 2.0.1 (Foreman 1.7)

### PR DESCRIPTION
**Pull request by lzap**
Do not merge, just a preview what I cherry-picked prior the SPEC change to
2.0.1.

### CODE REVIEW

**Comment by domcleal** [comment]
The only one you're missing is the changelog from 895861d.  Otherwise :+1:

**Comment by lzap** [comment]
Yeah I thought I can skip all the similar because tito will regenerate it... will cherry pick it too.

**Comment by domcleal** [comment]
It'll only add a new changelog entry, it won't fill in the 2.0.0 one.

**Comment by lzap** [comment]
Ok pushed thanks, going to bump to 2.0.1 now.

**Comment by domcleal** [comment]
> Ok pushed thanks, going to bump to 2.0.1 now.

@lzap?

**Comment by lzap** [comment]
On my plate... approaching.

**Comment by lzap** [comment]
Done. http://koji.katello.org/koji/taskinfo?taskID=238958

**Comment by lzap** [comment]
Do I do the same (cherry-picking) for debian?

**Comment by domcleal** [comment]
You shouldn't need to cherry pick anything, as we always build from deb/* branches directly - so it should already be at 2.0.0.  No retagging for debs makes it far less confusing.

**Comment by lzap** [comment]
Here we go, this was nicer :-) https://github.com/theforeman/foreman-packaging/pull/606

**Comment by domcleal** [comment]
Thanks @lzap!  Building now.

I've been working on ways that we can build RPMs from branches rather than retagging, but unfortunately we have to deal with the uniqueness of git/tito tags and uniqueness of NEVRAs in Koji.  I'll post something soon...

**Comment by lzap** [comment]
Thanks guys, going to bump hammer discovery cli as well. Develop only (new features).

**Comment by domcleal** [comment]
I opened #627 which implements what I hinted about above.  This should mean that we can always build releases on rpm/1.7, rpm/1.8, rpm/develop etc like deb/*, without the outdated mess in branches that retagging from rpm/develop caused in this PR.

**Pull request merged**
