### PR TITLE
support adding pypi packages to katello comps too

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
worked like a charm when I tried adding Django:

```diff
--- a/comps/comps-katello-server-rhel7.xml
+++ b/comps/comps-katello-server-rhel7.xml
@@ -1,6 +1,5 @@
 <?xml version="1.0"?>
 <!DOCTYPE comps PUBLIC "-//Red Hat, Inc.//DTD Comps info//EN" "comps.dtd">
-
 <comps>
   <!--  <meta> -->
   <!-- Meta information will go here eventually -->
@@ -20,9 +19,10 @@
       <packagereq type="default">katello-repos</packagereq>
       <packagereq type="default">katello-repos-testing</packagereq>
       <packagereq type="default">katello-utils</packagereq>
+      <packagereq type="default">pulp-katello</packagereq>
+      <packagereq type="default">python-django</packagereq>
       <packagereq type="default">python-gofer</packagereq>
       <packagereq type="default">python-gofer-qpid</packagereq>
-      <packagereq type="default">pulp-katello</packagereq>
       <packagereq type="default">tfm-rubygem-activerecord-import</packagereq>
       <packagereq type="default">tfm-rubygem-ethon</packagereq>
       <packagereq type="default">tfm-rubygem-foreman_virt_who_configure</packagereq>
@@ -32,7 +32,6 @@
       <packagereq type="default">tfm-rubygem-katello</packagereq>
       <packagereq type="default">tfm-rubygem-katello-assets</packagereq>
       <packagereq type="default">tfm-rubygem-redhat_access</packagereq>
-
       <!-- katello thirdparty nodejs packages -->
       <packagereq type="default">tfm-nodejs-angular</packagereq>
       <packagereq type="default">tfm-nodejs-bootstrap-select</packagereq>
@@ -42,7 +41,6 @@
       <packagereq type="default">tfm-nodejs-query-string</packagereq>
       <packagereq type="default">tfm-nodejs-react-helmet</packagereq>
       <packagereq type="default">tfm-nodejs-strict-uri-encode</packagereq>
-
       <!-- katello thirdparty rubygem packages -->
       <packagereq type="default">tfm-rubygem-anemone</packagereq>
       <packagereq type="default">tfm-rubygem-ansi</packagereq>
@@ -67,11 +65,9 @@
       <packagereq type="default">tfm-rubygem-sexp_processor</packagereq>
       <packagereq type="default">tfm-rubygem-typhoeus</packagereq>
       <packagereq type="default">tfm-rubygem-zest</packagereq>
-
       <!-- temporary qpid packages -->
       <packagereq type="default">qpid-dispatch-router</packagereq>
       <packagereq type="default">qpid-dispatch-tools</packagereq>
-
       <!-- other katello related packages -->
       <packagereq type="default">rhel8-kickstart-setup</packagereq>
     </packagelist>

```

**Comment by ehelms** [comment]
I would prefer if the Pulp packages were grouped in the comps files to make it cleaner to understand dependencies...

**Comment by evgeni** [comment]
@ehelms there is no word of pulp at all in here yet ;)

**Comment by pcreech** [comment]
needs rebase, but ACK from me

**Pull request merged**
