### PR TITLE
Katello 3.14.0 RC1

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by pcreech** [comment]
Looks like koji needs the new build environment:

koji: error: Unknown build target: katello-3.14-rhel7

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
Still fails after creating the tag via toobelt :(

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
Ah, well, it needs a foreman in the buoldroot

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Pull request merged**
