### PR TITLE
Restructure packages to prepare for obal

### PR DESCRIPTION
**Pull request by pcreech**
Restructure packages to prepare for obal

This PR moves all {package} directories to their respective 'packages/{foreman,plugins,katello}/{package}' directories in a manner that hopefully preserves git history.

There are currently two commits associated.  The first is the 'git mv' commits to preserve history.  The second commit is updates so this repo will continue to work with existing tooling.

This is to help structure foreman-packaging for use with obal tooling.

For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.17
* [ ] 1.16
* [ ] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ehelms** [comment]
[test]

**Comment by ekohl** [comment]
It'd be nice to see a description of steps what this is doing. Reviewing it is hard due to its size.

**Comment by pcreech** [comment]
@ekohl I've updated the description a bit, I hope that helps.  Let me know if i can add anything to make it more clear.

**Comment by ekohl** [comment]
Looks like the CI job can't handle subdirectories so we should fix that first.

**Comment by ekohl** [comment]
Tested it yesterday and those fixes are now included. Going to merge this and see what needs updating.

**Pull request merged**
