### PR TITLE
Fix dynflow_core bundler.d location on EL8

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
I've only edited the packages that actually place a file into that folder.

Ping if you want me to update all of them.

**Comment by ekohl** [comment]
I'd prefer to update them all. If they start to place a file there, you'll end up with an annoying bug that's hard to trace.

**Comment by evgeni** [comment]
@ekohl there you go. `sed` + `obal` = ♥

**Comment by ehelms** [comment]
Did scl_utils change? How does this work on EL7 and EL8 now?

**Comment by evgeni** [comment]
@ehelms well, on EL7 we're *inside* the SCL now, so no need for "if not in SCL prepend SCL path for dynflow core", and on EL8 it was always wrong to prepend it :)

**Comment by ekohl** [comment]
This is essentially step 2 of what @ehelms said in https://github.com/theforeman/foreman-packaging/pull/4147#discussion_r328714325. Sadly it took us more than a week to follow through.

**Pull request merged**
