### PR TITLE
Fixes #29281 - Forcefully remove dynflowd.service

### PR DESCRIPTION
**Pull request by ekohl**
The dynflowd.service was removed in Foreman 2.0 by just dropping the .service file which meansthe service keeps running.

Note I haven't tested this yet and this PR is here to I get deb packages.

### CODE REVIEW

**Comment by sthirugn** [comment]
is this applicable only to debian?

**Comment by ekohl** [comment]
https://projects.theforeman.org/issues/29281 has links to the RPM fixes that have already been merged.

**Comment by mmoll** [comment]
@ekohl Was this latest version tested? :)

**Comment by ekohl** [comment]
@mmoll not yet.

**Comment by ekohl** [comment]
This doesn't appear to work, not sure why yet.

**Comment by tbrisker** [comment]
Can we work around this in the release notes and fix properly for 2.0.1 (or even just a rebuild of 2.0.0) once we figure it out?

**Comment by ekohl** [comment]
The current issue is that `/etc/init.d/dynflowd` and `/etc/default/dynflowd` remain on the system. I added the `rm -rf` but that doesn't appear to work. @evgeni or @mmoll have any idea?

If not, I'm ok with removing those lines again and adding that to the upgrade notes. The systemd stuff is at least stopped.

**Comment by evgeni** [comment]
You do so on uninstall only, shouldn't this happen on install instead?

**Comment by ekohl** [comment]
I don't know the exact Debian hooks. Would you mind taking a stab at it instead?

**Comment by evgeni** [comment]
I can, but I'd need to better understand the context.
2.0 dropped dynflowd (aka 1.24 was the last release with dynflowd), but the service definition remains on disk. So now when users update to 2.0 (or newer) you want to purge any references to dynflowd, correct?

**Comment by ekohl** [comment]
Correct. What I did to work on this was install a box (vagrant up debian10-foreman-1.24). For convenience I created a snapshot of the box at this stage. Then I added my staging repo and upgraded:

```
root@debian10-foreman-1-24:~# echo deb http://stagingdeb.theforeman.org/ buster ekohl-nightly >> /etc/apt/sources.list.d/deb_theforeman_org.list && apt update && apt upgrade
```

The expected result was that the `dynflowd` service was entirely gone, however:
```
root@debian10-foreman-1-24:~# systemctl status dynflowd
● dynflowd.service - LSB: Init script for dynflowd
   Loaded: loaded (/etc/init.d/dynflowd; generated)
   Active: inactive (dead) since Fri 2020-04-03 13:14:59 UTC; 24min ago
     Docs: man:systemd-sysv-generator(8)
```

Manual cleanup after appears to yield the correct result:
```
root@debian10-foreman-1-24:~# rm -f /etc/init.d/dynflowd /etc/default/dynflowd
root@debian10-foreman-1-24:~# systemctl daemon-reload
root@debian10-foreman-1-24:~# systemctl status dynflowd
Unit dynflowd.service could not be found.
```

**Comment by evgeni** [comment]
I've  moved all handling to prerm (as it's the only place we can remove things we don't ship anymore) and use dpkg-maintscript-helper instead of blind rm ;)

I don't have time to test that today anymore, so @ekohl @mmoll @pcreech do as you see fit.

**Comment by ekohl** [comment]
Thanks, I still have my test VM so I'll give it a spin once the packages are available.

**Comment by ekohl** [comment]
Confirmed this works:
```
root@debian10-foreman-1-24:~# echo deb http://stagingdeb.theforeman.org/ buster ekohl-nightly >> /etc/apt/sources.list.d/deb_theforeman_org.list && apt update && apt upgrade -y
Hit:1 http://httpredir.debian.org/debian buster InRelease
Hit:2 http://apt.puppet.com buster InRelease                                     
Ign:3 http://stagingdeb.theforeman.org buster InRelease                          
Get:4 http://stagingdeb.theforeman.org buster Release [101 kB]               
Ign:5 http://deb.theforeman.org buster InRelease                             
Ign:6 http://deb.theforeman.org plugins InRelease      
Get:7 http://stagingdeb.theforeman.org buster Release.gpg [836 B]
Get:8 http://deb.theforeman.org buster Release [19.7 kB] 
Get:9 http://deb.theforeman.org plugins Release [116 kB]
Get:10 http://stagingdeb.theforeman.org buster/ekohl-nightly amd64 Packages [13.4 kB]
Get:11 http://deb.theforeman.org buster Release.gpg [836 B]        
Get:12 http://deb.theforeman.org plugins Release.gpg [836 B]
Fetched 253 kB in 2s (119 kB/s)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
4 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  foreman foreman-cli foreman-debug foreman-postgresql
4 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 72.9 MB of archives.
After this operation, 14.8 MB of additional disk space will be used.
Get:1 http://stagingdeb.theforeman.org buster/ekohl-nightly amd64 foreman-cli all 9999-buster+scratchbuild+20200406151111 [183 kB]
Get:2 http://stagingdeb.theforeman.org buster/ekohl-nightly amd64 foreman-postgresql all 9999-buster+scratchbuild+20200406151111 [184 kB]
Get:3 http://stagingdeb.theforeman.org buster/ekohl-nightly amd64 foreman amd64 9999-buster+scratchbuild+20200406151111 [72.3 MB]                                                    
Get:4 http://stagingdeb.theforeman.org buster/ekohl-nightly amd64 foreman-debug all 9999-buster+scratchbuild+20200406151111 [187 kB]                                                 
Fetched 72.9 MB in 21s (3,436 kB/s)                                                                                                                                                  
apt-listchanges: Reading changelogs...
(Reading database ... 97233 files and directories currently installed.)
Preparing to unpack .../foreman-cli_9999-buster+scratchbuild+20200406151111_all.deb ...
Unpacking foreman-cli (9999-buster+scratchbuild+20200406151111) over (1.24.2-1) ...
Preparing to unpack .../foreman-postgresql_9999-buster+scratchbuild+20200406151111_all.deb ...
Unpacking foreman-postgresql (9999-buster+scratchbuild+20200406151111) over (1.24.2-1) ...
Preparing to unpack .../foreman_9999-buster+scratchbuild+20200406151111_amd64.deb ...
Unpacking foreman (9999-buster+scratchbuild+20200406151111) over (1.24.2-1) ...
Preparing to unpack .../foreman-debug_9999-buster+scratchbuild+20200406151111_all.deb ...
Unpacking foreman-debug (9999-buster+scratchbuild+20200406151111) over (1.24.2-1) ...
Setting up foreman-cli (9999-buster+scratchbuild+20200406151111) ...
Setting up foreman-debug (9999-buster+scratchbuild+20200406151111) ...
Setting up foreman (9999-buster+scratchbuild+20200406151111) ...

Configuration file '/etc/foreman/settings.yaml'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** settings.yaml (Y/I/N/O/D/Z) [default=N] ? 

Setting up foreman-postgresql (9999-buster+scratchbuild+20200406151111) ...##################################################################################################################################################################################################################................................................................................
Processing triggers for systemd (241-7~deb10u3) ...
root@debian10-foreman-1-24:~# systemctl status dynflowd
Unit dynflowd.service could not be found.
root@debian10-foreman-1-24:~# ls /etc/init.d/dynflowd.dpkg-remove /etc/default/dynflowd.dpkg-remove 
/etc/default/dynflowd.dpkg-remove  /etc/init.d/dynflowd.dpkg-remove
```

**Comment by mmoll** [comment]
merged, bedankt @ekohl and спасибо @evgeni!

**Comment by tbrisker** [comment]
I guess we need to cp this to deb/2.0 as well, right?

**Comment by mmoll** [comment]
2.0: 1fe541037999ae36a026f26a890a270b88f7b33c

**Pull request merged**
