### PR TITLE
Use ffi from tfm SCL

### PR DESCRIPTION
**Pull request by ehelms**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.16
* [ ] 1.15
* [ ] 1.14

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ekohl** [comment]
Any reason why this package was pulled in while rh-ror42-rubygem-ffi is 1.9.10?

**Comment by mmoll** [comment]
merged, thanks @ehelms!

**Comment by ehelms** [comment]
We don't use the rh-ror42 scl but rather the sclo-ror42 that Dominic
created.

On Sep 29, 2017 3:11 PM, "Michael Moll" <notifications@github.com> wrote:

merged, thanks @ehelms <https://github.com/ehelms>!

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/theforeman/foreman-packaging/pull/1837#issuecomment-333213293>,
or mute the thread

**Comment by ekohl** [comment]
Ah

**Pull request merged**
