### PR TITLE
Remove fedora 29 from develop

### PR DESCRIPTION
**Pull request by pcreech**

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
In the past we've said we want to keep Fedora supported for client tools and kept it in develop so we can easily update it to Fedora latest (33 at the time of writing). Thoughts on doing that instead?

**Comment by pcreech** [comment]
So, based on the comment here, https://github.com/theforeman/foreman-packaging/pull/5939#discussion_r516762778 it sounded like fc29 is at least dropped in 2.2+.  Since this has bitten me for 2.3, i figured it was at least best to go ahead and remove this so it doesn't cause more pain in the future at time of branching.

I'm not against updating fedora build tags.  The question here is do we want to hold up removing f29 from develop when we've already dropped it in releases, or do we need to add in steps to remove fedora 29 in the branching docs?

**Comment by ekohl** [comment]
With 2.2 Fedora 29 was already EOL so we decided not to ship it there, but also said we should update it in develop. That never happened which is why it's a problem now. It would be my preference to update the tags to Fedora 33 before 2.4 branches.

**Comment by pcreech** [comment]
@ekohl While looking into some things fedora 33 related, it looks like they've changed a few things around with policies w/r to modularity an a manner that would be benificial.  in January 2021 we should be able to add fedora 33 as external repos and build out from there

**Comment by ekohl** [comment]
Sounds good. Do you agree it's easier to keep f29 in until then and replace it when we get to it?

**Comment by pcreech** [comment]
Given timeframes, and likeleyhood we will need to branch before we add f33 is low, a "removal, then add later" is moot.  Not sure yet if I'll close this PR or modify it.

**Comment by pcreech** [comment]
This pr is rather outdated.  closing

**Pull request closed without merging**
