### PR TITLE
Update for new Obal tito modules

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
Updates for -- https://github.com/theforeman/obal/pull/202

**Comment by ehelms** [comment]
@ekohl Can you give this another look? I had to update it further for where the obal changes landed

**Comment by ekohl** [comment]
Oh, I do see it is passed but not working. Looks like the builder is not passed:
```
fatal: [foreman-proxy]: FAILED! => changed=false 
  code: 1
  command:
  - tito
  - build
  - --srpm
  - --offline
  - --output
  - /home/ekohl/dev/foreman-packaging/SRPMs
  - --arg
  - jenkins_job=smart-proxy-develop-source-release
  - --arg
  - jenkins_url=https://ci.theforeman.org
  directory: /home/ekohl/dev/foreman-packaging/packages/foreman//foreman-proxy
  msg: Failed to tito build
  output: |-
    ERROR: Error running command: rpmbuild --define "_source_filedigest_algorithm md5"  --define "_binary_filedigest_algorithm md5"  --eval '%undefine scl' --define "_topdir /home/ekohl/dev/foreman-packaging/SRPMs/rpmbuild-foreman-proxysmcdsozz" --define "_sourcedir /home/ekohl/dev/foreman-packaging/SRPMs/rpmbuild-foreman-proxysmcdsozz/SOURCES/foreman-proxy-1.24.0" --define "_builddir /home/ekohl/dev/foreman-packaging/SRPMs/rpmbuild-foreman-proxysmcdsozz/BUILD" --define "_srcrpmdir /home/ekohl/dev/foreman-packaging/SRPMs" --define "_rpmdir /home/ekohl/dev/foreman-packaging/SRPMs"   --nodeps -bs /home/ekohl/dev/foreman-packaging/SRPMs/rpmbuild-foreman-proxysmcdsozz/SOURCES/foreman-proxy.spec
  
    Status code: 1
  
    Command output: ['error: Bad source: /home/ekohl/dev/foreman-packaging/SRPMs/rpmbuild-foreman-proxysmcdsozz/SOURCES/foreman-proxy-1.24.0/foreman-proxy-1.24.0-develop.tar.bz2: No such file or directory', '']
  
    Creating output directory: /home/ekohl/dev/foreman-packaging/SRPMs
    Building package [foreman-proxy-1.24.0-0.2.develop]
    error: Bad source: /home/ekohl/dev/foreman-packaging/SRPMs/rpmbuild-foreman-proxysmcdsozz/SOURCES/foreman-proxy-1.24.0/foreman-proxy-1.24.0-develop.tar.bz2: No such file or directory
```

**Comment by ehelms** [comment]
I was missing a line in the Obal PR (its added to the PR now):

```
build_srpm_tito_builder: "{{ build_package_tito_builder | default() }}"
```

**Comment by ekohl** [comment]
Yes, I came to the exact same conclusion. When I wanted to comment on the obal PR I see you already updated it.

**Comment by ehelms** [comment]
As for the repetition, I agree that its a bit ugly and could use some consolidation and design. However, these means I am starting to combine a lot of concerns into one. We already have these arguments, this is just expanding on those to be more precise and to match the new tito modules. I think having those modules is a greater benefit than holding them up to solve this repetition. At least this is very specific and understandable :)

**Pull request merged**
