### PR TITLE
Require python-requests in smart_proxy_ansible

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
@ares Any concerns with this approach?

**Comment by mmoll** [comment]
IMHO this is fine, but needs a changelog entry (3.0.0-2)

**Comment by ares** [comment]
I can't connect this to any issue, what is the reason? If this is a dependency that a lot of ansible modules rely on, then I'm fine with installing it.

**Comment by ekohl** [comment]
The reasoning is that the Ansible Foreman callback requires it. Currently the installer installs this, but on EL8 it's python3-requests. Rather than solving it there, we can also solve it in packaging which is generally more aware of those differences.

**Comment by ares** [comment]
Oh, I got it now, perhaps a comment in the spec file (or in worse case the changelog) would be good, so we don't drop it in future when we do some cleanup.

**Comment by ekohl** [comment]
I actually do think an installer issue (and this may refs it) would be good for tracking purposes.

**Comment by ekohl** [comment]
@mmoll please re-review - now has a changelog but since I suggested the command to @ehelms I'd like someone else to review it :)

**Comment by mmoll** [comment]
merged, thanks @ehelms!

**Pull request merged**
