### PR TITLE
Update rubygem-foreman_remote_execution to 5.0.1

### PR DESCRIPTION
**Pull request by adamruzicka**
CPs:
- 3.1

### CODE REVIEW

**Comment by Odilhao** [comment]
[test rpm]

**Comment by Odilhao** [comment]
Hi @adamruzicka looks like we will need to add BuildRequires `tfm-npm(graphql-tag)`

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'graphql-tag/loader' in '/builddir/build/BUILD/foreman_remote_execution-5.0.0/usr/share/foreman'
```

We are not seeing the graphql-tag being required here as well https://github.com/theforeman/foreman_remote_execution/blob/29d7c2036893a800a75ab5d26c4c808a9de7e721/package.json

**Comment by adamruzicka** [comment]
@mariaaga is it possible `graphql-tag` was getting pulled as a transitive dependency of something so we didn't need to declare it explicitly?

**Comment by evgeni** [comment]
We had this with `foreman_openscap` too. [It's not in the `package.json`](https://github.com/theforeman/foreman_openscap/blob/master/package.json), but the RPM spec has it listed:

https://github.com/theforeman/foreman-packaging/blob/d6215a4c4119f8ebba56cb71697b7684a076bc2b/packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec#L39-L42

**Comment by adamruzicka** [comment]
Yeah, that did the trick

**Review by Odilhao — APPROVED** [review]

**Pull request merged**
