### PR TITLE
Updated foreman_discovery to 8.0.1 (RPM)

### PR DESCRIPTION
**Pull request by lzap**
For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [x] 1.14

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by lzap** [comment]
Hmmm build failed: http://koji.katello.org/koji/getfile?taskID=606465&name=build.log

**Comment by lzap** [comment]
Whatever I do, why the heck is this failing for a minor release? I don't want to mess around with such things in minor updates.

**Comment by lzap** [comment]
I haven't touched engine.rb in between 8.0.0 and 8.0.1 why it errors out?

**Comment by lzap** [comment]
Ah I see it's the nigtly what's failing, can we build just stable for now?

**Comment by lzap** [comment]
By the way how do I reproduce this on my dev environment. I am trying to `db:migrate` an empty core database and it works fine.

**Comment by domcleal** [comment]
> Ah I see it's the nigtly what's failing, can we build just stable for now?

Submit the PR against rpm/1.14 or the appropriate branch then, not rpm/develop.

> By the way how do I reproduce this on my dev environment.

Probably run `db:schema:load` or `db:migrate` without the plugin, add the plugin, then run `db:migrate`.

**Comment by lzap** [comment]
Thanks, will do. For the record: 248db50 split DB setup into two commands. The DB has never been seeded.

**Comment by lzap** [comment]
I will get back to this later.

**Pull request closed without merging**
