### PR TITLE
Bump to 3.7.0-develop

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ehelms** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm] since I ran `koji regen-repo foreman-client-nightly-el9`, which I hope is the right command.

**Comment by ekohl** [comment]
I suspect this will need to be some other regen command:
```
DEBUG util.py:444:    kernel-headers-5.14.0-210.el9.x86_64: Download failed: Status code: 404 for https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/Packages/kernel-headers-5.14.0-210.el9.x86_64.rpm (IP: 18.160.41.128)
```

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
The el9 part passed (http://koji.katello.org/koji/taskinfo?taskID=547641). You were on the right path, but needed to regenerate a level lower:

```
koji regen-repo foreman-client-nightly-el9-build
```

The build tag is the one that always has the external repositories attached to it.

**Pull request merged**
