### PR TITLE
drop rubygem-hammer_cli_csv

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
@ehelms please double-check me, but my memory says we stopped supporting that hammer extension quite a while ago and just never dropped the packaging.

**Comment by ekohl** [comment]
The last update was in 2018 so I think you're right. Perhaps the repo should be archived too to make it clear?

**Comment by evgeni** [comment]
That's a good idea, but that's also for Eric as I don't have the powers in Katello.

**Review by ehelms — APPROVED** [review]

**Comment by ehelms** [comment]
Archived.

**Comment by evgeni** [comment]
```
koji untag-build --all katello-nightly-el8  rubygem-hammer_cli_csv
koji block-pkg katello-nightly-el8 rubygem-hammer_cli_csv
```

**Pull request merged**
