### PR TITLE
Update katello to 4.5.0

### PR DESCRIPTION
**Pull request by Odilhao**

### CODE REVIEW

**Comment by Odilhao** [comment]
[test rpm]

**Comment by Odilhao** [comment]
[test rpm]

**Comment by Odilhao** [comment]
[test rpm]

**Comment by Odilhao** [comment]
[test rpm]

**Comment by Odilhao** [comment]
Repoclosure fail is expected, we have packages that need to be signed first for repoclosure to pass

**Review by parthaa — APPROVED** [review]
APJ

**Pull request merged**
