### PR TITLE
Add rubygem-graphql package

### PR DESCRIPTION
**Pull request by xprazak2**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.21
* [ ] 1.20

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by evgeni** [comment]
This failed to build on koji:

```
Installing darkfish documentation for graphql-1.8.14
BUILDSTDERR: ERROR:  While executing gem ... (RDoc::Error)
BUILDSTDERR:     error generating GraphQL/Schema/Member/BuildType.html: no implicit conversion of nil into String (TypeError)
BUILDSTDERR: error: Bad exit status from /var/tmp/rpm-tmp.pcH5K8 (%build)
BUILDSTDERR:     Bad exit status from /var/tmp/rpm-tmp.pcH5K8 (%build)
```

Doesn't look packaging related, but obviously a blocker to get this merged ;)

**Comment by xprazak2** [comment]
Finally green. Generating RDoc was broken for some reason, so I skip it.

**Comment by ekohl** [comment]
> Finally green. Generating RDoc was broken for some reason, so I skip it.

I'm OK with that, but it might be good to file an issue upstream.

**Comment by evgeni** [comment]
```
% koji add-pkg foreman-nightly-rhel7 tfm-rubygem-graphql --owner=kojiadm 
Adding 1 packages to tag foreman-nightly-rhel7
```

**Comment by evgeni** [comment]
build: http://koji.katello.org/koji/taskinfo?taskID=173698

**Pull request merged**
