### PR TITLE
Bump rubygem-oauth to 1.1.0-1

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by evgeni** [comment]
I guess you still gotta package the new deps?

```
unresolved deps:

[2022-10-31T14:33:36.401Z]         (rubygem(oauth-tty) >= 1.0 with rubygem(oauth-tty) < 2 with rubygem(oauth-tty) >= 1.0.1)

[2022-10-31T14:33:36.401Z]         (rubygem(snaky_hash) >= 2.0
```

**Comment by ehelms** [comment]
Deps are here -- https://github.com/theforeman/foreman-packaging/pull/8669

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Review by evgeni — APPROVED** [review]

**Pull request merged**
