### PR TITLE
Updated foreman_discovery to 4.0.0

### PR DESCRIPTION
**Pull request by lzap**
I pushed 4.0.0 with few harmless locale POX files. Made a patch in discovery repo to prevent this in the future: https://github.com/theforeman/foreman_discovery/pull/207

```
Submitting build with: koji -c ~/.koji/katello-config build --nowait --scratch foreman-plugins-nightly-fedora19 /tmp/tito/rubygem-foreman_discovery-4.0.0-1.fm1_10.git.383.3e95ee3.fc19.src.rpm
Uploading srpm: /tmp/tito/rubygem-foreman_discovery-4.0.0-1.fm1_10.git.383.3e95ee3.fc19.src.rpm
[                                    ]  00% 00:00:00     0.00 B        - B/sec
[====================================] 100% 00:00:01 100.01 KiB  82.71 KiB/sec
Created task: 316911
Task info: http://koji.katello.org/koji/taskinfo?taskID=316911
Wrote: /tmp/tito/ruby193-rubygem-foreman_discovery-4.0.0-1.fm1_10.git.383.3e95ee3.git.383.3e95ee3.el6.src.rpm



Submitting build with: koji -c ~/.koji/katello-config build --nowait --scratch foreman-plugins-nightly-rhel6 /tmp/tito/ruby193-rubygem-foreman_discovery-4.0.0-1.fm1_10.git.383.3e95ee3.git.383.3e95ee3.el6.src.rpm
Uploading srpm: /tmp/tito/ruby193-rubygem-foreman_discovery-4.0.0-1.fm1_10.git.383.3e95ee3.git.383.3e95ee3.el6.src.rpm
[                                    ]  00% 00:00:00     0.00 B        - B/sec
[====================================] 100% 00:00:01 100.09 KiB  89.06 KiB/sec
Created task: 316913
Task info: http://koji.katello.org/koji/taskinfo?taskID=316913
Wrote: /tmp/tito/ruby193-rubygem-foreman_discovery-4.0.0-1.fm1_10.git.383.3e95ee3.git.383.3e95ee3.git.383.3e95ee3.el7.src.rpm



Submitting build with: koji -c ~/.koji/katello-config build --nowait --scratch foreman-plugins-nightly-rhel7 /tmp/tito/ruby193-rubygem-foreman_discovery-4.0.0-1.fm1_10.git.383.3e95ee3.git.383.3e95ee3.git.383.3e95ee3.el7.src.rpm
Uploading srpm: /tmp/tito/ruby193-rubygem-foreman_discovery-4.0.0-1.fm1_10.git.383.3e95ee3.git.383.3e95ee3.git.383.3e95ee3.el7.src.rpm
[                                    ]  00% 00:00:00     0.00 B        - B/sec
[====================================] 100% 00:00:01 100.11 KiB  84.56 KiB/sec
Created task: 316914
Task info: http://koji.katello.org/koji/taskinfo?taskID=316914

[lzap@lzapx foreman_discovery]$ gem compare -b foreman_discovery 3.0.0 4.0.0
Fetching: foreman_discovery-3.0.0.gem (100%)
Fetching: foreman_discovery-4.0.0.gem (100%)
Compared versions: ["3.0.0", "4.0.0"]
  DIFFERENT files:
    3.0.0->4.0.0:
      * Deleted:
            app/services/
      * Added:
            app/services/foreman_discovery/
            app/lib/facter_utils.rb
              (!) Unexpected permissions: 100664
            app/services/foreman_discovery/host_converter.rb
              (!) Unexpected permissions: 100664
            app/views/dashboard/_discovery_widget_host.html.erb
              (!) Unexpected permissions: 100664
            db/migrate/20150310153859_remove_discovery_attribute_sets_from_managed_hosts.rb
              (!) Unexpected permissions: 100664
            db/migrate/20150505111345_remove_leftover_tokens.rb
              (!) Unexpected permissions: 100664
            db/migrate/20150331132115_remove_old_permissions.rb
              (!) Unexpected permissions: 100664
            db/migrate/20150512150432_remove_old_discovery_reader_permissions.rb
              (!) Unexpected permissions: 100664
            db/migrate/20150714144500_review_discovery_permissions.rb
              (!) Unexpected permissions: 100664
            locale/ru/foreman_discovery.pox
              (!) Unexpected permissions: 100664
            locale/de/foreman_discovery.pox
              (!) Unexpected permissions: 100664
            locale/pt_BR/foreman_discovery.pox
              (!) Unexpected permissions: 100664
            locale/en_GB/foreman_discovery.pox
              (!) Unexpected permissions: 100664
            locale/zh_TW/foreman_discovery.pox
              (!) Unexpected permissions: 100664
            locale/es/foreman_discovery.pox
              (!) Unexpected permissions: 100664
            locale/fr/foreman_discovery.pox
              (!) Unexpected permissions: 100664
            locale/it/foreman_discovery.pox
              (!) Unexpected permissions: 100664
            locale/messages.mo
              (!) Unexpected permissions: 100664
            locale/ja/foreman_discovery.pox
              (!) Unexpected permissions: 100664
            locale/ko/foreman_discovery.pox
              (!) Unexpected permissions: 100664
            locale/zh_CN/foreman_discovery.pox
              (!) Unexpected permissions: 100664
            locale/gl/foreman_discovery.pox
              (!) Unexpected permissions: 100664
            test/unit/discovery_rule_test.rb
              (!) Unexpected permissions: 100664
  DIFFERENT test_files:
    3.0.0->4.0.0:
      * Added:
            test/unit/discovery_rule_test.rb
              (!) Unexpected permissions: 100664
  DIFFERENT runtime dependencies:
    3.0.0->4.0.0:
      * Updated:
            deface from: ["< 1.0"] to: ["< 2.0"]
```

### CODE REVIEW

**Comment by lzap** [comment]
All builds green, debian on its way.

**Comment by lzap** [comment]
Forgot to bump the foreman dependency: `Requires:   foreman >= 1.9.0`

```
Submitting build with: koji -c ~/.koji/katello-config build --nowait --scratch foreman-plugins-nightly-fedora19 /tmp/tito/rubygem-foreman_discovery-4.0.0-1.fm1_10.git.383.cd4469f.fc19.src.rpm
Uploading srpm: /tmp/tito/rubygem-foreman_discovery-4.0.0-1.fm1_10.git.383.cd4469f.fc19.src.rpm
[                                    ]  00% 00:00:00     0.00 B        - B/sec
[====================================] 100% 00:00:01 100.02 KiB  92.78 KiB/sec
Created task: 317310
Task info: http://koji.katello.org/koji/taskinfo?taskID=317310
Wrote: /tmp/tito/ruby193-rubygem-foreman_discovery-4.0.0-1.fm1_10.git.383.cd4469f.git.383.cd4469f.el6.src.rpm



Submitting build with: koji -c ~/.koji/katello-config build --nowait --scratch foreman-plugins-nightly-rhel6 /tmp/tito/ruby193-rubygem-foreman_discovery-4.0.0-1.fm1_10.git.383.cd4469f.git.383.cd4469f.el6.src.rpm
Uploading srpm: /tmp/tito/ruby193-rubygem-foreman_discovery-4.0.0-1.fm1_10.git.383.cd4469f.git.383.cd4469f.el6.src.rpm
[                                    ]  00% 00:00:00     0.00 B        - B/sec
[====================================] 100% 00:00:01 100.09 KiB  90.85 KiB/sec
Created task: 317311
Task info: http://koji.katello.org/koji/taskinfo?taskID=317311
Wrote: /tmp/tito/ruby193-rubygem-foreman_discovery-4.0.0-1.fm1_10.git.383.cd4469f.git.383.cd4469f.git.383.cd4469f.el7.src.rpm



Submitting build with: koji -c ~/.koji/katello-config build --nowait --scratch foreman-plugins-nightly-rhel7 /tmp/tito/ruby193-rubygem-foreman_discovery-4.0.0-1.fm1_10.git.383.cd4469f.git.383.cd4469f.git.383.cd4469f.el7.src.rpm
Uploading srpm: /tmp/tito/ruby193-rubygem-foreman_discovery-4.0.0-1.fm1_10.git.383.cd4469f.git.383.cd4469f.git.383.cd4469f.el7.src.rpm
[                                    ]  00% 00:00:00     0.00 B        - B/sec
[====================================] 100% 00:00:01 100.11 KiB  86.07 KiB/sec
Created task: 317312
Task info: http://koji.katello.org/koji/taskinfo?taskID=317312
```

**Comment by domcleal** [comment]
Merged and building, will also cherry pick to rpm/1.9.  Thanks @lzap.

**Comment by lzap** [comment]
Thanks!

-- 
Later,
 Lukas #lzap Zapletal

**Pull request merged**
