### PR TITLE
Update foreman_remote_execution to 1.7.1

### PR DESCRIPTION
**Pull request by adamruzicka**
And core to 1.1.6

For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.21
* [ ] 1.20

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ekohl** [comment]
It fails to build:
```
DEBUG util.py:491:  Error: No Package found for tfm-rubygem(foreman-tasks) >= 0.15.1
```

**Comment by adamruzicka** [comment]
Requires:
- [ ] https://github.com/theforeman/foreman-packaging/pull/3628

**Comment by ekohl** [comment]
Waiting for https://github.com/theforeman/foreman-packaging/pull/3753 to be merged so we don't need to rebuild immediately after.

**Comment by iNecas** [comment]
Closing in favor of rpm/foreman_remote_execution-1.8.0

**Pull request closed without merging**
