### PR TITLE
Release 1.17.1

### PR DESCRIPTION
**Pull request by xprazak2**
For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [x] 1.17
* [ ] 1.16
* [ ] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ekohl** [comment]
I think this failed because it's comparing the branch to *your* `deb/1.17` which doesn't exist. Not sure that's what we should do, but I think the quickest fix is if you push `deb/1.17` and rerun the tests.

**Comment by mmoll** [comment]
the job is indeed broken, or the parameter passing to it

**Comment by dLobatog** [comment]
Next step of the pipeline kicked off at http://ci.theforeman.org/job/release_packages/125, @xprazak2 please sign the RPMs once the job is done as I think you're the only one who has the keys.

@komidore64 Was this job one of the jobs recently rewritten to JJB? I also see `deb/deb/develop` for example in the tests in https://github.com/theforeman/foreman-packaging/pull/2514

**Comment by komidore64** [comment]
@dLobatog looks like was was [added](https://github.com/theforeman/foreman-infra/commit/403fd0ab) in February.

**Comment by mmoll** [comment]
iirc this stopped to work when jjb on ci.theforeman.org had some problems and after it got moved to slave02(because newer CentOS with newer python) somehow these problems arose...

**Comment by ekohl** [comment]
I wonder if I introduced this in https://github.com/theforeman/foreman-infra/commit/adb5642530827412a5a4cdfefe4b02ae4f905c2c

**Comment by mmoll** [comment]
unsure, but I think that worked...

**Comment by ekohl** [comment]
I think my commit in combination with https://github.com/theforeman/foreman-infra/blob/4815364015b0ae3de9b9376de8f01969fd86a05e/puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/packaging_build_deb_coreproject.yaml#L12 could be an issue. In https://github.com/theforeman/foreman-infra/commit/f87a62691b2d296048dab6f1147272d03de42258 the `deb/` was added to fix something, probably to reflect a change from my change.

**Pull request merged**
