### PR TITLE
Bump Foreman Ansible (core) to version 3

### PR DESCRIPTION
**Pull request by ekohl**
This bumps the SCL'ed bits of Foreman Ansible to version 3. It regenerates the spec files and includes the webpack dependencies now.

### CODE REVIEW

**Comment by ekohl** [comment]
> Error: No Package found for npm(classnames) >= 2.2.6
2.2.5

> Error: No Package found for npm(lodash) = 4.17.10
4.17.11

> Error: No Package found for npm(prop-types) >= 15.7.2
15.6.2

> Error: No Package found for npm(react-bootstrap) >= 0.32.4
0.32.1

> Error: No Package found for npm(react-redux) >= 6.0.0
5.0.7

> Error: No Package found for npm(redux) >= 4.0.1
3.7.2

> Error: No Package found for npm(seamless-immutable) = 7.1.2
7.1.3

**Comment by ekohl** [comment]
@theforeman/ansible this will need a new foreman_ansible release with compatible versions.

**Comment by ares** [comment]
@xprazak2 could you please pin those?

**Comment by xprazak2** [comment]
Changed in https://github.com/theforeman/foreman_ansible/pull/263

**Comment by ares** [comment]
should be replaced by the linked PR

**Pull request closed without merging**
