### PR TITLE
Foreman tasks 0.6.13 + dynflow 0.7.7

### PR DESCRIPTION
**Pull request by iNecas**

### CODE REVIEW

**Comment by domcleal** [comment]
@iNecas please use `git annex add` rather than `git add` for the gems.

**Comment by domcleal** [comment]
1. dynflow description has changed, now it's `Ruby workflow/orchestration engine`
2. foreman-tasks min dynflow version has increased

**Comment by iNecas** [comment]
@domcleal ty, I always forgot doing the anned, will update (my had a feeling something was different). Thanks for the comments (is the lint script you're using for that available somewhere?:)

**Comment by domcleal** [comment]
Yep, it's [gem-compare](https://rubygems.org/gems/gem-compare): https://gist.github.com/domcleal/7a602a5fc5dcf15f7f6a

**Comment by iNecas** [comment]
@domcleal updates ready for review

**Comment by domcleal** [comment]
Thanks @iNecas, building now.

**Comment by iNecas** [comment]
thanks, preparing the deb changes as well…

**Comment by domcleal** [comment]
That's very good of you!

**Pull request merged**
