### PR TITLE
Update rubygem-foreman_virt_who_configure to 0.4.5

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
this is a 1.24 release

**Comment by evgeni** [comment]
> this is a 1.24 release

what does that mean? it doesn't define a min_version of 1.24 and we didn't branch 1.24 yet :)

**Comment by ares** [comment]
This should be available in 1.24 / 3.14 repos, so either get it to nightlies or if branchinh happens first, we'll need to cherrypick. The only patch didn't need 1.24 bump, hence it's just minor version update.

**Comment by evgeni** [comment]
branching didn't happen yet, so you're good.

**Pull request merged**
