### PR TITLE
[RPM] Update kafo to 2.0.2

### PR DESCRIPTION
**Pull request by ares**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.15
* [ ] 1.14
* [ ] 1.13

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ehelms** [comment]
@ares Just to double check, the bug fixes in 2.0.2 are not worth 1.15 z-stream?

**Comment by ares** [comment]
I think it would be good but in past, we were only able to build plugin into released versions. If you and @dLobatog are ok with merging into 1.15 then let's do it. There are 4 fixes since last 1.15 version which is 2.0.0, all should be safe, the bigger 2 were tested in nightlies for a while. I'll update DEB PR too once it's confirmed.

**Comment by ares** [comment]
The 19215 fixes issues when parsing the typed params. I haven't seen the problem myself but the reproduced illustrated it pretty well. The second one is very safe, I haven't seen the issue in foreman-installer but katello-installer would probably appreciate that as it seems they define the type which would be registered twice.

Long story short: it should be safe even without huge impact on foreman-installer. I tested 2.0.2 with 1.15 installer and it worked fine.

**Comment by mmoll** [comment]
what's the status here?

**Comment by ehelms** [comment]
@dLobatog your call then here on whether I build this into 1.15. I think it has fixes that affect folks and is fairly safe myself.

**Comment by ehelms** [comment]
@dLobatog ping

**Comment by mmoll** [comment]
OPs comment in #1708 ;)

**Comment by ares** [comment]
ok, OP sets 1.15, he thought it was against rules which seems no longer the case :-)

**Comment by ares** [comment]
any chance this gets in? debs have been made available for some time

**Comment by mmoll** [comment]
merged, díky @ares!

**Pull request merged**
