### PR TITLE
Update foreman_expire_hosts to 4.0.0 [rpm]

### PR DESCRIPTION
**Pull request by timogoebel**
Please build for:

* [x] Nightly
* [x] 1.16
* [ ] 1.15
* [ ] 1.14

### CODE REVIEW

**Comment by ekohl** [comment]
Now that the plugin has seeds, should it call ```foreman_db_seed``` in ```%posttrans```?

**Comment by timogoebel** [comment]
@ekohl: Good catch, fixed. Thanks.

**Comment by timogoebel** [comment]
[test]

**Comment by ekohl** [comment]
[test]

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
