### PR TITLE
Bump Katello + h-c-k for 4.16 branching

### PR DESCRIPTION
**Pull request by ianballou**

### CODE REVIEW

**Review by ekohl — APPROVED** [review]

**Comment by ekohl** [comment]
Oh, I now see the new merge experience no longer has the option to bypass:
Screen Shot 2024-11-11 at 12 26 50
Compare it to the classic:
Screen Shot 2024-11-11 at 12 27 44

Note the missing checkbox.

**Comment by evgeni** [comment]
heh. yeah. I was about to say. I was bypassing that all the time.

**Comment by ekohl** [comment]
https://github.com/orgs/community/discussions/143787 lists a known bug:
> Admin bypass checkbox not always appearing preventing users from bypassing merge requirements

**Comment by ianballou** [comment]
Thanks all!

**Pull request merged**
