### PR TITLE
Update katello-certs-tools to 2.8.1

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
Repoclosure failure is unrelated and from local testing appears to either be something cached on the nodes or just network issues talking to the AppStream repository.

**Comment by evgeni** [comment]
Is this safe to pick to 2.5? Given it had 2.7.z before?
Also, if it is, can you include the old changelog entries? It will be tagged, not built, so the rpm wouldn't match git?

**Comment by ehelms** [comment]
> Is this safe to pick to 2.5? Given it had 2.7.z before? Also, if it is, can you include the old changelog entries? It will be tagged, not built, so the rpm wouldn't match git?

I feel OK with it. Before I opened this I looked at the diff and nothing stuck out to me.

**Comment by ehelms** [comment]
Here ya go -- added changelog entry and cherry picked the repoclosure fix

**Review by evgeni — APPROVED** [review]

**Comment by evgeni** [comment]
@ehelms I think you forgot to actually tag the build into 2.5 ;)

**Pull request merged**
