### PR TITLE
Release foreman_remote_execution 0.3.2 (RPM)

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by domcleal** [comment]
It looks like 0.3.1 isn't compatible with Rails 4.2, so I'm not sure this is meant to be targeted at rpm/develop.  Should it be on rpm/1.11?

**Comment by stbenjam** [comment]
0.3.2 should work on both

**Comment by stbenjam** [comment]
Good to go for 1.11 and nightly

**Comment by domcleal** [comment]
Thanks @stbenjam, merged and building for both now.

**Pull request merged**
