### PR TITLE
Update foreman_remote_execution to 1.6.1

### PR DESCRIPTION
**Pull request by adamruzicka**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.19
* [ ] 1.18
* [ ] 1.17

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by adamruzicka** [comment]
Guess I'll have to rebase this when https://github.com/theforeman/foreman-packaging/pull/2859 gets in

**Comment by adamruzicka** [comment]
Rebased

**Comment by mmoll** [comment]
The `1.20.0` version constraints need to get `~rc1` added.

**Comment by mmoll** [comment]
[test packaging]

**Comment by mmoll** [comment]
merged, díky @adamruzicka!

**Pull request merged**
