### PR TITLE
Fix react-popper dependency on typed-styles

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
eh, why does that fail closure?! halp

**Comment by evgeni** [comment]
because it didn't look at foreman at all -.-

**Comment by evgeni** [comment]
According to @ehelms this is another rabbit hole we don't want right now

**Comment by ehelms** [comment]
Ya... we *should* update it, but the build issues I hit were strange and a rabbit hole as @evgeni mentions. I'd rather us tackle that when things have calmed down and stick with what we know works.

**Comment by ehelms** [comment]
Filed a ticket to track: https://projects.theforeman.org/issues/29599

**Pull request merged**
