### PR TITLE
[RPM] Update kafo to 2.1.0

### PR DESCRIPTION
**Pull request by ares**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.16
* [ ] 1.15
* [ ] 1.14

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by mmoll** [comment]
blocked on https://github.com/voxpupuli/puppet-extlib/pull/89

**Comment by mmoll** [comment]
and https://github.com/voxpupuli/puppet-staging/pull/150

**Comment by ekohl** [comment]
Finally got around to creating https://github.com/voxpupuli/puppet-staging/pull/152

**Comment by ehelms** [comment]
This y-release of Kafo requires that all puppet modules support Puppet 5?

**Comment by ekohl** [comment]
Correct - it verifies the OS is listed in metadata.json and the running puppet version matches the constraints. The current issue is that puppetlabs-mysql doesn't allow puppet-staging 3.0. We need https://github.com/puppetlabs/puppetlabs-mysql/commit/c5eb9bacd8ce4833e45ace1e26bd534f810ca1ce to be in a released version. I haven't checked how it handles modules without a puppet metadata version (https://github.com/jlambert121/jlambert121-trusted_ca/blob/master/metadata.json - used in Katello) but I'm leaning to forking that anyway (https://github.com/jlambert121/jlambert121-trusted_ca/issues/37).

**Comment by ares** [comment]
> This y-release of Kafo requires that all puppet modules support Puppet 5?

I don't think that's a fair summary. Kafo 2.1 added  a feature to parse module metadata and validate the module can be used by the puppet that's used. There's a `--skip-puppet-version-check` for disabling it. See this for more details https://github.com/theforeman/kafo/pull/213 in fact it let us know about possible incompatibilities that we ignored so far.

**Comment by ekohl** [comment]
https://tickets.puppetlabs.com/browse/MODULES-6312

**Comment by mmoll** [comment]
to be merged together with https://github.com/theforeman/foreman-installer/pull/256

**Pull request merged**
