### PR TITLE
Update dynflow to 0.8.7 (DEB)

### PR DESCRIPTION
**Pull request by iNecas**

### CODE REVIEW

**Comment by mmoll** [comment]
ruby-sequel needs to be specified as dependency.

**Comment by mmoll** [comment]
also, the branch name must begin with `deb/` for the PR tests to work :)

**Comment by iNecas** [comment]
I do the deb releases exactly at a frequency, that I keep forgetting about the branch naming convetion (I knew there was some, but I though should not have '/' in the name :)

**Comment by iNecas** [comment]
@mmoll let's try again https://github.com/theforeman/foreman-packaging/pull/838

**Pull request closed without merging**
