### PR TITLE
Update kafo to 0.7.0

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
requires https://github.com/theforeman/foreman-packaging/pull/807

**Comment by domcleal** [comment]
Is this compatible with foreman-installer currently?  It looks like there might have been config changs.

**Comment by ares** [comment]
I haven't tested with foreman-installer exactly but all changes are backwards compatible (and I tested them separately with foreman-installer except the last one), @mbacovsky have you?

**Comment by mmoll** [comment]
At least it seems to work on my existing installation on Debian with 0.7.0 :+1:

**Comment by mbacovsky** [comment]
I tested scratch build of kafo 0.7.0 with kafo-wizards and existing installer and installation finished okay. New options like '--list-scenarios' are present in 'foreman-installer -h' and work. The original foreman-installer.yaml is selected by default, no config updates are needed.

**Comment by domcleal** [comment]
Thanks all, merged and building now.

**Pull request merged**
