### PR TITLE
Update ruby-libvirt to 0.7.0

### PR DESCRIPTION
**Pull request by xprazak2**
Created by command:

/usr/bin/tito tag --keep-version

For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [x] 1.15
* [ ] 1.14
* [ ] 1.13

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

Higher ruby-libvirt gem is required by [smart-proxy](https://github.com/theforeman/smart-proxy/blob/1.15-stable/bundler.d/libvirt.rb#L2)

### CODE REVIEW

**Comment by ekohl** [comment]
This may be my limited knowledge of RPM packaging but why don't you change ```%version```?

**Comment by xprazak2** [comment]
Version updated, thanks. I just took the commit that is already in nightlies and did not check it properly.

**Comment by ehelms** [comment]
@xprazak2 Looks like you amended an existing commit? I'd recommend starting fresh and pushing a new commit. Please also update the release! Thanks.

**Comment by xprazak2** [comment]
I created a fresh commit.

**Comment by ehelms** [comment]
@xprazak2 before I merge, want to check why this is not going into nightly?

**Comment by xprazak2** [comment]
@ehelms, 0.7.0 is already in [rpm/upstream](https://github.com/theforeman/foreman-packaging/tree/rpm/develop/rubygem-ruby-libvirt)

**Pull request merged**
