### PR TITLE
Update rubygem-foreman_discovery to 17.0.0

### PR DESCRIPTION
**Pull request by lzap**
For plugin updates, please indicate which repos this should be built into:

* Nightly
* 2.4

Do not merge yet, I will be testing the RPM build shortly.

### CODE REVIEW

**Review by evgeni — APPROVED** [review]

**Comment by lzap** [comment]
I am still testing, but okay, thanks :-)

**Comment by evgeni** [comment]
Don't open non-draft PRs if you're testing ;-)

**Comment by lzap** [comment]
I want to trigger tests to get scratchbuild to have an artifact to test.

**Comment by lzap** [comment]
CP 2.4: https://github.com/theforeman/foreman-packaging/pull/6590

Do not merge please.

**Comment by evgeni** [comment]
Draft PRs get scratch built.

**Comment by lzap** [comment]
Oh nice, converted the PR to draft: https://github.blog/changelog/2020-04-08-convert-pull-request-to-draft/

**Pull request merged**
