### PR TITLE
Fixes #22376 - Use TMPDIR instead own temporary directory

### PR DESCRIPTION
**Pull request by lzap**
@iNecas counterpart for https://github.com/theforeman/foreman/pull/5040

* [x] Nightly

---

### CODE REVIEW

**Comment by ekohl** [comment]
For me $AUXTMP is unset. I've never heard of that var either. How will this work?

**Comment by lzap** [comment]
@ekohl have you tried with the patch I reference from the description?

https://github.com/theforeman/foreman/pull/5040/files#diff-530ce7cdbd9b2169eb6a5d364c87b049R264

**Comment by ekohl** [comment]
Wouldn't it be better to just set ```TMPDIR``` since that's the convention? Tools like mktemp should also honor that if the script was ever expanded.

**Comment by iNecas** [comment]
I wasn't aware of the `$TMPDIR` behaviour, but looking at that, it really looks like the most suitable approach.

**Comment by lzap** [comment]
After discussion I am pushing new version that works via TMPDIR. I haven't tested on real setup, but I can confirm it should work.

```
[root@zzzap ~]# mktemp -d
/tmp/tmp.c8UjxXHR8U
[root@zzzap ~]# export TMPDIR=/tmp/test
[root@zzzap ~]# mktemp -d
/tmp/test/tmp.NJn24Ky5rt
```

**Pull request merged**
