### PR TITLE
Update rubygem-smart_proxy_ansible to 3.0.1

### PR DESCRIPTION
**Pull request by xprazak2**
(cherry picked from commit 7d10e92d7a1342c10dd3f8e16f99603108bb795f)

cp for 1.22

### CODE REVIEW

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm]

**Comment by xprazak2** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Pull request merged**
