### PR TITLE
Update rubygem-smart_proxy_acd to 0.3.0

### PR DESCRIPTION
**Pull request by sbernhard**
(cherry picked from commit d8d98adf87f6c947e7bd4f41961d41cef8f2ad04)

### CODE REVIEW

**Comment by sbernhard** [comment]
[test rpm]

**Comment by Odilhao** [comment]
[test rpm]

**Comment by Odilhao** [comment]
I'll try to run the rpm test again after #7313

**Comment by Odilhao** [comment]
[test rpm]

**Review by Odilhao — APPROVED** [review]

**Pull request merged**
