### PR TITLE
Fixes #32576:  Update Rails stack to 6.0.3.7

### PR DESCRIPTION
**Pull request by ehelms**
(cherry picked from commit f16262b51e1e2c99bdb8a12ec31e485c5bb94976)

### CODE REVIEW

**Comment by evgeni** [comment]
> This will need to include #6632 as part of the cherry pick once its merged.

it is merged now.

**Comment by ehelms** [comment]
> > This will need to include #6632 as part of the cherry pick once its merged.
> 
> it is merged now.

is cherry-picked now

**Review by evgeni — APPROVED** [review]

**Comment by ehelms** [comment]
> > > > This will need to include #6632 as part of the cherry pick once its merged.
> > > 
> > > 
> > > it is merged now.
> > 
> > 
> > is cherry-picked now
> 
> is approved now

is going to let the current release owner handle when to merge

**Comment by evgeni** [comment]
> > > > > This will need to include #6632 as part of the cherry pick once its merged.
> > > > 
> > > > 
> > > > it is merged now.
> > > 
> > > 
> > > is cherry-picked now
> > 
> > 
> > is approved now
> 
> is going to let the current release owner handle when to merge

is pretending to be release owner and has tagged everything in and is now merging

**Pull request merged**
