### PR TITLE
drop foremandist from the release of core gems

### PR DESCRIPTION
**Pull request by evgeni**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.20
* [ ] 1.19
* [ ] 1.18

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by evgeni** [comment]
Correct. But: we ship 124 "core" gems in the SCL (https://github.com/theforeman/foreman-packaging/blob/rpm/develop/rel-eng/tito.props#L176) and only  these three have foremandist in their release. Makes me wonder why. Are the other gems not dependant on the Ruby version in the SCL?

**Comment by evgeni** [comment]
Looking at commits like https://github.com/theforeman/foreman-packaging/commit/0935aa36cce7f6fcd94ddd46eb432b1a3283c4ae makes me think they are?

**Comment by ekohl** [comment]
Yes, but I think in practice we don't really cherry pick those so haven't ran into it. Perhaps here we have.

**Comment by evgeni** [comment]
obsoleted by https://github.com/theforeman/foreman-packaging/pull/3211

**Pull request closed without merging**
