### PR TITLE
Update rubygem-foreman_scap_client to 0.1.0.

### PR DESCRIPTION
**Pull request by isimluk**

### CODE REVIEW

**Comment by domcleal** [comment]
This release isn't available on rubygems.org, could you please push it there so our build system can retrieve it?  I'd strongly recommend adding a git tag to the project repo too.

**Comment by isimluk** [comment]
@ares Could you please upload the rubygem?

**Comment by ares** [comment]
@isimluk uploaded and added you as owner as well

**Comment by domcleal** [comment]
[test]

**Comment by domcleal** [comment]
Thanks @isimluk, building now!

**Pull request merged**
