### PR TITLE
Update puppetdb_foreman to 3.0.1 [rpm]

### PR DESCRIPTION
**Pull request by timogoebel**
Please build for

* [x] Nightly
* [x] 1.15
* [x] 1.14
* [x] 1.13

### CODE REVIEW

**Comment by timogoebel** [comment]
Tests fail because of https://github.com/Apipie/apipie-rails/issues/539

```
NoMethodError: undefined method `reloader' for #<Foreman::Application:0x000000036d2510>
/opt/theforeman/tfm/root/usr/share/gems/gems/apipie-rails-0.5.0/lib/apipie/application.rb:427:in `rails_mark_classes_for_reload'
/opt/theforeman/tfm/root/usr/share/gems/gems/apipie-rails-0.5.0/lib/apipie/application.rb:294:in `reload_documentation'
/opt/theforeman/tfm/root/usr/share/gems/gems/apipie-rails-0.5.0/lib/apipie/apipie_module.rb:18:in `method_missing'
/opt/theforeman/tfm/root/usr/share/gems/gems/apipie-rails-0.5.0/lib/tasks/apipie.rake:194:in `with_loaded_documentation'
/opt/theforeman/tfm/root/usr/share/gems/gems/apipie-rails-0.5.0/lib/tasks/apipie.rake:64:in `block (2 levels) in <top (required)>'
/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/builddir/build/BUILD/puppetdb_foreman-3.0.1/usr/share/foreman/lib/tasks/plugin_apipie.rake:18:in `block in <top (required)>'
/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/opt/rh/rh-ruby22/root/usr/share/ruby/monitor.rb:211:in `mon_synchronize'
/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/opt/rh/rh-ruby22/root/usr/share/gems/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/opt/rh/rh-ruby22/root/usr/bin/rake:33:in `<main>'
```

**Comment by timogoebel** [comment]
@domcleal : Any advice what the best approach is to overwrite this?

**Comment by domcleal** [comment]
Yes, I just removed the newer package from the buildroot, it should now work. [test]

**Comment by timogoebel** [comment]
@domcleal : Thanks. Added the `%posttrans` section. I must have missed that during diffing.

**Comment by domcleal** [comment]
Merged and building, thanks @timogoebel.

**Pull request merged**
