### PR TITLE
(DEB) Updated hammer_cli to 0.12.0

### PR DESCRIPTION
**Pull request by mbacovsky**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.17
* [ ] 1.16
* [ ] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by akofink** [comment]
Any thoughts on the failure?

```
09:10:46 -- Creating Debian source package from ./hammer-cli-0.12.0.tar.gz ...
09:10:58 /usr/lib/ruby/vendor_ruby/gem2deb/dh_make_ruby.rb:149:in `stat': No such file or directory @ rb_file_s_stat - /home/jenkins/.cache/gem2deb/gem_to_packages.yaml.new (Errno::ENOENT)
09:10:58 	from /usr/lib/ruby/vendor_ruby/gem2deb/dh_make_ruby.rb:149:in `generate_or_update_gem_to_package_data'
09:10:58 	from /usr/lib/ruby/vendor_ruby/gem2deb/dh_make_ruby.rb:66:in `initialize'
09:10:58 	from ../../gem2deb:96:in `new'
09:10:58 	from ../../gem2deb:96:in `<main>'
```

**Comment by mbacovsky** [comment]
I rebuild the job and it failed on different combination in configuration matrix so it seems rather related to the CI

**Comment by mmoll** [comment]
It's a long-standing problem. I *think* it fails an every host, if it's the very first time of a specific package to get built on that host.

**Comment by mmoll** [comment]
This needs the unicode dependency added. It's already packaged as ruby-unicode for all Debians and Ubuntus.

**Comment by mbacovsky** [comment]
Updated

**Comment by mmoll** [comment]
merged, díky @mbacovsky!

**Pull request merged**
