### PR TITLE
foreman-google: Add replaces for foreman before 3.5

### PR DESCRIPTION
**Pull request by evgeni**
We ship the same gems as foreman 3.4 which results in errors from apt if we don't allow to overwrite them and apt decides to unpack the plugin before foreman itself.

### CODE REVIEW

**Comment by evgeni** [comment]
needs https://github.com/theforeman/foreman-packaging/pull/8716

**Comment by ekohl** [comment]
Waiting for https://ci.theforeman.org/job/foreman-packaging-deb-nightly-release/281/ to complete.

**Comment by evgeni** [comment]
[test deb]

**Comment by evgeni** [comment]
🍏

**Review by ekohl — APPROVED** [review]

**Pull request merged**
