### PR TITLE
Refs #37212 - Retire foreman_setup plugin

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by evgeni** [comment]
Rewrite in what? "whitespace"? ;-)

**Review by evgeni — APPROVED** [review]
the commit message could use a rewrite, otherwise ACK

**Comment by ekohl** [comment]
Updated, and https://github.com/theforeman/foreman-installer/pull/926 is the installer side.

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman-packaging/pull/10625 also makes foreman itself conflict with the plugin. Should we do the same here?

**Comment by evgeni** [comment]
I don't think I like that (but can't really say why)

**Comment by evgeni** [comment]
```
[root@web01 apt]# rm ./plugins/nightly/ruby-foreman-setup_8.0.1-1_all.deb ./plugins/3.11/ruby-foreman-setup_8.0.1-1_all.deb
rm: remove regular file ‘./plugins/nightly/ruby-foreman-setup_8.0.1-1_all.deb’? y
rm: remove regular file ‘./plugins/3.11/ruby-foreman-setup_8.0.1-1_all.deb’? y
```

**Pull request merged**
