### PR TITLE
hammer_cli_foreman_google - add locale dir

### PR DESCRIPTION
**Pull request by stejskalleos**

### CODE REVIEW

**Comment by stejskalleos** [comment]
Somehow `The build in Copr has failed` ...

**Comment by ekohl** [comment]
Packaging only works on released gems. You need to create a release that actually includes this directory.

**Comment by stejskalleos** [comment]
Re-released 1.1.0

**Comment by stejskalleos** [comment]
Looks like it is almost fixed.

These two passed:
copr/rubygem-hammer_cli_foreman_google-rhel-8-x86_64
copr/rubygem-hammer_cli_foreman_google-rhel-9-x86_64

But not the rpm-copr

**Review by evgeni — APPROVED** [review]

**Pull request merged**
