### PR TITLE
Update rubygem-foreman_bootdisk to 19.0.0

### PR DESCRIPTION
**Pull request by lzap**
For plugin updates, please indicate which repos this should be built into:

* Nightly
* 3.1

Will do PR or cherry pick what you prefer, thanks!

### CODE REVIEW

**Comment by Odilhao** [comment]
[test rpm]

**Comment by evgeni** [comment]
https://github.com/theforeman/foreman_bootdisk/commit/3d35118e09a4c1db3c0bad61648c409b60fb54d7 changed the contents of the gem, but your `%files` section was not updated.

**Comment by Odilhao** [comment]
Hi @lzap 

Looking at the changes that Evgeni linked, we will need to to remove the following lines

https://github.com/theforeman/foreman-packaging/blob/f5b7c9c9422e54db60019aaf7381f3eb479f5af7/packages/plugins/rubygem-foreman_bootdisk/rubygem-foreman_bootdisk.spec#L107-L109

or only Remove line 108 and add `AUTHORS` back to the gemspec file.

https://github.com/theforeman/foreman-packaging/blob/f5b7c9c9422e54db60019aaf7381f3eb479f5af7/packages/plugins/rubygem-foreman_bootdisk/rubygem-foreman_bootdisk.spec#L108

**Comment by evgeni** [comment]
I've regenerated the whole spec file based on our templates, you can find the result in https://github.com/theforeman/foreman-packaging/pull/7400 :)

**Comment by evgeni** [comment]
#7400 is merged

**Comment by lzap** [comment]
Damn sorry, thanks. So from what I can tell (not done with PR notifications for this project yet) only DEB is pending.

**Pull request closed without merging**
