### PR TITLE
update Foreman/Katello nightly versions

### PR DESCRIPTION
**Pull request by evgeni**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.22
* [ ] 1.21
* [ ] 1.20

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ekohl** [comment]
Updated to reset releases and add a changelog. Hopefully the build finishes now.

**Comment by jturel** [comment]
[test rpm]

**Comment by ekohl** [comment]
@evgeni https://github.com/theforeman/foreman-infra/pull/1029 should do that.

**Comment by ekohl** [comment]
This shouldn't be merged before https://github.com/theforeman/tool_belt/pull/165

**Pull request merged**
