### PR TITLE
Update sass-rails dependency

### PR DESCRIPTION
**Pull request by ezr-ondrej**
This one is a reminder for:
- [ ] #4661 is merged

### CODE REVIEW

**Comment by tbrisker** [comment]
Can you please split off the update of the sass-rails dependency so that we can merge https://github.com/theforeman/foreman-packaging/pull/4661 and https://github.com/theforeman/foreman/pull/7396?

**Comment by ezr-ondrej** [comment]
Splitted, rebased :)

**Comment by tbrisker** [comment]
I believe this should now be green once foreman-source-release pipeline with the core change finishes

**Comment by ezr-ondrej** [comment]
I've rebased and opened a PR - #4828 to raise awarness to Ewound's comments from original PR.

**Comment by pcreech** [comment]
This looks like it can use a rebase

**Comment by ezr-ondrej** [comment]
I don't think there is a need for it anymore. This would just raise the dependency to `> 6` and I don't thinkg it's worth it.

**Pull request closed without merging**
