### PR TITLE
Refs #26542 - Fix references to GPL-3

### PR DESCRIPTION
**Pull request by bkearney**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.21
* [ ] 1.20

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ekohl** [comment]
Looks like we rev bumps for this though.

**Comment by bkearney** [comment]
@ekohl I dont know what that last one means.

**Comment by dgoetz** [comment]
@bkearney He means, that this requires a rebuild of the package which requires an increase of the revision number, so for example `Release: 1%{?dist}` should be increased to `Release: 2%{?dist}`.

**Comment by ekohl** [comment]
The easiest is to use `obal bump-release rubygem-kafo rhel8-kickstart-setup rubygem-foreman_git_templates --changelog '- Corrected the license format'. https://copr.fedorainfracloud.org/coprs/ekohl/obal/ is the RPMs I maintain for it.

**Comment by ehelms** [comment]
@bkearney ping

**Comment by ehelms** [comment]
Replaced by https://github.com/theforeman/foreman-packaging/pull/4131

**Pull request closed without merging**
