### PR TITLE
Don't install package and repository upload on DNF installs

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by jturel** [comment]
Subman started uploading this data itself on el8 but (_someone_ asked for it) still needed a way to force the uploads so  we left the CLI tools. I have a distant memory of adding dnf plugin commands to do the same so (iirc) there is a way to force the upload without these scripts - doubt anyone ever used them

At one point I think some REX or katello-agent package actions (or something) called these commands after performing whatever the action was - this may break those if that's still the case but was probably a hack anyway :smile:

**Comment by ekohl** [comment]
So is this still a valid PR or should it be closed?

**Comment by ehelms** [comment]
@evgeni I lean towards closing this as it has sat stagnant and we do not have a clear answer to if it would break things.

**Comment by evgeni** [comment]
we don't ship the configs on DNF installs:
https://github.com/theforeman/foreman-packaging/blob/02ad412427a7b723c25b6bdfa515d0a74918c1b3/packages/client/katello-host-tools/katello-host-tools.spec#L362-L365

so it can't (and won't) work today (as it's not needed).

**Comment by ehelms** [comment]
> %config(noreplace) %{plugins_confdir}/package_upload.conf 
>  %config(noreplace) %{plugins_confdir}/enabled_repos_upload.conf

Touche. Care to rebase this PR?

**Comment by evgeni** [comment]
rebased

**Comment by ekohl** [comment]
Looks like there's another conflict by now.

**Comment by evgeni** [comment]
:disappointed:

**Review by ehelms — APPROVED** [review]

**Pull request merged**
