### PR TITLE
foreman_remote_execution 1.3.4 and friends [rpm/1.15]

### PR DESCRIPTION
**Pull request by iNecas**
For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [ ] 1.16
* [x] 1.15
* [ ] 1.14

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

Updating to 1.15 for now, until tasks packaging gets resolved in 1.16 and nightly in https://github.com/theforeman/foreman-packaging/pull/1549

### CODE REVIEW

**Comment by mmoll** [comment]
rubygem-foreman_remote_execution/foreman_remote_execution-1.3.4.gem is not a git-annexed file

**Comment by iNecas** [comment]
Damn, sry, updated

**Comment by ehelms** [comment]
Looks like this is having issues resolving the git annexed files

**Comment by iNecas** [comment]
It seems that was due to fact that I forgot to remove the old gems from the dirs. Pushed the fixed versions

**Pull request merged**
