### PR TITLE
Update foreman_ansible_core to 2.1.1

### PR DESCRIPTION
**Pull request by ares**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.19
* [x] 1.18
* [ ] 1.17

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by mmoll** [comment]
according to the gemspec, net-ssh ~> 4.0 was added as dependency?

**Comment by mmoll** [comment]
https://github.com/theforeman/foreman_ansible/commit/e258437698c7cc5115f5c7b3673bea4cb84273e6#commitcomment-29794543

**Comment by ares** [comment]
just opened https://github.com/theforeman/foreman_ansible/pull/194

**Comment by mmoll** [comment]
I took the liberty to update the control file to the actual gem dependencies. As only Ubuntu/bionic has net-ssh >4, Debian/stretch and Ubuntu/xenial would need net-ssh added in our repo or the net-ssh requirement needs to get lowered... Was there an actual feature required to use >4?

**Comment by ares** [comment]
> Was there an actual feature required to use >4?

No I think it was just developed with 4, I tested with 5 but most likely works with 3 too. I think the recent things we added was ssh key support for REX but since they don't ping anything, we should be fine without too https://github.com/theforeman/foreman_remote_execution/blob/master/foreman_remote_execution_core.gemspec#L21

So, should we drop the pin from gemspec entirely?

**Comment by mmoll** [comment]
I have no idea of the differences between their versions, for the currently supported DEB platforms, 3.0.1 is the lowest version...

**Comment by mmoll** [comment]
updated to 2.1.2 and merged, díky @ares!

**Pull request merged**
