### PR TITLE
Moved config out of hammer-cli-foreman-bootdisk

### PR DESCRIPTION
**Pull request by lzap**
For https://github.com/theforeman/hammer_cli_foreman_bootdisk/pull/2

Build to follow

### CODE REVIEW

**Comment by domcleal** [comment]
Thanks, though we'll do this on the next release.  Mind if I close it for now?

**Comment by lzap** [comment]
Sure, but why to close? Could keep it opened. Anyway it fails... http://koji.katello.org/koji/getfile?taskID=221295&name=build.log go ahead.

**Comment by domcleal** [comment]
Alright, though we'll probably encounter it anyway on the next release :)

**Comment by domcleal** [comment]
Part of b8eadcb, thanks.

**Pull request closed without merging**
