### PR TITLE
Update katello to 4.0.0

### PR DESCRIPTION
**Pull request by pcreech**

### CODE REVIEW

**Comment by evgeni** [comment]
```
Gem loading error: Could not find 'pulp_rpm_client' (< 3.10.0, >= 3.9.0) - did find: [pulp_rpm_client-3.8.0]
```

missing picks, once more ;)

**Comment by pcreech** [comment]
Yup, just getting back around to it.

**Comment by pcreech** [comment]
https://github.com/theforeman/foreman-packaging/pull/6471

**Comment by evgeni** [comment]
[test rpm]

**Review by evgeni — APPROVED** [review]

**Pull request merged**
