### PR TITLE
Update rubygem-foreman_fog_proxmox to 0.11.1

### PR DESCRIPTION
**Pull request by tristanrobert**
* Nightly

### CODE REVIEW

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
repoclosure expected, we didn't mash yet

**Comment by evgeni** [comment]
@tristanrobert thanks! as 2.1 branched in the meantime, can you please also open a PR against `rpm/2.1`?

**Comment by tristanrobert** [comment]
Thank you @evgeni . Ok I open a PR against rpm/2.1

**Pull request merged**
