### PR TITLE
Release foreman_remote_execution 0.0.7 (DEB)

### PR DESCRIPTION
**Pull request by stbenjam**
- [x] dynflow plugin 0.8.6 https://github.com/theforeman/foreman-packaging/pull/823
- [x] dynflow dep 0.8.6 https://github.com/theforeman/foreman-packaging/pull/825
- [x] smart_proxy_dynflow 0.0.4 https://github.com/theforeman/foreman-packaging/pull/824
- [x] smart_proxy_remote_execution_ssh 0.0.6 https://github.com/theforeman/foreman-packaging/pull/827
- [x] tasks 0.7.6 https://github.com/theforeman/foreman-packaging/pull/826
- [x] This PR

### CODE REVIEW

**Comment by ares** [comment]
Failed on `Could not connect to deb.theforeman.org:80` [test]

**Comment by mmoll** [comment]
[test]

**Comment by mmoll** [comment]
merged as 5f1f00c

**Comment by mmoll** [comment]
ruby-dynflow will appear on deb.tf.org after the next successful systest, the rest is already there, thanks a lot @stbenjam!

**Pull request closed without merging**
