### PR TITLE
Add rubygem-foreman_admin package

### PR DESCRIPTION
**Pull request by komidore64**

### CODE REVIEW

**Comment by domcleal** [comment]
This isn't a core Foreman project so it wouldn't be added to our main release repo as suggested in this PR, and we don't really have a contrib repo for third party tools.

Is this meant to be installed on a Foreman server?  How will that be done - manual installation, package dependencies or via our installer?

**Comment by komidore64** [comment]
Yes, this is meant to be installed on a Foreman (as well as on a Katello) server. I want it to be installed with the installer. That's next on the list of things to do for `foreman-admin`.

**Comment by mmoll** [comment]
Please also think about a Debian package then.

**Comment by domcleal** [comment]
Yeah, in that case I'd suggest submitting it to https://github.com/theforeman/foreman/tree/develop/script so it can be installed as part of Foreman.

**Comment by komidore64** [comment]
I have little knowledge of building DEB packages, help would be greatly appreciated.

I have some high-priority stuff to work on currently, but I will get back on this sometime next week.

**Comment by domcleal** [comment]
Yeah, that's one reason why simply putting it in Foreman saves us the burden of extra packages.

**Comment by komidore64** [comment]
@domcleal placing `foreman-admin` into `foreman`?

**Comment by domcleal** [comment]
Yes.

**Comment by komidore64** [comment]
the Foreman package is where Foreman bits live though. The server lives there. Foreman-Admin isn't really part of the server, so it doesn't make sense to me to lump it in with the server.

**Comment by domcleal** [comment]
If it's being installed on the Foreman server, then it's part of it and it can be maintained in the same way with branches etc.

**Comment by komidore64** [comment]
@domcleal I don't quite follow. can you please explain further? "maintained with branches" ?

**Comment by domcleal** [comment]
> "maintained with branches" ?

Foreman, like the other three top-level projects we ship in this repo is branched for releases.  It's likely that if we adopted this tool from you that we'd have to do the same, and I don't think adding another project is worth it for one command/tool.

If it's installed with the Foreman server then we should ship it as part of it, along with the other scripts and commands we install too.  It also will make it easier for plugins to extend as extensions can be carried in the Foreman plugin itself.

**Comment by mmoll** [comment]
what's the status here? :)

**Comment by komidore64** [comment]
``foreman-admin`` needs some more work before getting distributed with Foreman and/or Katello. I'm going to close this. I'll revisit in the future. @domcleal and @mmoll thank you for all your feedback!

**Pull request closed without merging**
