### PR TITLE
update webpack to v3.0

### PR DESCRIPTION
**Pull request by ohadlevy**

### CODE REVIEW

**Comment by dLobatog** [comment]
http://koji.katello.org/kojifiles/work/tasks/8155/8155/build.log fails because there's no npm:

```
+ npm cache add --cache ./npm_cache /builddir/build/SOURCES/webpack-3.0.0.tgz
/var/tmp/rpm-tmp.ywlyav: line 32: npm: command not found
```

**Comment by ohadlevy** [comment]
@dLobatog any idea why there is no npm?

**Comment by ohadlevy** [comment]
[test]

**Comment by ohadlevy** [comment]
@ehelms the tests fails because of it cant find packages introduced in this ps, is there a way to test all changes in one pr? or must i break it down to a PR per package? thanks.

**Comment by ehelms** [comment]
@ohadlevy Traditionally these kinds of changes have been done in a PR like this one. But it puts a burden on the reviewer to check it out locally, run mockchain builds to ensure everything passes. So while I prefer smaller individual PRs to address, this is fine but will take me a (or another maintainer) a bit longer to get to.

**Comment by ehelms** [comment]
@ohadlevy How many packages are updated in this PR? It's really hard to tell with the number of files changed what all has been changed and waht is going to need updating and what are new packages. If you could either list that out or split this up it would help a ton.

**Comment by ehelms** [comment]
@ohadlevy there appear to be some actual build errors when looking at (http://ci.theforeman.org/job/packaging_test_pull_request/2329/) that aren't in root log (typically the case for when dependent packages are missing. For example, I see (http://koji.katello.org/koji/taskinfo?taskID=8560) failing in the build.log with what appears to be a legitimate error. Can you check these and confirm?

**Comment by mmoll** [comment]
@ohadlevy what's the status here?

**Comment by ohadlevy** [comment]
@ehelms I'm not seeing the actual error - does koji no longer keeps it?

**Comment by ehelms** [comment]
@ohadlevy it will keep scratch builds for a short time, we can re-run it

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
I had to make the following changes to get the builds passing:

```
diff --git a/nodejs-extract-text-webpack-plugin/nodejs-bundle-extract-text-webpack-plugin.spec b/nodejs-extract-text-webpack-plugin/nodejs-extract-text-webpack-plugin.spec
similarity index 92%
rename from nodejs-extract-text-webpack-plugin/nodejs-bundle-extract-text-webpack-plugin.spec
rename to nodejs-extract-text-webpack-plugin/nodejs-extract-text-webpack-plugin.spec
index 5ebdea2..a553bc3 100644
--- a/nodejs-extract-text-webpack-plugin/nodejs-bundle-extract-text-webpack-plugin.spec
+++ b/nodejs-extract-text-webpack-plugin/nodejs-extract-text-webpack-plugin.spec
@@ -51,8 +51,8 @@ Provides: bundled-npm(fast-deep-equal) = 0.1.0
 Provides: bundled-npm(json-stable-stringify) = 1.0.1
 Provides: bundled-npm(co) = 4.6.0
 Provides: bundled-npm(jsonify) = 0.0.0
-AutoReq: no 
-AutoProv: no 
+AutoReq: no
+AutoProv: no
 
 
 %description
@@ -72,13 +72,10 @@ npm install --cache-min Infinity --cache . --no-optional --global-style true %{n
 %install
 mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
 cd node_modules/extract-text-webpack-plugin
-cp -pfr CHANGELOG.md ExtractedModule.js LICENSE OrderUndefinedError.js README.md index.js loader.js package.json schema node_modules %{buildroot}%{nodejs_sitelib}/%{npm_name}
+cp -pfr CHANGELOG.md ExtractedModule.js OrderUndefinedError.js README.md index.js loader.js package.json schema node_modules %{buildroot}%{nodejs_sitelib}/%{npm_name}
 cp -pf CHANGELOG.md README.md ../../
 # If any binaries are included, symlink them to bindir here
 
-
-%nodejs_symlink_deps
-
 %if 0%{?enable_tests}
 %check
 %{nodejs_symlink_deps} --check
@@ -88,7 +85,6 @@ cp -pf CHANGELOG.md README.md ../../
 %files
 %{nodejs_sitelib}/%{npm_name}
 
-%doc LICENSE
 %doc CHANGELOG.md
 %doc README.md
 
diff --git a/nodejs-fbjs/nodejs-bundle-fbjs.spec b/nodejs-fbjs/nodejs-fbjs.spec
similarity index 90%
rename from nodejs-fbjs/nodejs-bundle-fbjs.spec
rename to nodejs-fbjs/nodejs-fbjs.spec
index 9c5ed42..453f187 100644
--- a/nodejs-fbjs/nodejs-bundle-fbjs.spec
+++ b/nodejs-fbjs/nodejs-fbjs.spec
@@ -1,6 +1,3 @@
-# FIXME
-# Remove nodejs_symlink_deps if installing bundled module with NPM
-
 %global npm_name fbjs
 %global enable_tests 0
 
@@ -47,8 +44,8 @@ Provides: bundled-npm(node-fetch) = 1.7.1
 Provides: bundled-npm(is-stream) = 1.1.0
 Provides: bundled-npm(encoding) = 0.1.12
 Provides: bundled-npm(iconv-lite) = 0.4.18
-AutoReq: no 
-AutoProv: no 
+AutoReq: no
+AutoProv: no
 
 
 %description
@@ -68,13 +65,10 @@ npm install --cache-min Infinity --cache . --no-optional --global-style true %{n
 %install
 mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
 cd node_modules/fbjs
-cp -pfr CHANGELOG.md LICENSE PATENTS README.md flow index.js lib module-map.json package.json node_modules %{buildroot}%{nodejs_sitelib}/%{npm_name}
+cp -pfr CHANGELOG.md PATENTS README.md flow index.js lib module-map.json package.json node_modules %{buildroot}%{nodejs_sitelib}/%{npm_name}
 cp -pf CHANGELOG.md README.md ../../
 # If any binaries are included, symlink them to bindir here
 
-
-%nodejs_symlink_deps
-
 %if 0%{?enable_tests}
 %check
 %{nodejs_symlink_deps} --check
@@ -84,7 +78,6 @@ cp -pf CHANGELOG.md README.md ../../
 %files
 %{nodejs_sitelib}/%{npm_name}
 
-%doc LICENSE
 %doc CHANGELOG.md
 %doc README.md
 
diff --git a/nodejs-stats-webpack-plugin/nodejs-bundle-stats-webpack-plugin.spec b/nodejs-stats-webpack-plugin/nodejs-stats-webpack-plugin.spec
similarity index 84%
rename from nodejs-stats-webpack-plugin/nodejs-bundle-stats-webpack-plugin.spec
rename to nodejs-stats-webpack-plugin/nodejs-stats-webpack-plugin.spec
index 6d23add..aae37a6 100644
--- a/nodejs-stats-webpack-plugin/nodejs-bundle-stats-webpack-plugin.spec
+++ b/nodejs-stats-webpack-plugin/nodejs-stats-webpack-plugin.spec
@@ -1,6 +1,3 @@
-# FIXME
-# Remove nodejs_symlink_deps if installing bundled module with NPM
-
 %global npm_name stats-webpack-plugin
 %global enable_tests 0
 
@@ -21,8 +18,8 @@ ExclusiveArch: %{nodejs_arches} noarch
 
 Provides: bundled-npm(stats-webpack-plugin) = 0.6.1
 Provides: bundled-npm(lodash) = 4.17.4
-AutoReq: no 
-AutoProv: no 
+AutoReq: no
+AutoProv: no
 
 
 %description
@@ -42,13 +39,10 @@ npm install --cache-min Infinity --cache . --no-optional --global-style true %{n
 %install
 mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
 cd node_modules/stats-webpack-plugin
-cp -pfr LICENSE README.md index.js package.json node_modules %{buildroot}%{nodejs_sitelib}/%{npm_name}
+cp -pfr README.md index.js package.json node_modules %{buildroot}%{nodejs_sitelib}/%{npm_name}
 cp -pf README.md ../../
 # If any binaries are included, symlink them to bindir here
 
-
-%nodejs_symlink_deps
-
 %if 0%{?enable_tests}
 %check
 %{nodejs_symlink_deps} --check
@@ -58,7 +52,6 @@ cp -pf README.md ../../
 %files
 %{nodejs_sitelib}/%{npm_name}
 
-%doc LICENSE
 %doc README.md
 
 %changelog
diff --git a/nodejs-webpack/nodejs-bundle-webpack.spec b/nodejs-webpack/nodejs-webpack.spec
similarity index 99%
rename from nodejs-webpack/nodejs-bundle-webpack.spec
rename to nodejs-webpack/nodejs-webpack.spec
index c00e921..5e7fa94 100644
--- a/nodejs-webpack/nodejs-bundle-webpack.spec
+++ b/nodejs-webpack/nodejs-webpack.spec
@@ -1,6 +1,3 @@
-# FIXME
-# Remove nodejs_symlink_deps if installing bundled module with NPM
-
 %global npm_name webpack
 %global enable_tests 0
 
@@ -629,8 +626,8 @@ Provides: bundled-npm(ecc-jsbn) = 0.1.1
 Provides: bundled-npm(tweetnacl) = 0.14.5
 Provides: bundled-npm(is-number) = 3.0.0
 Provides: bundled-npm(kind-of) = 4.0.0
-AutoReq: no 
-AutoProv: no 
+AutoReq: no
+AutoProv: no
 
 
 %description
@@ -650,17 +647,14 @@ npm install --cache-min Infinity --cache . --no-optional --global-style true %{n
 %install
 mkdir -p %{buildroot}%{nodejs_sitelib}/%{npm_name}
 cd node_modules/webpack
-cp -pfr LICENSE README.md bin buildin hot lib package.json schemas web_modules node_modules %{buildroot}%{nodejs_sitelib}/%{npm_name}
+cp -pfr README.md bin buildin hot lib package.json schemas web_modules node_modules %{buildroot}%{nodejs_sitelib}/%{npm_name}
 cp -pf README.md ../../
 # If any binaries are included, symlink them to bindir here
-mkdir -p %{buildroot}%{nodejs_sitelib}/${npm_name}/bin 
-mkdir -p %{buildroot}%{_bindir}/ 
+mkdir -p %{buildroot}%{nodejs_sitelib}/${npm_name}/bin
+mkdir -p %{buildroot}%{_bindir}/
 install -p -D -m0755 bin/webpack.js %{buildroot}%{nodejs_sitelib}/%{npm_name}/bin/webpack.js
 ln -sf %{nodejs_sitelib}/%{npm_name}/bin/webpack.js %{buildroot}%{_bindir}/webpack.js
 
-
-%nodejs_symlink_deps
-
 %if 0%{?enable_tests}
 %check
 %{nodejs_symlink_deps} --check
@@ -670,7 +664,6 @@ ln -sf %{nodejs_sitelib}/%{npm_name}/bin/webpack.js %{buildroot}%{_bindir}/webpa
 %files
 %{nodejs_sitelib}/%{npm_name}
 %{_bindir}/webpack.js
-%doc LICENSE
 %doc README.md
 
 %changelog
```

**Comment by ohadlevy** [comment]
@ehelms I've applied your changes.

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
Thanks @ohadlevy . The webpack package is passing so I expect the plugins to also pass as they did locally. Merging and will build.

**Pull request merged**
