### PR TITLE
Update rubygem-net-ldap to 0.16.1

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ohadlevy** [comment]
bump as this is cve related? /cc @tbrisker

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman-packaging/pull/3864 should fix the repoclosure problem.

**Comment by ekohl** [comment]
[test rpm] because IIRC it merges the latest branch.

**Comment by ekohl** [comment]
I just realized that this should have had a `Refs #27154` after merging. Better yet, a real issue so we can properly make sure it's cherry picked. See https://github.com/theforeman/foreman/pull/6860#issuecomment-506314177 why it's easy to not really fix the CVE but be under the impression it is.

**Pull request merged**
