### PR TITLE
Build rubygem-logging for EL8

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by pcreech** [comment]
```
  package: rubygem-logging-2.2.2-5.el8.noarch from downloaded_rpms
       unresolved deps:
          (rubygem(multi_json) >= 1.10 with rubygem(multi_json) < 2)
          (rubygem(little-plugger) >= 1.1 with rubygem(little-plugger) < 2)
```

**Comment by ehelms** [comment]
Yes, I am trying to figure out why given http://koji.katello.org/releases/yum/foreman-nightly/RHEL/8/x86_64/rubygem-little-plugger-1.1.4-2.el8.noarch.rpm

**Comment by ehelms** [comment]
Ahh I think I see why, no lookaside defined.

**Comment by ehelms** [comment]
Oh wait, it is targeting the foreman Koji repository. I am stumped a smidge then.

**Comment by ehelms** [comment]
Looks like this is a problem with EL7's repoclosure not able to properly handle EL8 in all cases. The `dnf repoclosure` method does work. This will require a special EL8 based machine or a container to run repoclosure form.

**Comment by ehelms** [comment]
[test rpm]

**Pull request merged**
