### PR TITLE
Refs #24213 - Upgrade fog-vsphere gem version to 2.3.0

### PR DESCRIPTION
**Pull request by chris1984**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.18
* [ ] 1.17
* [ ] 1.16

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by dLobatog** [comment]
@chris1984 Is there any reason why this shouldn't go in 1.18, 1.17, 1.16? I'm wondering because someone asked today  on IRC as they want https://github.com/fog/fog-vsphere/commit/6da0386a4e0e993f746f954756b39c9899c616e7

**Comment by ares** [comment]
definitely should work with 1.18

**Comment by dLobatog** [comment]
Cherry-picked and tagged in 1.18, 1.17 and 1.16.  cc @sbernhard as afaik you needed it http://koji.katello.org/koji/buildinfo?buildID=29892

**Comment by dLobatog** [comment]
@xprazak2 Could you sign the package for 1.17 and 1.18 inclusion? https://github.com/dLobatog/foreman_release/blob/master/download-builds.sh is what I did

**Comment by xprazak2** [comment]
Signed for 1.17 and 1.18.

**Comment by timogoebel** [comment]
We got reports that this broke vm creation for users, see https://community.theforeman.org/t/foreman-1-16-2-vmware-fails/10565.

We also need to have https://github.com/theforeman/foreman/pull/5756 in 1.16+.

**Comment by tbrisker** [comment]
1.16 is no longer supported, and we won't have another release in that line. looks like we need to remove these packages from the 1.16 repo since it is incompatible with 1.16, to ensure users of 1.16 don't face issues due to the mismatching versions.

**Comment by ekohl** [comment]
For completeness, we have untagged it from 1.16 and 1.17. Even that patch it created a regression in 1.17.2 so we never released that and reverted it in 1.17.3.

**Pull request merged**
