### PR TITLE
Release foreman_ansible 1.4.2 [deb]

### PR DESCRIPTION
**Pull request by dLobatog**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.14
* [x] 1.13
* [x] 1.12

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

Replaces https://github.com/theforeman/foreman-packaging/pull/1498/files

### CODE REVIEW

**Comment by domcleal** [comment]
[test]

**Comment by mmoll** [comment]
https://github.com/theforeman/foreman_ansible/pull/76 might fix that error

**Comment by dLobatog** [comment]
Replaced by https://github.com/theforeman/foreman-packaging/pull/1527 which includes your change 😄 thanks @mmoll

**Comment by mmoll** [comment]
@dLobatog it would have been easier to just update this PR. Are there particular reasons not to re-use PRs by rebasing and updating also for the packaging repo?

**Pull request closed without merging**
