### PR TITLE
Add nodejs react router bootstrap

### PR DESCRIPTION
**Pull request by ehelms**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.17
* [ ] 1.16
* [ ] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by waldenraines** [comment]
We will also need `"react-router": "^4.2.0"` and `"react-bootstrap-tooltip-button": "^1.0.6"`.

**Comment by dLobatog** [comment]
router-bootstrap - http://koji.katello.org/koji/taskinfo?taskID=95707
router-dom - http://koji.katello.org/koji/taskinfo?taskID=95705
bootstrap-select -http://koji.katello.org/koji/taskinfo?taskID=95702
downshift - http://koji.katello.org/koji/taskinfo?taskID=95683

**Comment by ehelms** [comment]
Thanks @dLobatog ! Looks like maybe I needed to have done a few of these as bundles?

```
17:56:20 Num Packages in Repos: 33169
17:56:20 package: nodejs-react-router-dom-4.2.2-1.el7.noarch from undertest-yum_el7-4203183943-68
17:56:20   unresolved deps: 
17:56:20      npm(warning) < 0:4.0.0
17:56:20      npm(warning) < 0:4
17:56:20      npm(warning) >= 0:3.0.0
17:56:20      npm(react-router) < 0:5.0.0
17:56:20      npm(react-router) < 0:5
17:56:20      npm(react-router) >= 0:4.2.0
17:56:20      npm(invariant) < 0:3.0.0
17:56:20      npm(invariant) < 0:3
17:56:20      npm(invariant) >= 0:2.2.2
17:56:20      npm(history) < 0:5.0.0
17:56:20      npm(history) < 0:5
17:56:20      npm(history) >= 0:4.7.2
```

**Comment by evgeni** [comment]
@ehelms yeah, that, or packaging them :)

**Comment by ekohl** [comment]
Also, since these are katello dependencies, should they live in katello rather than foreman? I've been toying with rewriting the package addition script to support that but ran into some issues with the comps script and some repositories where it had assumptions on the comps structure. I'll continue on it and hopefully finish it soon.

**Pull request merged**
