### PR TITLE
[RPM] Update foreman_remote_execution to 1.4.5

### PR DESCRIPTION
**Pull request by ares**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.17
* [ ] 1.16
* [ ] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ekohl** [comment]
It failed: http://koji.katello.org/kojifiles/work/tasks/7604/77604/build.log

```
TypeError: no implicit conversion of nil into Hash
/builddir/build/BUILD/rubygem-foreman_remote_execution-1.4.3/usr/share/foreman/config/initializers/assets.rb:78:in `merge'
```

**Comment by mmoll** [comment]
I guess that's because https://github.com/theforeman/foreman/commit/e2194150e7532e03a1e6dce9c24b25d5725fa3c8 and _rex has assets outside its namespace.

**Comment by ares** [comment]
REX does not have its own namespace, anyway if [this](https://github.com/theforeman/foreman/commit/e2194150e7532e03a1e6dce9c24b25d5725fa3c8#diff-ef93e46bed34145a99e4a82b596fef21L14),  was removed, what is the correct way now?

**Comment by ares** [comment]
Ok, it seems we can introduce namespace just for assets, that means new foreman_remote_execution will be most likely released today, I'll update PRs afterwards

**Comment by ares** [comment]
[test]

**Comment by ares** [comment]
[test default]

**Pull request merged**
