### PR TITLE
update pulpcore and dependencies

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
I have expected this to fail repoclosure, but differently, investigating

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
contrary to what the repoclosure says, this would break pulpcore :/

**Comment by ehelms** [comment]
So repoclosure passing is a false positive? What should be breaking?

**Comment by evgeni** [comment]
@ehelms the pulpcore version in the repo does not allow pyyaml 5.2 (3.0 GA does, that's why it's here), but repoclosure does not honour conflicts :(

**Pull request merged**
