### PR TITLE
Update rubygem-hammer_cli_foreman to 0.15.0

### PR DESCRIPTION
**Pull request by mbacovsky**
For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [x] 1.20
* [ ] 1.19
* [ ] 1.18

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm]

**Comment by mbacovsky** [comment]
[test rpm]

**Comment by mbacovsky** [comment]
[test rpm]

**Comment by ekohl** [comment]
The issue is that hammer_cli 0.15.0 wasn't published at the URL yet so repoclosure is failing. I'll kick off mashing and see again.

**Comment by ekohl** [comment]
[test rpm]

**Comment by mbacovsky** [comment]
@ekohl thanks for taking care of the issues!

**Pull request merged**
