### PR TITLE
Drop foreman-compute requirement

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ehelms** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by tbrisker** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by tbrisker** [comment]
should we actually make foreman obsolete foreman-compute to make sure it gets removed?

**Comment by evgeni** [comment]
Yes please

**Comment by tbrisker** [comment]
https://github.com/theforeman/foreman-packaging/pull/3580

**Pull request merged**
