### PR TITLE
[WIP] Add nodejs-theforeman-vendor

### PR DESCRIPTION
**Pull request by ekohl**
Includes https://github.com/theforeman/foreman-packaging/pull/3828

### CODE REVIEW

**Comment by ekohl** [comment]
Note about testing this:
It makes sense to first build the nodejs packages:
```sh
# Build SRPMs for the new packages
obal srpm nodejs-theforeman-vendor nodejs-copy-webpack-plugin
# Build RPMs
mockchain -l mock-output -r mock/el7-scl.cfg SRPMs/nodejs-*
```

Then 
```sh
# Make sure you have a foreman.git checkout here with PR 6605 checkout out
FOREMAN_CHECKOUT=~/dev/foreman
# Update NPM requirements inline
./update-requirements npm $FOREMAN_CHECKOUT/package.json packages/foreman/foreman/foreman.spec
# Build Foreman SRPM
rm -f SRPMs/foreman-*.src.rpm
obal srpm foreman -e "{'build_package_tito_releaser_args': ['--arg source_dir=$FOREMAN_CHECKOUT --builder tito.builder.FetchBuilder']}"
# Builds RPMs
mockchain -l mock-output -r mock/el7-scl.cfg SRPMs/foreman-*
```

**Comment by ekohl** [comment]
This currently fails:
```
BUILDSTDERR: webpack --bail --config config/webpack.config.js
BUILDSTDERR: '
BUILDSTDERR: module.js:478
BUILDSTDERR:     throw err;
BUILDSTDERR:     ^
BUILDSTDERR: Error: Cannot find module '@theforeman/vendor-core'
BUILDSTDERR:     at Function.Module._resolveFilename (module.js:476:15)
BUILDSTDERR:     at Function.Module._load (module.js:424:25)
BUILDSTDERR:     at Module.require (module.js:504:17)
BUILDSTDERR:     at require (internal/module.js:20:19)
BUILDSTDERR:     at Object.<anonymous> (/usr/lib/node_modules/@theforeman/vendor/lib/createWebpackExternals.js:1:83)
BUILDSTDERR:     at Module._compile (module.js:577:32)
BUILDSTDERR:     at Object.Module._extensions..js (module.js:586:10)
BUILDSTDERR:     at Module.load (module.js:494:32)
BUILDSTDERR:     at tryModuleLoad (module.js:453:12)
BUILDSTDERR:     at Function.Module._load (module.js:445:3)
BUILDSTDERR:     at Module.require (module.js:504:17)
BUILDSTDERR:     at require (internal/module.js:20:19)
BUILDSTDERR:     at Object.<anonymous> (/usr/lib/node_modules/@theforeman/vendor/webpack.plugin.js:5:32)
BUILDSTDERR:     at Module._compile (module.js:577:32)
BUILDSTDERR:     at Object.Module._extensions..js (module.js:586:10)
BUILDSTDERR:     at Module.load (module.js:494:32)
```

**Comment by sharvit** [comment]
Why do you run webpack build? You do need vendor-core to build vendor but if you download the vendor from npm it already comes with the `dist` folder.

**Comment by ekohl** [comment]
That's what we've always done to build the webpack config. Ideally we would actually call a rake task to compile and it looks like we override `webpack:compile` so I'll change the config to that and retry.

**Comment by sharvit** [comment]
> That's what we've always done to build the webpack config. Ideally we would actually call a rake task to compile and it looks like we override `webpack:compile` so I'll change the config to that and retry.

Notice my edit.
I have found the issue and I can fix it, I made a mistake with the last version and used vendor-core here:
https://github.com/theforeman/foreman-js/blob/master/packages/vendor/lib/createWebpackExternals.js#L1

I will solve it with a build process that will build files from vendor-core to vendor so you won't need vendor core installed to build foreman.

**Comment by sharvit** [comment]
@ekohl https://github.com/theforeman/foreman-js/pull/13 is merged, fix this issue and deployed to npm as version `0.1.0-alpha.0`.

**Comment by sharvit** [comment]
https://github.com/theforeman/foreman-js/pull/14 is closed so version alpha-9 will continue to be the latest version for now.

**Comment by evgeni** [comment]
my progress is here: https://github.com/evgeni/foreman-packaging/commits/newjs

but I fail to build foreman.srpm right now, will look later

**Comment by evgeni** [comment]
my bad, didn't bundle install in the foreman checkout, now building

**Comment by evgeni** [comment]
the foreman build now fails with

```
BUILDSTDERR: webpack --bail --config config/webpack.config.js
BUILDSTDERR: '
Hash: e3fc8e01761ea32d2316
Version: webpack 3.12.0
Time: 3810ms
 4 assets
   [0] multi react-intl intl 40 bytes {1} [built]
[./webpack/assets/javascripts/bundle.js] ./webpack/assets/javascripts/bundle.js 1.26 kB {0} [built] [failed] [1 error]
[node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {1} [built]
    + 29 hidden modules
WARNING in bundle-a84f93a6a508ac863ed5.js contain invalid source map
ERROR in ./webpack/assets/javascripts/bundle.js
Module build failed: Error: Couldn't find preset "@theforeman/vendor-dev/babel.preset.js" relative to directory "/builddir/build/BUILD/foreman-1.23.0-develop"
    at /usr/lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/usr/lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/usr/lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/usr/lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/usr/lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/usr/lib/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/usr/lib/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/usr/lib/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/usr/lib/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/usr/lib/node_modules/babel-loader/lib/index.js:173:20)
```

**Comment by evgeni** [comment]
rebased

**Comment by sharvit** [comment]
The issue is because we load `@theforeman/vendor-dev/babel.preset.js` into `.babelrc` and `webpack` using it.

The solution should be: "Use `@theforeman/vendor-dev/babel.preset.js` only in dev/test/storybook enviorments".

I will try 2 different approaches:

1. Use `.babelrc` -> `env`: https://babeljs.io/docs/en/options#env

2. Update the `webpack.config.js` so it will use a different babel config.

**Comment by evgeni** [comment]
Having `env` in the `.babelrc` sounds better to me I think.
Duplicating (most parts of) `babelrc` sounds like a source of "forgot to update the other copy" errors :)

**Comment by sharvit** [comment]
> Having `env` in the `.babelrc` sounds better to me I think.
> Duplicating (most parts of) `babelrc` sounds like a source of "forgot to update the other copy" errors :)

Agree, that was the reason I removed it in the vendor PR:
https://github.com/theforeman/foreman/pull/6605/files#diff-6da49b24efd584154cfb4ec759745192L12

**Comment by sharvit** [comment]
`@theforeman/vendor` version `0.1.0-alpha.10` has released and https://github.com/theforeman/foreman/pull/6605 rebased.

Can you please try again?

**Comment by ekohl** [comment]
This now fails on scss:
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'patternfly-react/dist/sass/_breadcrumb.scss' in '/builddir/build/BUILD/foreman-1.23.0-develop/webpack/assets/javascripts/react_app/components/BreadcrumbBar/components'
    at factoryCallback (/usr/lib/node_modules/webpack/lib/Compilation.js:282:40)
    at factory (/usr/lib/node_modules/webpack/lib/NormalModuleFactory.js:237:20)
    at resolver (/usr/lib/node_modules/webpack/lib/NormalModuleFactory.js:60:20)
    at asyncLib.parallel.e (/usr/lib/node_modules/webpack/lib/NormalModuleFactory.js:127:20)
    at /usr/lib/node_modules/webpack/node_modules/async/dist/async.js:3888:9
    at /usr/lib/node_modules/webpack/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/usr/lib/node_modules/webpack/node_modules/async/dist/async.js:1062:13)
    at /usr/lib/node_modules/webpack/node_modules/async/dist/async.js:969:16
    at /usr/lib/node_modules/webpack/node_modules/async/dist/async.js:3885:13
    at resolvers.normal.resolve (/usr/lib/node_modules/webpack/lib/NormalModuleFactory.js:119:22)
    at onError (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:65:10)
    at loggingCallbackWrapper (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/usr/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:252:11)
    at /usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/usr/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:252:11)
    at innerCallback (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:144:11)
    at loggingCallbackWrapper (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/usr/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:249:35)
    at resolver.doResolve.createInnerCallback (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6)
    at loggingCallbackWrapper (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:166:11)
    at loggingCallbackWrapper (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/usr/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:249:35)
resolve 'patternfly-react/dist/sass/_breadcrumb.scss' in '/builddir/build/BUILD/foreman-1.23.0-develop/webpack/assets/javascripts/react_app/components/BreadcrumbBar/components'
  Parsed request is a module
  using description file: /builddir/build/BUILD/foreman-1.23.0-develop/package.json (relative path: ./webpack/assets/javascripts/react_app/components/BreadcrumbBar/components)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /builddir/build/BUILD/foreman-1.23.0-develop/package.json (relative path: ./webpack/assets/javascripts/react_app/components/BreadcrumbBar/components)
    resolve as module
      looking for modules in /builddir/build/BUILD/foreman-1.23.0-develop/webpack
        using description file: /builddir/build/BUILD/foreman-1.23.0-develop/package.json (relative path: ./webpack)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /builddir/build/BUILD/foreman-1.23.0-develop/package.json (relative path: ./webpack)
          using description file: /builddir/build/BUILD/foreman-1.23.0-develop/package.json (relative path: ./webpack/patternfly-react/dist/sass/_breadcrumb.scss)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /builddir/build/BUILD/foreman-1.23.0-develop/webpack/patternfly-react/dist/sass/_breadcrumb.scss doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /builddir/build/BUILD/foreman-1.23.0-develop/webpack/patternfly-react/dist/sass/_breadcrumb.scss.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /builddir/build/BUILD/foreman-1.23.0-develop/webpack/patternfly-react/dist/sass/_breadcrumb.scss.json doesn't exist
            as directory
              /builddir/build/BUILD/foreman-1.23.0-develop/webpack/patternfly-react/dist/sass/_breadcrumb.scss doesn't exist
      looking for modules in /builddir/build/BUILD/foreman-1.23.0-develop/node_modules
        using description file: /builddir/build/BUILD/foreman-1.23.0-develop/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /builddir/build/BUILD/foreman-1.23.0-develop/package.json (relative path: ./node_modules)
          using description file: /builddir/build/BUILD/foreman-1.23.0-develop/package.json (relative path: ./node_modules/patternfly-react/dist/sass/_breadcrumb.scss)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              resolved symlink to /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss
                No description file found
              after resolved symlink to /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss
                no extension
                  Field 'browser' doesn't contain a valid alias configuration
                  /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss doesn't exist
                .js
                  Field 'browser' doesn't contain a valid alias configuration
                  /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.js doesn't exist
                .json
                  Field 'browser' doesn't contain a valid alias configuration
                  /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.json doesn't exist
                as directory
                  /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss doesn't exist
              /builddir/build/BUILD/foreman-1.23.0-develop/node_modules/patternfly-react/dist/sass/_breadcrumb.scss doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              resolved symlink to /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.js
                No description file found
              after resolved symlink to /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.js
                no extension
                  Field 'browser' doesn't contain a valid alias configuration
                  /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.js doesn't exist
                .js
                  Field 'browser' doesn't contain a valid alias configuration
                  /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.js.js doesn't exist
                .json
                  Field 'browser' doesn't contain a valid alias configuration
                  /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.js.json doesn't exist
                as directory
                  /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.js doesn't exist
              /builddir/build/BUILD/foreman-1.23.0-develop/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              resolved symlink to /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.json
                No description file found
              after resolved symlink to /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.json
                no extension
                  Field 'browser' doesn't contain a valid alias configuration
                  /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.json doesn't exist
                .js
                  Field 'browser' doesn't contain a valid alias configuration
                  /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.json.js doesn't exist
                .json
                  Field 'browser' doesn't contain a valid alias configuration
                  /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.json.json doesn't exist
                as directory
                  /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.json doesn't exist
              /builddir/build/BUILD/foreman-1.23.0-develop/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.json doesn't exist
            as directory
              /builddir/build/BUILD/foreman-1.23.0-develop/node_modules/patternfly-react/dist/sass/_breadcrumb.scss doesn't exist
      /builddir/build/BUILD/foreman-1.23.0-develop/webpack/assets/javascripts/react_app/components/BreadcrumbBar/components/node_modules/ doesn't exist or is not a directory
      /builddir/build/BUILD/foreman-1.23.0-develop/webpack/assets/javascripts/react_app/components/BreadcrumbBar/node_modules/ doesn't exist or is not a directory
      /builddir/build/BUILD/foreman-1.23.0-develop/webpack/assets/javascripts/react_app/components/node_modules/ doesn't exist or is not a directory
      /builddir/build/BUILD/foreman-1.23.0-develop/webpack/assets/javascripts/react_app/node_modules/ doesn't exist or is not a directory
      /builddir/build/BUILD/foreman-1.23.0-develop/webpack/assets/javascripts/node_modules/ doesn't exist or is not a directory
      /builddir/build/BUILD/foreman-1.23.0-develop/webpack/assets/node_modules/ doesn't exist or is not a directory
      /builddir/build/BUILD/foreman-1.23.0-develop/webpack/node_modules/ doesn't exist or is not a directory
      /builddir/build/BUILD/node_modules/ doesn't exist or is not a directory
      /builddir/build/node_modules/ doesn't exist or is not a directory
      /builddir/node_modules/ doesn't exist or is not a directory
      /node_modules/ doesn't exist or is not a directory
      looking for modules in /builddir/build/BUILD/foreman-1.23.0-develop/node_modules/
        using description file: /builddir/build/BUILD/foreman-1.23.0-develop/package.json (relative path: ./node_modules/)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /builddir/build/BUILD/foreman-1.23.0-develop/package.json (relative path: ./node_modules/)
          using description file: /builddir/build/BUILD/foreman-1.23.0-develop/package.json (relative path: ./node_modules/patternfly-react/dist/sass/_breadcrumb.scss)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              resolved symlink to /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss
                No description file found
              after resolved symlink to /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss
                no extension
                  Field 'browser' doesn't contain a valid alias configuration
                  /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss doesn't exist
                .js
                  Field 'browser' doesn't contain a valid alias configuration
                  /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.js doesn't exist
                .json
                  Field 'browser' doesn't contain a valid alias configuration
                  /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.json doesn't exist
                as directory
                  /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss doesn't exist
              /builddir/build/BUILD/foreman-1.23.0-develop/node_modules/patternfly-react/dist/sass/_breadcrumb.scss doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              resolved symlink to /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.js
                No description file found
              after resolved symlink to /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.js
                no extension
                  Field 'browser' doesn't contain a valid alias configuration
                  /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.js doesn't exist
                .js
                  Field 'browser' doesn't contain a valid alias configuration
                  /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.js.js doesn't exist
                .json
                  Field 'browser' doesn't contain a valid alias configuration
                  /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.js.json doesn't exist
                as directory
                  /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.js doesn't exist
              /builddir/build/BUILD/foreman-1.23.0-develop/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              resolved symlink to /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.json
                No description file found
              after resolved symlink to /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.json
                no extension
                  Field 'browser' doesn't contain a valid alias configuration
                  /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.json doesn't exist
                .js
                  Field 'browser' doesn't contain a valid alias configuration
                  /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.json.js doesn't exist
                .json
                  Field 'browser' doesn't contain a valid alias configuration
                  /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.json.json doesn't exist
                as directory
                  /usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.json doesn't exist
              /builddir/build/BUILD/foreman-1.23.0-develop/node_modules/patternfly-react/dist/sass/_breadcrumb.scss.json doesn't exist
            as directory
              /builddir/build/BUILD/foreman-1.23.0-develop/node_modules/patternfly-react/dist/sass/_breadcrumb.scss doesn't exist

```

**Comment by sharvit** [comment]
Thanks @ekohl 

I'm trying to fix it by compiling `variables.scss` and `mixins.scss` to `variables.bundle.scss` and `mixins.bundle.scss` so they will be consumable.

atm I'm researching how to compile scss to scss :hankey:

**Comment by ekohl** [comment]
Probably way too big, but I wonder if CSS variables might be a good solution.

**Comment by sharvit** [comment]
> Probably way too big

What do you mean?

> I wonder if CSS variables might be a good solution.

AFAIK the browser support is an issue. I would love to see it landing in foreman eventually.

**Comment by ekohl** [comment]
> > Probably way too big
> 
> What do you mean?

To be done in time for 1.23.

**Comment by sharvit** [comment]
> To be done in time for 1.23.

Hopefully not, I'm trying to find a webpack-loader to reuse and I will update about this effort.

**Comment by sharvit** [comment]
The css-loader might do the job https://webpack.js.org/loaders/css-loader/

**Comment by sharvit** [comment]
foreman-vendor pr is updated and using `@theforeman/vendor` version `alpha.11`:
https://github.com/theforeman/foreman/pull/6605

can you try again please?

**Comment by evgeni** [comment]
with alpha 11 and the current state of https://github.com/theforeman/foreman/pull/6605 I could get it to build (yay), and after installation the result looks OK to me (login page renders fine, the menus render fine, widgets too)

what else shall I test?

**Comment by evgeni** [comment]
follow up, this (obviously) breaks plugins that use webpack, but a rebuild with the new foreman build is sufficient to make them work again.

**Comment by evgeni** [comment]
So I think the next steps should be:

1. split the changes to `foreman.spec` into an own PR
2. merge the `nodejs-theforeman-vendor` package (aka this PR)
3. merge https://github.com/theforeman/foreman/pull/6605
4. update the deps in the PR created in 1. after 3.
5. merge the foreman PR
6. rebuild tasks, rex, ansible, katello
7. :champagne:

**Comment by evgeni** [comment]
I kept this PR as it is, and opened the splits here:
https://github.com/theforeman/foreman-packaging/pull/3924 - vendor packaging
https://github.com/theforeman/foreman-packaging/pull/3922 - unrelated fixup by ewoud for source building
https://github.com/theforeman/foreman-packaging/pull/3921 - foreman update to use vendor

**Comment by evgeni** [comment]
(I can also force push #3924 here, but it felt kinda weird)

**Comment by tbrisker** [comment]
shall we close this one then?

**Pull request closed without merging**
