### PR TITLE
Update rubygem-foreman_ansible to 7.0.1

### PR DESCRIPTION
**Pull request by ezr-ondrej**
(cherry picked from commit 764f8be272dfaa6d98a4e9c21be213eb35f6ae0f)

### CODE REVIEW

**Comment by evgeni** [comment]
This will fail until we have https://github.com/theforeman/foreman/pull/8981 in and built

**Comment by ezr-ondrej** [comment]
It is in :)

**Comment by evgeni** [comment]
*and built* which means we need to wait for tagging and building ti happen tomorrow ;)

**Comment by ezr-ondrej** [comment]
[test deb]

**Comment by Odilhao** [comment]
[test deb]

**Comment by evgeni** [comment]
Yay

**Review by evgeni — APPROVED** [review]

**Pull request merged**
