### PR TITLE
Rebuild against new foreman-js

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
@zjhuntin @ekohl this should fix the smoker issues in 3.9

**Review by ekohl — APPROVED** [review]

**Comment by ekohl** [comment]
Will this mean 3.9 is newer than nightly?

**Comment by evgeni** [comment]
> Will this mean 3.9 is newer than nightly?

Yeah. We can also rebuild nightly (even tho it's not required there) for consistency.

**Comment by ekohl** [comment]
I'd prefer that and make this a cherry pick.

**Comment by evgeni** [comment]
https://github.com/theforeman/foreman-packaging/pull/10203

**Pull request merged**
