### PR TITLE
Update rubygem-fog-proxmox to 0.8.0

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by evgeni** [comment]
```
Requires: tfm-runtime
Checking for unpackaged file(s): /usr/lib/rpm/check-files /builddir/build/BUILDROOT/tfm-rubygem-fog-proxmox-0.8.0-1.el7.noarch
BUILDSTDERR: error: Installed (but unpackaged) file(s) found:
BUILDSTDERR:    /opt/theforeman/tfm/root/usr/share/gems/gems/fog-proxmox-0.8.0/bin/console
BUILDSTDERR:    /opt/theforeman/tfm/root/usr/share/gems/gems/fog-proxmox-0.8.0/bin/setup
BUILDSTDERR:     Installed (but unpackaged) file(s) found:
BUILDSTDERR:    /opt/theforeman/tfm/root/usr/share/gems/gems/fog-proxmox-0.8.0/bin/console
BUILDSTDERR:    /opt/theforeman/tfm/root/usr/share/gems/gems/fog-proxmox-0.8.0/bin/setup
RPM build errors:
Child return code was: 1
```

**Comment by evgeni** [comment]
See https://github.com/theforeman/foreman-packaging/pull/3571/files#diff-20cf10cafc851a1fab225d3894a6100cL82, where we had:

```
%{_bindir}/console
%{_bindir}/setup
```

in `%files`

**Comment by ekohl** [comment]
@evgeni it's now green. Perhaps not the cleanest but could you have a look?

**Comment by evgeni** [comment]
Why rm instead of exclude?

**Comment by ekohl** [comment]
I wanted to be sure that they were removed from both the gem itself and bin, but you're right, they could also be excluded.

**Comment by ekohl** [comment]
Updated

**Pull request merged**
