### PR TITLE
Updated foreman_discovery to 5.0.1 (RPM)

### PR DESCRIPTION
**Pull request by lzap**

### CODE REVIEW

**Comment by domcleal** [comment]
The gem isn't yet available on rubygems.org, causing the build failure.

**Comment by lzap** [comment]
Right [test]

**Comment by lzap** [comment]
```
Fetching: foreman_discovery-5.0.0.gem (100%)
Fetching: foreman_discovery-5.0.1.gem (100%)
Compared versions: ["5.0.0", "5.0.1"]
  DIFFERENT files:
    5.0.0->5.0.1:
      * Added:
            app/mailers/
            app/helpers/concerns/foreman_discovery/
            app/views/discovered_mailer/
            app/mailers/discovered_mailer.rb
              (!) Unexpected permissions: 100664
            app/services/foreman_discovery/fact_parser.rb
              (!) Unexpected permissions: 100664
            app/helpers/concerns/foreman_discovery/settings_helper_extensions.rb
              (!) Unexpected permissions: 100664
            app/views/discovered_mailer/_discovered_host.html.erb
              (!) Unexpected permissions: 100664
            app/views/discovered_mailer/discovered_summary.text.erb
              (!) Unexpected permissions: 100664
            app/views/discovered_mailer/discovered_summary.html.erb
              (!) Unexpected permissions: 100664
            db/seeds.d/70_discovery_mail_notification.rb
              (!) Unexpected permissions: 100664
            locale/ru/foreman_discovery.edit.po
              (!) Unexpected permissions: 100664
            locale/de/foreman_discovery.edit.po
              (!) Unexpected permissions: 100664
            locale/pt_BR/foreman_discovery.edit.po
              (!) Unexpected permissions: 100664
            locale/en_GB/foreman_discovery.edit.po
              (!) Unexpected permissions: 100664
            locale/zh_TW/foreman_discovery.edit.po
              (!) Unexpected permissions: 100664
            locale/es/foreman_discovery.edit.po
              (!) Unexpected permissions: 100664
            locale/fr/foreman_discovery.edit.po
              (!) Unexpected permissions: 100664
            locale/it/foreman_discovery.edit.po
              (!) Unexpected permissions: 100664
            locale/ca/foreman_discovery.edit.po
              (!) Unexpected permissions: 100664
            locale/ja/foreman_discovery.edit.po
              (!) Unexpected permissions: 100664
            locale/ko/foreman_discovery.edit.po
              (!) Unexpected permissions: 100664
            locale/zh_CN/foreman_discovery.edit.po
              (!) Unexpected permissions: 100664
            locale/gl/foreman_discovery.edit.po
              (!) Unexpected permissions: 100664
            locale/sv_SE/foreman_discovery.edit.po
              (!) Unexpected permissions: 100664
            test/unit/fact_parser_test.rb
              (!) Unexpected permissions: 100664
            test/unit/discovered_mailer_test.rb
              (!) Unexpected permissions: 100664
            test/test_helper_discovery.rb
              (!) Unexpected permissions: 100664
  DIFFERENT test_files:
    5.0.0->5.0.1:
      * Added:
            test/unit/fact_parser_test.rb
              (!) Unexpected permissions: 100664
            test/unit/discovered_mailer_test.rb
              (!) Unexpected permissions: 100664
            test/test_helper_discovery.rb
              (!) Unexpected permissions: 100664
```

**Comment by lzap** [comment]
Oh tests were green, but I squashed the `-k` option for the README. Edited http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#section-7 as well.

**Comment by lzap** [comment]
For the record, I don't think I will be changing all the permissions in the git repo to `644` since `664` is the typical umask on workstations...

**Comment by lzap** [comment]
The debian change is at https://github.com/theforeman/foreman-packaging/pull/1041

**Comment by domcleal** [comment]
Thanks @lzap, merged and building.  Did you also want this cherry picked to rpm/1.11?

**Comment by domcleal** [comment]
Built on rpm/1.11 via 64b2cf6.

**Comment by lzap** [comment]
Thanks! @ehelms looks like I hit the deadline :-)

**Pull request merged**
