### PR TITLE
update hammer to 0.5 (DEB)

### PR DESCRIPTION
**Pull request by mmoll**
the resulting .debs work fine for me on jessie

### CODE REVIEW

**Comment by domcleal** [comment]
Merged and building, thanks @mmoll!

**Comment by domcleal** [comment]
@tstrachota it looks like the hammer_cli 0.5.0 we packaged here was yanked, is there anything to be concerned about, or do we just update again to 0.5.1?

**Comment by tstrachota** [comment]
@domcleal @mmoll  Oops, I missed this PR. I packed output from benchmarking by mistake so I had to raise the version to 0.5.1

**Comment by tstrachota** [comment]
@domcleal I'm sorry https://github.com/theforeman/foreman-packaging/pull/918

**Pull request merged**
