### PR TITLE
build amazing_print for jammy

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
```
E: The repository 'http://deb.theforeman.org/ jammy Release' does not have a Release file.
```

chicken and eggs, let's find out how *that* works again

**Comment by evgeni** [comment]
```
# mkdir /var/www/freightstage/apt/jammy/
# chown freightstage.freightstage /var/www/freightstage/apt/jammy/
# sudo -u freightstage /usr/bin/freight-cache -c /home/freightstage/freight.conf
```

**Comment by evgeni** [comment]
[test deb]

**Comment by evgeni** [comment]
[test deb]

**Comment by evgeni** [comment]
[test deb]

**Review by ekohl — APPROVED** [review]

**Pull request merged**
