### PR TITLE
Add rubygem-promise.rb package

### PR DESCRIPTION
**Pull request by xprazak2**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.21
* [ ] 1.20

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ekohl** [comment]
Is a dot in the package name valid?

**Comment by xprazak2** [comment]
I changed dot to dash.

**Comment by evgeni** [comment]
@xprazak2 I think a dot is valid in an RPM name, so no need to change it?
@ekohl what do you think

**Comment by xprazak2** [comment]
So, do we want a dot in the package name or a slash?

**Comment by evgeni** [comment]
I can live with either, but slight preference for being as close to the original name as possible.

We even already have packages with a dot in the repo:
* [nodejs-lodash.debounce](https://github.com/theforeman/foreman-packaging/tree/rpm/develop/packages/foreman/nodejs-lodash.debounce)
* [nodejs-jquery.cookie](https://github.com/theforeman/foreman-packaging/tree/rpm/develop/packages/foreman/nodejs-jquery.cookie)

Last call on @ekohl as he brought that up.

**Comment by ekohl** [comment]
In that case I think a dot is best since it's closest to the original package name.

**Comment by xprazak2** [comment]
I changed it to use dot.

**Comment by evgeni** [comment]
```
% koji add-pkg foreman-nightly-rhel7 tfm-rubygem-promise.rb --owner=kojiadm
Adding 1 packages to tag foreman-nightly-rhel7
```

build: http://koji.katello.org/koji/taskinfo?taskID=173666

**Pull request merged**
