### PR TITLE
Packages needed for Red Hat Repositories page

### PR DESCRIPTION
**Pull request by waldenraines**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.17
* [ ] 1.16
* [ ] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ekohl** [comment]
@waldenraines mind using https://github.com/dLobatog/npm2rpm/pull/36 to generate specs? It's fine if this is a single PR.

**Comment by waldenraines** [comment]
@ekohl updated.

**Comment by jturel** [comment]
[test rpm]

**Comment by waldenraines** [comment]
@ekohl any thoughts on the failure, I'm pretty sure I followed the directions correctly.

**Comment by ekohl** [comment]
@waldenraines you need to add the packages to ```package_manifest.yaml``` as well. Sadly we can't do this automatically just yet because we want to maintain some formatting.

**Comment by waldenraines** [comment]
Oh, yep, right there in step 4, sorry about that.

**Comment by waldenraines** [comment]
@ekohl updated but now it's failing for some other reason that I don't understand.

**Comment by ekohl** [comment]
I'll get back to this later. Currently we don't build any webpack assets for katello and foreman nightly is broken. Once that's fixed, I'll work on a proper solution.

**Comment by waldenraines** [comment]
Thanks @ekohl!

**Comment by waldenraines** [comment]
[test rpm]

**Comment by ekohl** [comment]
This is blocked on getting core to be able to build webpack resources: https://github.com/theforeman/foreman/pull/5413 + https://github.com/theforeman/foreman/pull/5413 should allow that.

**Comment by mccun934** [comment]
[test rpm]

**Comment by ehelms** [comment]
@ekohl I took this over here https://github.com/theforeman/foreman-packaging/pull/2417

**Pull request closed without merging**
