### PR TITLE
Update rubygem-foreman_discovery to 18.0.0

### PR DESCRIPTION
**Pull request by lzap**
For plugin updates, please indicate which repos this should be built into:

* Nightly
* 3.0

Will do PR, it was so broken that it took me a week to figure everything out...

### CODE REVIEW

**Comment by lzap** [comment]
Debian: https://github.com/theforeman/foreman-packaging/pull/7111

**Comment by lzap** [comment]
Do not merge, there is another unit test failing.

This fails with `DEBUG util.py:600:  No matching package to install: 'npm(@theforeman/builder) < 7.0.0'` I guess I should not update that dependency.

**Comment by lzap** [comment]
Actually, it was just a test assertion what failed, I can release the code there were no changes.

**Comment by lzap** [comment]
Do not merge yet, still waiting for CI to confirm all unit tests are green.

**Comment by lzap** [comment]
It is passing, it works fine, ready for merge.

**Review by ekohl — APPROVED** [review]

**Comment by lzap** [comment]
Thanks there is also a deb version, I guess I need to wait more for that one.

CP 3.0: https://github.com/theforeman/foreman-packaging/pull/7125

**Pull request merged**
