### PR TITLE
Tracer deps

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
@pcreech do you know why it can't find python3-lxml?

**Comment by pcreech** [comment]
The simple answer is, it does not exist in the flattened repo.  Digging into why

**Comment by pcreech** [comment]
[test]

**Comment by pcreech** [comment]
[test rpm]

**Comment by pcreech** [comment]
So, currently, I am not sure.  it exists under the "non_modular" folder, it exists in the repodata, and I can install the package on a centos:8 container by removing all the repos and adding the url to the flat repo.

**Comment by evgeni** [comment]
thankfully it's not really a build-dep, so I just dropped it :disappointed_relieved:

**Pull request merged**
