### PR TITLE
remove foreman_userdata package

### PR DESCRIPTION
**Pull request by timogoebel**
This is only for Nightly and removes `foreman_userdata`, which was moved to core in (https://github.com/theforeman/foreman/pull/6057).

### CODE REVIEW

**Comment by evgeni** [comment]
@timogoebel this needs a rebase please (and it should then magically build ;))

**Comment by timogoebel** [comment]
@evgeni: Rebased.

**Comment by evgeni** [comment]
thanks!

**Comment by evgeni** [comment]
```
% koji untag-build --all foreman-plugins-nightly-rhel7 tfm-rubygem-foreman_userdata
% koji remove-pkg foreman-plugins-nightly-rhel7 tfm-rubygem-foreman_userdata
```

**Pull request merged**
