### PR TITLE
update hammer_cli(_foreman) to 0.4.0 (DEB)

### PR DESCRIPTION
**Pull request by mmoll**
now with `deb/` :panda_face:

### CODE REVIEW

**Comment by domcleal** [comment]
[test]

**Comment by domcleal** [comment]
Could you also delete fastercsv and rb-readline?  We can remove them from the nightly repos too once these new versions are built.

**Comment by mmoll** [comment]
with great pleasure :)

**Comment by domcleal** [comment]
Thanks @mmoll, building.  I'll also try and delete those packages from the nightly repos.

**Pull request merged**
