### PR TITLE
Update kafo to 0.9.6 [rpm]

### PR DESCRIPTION
**Pull request by ares**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.13
* [ ] 1.12
* [ ] 1.11

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by domcleal** [comment]
Merged, thanks @ares.

**Comment by ares** [comment]
Thanks @domcleal, I suppose I should bug you with 1.13 tagging at RC2 time?

**Comment by domcleal** [comment]
Yeah, just check it's done - I added it to the post-1.13.0-RC1 milestone so should see it.

**Comment by domcleal** [comment]
Retagged to 1.13 tags for 1.13.0-RC2.

**Comment by ares** [comment]
\o/

**Pull request merged**
