### PR TITLE
Update foreman-release repos to simplify releases

### PR DESCRIPTION
**Pull request by ekohl**
This should now automatically pick up releases when we drop the develop part from versions.

Note: didn't have a chance to test this yet.

### CODE REVIEW

**Comment by ehelms** [comment]
[test packaging]

**Comment by ekohl** [comment]
[test packaging]

**Comment by ekohl** [comment]
[test packaging]

**Comment by ekohl** [comment]
[test packaging]

**Comment by ekohl** [comment]
[test packaging]

**Comment by ekohl** [comment]
[test packaging]

**Comment by ekohl** [comment]
[test packaging]

**Comment by ekohl** [comment]
[test packaging]

**Comment by ehelms** [comment]
[test packaging]

**Comment by ehelms** [comment]
[test packaging]

**Comment by ehelms** [comment]
[test packaging]

**Comment by ehelms** [comment]
[test packaging]

**Comment by ehelms** [comment]
[test packaging]

**Comment by ehelms** [comment]
[test packaging]

**Comment by ehelms** [comment]
[test packaging]

**Pull request merged**
