### PR TITLE
Update rubygem-katello to use pulp-python-client 3.7

### PR DESCRIPTION
**Pull request by ianballou**
Merge after https://github.com/theforeman/foreman-packaging/pull/8083

### CODE REVIEW

**Comment by ekohl** [comment]
Marking as draft until the other PR has been merged. Please mark it as ready for review once it's ready.

**Comment by ianballou** [comment]
[test]

**Comment by ianballou** [comment]
[test rpm]

**Review by ekohl — APPROVED** [review]
Repoclosure is on the old package.

**Pull request merged**
