### PR TITLE
Release rubygem-foreman_scap_client 0.5.2

### PR DESCRIPTION
**Pull request by ofedoren**
(cherry picked from commit fad7631abb6e2174a7ed9123be7f1eb5245695c2)

### CODE REVIEW

**Comment by zjhuntin** [comment]
[test rpm-copr]

**Comment by zjhuntin** [comment]
[test rpm-copr]

**Comment by zjhuntin** [comment]
[test rpm-copr]

**Comment by ehelms** [comment]
[test rpm-copr]

**Comment by ofedoren** [comment]
@ekohl, thanks, updated with the merged commit.

**Review by ekohl — APPROVED** [review]

**Pull request merged**
