### PR TITLE
Update rubygem-pulp_deb_client to 2.9.1 for Katello 3.18

### PR DESCRIPTION
**Pull request by quba42**
Needs to be coordinated with:
- https://github.com/theforeman/pulpcore-packaging/pull/144
- https://github.com/Katello/katello/pull/9329
- The Katello 3.18.4 release

### CODE REVIEW

**Comment by pcreech** [comment]
[test rpm]

**Comment by jturel** [comment]
[test rpm]

**Comment by jturel** [comment]
@pcreech can you work with @quba42 to get these two packaging PRs merged (second one is https://github.com/theforeman/pulpcore-packaging/pull/144) - they look good as far as I can tell

**Comment by quba42** [comment]
AFAIK they can be merged at any time, but this may break nightlies until the next 3.18 dot release, which is why they were kept open. I will have a look now if they can be rebased to the tip of the relevant branch one more time.

**Comment by evgeni** [comment]
@jturel @quba42 are you planning another 3.18.z that should bring compatibility with pulp_deb 2.9, or should we close this one out?

**Comment by jturel** [comment]
@evgeni yes, this will be the basis of 3.18.4

**Review by jlsherrill — APPROVED** [review]

**Comment by evgeni** [comment]
```console
% koji tag-build katello-3.18-el8 rubygem-pulp_deb_client-2.9.1-1.el8
Created task 437953
Watching tasks (this may be safely interrupted)...
437953 tagBuild (noarch): free
437953 tagBuild (noarch): free -> closed
  0 free  0 open  1 done  0 failed

437953 tagBuild (noarch) completed successfully

% koji tag-build katello-3.18-rhel7 tfm-rubygem-pulp_deb_client-2.9.1-1.el7
Created task 437954
Watching tasks (this may be safely interrupted)...
437954 tagBuild (noarch): free
437954 tagBuild (noarch): free -> closed
  0 free  0 open  1 done  0 failed

437954 tagBuild (noarch) completed successfully
```

**Pull request merged**
