### PR TITLE
Remove anemone and add spidr dependency

### PR DESCRIPTION
**Pull request by sjha4**
Followup to https://github.com/theforeman/foreman-packaging/pull/10937 which added spidr rubygem.

This PR adds spidr as a katello dependency and also removes anemone from packaging and deps.

Used the helpful `./remove_package rubygem-anemone`  command and made a couple more changes.

### CODE REVIEW

**Comment by ekohl** [comment]
This will fail until https://github.com/Katello/katello/pull/10947 is merged and released to nightly.

**Comment by sjha4** [comment]
Merged the katello PR. 👍🏼

**Comment by ekohl** [comment]
@sjha4 could you rebase to force a build?

**Comment by evgeni** [comment]
[test rpm-copr]

**Review by evgeni — APPROVED** [review]

**Comment by sjha4** [comment]
Thanks @ekohl @evgeni ❤️

**Pull request merged**
