### PR TITLE
Release katello-client-bootstrap 1.7.7

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Review by zjhuntin — APPROVED** [review]

**Comment by evgeni** [comment]
```


BuildError: Unknown origin for tfm-runtime-assets-7.0-4.el7.x86_64: file:///var/tmp/koji/tasks/4489/454489/repo_73534_premerge/


```

WHAT?

**Comment by evgeni** [comment]
[test rpm]

**Comment by pcreech** [comment]
hrm... trying `koji regen-repo katello-nightly-rhel7-build`

http://koji.katello.org/koji/taskinfo?taskID=454570

**Comment by evgeni** [comment]
[test rpm]

**Comment by pcreech** [comment]
looks good to go now

**Pull request merged**
