### PR TITLE
Revert "Remove unused package nodejs-node-gyp"

### PR DESCRIPTION
**Pull request by ehelms**
This reverts commit 368ec4754fd00d140dcc632133c5d24b43a6cf75.

### CODE REVIEW

**Comment by ehelms** [comment]
This is still needed in order to build nodejs-node-sass.

**Comment by evgeni** [comment]
This was missing a `koji unblock-pkg foreman-nightly-el8 nodejs-node-gyp` to allow the package back in.

**Comment by ekohl** [comment]
> This is still needed in order to build nodejs-node-sass.

Then why is it not declared in the dependencies? Looking at the spec it claims it uses a bundled version.

**Comment by ekohl** [comment]
One theory I have is that it needs some development dependency that nodejs-node-gyp happens to pull in, but without build logs that's hard to determine.

**Comment by ehelms** [comment]
> One theory I have is that it needs some development dependency that nodejs-node-gyp happens to pull in, but without build logs that's hard to determine.

It does build require it: https://github.com/theforeman/foreman-packaging/blob/rpm/develop/packages/foreman/nodejs-node-sass/nodejs-node-sass.spec#L194

And then there is some fun magic that happens:

https://github.com/theforeman/foreman-packaging/blob/rpm/develop/packages/foreman/nodejs-node-sass/nodejs-node-sass.spec#L408-L410

**Comment by ekohl** [comment]
There's something weird:
```console
# rpm -q --requires nodejs-node-sass-4.13.1-1.el8.src.rpm
warning: nodejs-node-sass-4.13.1-1.el8.src.rpm: Header V4 RSA/SHA256 Signature, key ID bdcc85ae: NOKEY
nodejs-devel
nodejs-node-gyp
nodejs-packaging
npm
python3
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
```

Yet in repoquery it doesn't show up. And that appears to work for all other packages.

**Comment by ehelms** [comment]
Could it be the Provides? https://github.com/theforeman/foreman-packaging/blob/rpm/develop/packages/foreman/nodejs-node-sass/nodejs-node-sass.spec#L302

**Pull request merged**
