### PR TITLE
Update ruby-foreman-statistics to 2.0.0

### PR DESCRIPTION
**Pull request by ezr-ondrej**
RPM: #7213

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
Could you also change the minimum Foreman version in debian/control here?

**Comment by ezr-ondrej** [comment]
Is this ok, or do I need to have the `~rc` part?

**Review by ekohl — COMMENTED** [review]
I think you need the rc part. Otherwise you can't install it with RCs. `3.1.0~rc1 < 3.1.0`.

**Comment by ezr-ondrej** [comment]
Ah, right :)

**Review by ekohl — APPROVED** [review]

**Pull request merged**
