### PR TITLE
[DEB] Update kafo to 2.1.0

### PR DESCRIPTION
**Pull request by ares**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.16
* [ ] 1.15
* [ ] 1.14

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by mmoll** [comment]
ARMv8 test failure unrelated.

**Comment by mmoll** [comment]
blocked on https://github.com/voxpupuli/puppet-extlib/pull/89

**Comment by ekohl** [comment]
extlib 2.0.1 was released

**Comment by mmoll** [comment]
to be merged together with https://github.com/theforeman/foreman-installer/pull/256

**Comment by ekohl** [comment]
With the installer side merged, is anything else needed to merge this?

**Comment by mmoll** [comment]
nope. merged, díky @ares!

**Pull request merged**
