### PR TITLE
Update rubygem-foreman_virt_who_configure to 0.5.9

### PR DESCRIPTION
**Pull request by chris1984**

### CODE REVIEW

**Comment by ekohl** [comment]
I broke nightly, working on that first.

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
Looks like rubygem-pulpcore_client needs an update to allow Faraday 1.x.

**Comment by Odilhao** [comment]
[test rpm]

**Comment by Odilhao** [comment]
At least now it's only repoclosure

**Review by ekohl — APPROVED** [review]
Oh yes, I haven't mashed yet. Failures are unrelated. I'll run a pipeline after this has built.

**Pull request merged**
