### PR TITLE
Package concurrent-ruby (dynflow dependency) (DEB)

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by stbenjam** [comment]
There's something weird with this gem that gem2deb doesn't like:

```
$ ../gem2deb concurrent-ruby
concurrent-ruby doesn't seem to exist. Let's try to download it with 'gem fetch concurrent-ruby'
"gem fetch concurrent-ruby"
Fetching: concurrent-ruby-0.7.2-x86_64-linux.gem (100%)
Downloaded concurrent-ruby-0.7.2-x86_64-linux
-- Creating source tarball from concurrent-ruby-0.7.2-x86_64-linux.gem ...
tar xfm /home/vagrant/foreman-packaging/dependencies/concurrent/concurrent-ruby-0.7.2-x86_64-linux.gem
"tar xzfm data.tar.gz"
"zcat metadata.gz > metadata.yml"
tar czf /home/vagrant/foreman-packaging/dependencies/concurrent/concurrent-ruby-0.7.2-x86-64-linux.tar.gz concurrent-ruby-0.7.2-x86-64-linux
-- Successfully created ./concurrent-ruby-0.7.2-x86-64-linux.tar.gz

-- Creating Debian source package from ./concurrent-ruby-0.7.2-x86-64-linux.tar.gz ...
ln -s concurrent-ruby-0.7.2-x86-64-linux.tar.gz ruby-concurrent-ruby-0.7.2-x86-64_linux.orig.tar.gz
tar xzf ruby-concurrent-ruby-0.7.2-x86-64_linux.orig.tar.gz
/usr/lib/ruby/1.9.1/rubygems/psych_tree.rb:31: warning: method redefined; discarding old visit_String
/usr/lib/ruby/1.9.1/rubygems/psych_tree.rb:4: warning: previous definition of visit_String was here
/usr/lib/ruby/1.9.1/rubygems/psych_tree.rb:39: warning: method redefined; discarding old register
/usr/lib/ruby/1.9.1/rubygems/psych_tree.rb:12: warning: previous definition of register was here
/usr/lib/ruby/1.9.1/rubygems/psych_tree.rb:43: warning: method redefined; discarding old format_time
/usr/lib/ruby/1.9.1/rubygems/psych_tree.rb:16: warning: previous definition of format_time was here
/usr/lib/ruby/1.9.1/rubygems/syck_hack.rb:115: warning: method redefined; discarding old to_s
/usr/lib/ruby/1.9.1/rubygems/syck_hack.rb:44: warning: previous definition of to_s was here
/usr/lib/ruby/vendor_ruby/gem2deb/dh_make_ruby.rb:139:in `chdir': No such file or directory - ruby-concurrent-ruby-0.7.2-x86-64-0.7.2 (Errno::ENOENT)
	from /usr/lib/ruby/vendor_ruby/gem2deb/dh_make_ruby.rb:139:in `build_in_directory'
	from /usr/lib/ruby/vendor_ruby/gem2deb/dh_make_ruby.rb:133:in `block in build'
	from /usr/lib/ruby/vendor_ruby/gem2deb/dh_make_ruby.rb:129:in `chdir'
	from /usr/lib/ruby/vendor_ruby/gem2deb/dh_make_ruby.rb:129:in `build'
	from ../gem2deb:97:in `<main>'
```

**Comment by stbenjam** [comment]
It's :green_apple: except for precise

**Comment by stbenjam** [comment]
:green_apple:

**Comment by mmoll** [comment]
merged as e9ce0d3, thanks @stbenjam!
building now

**Pull request closed without merging**
