### PR TITLE
Bump foreman_salt / smart_proxy_salt versions

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by zjhuntin** [comment]
[test]

**Comment by zjhuntin** [comment]
[test rpm]

**Comment by zjhuntin** [comment]
[test koji]

**Comment by ekohl** [comment]
@zjhuntin looks like you didn't tag these packages:
```
$ koji tag-build foreman-plugins-1.24-nonscl-rhel7 rubygem-smart_proxy_salt-3.1.1-1.el7
Created task 248562
Watching tasks (this may be safely interrupted)...
248562 tagBuild (noarch): free
248562 tagBuild (noarch): free -> closed
  0 free  0 open  1 done  0 failed

248562 tagBuild (noarch) completed successfully
$ koji tag-build foreman-plugins-1.24-rhel7 tfm-rubygem-smart_proxy_salt_core-0.0.2-1.el7
Created task 248563
Watching tasks (this may be safely interrupted)...
248563 tagBuild (noarch): free
248563 tagBuild (noarch): free -> closed
  0 free  0 open  1 done  0 failed

248563 tagBuild (noarch) completed successfully
```

**Pull request merged**
