### PR TITLE
Remote Execution - Iteration 5 - Develop (DEB)

### PR DESCRIPTION
**Pull request by stbenjam**
- [x] smart_proxy_remote_execution_ssh
- [x] smart proxy dynflow
- [x] foreman remote execution 0.2.1

### CODE REVIEW

**Comment by mmoll** [comment]
Merging and building, although I know the core plugin won't install on 1.11.
Thanks @stbenjam! :ice_cream:

**Comment by stbenjam** [comment]
it should actually work on 1.11 :)

**Comment by mmoll** [comment]
then `foreman (<< 1.11)` should go from the `Depends` field :)

**Comment by stbenjam** [comment]
Why's that? << is less than, right?

**Comment by mmoll** [comment]
exactly

**Comment by stbenjam** [comment]
So why would I include that? The plugin is compatible with 1.11

**Comment by domcleal** [comment]
It's there at the moment - it can be removed.

**Comment by stbenjam** [comment]
Oh sorry, I was only looking at the Build-Depends line. It doesn't matter, we're about to release 0.3.0  which drops 1.10 support, I'll fix it then

**Pull request closed without merging**
