### PR TITLE
drop fog-google from packaging

### PR DESCRIPTION
**Pull request by evgeni**
foreman-gce is gone and foreman_google doesn't need fog anymore

### CODE REVIEW

**Comment by evgeni** [comment]
question: users of foreman-gce that have fog-google installed, will have issues upgrading to 3.6 as fog-google wanted fog-core <2.3 but we ship 2.3 now.

@ekohl time to introduce the foreman-obsoletes package we've been talking about?

**Comment by evgeni** [comment]
FTR, I've already dropped it from koji to unblock nightlies (repoclosure has been complaining):
```console
% koji untag-build --all foreman-nightly-el8 rubygem-fog-google
% koji block-pkg foreman-nightly-el8 rubygem-fog-google
```

**Comment by ekohl** [comment]
> @ekohl time to introduce the foreman-obsoletes package we've been talking about?

I'll submit a PR after this.

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman-packaging/pull/8751 is that PR.

**Pull request merged**
