### PR TITLE
Remove unused nodejs packages

### PR DESCRIPTION
**Pull request by ekohl**
Candidates I didn't fully check or are needed by plugins:
* nodejs-babel-cli
* nodejs-babel-plugin-lodash
* nodejs-babel-plugin-syntax-dynamic-import
* nodejs-babel-plugin-syntax-object-rest-spread
* nodejs-babel-plugin-transform-class-properties
* nodejs-babel-plugin-transform-object-assign
* nodejs-babel-plugin-transform-object-rest-spread
* nodejs-babel-polyfill
* nodejs-babel-preset-env
* nodejs-babel-preset-react
* nodejs-babel-register
* nodejs-babel-runtime
* nodejs-c3
* nodejs-core-js
* nodejs-d3
* nodejs-escape-string-regexp
* nodejs-harmony-reflect
* nodejs-humanize-duration
* nodejs-identity-obj-proxy
* nodejs-invariant
* nodejs-jquery
* nodejs-js-tokens
* nodejs-lodash
* nodejs-lodash-es
* nodejs-loose-envify
* nodejs-node-gyp
* nodejs-object-assign
* nodejs-performance-now
* nodejs-popper.js
* nodejs-raf
* nodejs-react
* nodejs-react-bootstrap
* nodejs-react-dom
* nodejs-react-ellipsis-with-tooltip
* nodejs-react-is
* nodejs-react-lifecycles-compat
* nodejs-react-redux
* nodejs-redux
* nodejs-redux-thunk
* nodejs-regenerator-runtime
* nodejs-reselect
* nodejs-seamless-immutable
* nodejs-sortabular
* nodejs-symbol-observable
* nodejs-table-resolver
* nodejs-typed-styles
* nodejs-urijs
* nodejs-uuid
* nodejs-warning

It appears mostly `foreman_acd` pulls in a lot of dependencies as build requires, but I think the Foreman dependency should be enough. If that can be cleaned up, a few more packages could be cleaned up.

### CODE REVIEW

**Review by tbrisker — APPROVED** [review]
LGTM, though i guess we would only see if repoclosure fails once the packages are actually cleaned/untagged from koji?

**Comment by ekohl** [comment]
Ideally speaking I did this right and we wouldn't see repoclosure fails, but yes, if I did make a mistake then it'd only show up after cleaning from koji.

**Comment by ezr-ondrej** [comment]
Well, let's see it then? :thinking: 
Better sooner than later? :upside_down_face:

**Comment by evgeni** [comment]
Repoclosure will start failing once those packages are removed from comps, so I'd say it's safe to merge this, see that closure is still good and *then* untag/block the pkgs

**Comment by ekohl** [comment]
Should I press the big green button and run the foreman nightly pipeline?

**Review by evgeni — APPROVED** [review]

**Comment by evgeni** [comment]
cleanup:

```console
% koji untag-build --all foreman-nightly-el8 nodejs-bootstrap-slider-without-jquery nodejs-breakjs nodejs-change-emitter nodejs-classnames nodejs-create-react-context nodejs-css-element-queries nodejs-dom-helpers nodejs-escape-string-regexp nodejs-fbjs nodejs-fortawesome-fontawesome-common-types nodejs-fortawesome-free-brands-svg-icons nodejs-gud nodejs-hoist-non-react-statics nodejs-lodash.debounce nodejs-patternfly nodejs-patternfly-react nodejs-patternfly-react-icons nodejs-patternfly-react-tokens nodejs-prop-types nodejs-prop-types-extra nodejs-react-bootstrap-switch nodejs-react-bootstrap-typeahead nodejs-react-c3js nodejs-react-click-outside nodejs-react-collapse nodejs-react-debounce-input nodejs-react-fontawesome nodejs-react-motion nodejs-react-overlays nodejs-react-popper nodejs-react-transition-group nodejs-reactabular-table nodejs-recompose nodejs-regenerator-runtime
% koji untag-build --all foreman-nightly-rhel7 tfm-nodejs-bootstrap-slider-without-jquery tfm-nodejs-breakjs tfm-nodejs-change-emitter tfm-nodejs-classnames tfm-nodejs-create-react-context tfm-nodejs-css-element-queries tfm-nodejs-dom-helpers tfm-nodejs-escape-string-regexp tfm-nodejs-fbjs tfm-nodejs-fortawesome-fontawesome-common-types tfm-nodejs-fortawesome-free-brands-svg-icons tfm-nodejs-gud tfm-nodejs-hoist-non-react-statics tfm-nodejs-lodash.debounce tfm-nodejs-patternfly tfm-nodejs-patternfly-react tfm-nodejs-patternfly-react-icons tfm-nodejs-patternfly-react-tokens tfm-nodejs-prop-types tfm-nodejs-prop-types-extra tfm-nodejs-react-bootstrap-switch tfm-nodejs-react-bootstrap-typeahead tfm-nodejs-react-c3js tfm-nodejs-react-click-outside tfm-nodejs-react-collapse tfm-nodejs-react-debounce-input tfm-nodejs-react-fontawesome tfm-nodejs-react-motion tfm-nodejs-react-overlays tfm-nodejs-react-popper tfm-nodejs-react-transition-group tfm-nodejs-reactabular-table tfm-nodejs-recompose
% koji remove-pkg foreman-nightly-el8 nodejs-bootstrap-slider-without-jquery nodejs-breakjs nodejs-change-emitter nodejs-classnames nodejs-create-react-context nodejs-css-element-queries nodejs-dom-helpers nodejs-escape-string-regexp nodejs-fbjs nodejs-fortawesome-fontawesome-common-types nodejs-fortawesome-free-brands-svg-icons nodejs-gud nodejs-hoist-non-react-statics nodejs-lodash.debounce nodejs-patternfly nodejs-patternfly-react nodejs-patternfly-react-icons nodejs-patternfly-react-tokens nodejs-prop-types nodejs-prop-types-extra nodejs-react-bootstrap-switch nodejs-react-bootstrap-typeahead nodejs-react-c3js nodejs-react-click-outside nodejs-react-collapse nodejs-react-debounce-input nodejs-react-fontawesome nodejs-react-motion nodejs-react-overlays nodejs-react-popper nodejs-react-transition-group nodejs-reactabular-table nodejs-recompose nodejs-regenerator-runtime  
% koji remove-pkg foreman-nightly-rhel7 tfm-nodejs-bootstrap-slider-without-jquery tfm-nodejs-breakjs tfm-nodejs-change-emitter tfm-nodejs-classnames tfm-nodejs-create-react-context tfm-nodejs-css-element-queries tfm-nodejs-dom-helpers tfm-nodejs-escape-string-regexp tfm-nodejs-fbjs tfm-nodejs-fortawesome-fontawesome-common-types tfm-nodejs-fortawesome-free-brands-svg-icons tfm-nodejs-gud tfm-nodejs-hoist-non-react-statics tfm-nodejs-lodash.debounce tfm-nodejs-patternfly tfm-nodejs-patternfly-react tfm-nodejs-patternfly-react-icons tfm-nodejs-patternfly-react-tokens tfm-nodejs-prop-types tfm-nodejs-prop-types-extra tfm-nodejs-react-bootstrap-switch tfm-nodejs-react-bootstrap-typeahead tfm-nodejs-react-c3js tfm-nodejs-react-click-outside tfm-nodejs-react-collapse tfm-nodejs-react-debounce-input tfm-nodejs-react-fontawesome tfm-nodejs-react-motion tfm-nodejs-react-overlays tfm-nodejs-react-popper tfm-nodejs-react-transition-group tfm-nodejs-reactabular-table tfm-nodejs-recompose
```

**Pull request merged**
