### PR TITLE
Bump foreman_ansible_core to 2.0.2

### PR DESCRIPTION
**Pull request by dLobatog**
* [x] 1.16

### CODE REVIEW

**Comment by akofink** [comment]
Do we care about arm? If not, then LGTM

**Comment by ekohl** [comment]
@akofink typically we do care about ARM and every arch must build.

**Comment by mmoll** [comment]
[test packaging]

**Comment by mmoll** [comment]
There are some recent problems which I couldn't solve regarding such builds, but as this package is marked as `Architecture: all` it would get build on x86 only at the end of the day anyway.

**Comment by mmoll** [comment]
@dLobatog `plugins/smart_proxy_ansible/control` for 1.16 says `ruby-foreman-ansible-core (>= 1.1.0), ruby-foreman-ansible-core (<< 2.0.0)`  (smart_proxy_ansible 1.1.1).

**Comment by mmoll** [comment]
I'll need to solve the gem2deb problem first. This will probably require to build a patched version of gem2deb into our repos, I hope to get to this over the weekend.

**Comment by mmoll** [comment]
merged, gracias @dLobatog!

**Pull request merged**
