### PR TITLE
Add 1.18 to the PR template

### PR DESCRIPTION
**Pull request by ekohl**
Also changes the link to Redmine to use HTTPS

### CODE REVIEW

**Comment by mmoll** [comment]
looking at the history of this file, do we want do also remove 1.15 with this change?

**Comment by ekohl** [comment]
I thought about that. Have we formally ended support for 1.15? It'd be useful if we said that with the release of 1.17 "now 1.15 is unsupported" and when 1.18.0 is out we stop support with 1.16. Now it's not always that clear.

**Comment by mmoll** [comment]
@dLobatog :point_up: :question:

**Comment by ehelms** [comment]
Our support policy says N and N-1 so even though we haven't been explicitly stating it in release notes this would mean 1.15 was dead.

**Comment by ekohl** [comment]
Updated to remove 1.15

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Pull request merged**
