### PR TITLE
Update rubygem-foreman_openscap to 0.11.4

### PR DESCRIPTION
**Pull request by evgeni**
(cherry picked from commit 5983698d50455cc362e127dab132aff8f3273cf1)

For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [x] 1.21
* [ ] 1.20

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
this has built now, is a CP only PR, merging.

**Comment by evgeni** [comment]
build: http://koji.katello.org/koji/taskinfo?taskID=167404

**Pull request merged**
