### PR TITLE
Update dynflow dependency to 1.6.0

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by pcreech** [comment]
[test packaging]

**Comment by evgeni** [comment]
[test deb]

**Comment by pcreech** [comment]
@adamruzicka Is this still in progress?

**Comment by evgeni** [comment]
Yes I promised to look into this, and forgot 😅

**Comment by evgeni** [comment]
@adamruzicka this PR says it needs `msgpack << 1.4.0`, but in https://github.com/theforeman/foreman-packaging/pull/7252 you packaged 1.4.2?

**Comment by evgeni** [comment]
rebased and made sure `d/control` for all releases matches

**Review by evgeni — APPROVED** [review]

**Pull request merged**
