### PR TITLE
Update rubygem-foreman_maintain to 0.4.2

### PR DESCRIPTION
**Pull request by mbacovsky**

### CODE REVIEW

**Comment by mbacovsky** [comment]
@tbrisker, @ekohl  Is there anything I could do to get this in?

**Comment by evgeni** [comment]
I'd prefer if this change first happens in `rpm/develop` and is then cherrypicked into 1.22, unless there is a reason not to do it in `rpm/develop` first.

**Comment by mbacovsky** [comment]
@evgeni PR added in rpm/develop https://github.com/theforeman/foreman-packaging/pull/3806

**Comment by evgeni** [comment]
```
% koji tag-build foreman-1.22-nonscl-rhel7 rubygem-foreman_maintain-0.4.2-1.el7 
Created task 199728
Watching tasks (this may be safely interrupted)...
199728 tagBuild (noarch): free
199728 tagBuild (noarch): free -> open (kojibuilder1)
199728 tagBuild (noarch): open (kojibuilder1) -> closed
  0 free  0 open  1 done  0 failed

199728 tagBuild (noarch) completed successfully
```

**Pull request merged**
