### PR TITLE
Update foreman_chef to 0.2.0 (DEB)

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
Please build to 1.9 plugins as well

**Comment by mmoll** [comment]
Please specify the Foreman version dependency as `foreman (>= 1.9.0~rc1)` in the control file.

**Comment by ares** [comment]
added, thanks, I suppose `>= rc1` correctly takes 1.9.0

**Comment by mmoll** [comment]
`(>= 1.9.0~rc1)`, not `((= 1.9.0~rc1)` ;)

**Comment by ares** [comment]
oops, seems I can't even copy :-) thanks

**Comment by mmoll** [comment]
merged as 5a89715 for develop and 35050a1 for 1.9, díky @ares!

**Pull request closed without merging**
