### PR TITLE
Update kafo to 0.9.0

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by mmoll** [comment]
working fine here :+1: 
Is this also for 1.12?

**Comment by ares** [comment]
Yes, I think it should get to 1.12. @domcleal wanted hiera patch for some 1.12 issues. I know there's at least [this](http://projects.theforeman.org/issues/14789). We might want to keep it in nightly for few days just to be sure. 0.9 adds hiera patch and one minor fix for settings reloading so it should be quite safe though.

**Comment by domcleal** [comment]
Probably best to build for nightly only for now and then we can add 1.12 as/when needed.

**Comment by mmoll** [comment]
merged, díky @ares!

**Pull request merged**
