### PR TITLE
Release 1.24.0-RC2

### PR DESCRIPTION
**Pull request by zjhuntin**

### CODE REVIEW

**Comment by ehelms** [comment]
@mmoll seems to be looking for the wrong tarball, without the RC2 attached, what are we missing here?

**Comment by mmoll** [comment]
```
21:38:11 + wget http://downloads.theforeman.org/foreman/foreman-1.24.0-RC2.tar.bz2.sig
21:38:11 --2019-11-04 21:38:11--  http://downloads.theforeman.org/foreman/foreman-1.24.0-RC2.tar.bz2.sig
21:38:11 Resolving downloads.theforeman.org (downloads.theforeman.org)... 2a04:4e42:2f::561, 151.101.202.49
21:38:11 Connecting to downloads.theforeman.org (downloads.theforeman.org)|2a04:4e42:2f::561|:80... connected.
21:38:11 HTTP request sent, awaiting response... 404 Not Found
```

**Comment by ekohl** [comment]
Looks like you forgot the https://github.com/theforeman/theforeman-rel-eng/blob/master/sign_tarballs step. https://community.theforeman.org/t/foreman-1-24-0-rc2-release-process/16061 it a linear process where you can't skip any step.

**Comment by ekohl** [comment]
Note also that the CDN does cache a 404 for a bit. IIRC 2 minutes. https://github.com/theforeman/foreman-infra/blob/837ea483adfdf850eb7f8c53eace447c93e9f847/puppet/modules/jenkins_job_builder/files/theforeman.org/pipelines/release/foreman-discovery-image.groovy#L60 is a example of how to purge the cache.

**Comment by zjhuntin** [comment]
ACK, that's on me my bad.

**Comment by evgeni** [comment]
buster packages were not updated

**Comment by evgeni** [comment]
updated in #4285

**Pull request closed without merging**
