### PR TITLE
update katello-debug deps

### PR DESCRIPTION
**Pull request by sean797**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.17
* [ ] 1.16
* [ ] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ehelms** [comment]
Eeesh, good find -- mind revving the release number?  Are any of the quires not unique to `katello-debug` and could thus live or come with `foreman-debug` ?

**Comment by ekohl** [comment]
> mind revving the release number?

Is that needed with nightlies?

**Comment by sean797** [comment]
>  Are any of the quires not unique to katello-debug and could thus live or come with foreman-debug ?

probably, but as long as katello-debug directly uses them directly they should also be included here. That way if foreman-debug changes, we don't care.

**Comment by ehelms** [comment]
Aye, the release should be revved. We do not build this RPM on a nightly basis.

**Comment by ekohl** [comment]
Since the other PR increases the revision I'm merging this.

**Pull request merged**
