### PR TITLE
Fixes #30313 - Use case-insensitive sed for hostname change

### PR DESCRIPTION
**Pull request by synkd**

### CODE REVIEW

**Comment by ehelms** [comment]
@synkd Do you mind bumping the release on the katello package? You can do:

```
pip install obal
obal bump-release katello --changelog "Use case-insensitive sed for hostname change"
```

**Comment by ekohl** [comment]
I also maintain RPMs @ https://copr.fedorainfracloud.org/coprs/ekohl/obal/ if you prefer to avoid `pip install`. It has the added benefit that it already pulls in all dependencies rather than requiring you to use `obal setup` and gives you bash completion out of the box.

**Comment by pcreech** [comment]
[test rpm]

**Review by wbclark — APPROVED** [review]
LGTM. Thanks @synkd for the collab on this one!

**Review by evgeni — APPROVED** [review]

**Pull request merged**
