### PR TITLE
Updated pulp deps

### PR DESCRIPTION
**Pull request by evgeni**
this splits out the "bumped" packages from #4886 and ignores dynaconf for now

### CODE REVIEW

**Comment by evgeni** [comment]
repoclosure errors expected, needs #4892 to fix

**Comment by sjha4** [comment]
@evgeni : Is the python-requests failure expected?

**Comment by evgeni** [comment]
No it's not

**Comment by sjha4** [comment]
It passed in the el7 build.. :confused:

**Comment by evgeni** [comment]
My best guess is rpm on EL8 uses stricter patch settings when it comes to fuzz and that fails. I'll look into it on Monday

**Comment by evgeni** [comment]
repoclosure expected

**Pull request merged**
