### PR TITLE
Update rubygem-foreman_remote_execution to 5.0.2

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by Odilhao** [comment]
[test rpm]

**Comment by adamruzicka** [comment]
This requires a version of Foreman with https://github.com/theforeman/foreman/pull/9072 . 3.1.2 should have it

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
> This requires a version of Foreman with [theforeman/foreman#9072](https://github.com/theforeman/foreman/pull/9072) . 3.1.2 should have it

Should we bump `foreman_min_version` then? Just to ensure users don't accidentally update the plugin without foreman?

**Comment by adamruzicka** [comment]
Done

**Review by evgeni — APPROVED** [review]

**Pull request merged**
