### PR TITLE
Release 3.10.0-rc1

### PR DESCRIPTION
**Pull request by pcreech**

### CODE REVIEW

**Comment by pcreech** [comment]
[test rpm-copr]

**Comment by pcreech** [comment]
@ekohl @evgeni Looks like a copr build issue, any thoughts?

```
DEBUG util.py:463:  Additional repo https_download_copr_fedorainfra 2.2 kB/s | 341  B     00:00    
DEBUG util.py:461:  Errors during downloading metadata for repository 'https_download_copr_fedorainfracloud_org_results_theforeman_client_3_10_staging_rhel_9_x86_64':
DEBUG util.py:461:    - Status code: 404 for https://download.copr.fedorainfracloud.org/results/@theforeman/client-3.10-staging/rhel-9-x86_64/repodata/repomd.xml (IP: 2600:9000:2509:3200:4:bbc1:1840:93a1)
DEBUG util.py:461:  Error: Failed to download metadata for repo 'https_download_copr_fedorainfracloud_org_results_theforeman_client_3_10_staging_rhel_9_x86_64': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
DEBUG util.py:610:  Child return code was: 1
```

**Comment by evgeni** [comment]
did you branch client? https://copr.fedorainfracloud.org/coprs/g/theforeman/client-3.10-staging/ doesn't exist.
neither does https://copr.fedorainfracloud.org/coprs/g/theforeman/plugins-3.10-staging/

**Comment by pcreech** [comment]
Repoclosure failures currently expected at this stage.

**Pull request merged**
