### PR TITLE
Update rubygem-foreman_virt_who_configure to 0.5.19

### PR DESCRIPTION
**Pull request by chris1984**

### CODE REVIEW

**Comment by chris1984** [comment]
@pcreech can this get a bump for the 6.15 translations epic

**Comment by evgeni** [comment]
can you please bump in develop first?

**Comment by chris1984** [comment]
This has been done in develop already https://github.com/theforeman/foreman-packaging/commit/78c2ba1ecb483b0f2396994c8dbef8e372a4e860

**Comment by evgeni** [comment]
Then why isn't this PR a cherry pick?
Having (even only subtle) different packages with the same source can be very confusing.

**Comment by chris1984** [comment]
@evgeni updated to be a cherry-pick

**Review by evgeni — APPROVED** [review]

**Pull request merged**
