### PR TITLE
Update rubygem-netbox-client-ruby to 0.7.0

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ekohl** [comment]
This is blocked on updating foreman_netbox to allow this version.

**Comment by ehelms** [comment]
https://github.com/dm-drogeriemarkt/foreman_netbox/pull/65 has been merged -- are we now awaiting a release?

**Comment by ekohl** [comment]
Correct.

**Comment by evgeni** [comment]
#9700 updated the client to 0.6.0 and the plugin, as now the plugin seems to pin to `~> 0.6.0` :thinking: https://github.com/dm-drogeriemarkt/foreman_netbox/blob/bb8a1423b25dc48c4eb836a1d5a9f47c474a746c/foreman_netbox.gemspec#L19

**Comment by dgoetz** [comment]
Yes, had to go with the specified dependencies. Did the update of the netbox plugin because one customer wanted to try it and in 1.1.0 it still failed because of the "new" settings API, so backports for it are currently running tests. But without another release it is still blocking this one which is already available in 0.9.0.

**Comment by ekohl** [comment]
Blocked by https://github.com/dm-drogeriemarkt/foreman_netbox/pull/103. I'm closing this for now.

**Pull request closed without merging**
