### PR TITLE
Update rubygem-foreman-tasks to 3.0.0

### PR DESCRIPTION
**Pull request by adamruzicka**
CPs:
- [ ] 2.2

### CODE REVIEW

**Comment by tbrisker** [comment]
Looks like you need to update the specfile to include `.github/` instead of `.travis.yaml` (or remove these files from the gemspec altogether):

error: Installed (but unpackaged) file(s) found:
   /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-3.0.0/.github/workflows/js_tests.yml
   /opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-3.0.0/.github/workflows/ruby_tests.yml
    File not found: /builddir/build/BUILDROOT/tfm-rubygem-foreman-tasks-3.0.0-1.fm2_3.el7.noarch/opt/theforeman/tfm/root/usr/share/gems/gems/foreman-tasks-3.0.0/.travis.yml

**Comment by tbrisker** [comment]
Looks like a repoclosure issue not directly related to this one:
```
[2020-09-09T08:43:10.705Z]     package: tfm-rubygem-foreman_leapp-0.1.4-1.fm2_3.el7.noarch from el7-foreman-plugins-nightly
[2020-09-09T08:43:10.705Z]       unresolved deps:
[2020-09-09T08:43:10.705Z]         tfm-rubygem(foreman_ansible) < 6

```

**Comment by pcreech** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Review by evgeni — APPROVED** [review]

**Pull request merged**
