### PR TITLE
Update rubygem-pulp_rpm_client to 3.17.3

### PR DESCRIPTION
**Pull request by ianballou**
Updates pulp_rpm_client to 3.17.3.

### CODE REVIEW

**Comment by ianballou** [comment]
We're updating pulp-rpm to 3.17 first by itself since it's compatible with pulpcore 3.16.

**Comment by ianballou** [comment]
I'm seeing unresolved dependencies: `tfm-rubygem(faraday) >= 1.0`.  Do I need to bump up that version as well?

**Comment by Odilhao** [comment]
[test rpm]

**Comment by jlsherrill** [comment]
i think we may need a 3.17.3.1 with the faraday requirement loosened (built with https://github.com/pulp/pulp-openapi-generator/commit/b60bc0381879ab17722274ca625e0828ab4f789e)

**Comment by Odilhao** [comment]
> i think we may need a 3.17.3.1 with the faraday requirement loosened (built with [pulp/pulp-openapi-generator@b60bc03](https://github.com/pulp/pulp-openapi-generator/commit/b60bc0381879ab17722274ca625e0828ab4f789e))

3.17.4 got released yesterday https://rubygems.org/gems/pulp_rpm_client/versions/3.17.4, it lowered the faraday requirement

**Comment by ianballou** [comment]
Looks like it's all good!

**Review by Odilhao — APPROVED** [review]

**Pull request merged**
