### PR TITLE
Bump rubygem-foreman_rh_cloud to 3.0.21.1-1

### PR DESCRIPTION
**Pull request by laviro**

### CODE REVIEW

**Comment by laviro** [comment]
@evgeni ready for review :)
@shimshtein for the `develop` branch, should we release v4 of the plugin, or can we still use the same version for both?

**Comment by evgeni** [comment]
given `develop` has 3.0.21 right now (via https://github.com/theforeman/foreman-packaging/pull/6727), I'd think it also needs the same update?

**Comment by evgeni** [comment]
develop in #6744

**Comment by ShimShtein** [comment]
@laviro, since we're already branched, let's do the proper 4.0.21 for develop. This way at least the versioning won't be confusing.

**Comment by laviro** [comment]
@evgeni @ShimShtein, I released `v4` properly now and added it to `develop` in https://github.com/theforeman/foreman-packaging/pull/6750
once it goes in I will do the CPs to `2.5` & `2.4`

**Comment by evgeni** [comment]
ACK!

**Pull request merged**
