### PR TITLE
Update kafo to 0.8.1

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by domcleal** [comment]
Could you also delete the patch fix_require_in_add_progress.diff?  I think it's obsolete with the inclusion of #14941.

**Comment by ares** [comment]
I removed the patch from all versions

**Comment by domcleal** [comment]
Thanks, though I think you also need to remove it from dependencies/*/kafo/patches/series or the build may fail.

**Comment by ares** [comment]
Right, here it is.

**Comment by mmoll** [comment]
working fine here on jessie, merged, díky @ares!

**Pull request merged**
