### PR TITLE
Bump smart_proxy_dns_powerdns to 0.2.1

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by mmoll** [comment]
test failed because the branch name has to start with `deb/`, but this looks good anyway. The required version of foreman-proxy should maybe be >= 1.11.2, even if it's not yet released, or is there just some functionality missing with 1.11 now?

**Comment by ekohl** [comment]
The master branch would need a backport, but I created a branch that should work with 1.11. I hoped this would create a scatch build so I could test it. Should I close this PR and reopen with a different branch name?

**Comment by domcleal** [comment]
@ekohl yeah, you'll need to

**Comment by ekohl** [comment]
I first thought it was the double slash in the branch name but I now see I made a typo in deb.

**Pull request closed without merging**
