### PR TITLE
Bump Pulp bindings requirements in Katello

### PR DESCRIPTION
**Pull request by ianballou**
Bumps up the requirements for Pulpcore 3.22.  Goes along with https://github.com/theforeman/foreman-packaging/pull/9048

### CODE REVIEW

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
I think this depends on https://github.com/Katello/katello/pull/10453 to pass.

**Review by ekohl — COMMENTED** [review]
Should we also bump the repo in this PR:
https://github.com/theforeman/foreman-packaging/blob/289c678f7fd313548f742ae5a98e13d9e5c5d7bc/packages/katello/katello-repos/katello-repos.spec#L1

**Comment by ianballou** [comment]
https://github.com/Katello/katello/pull/10453 is merged!

**Comment by ekohl** [comment]
Slight nit: your commit message says 3.21.

**Comment by ianballou** [comment]
@ekohl all set! Guess the Katello source needs to be built before these tests pass.

**Comment by ekohl** [comment]
https://ci.theforeman.org/job/katello-master-source-release/2122/ does take an hour, which is much longer than I'd expected.

**Comment by ianballou** [comment]
Hm I wonder if it got stuck during the tests, rarely we do have some timeouts that get hit.

**Comment by evgeni** [comment]
it hit some, yeah. I re-kicked it, and so I am here:

[test rpm]

**Review by evgeni — APPROVED** [review]

**Comment by evgeni** [comment]
repoclosure complains about packages in the repo, not this PR, merging.

https://github.com/theforeman/forklift/pull/1655 will need a merge too so that we can actually test against 3.22

**Pull request merged**
