### PR TITLE
Update rubygem-clamp to 1.1.2

### PR DESCRIPTION
**Pull request by mbacovsky**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.16
* [ ] 1.15
* [ ] 1.14

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ekohl** [comment]
Have you run the unit tests of 1.1.2 against Ruby 2.0? If they pass I'd be fine with including what's officially not supported.

**Comment by mbacovsky** [comment]
@ekohl, non-scl clamp is used in kafo (installer) AFAIK and I tested clamp 1.1.2 with installer on ruby 2.0 and the tests were successful. I didn't tried the unittest but there were no changes in the clamp code requiring ruby > 2.0.

**Comment by ekohl** [comment]
@mbacovsky I would feel safer if we ran the clamp unittests on ruby 2.0 (so not kafo). If they pass 👍

**Comment by ekohl** [comment]
Just ran ```rake spec``` and it all passed.

**Comment by ehelms** [comment]
@ekohl does that mean this is good to be merged and built?

**Comment by ekohl** [comment]
@ehelms I think it does.

Short summary:
* hammer nightlies need clamp 1.1.1
* clamp >= 1.1.0 doesn't officially support ruby 2.0
* kafo uses clamp
* kafo runs under system ruby
* system ruby is 2.0 on EL7
* We've verified by reading the diffs and running unit tests that it should work

**Comment by dLobatog** [comment]
Building in:

http://koji.katello.org/koji/taskinfo?taskID=42862
http://koji.katello.org/koji/taskinfo?taskID=42861

**Pull request merged**
