### PR TITLE
Release Foreman RC1

### PR DESCRIPTION
**Pull request by ehelms**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.20
* [ ] 1.19
* [ ] 1.18

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by mmoll** [comment]
the source branch needs to start with `deb/`, but merging anyway...

**Comment by mmoll** [comment]
merged, thanks @ehelms!

**Comment by mmoll** [comment]
It didn't build, but I'd argue that there won't be additional changes needed to those files. :mag:

**Comment by ekohl** [comment]
Fair enough

**Pull request merged**
