### PR TITLE
Bump rubygem-fog-vsphere version to 2.1.1

### PR DESCRIPTION
**Pull request by sbernhard**
For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [ ] 1.17
* [x] 1.16
* [ ] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ekohl** [comment]
This will also need a PR to https://github.com/theforeman/foreman/blob/1.16-stable/bundler.d/fog.rb

**Comment by sbernhard** [comment]
I guess you mean 'this ought to solve the problem we have with 1.16.1`?  We are preparing to create the 1.16.2?

**Comment by ekohl** [comment]
> @ekohl Are you sure? I was able to install this on 1.16-stable, using fog 1.41 (same as the one we have 1.16-stable).

You're right, I was clearly not paying attention. I meant to look at https://github.com/theforeman/foreman/blob/1.16-stable/bundler.d/vmware.rb but didn't. That looks correct so we can include this.

**Comment by dLobatog** [comment]
Hmm. In reality fog-vsphere 2.1.1 was already built in 1.17-stable and nightly, http://koji.katello.org/koji/taskinfo?taskID=99584 - the spec changes were pretty minor.

http://koji.katello.org/koji/buildinfo?buildID=27604 was tagged now as foreman-1.16-rhel7, it should be shortly available in the repos

**Comment by dLobatog** [comment]
http://yum.theforeman.org/releases/1.16/el7/x86_64/tfm-rubygem-fog-vsphere-2.1.1-1.el7.noarch.rpm built, @sbernhard  time to test it :smile:

**Pull request merged**
