### PR TITLE
drop host_reports

### PR DESCRIPTION
**Pull request by evgeni**
(cherry picked from commit cfcf488613cc58a7e9703fc84cbd9fa476ff10e6)

### CODE REVIEW

**Comment by evgeni** [comment]
@pcreech did you also remove the packages from the repo?

**Comment by pcreech** [comment]
um..... no..... *facepalm*

I won't have time to get to it until Monday personally.  I'll see if someone can take care of it in my absence.

**Comment by evgeni** [comment]
https://github.com/theforeman/foreman-packaging/pull/8386#issuecomment-1226903535

Has the details what I did for nightly and should be adoptable. (Based on https://github.com/theforeman/foreman-packaging/tree/deb/develop#howto-removing-packages)

**Comment by evgeni** [comment]
```console
# rm /var/www/freight/apt/plugins/3.4/ruby-foreman-host-reports_1.0.2-1_all.deb /var/www/freight/apt/plugins/3.4/ruby-smart-proxy-reports_1.0.0-1_all.deb
rm: remove regular file ‘/var/www/freight/apt/plugins/3.4/ruby-foreman-host-reports_1.0.2-1_all.deb’? y
rm: remove regular file ‘/var/www/freight/apt/plugins/3.4/ruby-smart-proxy-reports_1.0.0-1_all.deb’? y

# rm /var/www/freight/apt/bullseye/3.4/ruby-hammer-cli-foreman-host-reports_0.1.0-1_all.deb  /var/www/freight/apt/focal/3.4/ruby-hammer-cli-foreman-host-reports_0.1.0-1_all.deb
rm: remove regular file ‘/var/www/freight/apt/bullseye/3.4/ruby-hammer-cli-foreman-host-reports_0.1.0-1_all.deb’? y
rm: remove regular file ‘/var/www/freight/apt/focal/3.4/ruby-hammer-cli-foreman-host-reports_0.1.0-1_all.deb’? y

# rm /var/www/freightstage/apt/bullseye/theforeman-3.4/ruby-hammer-cli-foreman-host-reports_0.1.0-1_all.deb  /var/www/freightstage/apt/focal/theforeman-3.4/ruby-hammer-cli-foreman-host-reports_0.1.0-1_all.deb
rm: remove regular file ‘/var/www/freightstage/apt/bullseye/theforeman-3.4/ruby-hammer-cli-foreman-host-reports_0.1.0-1_all.deb’? y
rm: remove regular file ‘/var/www/freightstage/apt/focal/theforeman-3.4/ruby-hammer-cli-foreman-host-reports_0.1.0-1_all.deb’? y
```

it's gone

**Pull request merged**
