### PR TITLE
fixes #8996 - use Ruby 1.9 for hammer on precise

### PR DESCRIPTION
**Pull request by mmoll**
yet untested.

### CODE REVIEW

**Comment by domcleal** [comment]
Interesting, I'll try and give it a go soon.  I was wondering if we should rely on the Brightbox version too, but hopefully the p0 in 12.04 will be enough.

**Comment by mmoll** [comment]
[test]

**Comment by domcleal** [comment]
A quick test of upgrading installed the right locale package, but the shebang line in /usr/bin/hammer needs changing to ruby1.9.1 after which point a host list worked fine.

**Comment by mmoll** [comment]
This should be handled by the XS-Ruby-Versions line, need to check this again...

**Comment by domcleal** [comment]
Hm okay, it was just `/usr/bin/env ruby`.

**Comment by mmoll** [comment]
I see the problem now: https://wiki.debian.org/Teams/Ruby/Packaging#Handling_of_shebangs requires ```/usr/bin/ruby```, while hammer is using ```/usr/bin/env ruby```, I'll just replace this after unpacking and see what's happening.

**Comment by mmoll** [comment]
Should all be fine now. By also dropping the dependency onto the rubygems package, it even works without any ruby1.8 components.

**Comment by domcleal** [comment]
Merged, thanks very much @mmoll!  Building now.

**Pull request merged**
