### PR TITLE
Update smart_proxy_remote_execution_ssh to 0.5.0

### PR DESCRIPTION
**Pull request by adamruzicka**
(cherry picked from commit 5985511c0e446839ee52971ad18dfa02a3a62387)

### CODE REVIEW

**Review by Odilhao — APPROVED** [review]

**Comment by shr-project** [comment]
Shouldn't this depend on ruby-mqtt as in rpm packaging?

it was added there with https://github.com/theforeman/foreman-packaging/pull/7349, but ruby-mqtt isn't packaged for debian only for rpm as in:
https://github.com/theforeman/foreman-packaging/pull/7327

On Ubuntu 20.04 with foreman 3.1 I'm seeing:
```
Message
Couldn't enable 'ssh'
Backtrace
cannot load such file -- mqtt: /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/vendor_ruby/smart_proxy_remote_execution_ssh/actions/pull_script.rb:1:in `<top (required)>'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/vendor_ruby/smart_proxy_remote_execution_ssh/actions.rb:4:in `<module:Actions>'
/usr/lib/ruby/vendor_ruby/smart_proxy_remote_execution_ssh/actions.rb:2:in `<module:Ssh>'
/usr/lib/ruby/vendor_ruby/smart_proxy_remote_execution_ssh/actions.rb:1:in `<top (required)>'
```

**Comment by adamruzicka** [comment]
> Shouldn't this depend on ruby-mqtt as in rpm packaging?

Yes, it should. Thank you for pointing that out

**Comment by evgeni** [comment]
This should only fail when using the MQTT backend, right?

Because our tests call `hammer job-invocation create --job-template 'Run Command - SSH Default' --inputs 'command=uptime' --search-query "name = $HOSTNAME"` and that seems to still work fine?

**Comment by adamruzicka** [comment]
This is interesting. It attempts to load to load `mqtt` on startup without any failsafes, however if an exception is raised doing loading, smart proxy merrily ignores it and still marks the feature as available. I think this is not the first time we're running into this (cc @ekohl). Although it seems to be up and apparently working in our tests, I wouldn't vouch for it being 100% ready

```
$ bundle exec ruby bin/smart-proxy | grep mqtt &
2021-12-10T17:23:30  [W] Error details for Couldn't enable 'ssh': <LoadError>: cannot load such file -- mqtt

$ curl http://localhost:8000/features
["ansible","dynflow","logs","probing","salt","shellhooks","ssh"]
```

**Comment by evgeni** [comment]
@adamruzicka packaging fixes in https://github.com/theforeman/foreman-packaging/pull/7416 -- mind having a quick look?

the smart-proxy behavior is disturbing :(

**Comment by ekohl** [comment]
I think https://github.com/theforeman/smart_proxy_remote_execution_ssh/pull/57 would have caught that. Right now it's loading the plugin in `after_activation` (which is deprecated). The `load_classes` method is ran before the plugin is marked as `:running`.

**Pull request merged**
