### PR TITLE
Update gem dependencies

### PR DESCRIPTION
**Pull request by ofedoren**

### CODE REVIEW

**Comment by tbrisker** [comment]
Looks like this needs a rebase

**Comment by ofedoren** [comment]
@tbrisker, updated.

**Comment by tbrisker** [comment]
that's odd indeed, perhaps try manually removing them? Also you need to bump the release, `obal bump-release foreman --changelog "Add apipie-dsl"` should do the trick

**Comment by ofedoren** [comment]
@tbrisker, thanks for help! Updated.

**Comment by tbrisker** [comment]
Looks like el8 failed for some reason... @ehelms is it possible you only tagged apipie-dsl to el7?

**Comment by tbrisker** [comment]
[test rpm] core was merged, now package release fails due to this missing

**Comment by ofedoren** [comment]
Closing this one as per discussion on IRC.

**Pull request closed without merging**
