### PR TITLE
Rpm/release foreman 2.0.1 update foreman release 2.0.1 update foreman 2.0.1 update foreman installer 2.0.1 update foreman selinux 2.0.1 update foreman proxy 2.0.1

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by tbrisker** [comment]
el8 build failed:
```
DEBUG util.py:600:  Error: Error downloading packages:
DEBUG util.py:600:    Status code: 404 for http://koji.katello.org/kojifiles/releases/split/yum/koji-modules/koji/staged/x86_64/RHEL-8-001/non_modular/binutils-2.30-58.el8_1.1.x86_64.rpm (IP: 172.30.3.224)

**Comment by tbrisker** [comment]
looks like the repo has `binutils-2.30-58.el8_1.2.x86_64.rpm` but not `binutils-2.30-58.el8_1.1.x86_64.rpm` - maybe mashing needed?

**Comment by evgeni** [comment]
[test rpm]

I did a `koji regen-repo` which hopefully fixed this.

**Comment by evgeni** [comment]
(it did: http://koji.katello.org/koji/taskinfo?taskID=348012)

**Comment by evgeni** [comment]
foreman fails to build due to nulldb, needs something like https://github.com/theforeman/foreman-packaging/commit/d106c7bb0a9f65b3491306c982d60e7cc5634d4e applied

**Comment by evgeni** [comment]
(which I just did)

**Comment by evgeni** [comment]
repoclosure is repoclosure :eyes:

**Pull request merged**
