### PR TITLE
Bump foreman_ygg_worker to 0.2.1

### PR DESCRIPTION
**Pull request by adamruzicka**
CP:
- 3.8
- 3.7
- 3.6

### CODE REVIEW

**Comment by ekohl** [comment]
I thought we used a newer Go?
```
./runner.go:61:21: undefined: os.CreateTemp
note: module requires Go 1.16
```

**Comment by ekohl** [comment]
Oops: http://koji.katello.org/kojifiles/releases/split/yum/koji-modules/koji/staged/x86_64/RHEL-8-001/go-toolset:rhel8/

**Comment by ehelms** [comment]
> Oops: http://koji.katello.org/kojifiles/releases/split/yum/koji-modules/koji/staged/x86_64/RHEL-8-001/go-toolset:rhel8/

I am working on this, harder than it should be to do, one place that Copr wins over Koji.

**Comment by ehelms** [comment]
Adding go-toolset 1.20 -- https://github.com/theforeman/tool_belt/pull/565

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Pull request merged**
