### PR TITLE
Rebuild rubygem-rkerberos against new libkadm5 in EL 8.3

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
this will need to be backported to all stable branches

**Comment by evgeni** [comment]
```
[2020-12-08T07:19:58.506Z]     package: rubygem-rkerberos-0.1.5-19.el8.x86_64 from downloaded_rpms
[2020-12-08T07:19:58.506Z]       unresolved deps:
[2020-12-08T07:19:58.506Z]         libkadm5clnt_mit.so.11()(64bit)
[2020-12-08T07:19:58.506Z]         libkadm5clnt_mit.so.11(kadm5clnt_mit_11_MIT)(64bit)
```

Great, Koji doesn't have the new libkadm5 yet…

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
@pcreech help me out please, why does Koji not see CentOS 8.3 changes yet? Or do we need to update something manually?

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
well, now it has the right kerberos libs, but links against Ruby 2.7…

```
[2020-12-10T07:44:05.465Z]     package: rubygem-rkerberos-0.1.5-19.el8.x86_64 from downloaded_rpms
[2020-12-10T07:44:05.465Z]       unresolved deps:
[2020-12-10T07:44:05.465Z]         libruby.so.2.7()(64bit)
```

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
perfect, now repoclosure only complains about the old pkg

**Review by tbrisker — APPROVED** [review]
Thanks @evgeni !

**Pull request merged**
