### PR TITLE
Bump discovery to 18.0.4

### PR DESCRIPTION
**Pull request by lzap**
For plugin updates, please indicate which repos this should be built into:

* Nightly
* 3.0

RPM: https://github.com/theforeman/foreman-packaging/pull/7170

### CODE REVIEW

**Comment by lzap** [comment]
Weird it should be, let me rebase then: https://rubygems.org/gems/foreman_discovery

**Comment by pcreech** [comment]
The title of the PR says Discovery, but the commit is on foreman-bootdisk.  There is no foreman_bootdisk 18.0.4 on rubygems.

**Comment by lzap** [comment]
Apologies for the delay, finally I got to this. Should be okay now. I will do 3.0 CP once this is fixed, these are important fixes.

**Comment by lzap** [comment]
This is now ready for re-review.

**Review by pcreech — APPROVED** [review]

**Comment by lzap** [comment]
CP 3.0: https://github.com/theforeman/foreman-packaging/pull/7263 TY

**Pull request merged**
