### PR TITLE
[deb] Update foreman-ansible to 2.2.0

### PR DESCRIPTION
**Pull request by dLobatog**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.18
* [ ] 1.17
* [ ] 1.16

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by dLobatog** [comment]
Leaving https://github.com/theforeman/foreman-packaging/pull/2257/files for 1.17

**Comment by mmoll** [comment]
waiting on GH-2442

**Comment by mmoll** [comment]
Please update the dependency versions (foreman-tasks and foreman-*).
Also, does foreman_ansible_core in gem.list need updating?

**Comment by ares** [comment]
This is now replaced by https://github.com/theforeman/foreman-packaging/pull/2721 and I think can be closed.
In replacing PR, I omitted foreman tasks bump, I think this matches the gemspec. I'm not sure what asked with with foreman_ansible_core in gem.list, 2.0.2 is latest greatest released, so I think that version is correct. Also not sure what other dependency version (foreman-*) you meant, please add inline comments in the new PR, thanks!

**Pull request closed without merging**
