### PR TITLE
Update rubygem-foreman_discovery to 18.0.0

### PR DESCRIPTION
**Pull request by lzap**
(cherry picked from commit be6c62ff0a3b3d2d9f5b05a9f86d1e4492625186)

### CODE REVIEW

**Comment by lzap** [comment]
Once this is merged I can just wait until repo gets published automatically and I can announce, there is no need to wait for 3.0.1 with this one, right?

**Comment by ekohl** [comment]
Correct - once it's built we can kick off https://ci.theforeman.org/job/foreman-plugins-3.0-rpm-pipeline/

**Comment by lzap** [comment]
Thank you!

**Comment by lzap** [comment]
I see the package in 3.0 repos now, thanks.

**Pull request merged**
