### PR TITLE
Update rubygem-foreman_azure_rm to 2.2.1

### PR DESCRIPTION
**Pull request by upadhyeammit**

### CODE REVIEW

**Comment by upadhyeammit** [comment]
[test rpm]

**Review by ekohl — COMMENTED** [review]
Looks like the azure gems need to be updated as well. Since they're build dependencies that needs to go in a separate PR. Sadly our build system can't use updated builds in the same PR.

**Comment by upadhyeammit** [comment]
Created separate pr for dependencies : https://github.com/theforeman/foreman-packaging/pull/6515

**Comment by upadhyeammit** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
```
foreman_azure_rm-2.2.1-1.fm2_5.el7.noarch/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_azure_rm-2.2.1/app/models/foreman_azure_rm/azure_rm_compute.rb:13: circular argument reference - sdk
```

I think ruby 2.7 doesn't like that

**Comment by evgeni** [comment]
I proposed a fix in https://github.com/theforeman/foreman_azure_rm/pull/113

**Comment by evgeni** [comment]
2.2.2 was released so I've updated it in https://github.com/theforeman/foreman-packaging/pull/6534

**Pull request closed without merging**
