### PR TITLE
Drop rackspace packages

### PR DESCRIPTION
**Pull request by tbrisker**
Core PR: https://github.com/theforeman/foreman/pull/7612

### CODE REVIEW

**Comment by tbrisker** [comment]
added rackspace to breaks section

**Comment by tbrisker** [comment]
not sure why, tests are trying to get the 2.1 tarballs?

**Comment by ekohl** [comment]
Your branch name doesn't start with `deb/develop` so it can't detect that it's a develop branch.

**Comment by tbrisker** [comment]
gah... will reopen from right branch name

**Comment by tbrisker** [comment]
https://github.com/theforeman/foreman-packaging/pull/5112

**Pull request closed without merging**
