### PR TITLE
just a test, nothing to see here

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by ekohl** [comment]
image

**Comment by evgeni** [comment]
[test packaging]

**Comment by evgeni** [comment]
```
cp: cannot create regular file '/var/cache/pbuilder/bionic64/result/ansible-collection-theforeman-foreman_9999-plugin+scratchbuild+20210830145932_all.deb': Permission denied
```

Meh, that's what the second sudo did? Baaaaah

**Comment by evgeni** [comment]
@ekohl  the cheap solution would be to do env_keep for everyone, not just Jenkins?

**Comment by ekohl** [comment]
Just an idea (and much bigger) but would https://tauware.blogspot.com/2020/04/building-packages-with-buildah-in-debian.html be a good idea? Benefits would be that it's rootless (no more sudo) and no longer requires anything Debian-specific (no more need for a Debian node which also means we have a lot more capacity for Debian packaging). Obvious downside is that it's rewriting our entire Debian package build process.

**Comment by evgeni** [comment]
Long term? Yeah. But I'd prefer to switch one thing at a time right now ;)

**Comment by ekohl** [comment]
This looks like something we need: https://unix.stackexchange.com/questions/13240/etc-sudoers-specify-env-keep-for-one-command-only/13298#13298

**Comment by evgeni** [comment]
You mean so that the env_keep is anchored on the command, not the user?

**Comment by evgeni** [comment]
Or we can tell pdebuild to do the right thing: https://github.com/theforeman/foreman-infra/pull/1647

**Comment by evgeni** [comment]
[test packaging]

**Comment by evgeni** [comment]
cool, seems to work again \o/

**Pull request closed without merging**
