### PR TITLE
Remove *.js.map file after asset precompile

### PR DESCRIPTION
**Pull request by evgeni**
Inspired by https://github.com/theforeman/foreman-packaging/pull/3083

For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.20
* [ ] 1.19
* [ ] 1.18

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ohadlevy** [comment]
@tstrachota doesnt this goes against your original intent? just want to make sure we are not missing anything...

**Comment by evgeni** [comment]
@ohadlevy the `.js.map` files work fine in Foreman itself, but not in Plugins. One of the issues is that they contain build-time filepaths, which Koji/Brew forbids to be shipped in an RPM. So without the above change, the plugin does not build to RPM.

**Comment by ohadlevy** [comment]
@evgeni I understand, I wonder in that case if we shouldn't remove the webpack change (to generate it in the first place) as I believe the original goal was to include it in the RPM...

**Comment by tstrachota** [comment]
Yes, that was the original intent. If we can keep the maps at least for the core then it's also an improvement and I wouldn't remove it from the webpack config.

@evgeni what do we need to change to get the maps in for plugins too?

**Comment by evgeni** [comment]
We do ship the maps in core at the moment, and there it seems to work just fine.

@tstrachota I think the current problem was (and @ekohl can correct me here) that the `.map` file contains build-time paths and RPM does not like this:
```
+ /usr/lib/rpm/check-buildroot
/builddir/build/BUILDROOT/tfm-rubygem-foreman_ansible-2.2.9-3.el7sat.noarch/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_ansible-2.2.9/public/webpack/foreman_ansible/foreman_ansible-3e92a72ba2eea7b84016.js.map:{"version":3,"sources":["webpack:////builddir/build/BUILDROOT/tfm-rubygem-foreman_ansible-2.2.9-3.el7sat.noarch/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_ansible-2.2.9/webpack/components/ReportJsonViewer.js","webpack:////builddir/build/BUILDROOT/tfm-rubygem-foreman_ansible-2.2.9-3.el7sat.noarch/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_ansible-2.2.9/webpack/index.js","webpack:///./webpack/assets/javascripts/foreman_editor.js","webpack:///./webpack/assets/javascripts/foreman_navigation.js",…
Found '/builddir/build/BUILDROOT/tfm-rubygem-foreman_ansible-2.2.9-3.el7sat.noarch' in installed files; aborting
```

the core maps only reference `/usr/lib/node_modules/`, not `/builddir/build/BUILDROOT/`

if we can generate maps that do not contain these (`/builddir/build/BUILDROOT/`) paths, we should be good (at least on the RPM side, no idea how useable these maps are).

**Comment by ohadlevy** [comment]
i wonder why source maps include the full path, but i guess its just to
recreate the source directory structure, nothing more - which imho is
harmless?

**Comment by tstrachota** [comment]
I also think it should be harmless. I wonder if this setting could help us: https://webpack.js.org/configuration/output/#output-devtoolmodulefilenametemplate

**Comment by evgeni** [comment]
Yeah. I thought the same, but didn't try yet.

**Comment by ekohl** [comment]
Replaced by https://github.com/theforeman/foreman-packaging/pull/3152. There's a generic fix in https://github.com/theforeman/foreman-packaging/pull/3151 so if we find a solution it only needs to be fixed in 1 place.

**Pull request closed without merging**
