### PR TITLE
Update foreman-tasks to 0.8.6 and dynflow to 0.8.17 [deb]

### PR DESCRIPTION
**Pull request by iNecas**

### CODE REVIEW

**Comment by mmoll** [comment]
[test]

**Comment by mmoll** [comment]
plugins/ruby-foreman-tasks/foreman-tasks.rb needs updating, too

**Comment by iNecas** [comment]
Updated

**Comment by mmoll** [comment]
merged as ddb5b16 and 3fcf3a7, díky @iNecas!

**Pull request closed without merging**
