### PR TITLE
Bump version to 2.0-develop

### PR DESCRIPTION
**Pull request by tbrisker**
I'm guessing this will likely fail on some missing koji tags or something...

### CODE REVIEW

**Comment by ekohl** [comment]
[test rpm]

**Comment by tbrisker** [comment]
why are we building foreman-release for el5 and fedora?

**Comment by evgeni** [comment]
el5/el6 and fedora are for the client packages

the error is
```
DEBUG util.py:596:  warning: Could not canonicalize hostname: koji.katello.org
DEBUG util.py:596:  error: Could not open /chroot_tmpdir/srpm_unpacked/SRPMS/foreman-release-2.0.0-0.1.develop.el5.src.rpm: No such file or directory
```

@pcreech is that some koji upgrade fallout?

**Comment by pcreech** [comment]
[test]

**Comment by pcreech** [comment]
[test rpm]

**Comment by evgeni** [comment]
No, repoclosure is failing because this is a PR that touches SCL and non-SCL at the same time, and that confuses our repoclosure checks.

**Pull request merged**
