### PR TITLE
Update discovery to 10.0.0

### PR DESCRIPTION
**Pull request by lzap**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.16

### CODE REVIEW

**Comment by ekohl** [comment]
Similar to the deb this needs to update the require on foreman-proxy to ```>= 1.16```

**Comment by dLobatog** [comment]
@ekohl You mean the require on foreman >= 1.15? I don't see why this would add a requirement on foreman-proxy

**Comment by ekohl** [comment]
@dLobatog you're right. I meant this line: https://github.com/theforeman/foreman-packaging/blob/d06685b99f659d3b1376a4895bb2a532ff751f09/rubygem-foreman_discovery/rubygem-foreman_discovery.spec#L35

Most likely this one too: https://github.com/theforeman/foreman-packaging/blob/d06685b99f659d3b1376a4895bb2a532ff751f09/rubygem-foreman_discovery/rubygem-foreman_discovery.spec#L41

**Comment by lzap** [comment]
Oh good catch thanks! Done.

**Comment by dLobatog** [comment]
nightly - http://koji.katello.org/koji/buildinfo?buildID=18450
1.16 - http://koji.katello.org/koji/taskinfo?taskID=44434

**Pull request merged**
