### PR TITLE
Update katello 4.1 to use pulpcore 3.14

### PR DESCRIPTION
**Pull request by jjeffers**

### CODE REVIEW

**Comment by evgeni** [comment]
The diff looks good.

Is there already a cherry pick PR open for Katello itself to bring in compatibility with 3.14?

**Comment by jeremylenz** [comment]
@evgeni yes it's almost ready! Hoping to build the gem tomorrow; we'll see..

**Review by evgeni — APPROVED** [review]
Katello is ready \o/

**Comment by evgeni** [comment]
```console
% koji tag-build katello-4.1-el8 rubygem-pulp_ansible_client-0.8.0-1.el8 rubygem-pulp_certguard_client-1.4.0-1.el8 rubygem-pulp_container_client-2.7.0-1.el8 rubygem-pulp_deb_client-2.13.0-1.el8 rubygem-pulp_file_client-1.8.1-1.el8 rubygem-pulp_rpm_client-3.13.3-1.el8 rubygem-pulpcore_client-3.14.1-1.el8
Created task 437138
Created task 437139
Created task 437141
Created task 437142
Created task 437143
Created task 437144
Created task 437145
Watching tasks (this may be safely interrupted)...
437138 tagBuild (noarch): free
437139 tagBuild (noarch): free
437141 tagBuild (noarch): free
437142 tagBuild (noarch): free
437143 tagBuild (noarch): free
437144 tagBuild (noarch): free
437145 tagBuild (noarch): free
437138 tagBuild (noarch): free -> closed
  6 free  0 open  1 done  0 failed
437139 tagBuild (noarch): free -> closed
  5 free  0 open  2 done  0 failed
437141 tagBuild (noarch): free -> closed
  4 free  0 open  3 done  0 failed
437142 tagBuild (noarch): free -> closed
  3 free  0 open  4 done  0 failed
437143 tagBuild (noarch): free -> closed
  2 free  0 open  5 done  0 failed
437144 tagBuild (noarch): free -> closed
  1 free  0 open  6 done  0 failed
437145 tagBuild (noarch): free -> closed
  0 free  0 open  7 done  0 failed

437138 tagBuild (noarch) completed successfully
437139 tagBuild (noarch) completed successfully
437141 tagBuild (noarch) completed successfully
437142 tagBuild (noarch) completed successfully
437143 tagBuild (noarch) completed successfully
437144 tagBuild (noarch) completed successfully
437145 tagBuild (noarch) completed successfully

% koji tag-build katello-4.1-rhel7 tfm-rubygem-pulp_ansible_client-0.8.0-1.el7 tfm-rubygem-pulp_certguard_client-1.4.0-1.el7 tfm-rubygem-pulp_container_client-2.7.0-1.el7 tfm-rubygem-pulp_deb_client-2.13.0-1.el7 tfm-rubygem-pulp_file_client-1.8.1-1.el7 tfm-rubygem-pulp_rpm_client-3.13.3-1.el7 tfm-rubygem-pulpcore_client-3.14.1-1.el7
Created task 437150
Created task 437151
Created task 437153
Created task 437154
Created task 437155
Created task 437156
Created task 437157
Watching tasks (this may be safely interrupted)...
437150 tagBuild (noarch): free
437151 tagBuild (noarch): free
437153 tagBuild (noarch): free
437154 tagBuild (noarch): free
437155 tagBuild (noarch): free
437156 tagBuild (noarch): free
437157 tagBuild (noarch): free
437150 tagBuild (noarch): free -> closed
  6 free  0 open  1 done  0 failed
437151 tagBuild (noarch): free -> closed
  5 free  0 open  2 done  0 failed
437153 tagBuild (noarch): free -> closed
  4 free  0 open  3 done  0 failed
437154 tagBuild (noarch): free -> closed
  3 free  0 open  4 done  0 failed
437155 tagBuild (noarch): free -> closed
  2 free  0 open  5 done  0 failed
437156 tagBuild (noarch): free -> closed
  1 free  0 open  6 done  0 failed
437157 tagBuild (noarch): free -> closed
  0 free  0 open  7 done  0 failed

437150 tagBuild (noarch) completed successfully
437151 tagBuild (noarch) completed successfully
437153 tagBuild (noarch) completed successfully
437154 tagBuild (noarch) completed successfully
437155 tagBuild (noarch) completed successfully
437156 tagBuild (noarch) completed successfully
437157 tagBuild (noarch) completed successfully
```

**Pull request merged**
