### PR TITLE
Refs #35088 - Remove foreman-gce and mark foreman_google as replacement

### PR DESCRIPTION
**Pull request by ekohl**
I think this is the migration path for users, but not really sure.

### CODE REVIEW

**Review by evgeni — APPROVED** [review]
This looks correct to me.

Build fails with
```
Installed (but unpackaged) file(s) found:
   /usr/share/foreman/bundler.d/gce.rb
```

Which will be fixed once https://github.com/theforeman/foreman/pull/9272 is merged

**Comment by ekohl** [comment]
Should be there once https://ci.theforeman.org/job/foreman-develop-source-release/1811/ is done.

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
```
[2022-11-04T15:34:43.869Z]     package: rubygem-foreman_google-0.0.2-2.fm3_5.el8.noarch from downloaded_rpms
[2022-11-04T15:34:43.869Z]       unresolved deps:
[2022-11-04T15:34:43.869Z]         (rubygem(google-cloud-compute) >= 0.2 with rubygem(google-cloud-compute) < 1)
```

I wonder why this fails because it should be there. If anything, that part was unchanged.

**Comment by ekohl** [comment]
Manually checking:
```console
# dnf install https://yum.theforeman.org/releases/nightly/el8/x86_64/foreman-release.rpm -y
# dnf module enable foreman:el8 -y
# dnf install foreman-gce -y
# dnf install http://koji.katello.org/kojifiles/work/tasks/8616/538616/rubygem-foreman_google-0.0.2-2.fm3_5.el8.noarch.rpm
Last metadata expiration check: 0:02:06 ago on Fri Nov  4 15:53:14 2022.
rubygem-foreman_google-0.0.2-2.fm3_5.el8.noarch.rpm                                                                            2.4 MB/s | 1.9 MB     00:00    
Dependencies resolved.
===============================================================================================================================================================
 Package                                                  Architecture             Version                             Repository                         Size
===============================================================================================================================================================
Installing:
 rubygem-foreman_google                                   noarch                   0.0.2-2.fm3_5.el8                   @commandline                      1.9 M
     replacing  foreman-gce.noarch 3.5.0-0.16.develop.20221103184054git36f2892.el8
Installing dependencies:
 rubygem-gapic-common                                     noarch                   0.12.0-1.el8                        foreman-plugins                    37 k
 rubygem-google-cloud-common                              noarch                   1.1.0-1.el8                         foreman-plugins                   9.7 k
 rubygem-google-cloud-compute                             noarch                   0.5.0-1.el8                         foreman-plugins                    20 k
 rubygem-google-cloud-compute-v1                          noarch                   1.7.1-1.el8                         foreman-plugins                   346 k
 rubygem-google-cloud-core                                noarch                   1.6.0-1.el8                         foreman-plugins                    22 k
 rubygem-google-cloud-errors                              noarch                   1.3.0-1.el8                         foreman-plugins                    17 k
 rubygem-google-protobuf                                  x86_64                   3.21.6-1.el8                        foreman-plugins                   114 k
 rubygem-googleapis-common-protos                         noarch                   1.3.12-1.el8                        foreman-plugins                    11 k
 rubygem-googleapis-common-protos-types                   noarch                   1.4.0-1.el8                         foreman-plugins                    25 k
 rubygem-grpc                                             x86_64                   1.49.1-1.el8                        foreman-plugins                    16 M

Transaction Summary
===============================================================================================================================================================
Install  11 Packages

Total size: 18 M
Total download size: 16 M
Is this ok [y/N]: ^COperation aborted.
```

I'm going to merge this.

**Pull request merged**
