### PR TITLE
Update rubygem-foreman_maintain to 0.6.9

### PR DESCRIPTION
**Pull request by upadhyeammit**

### CODE REVIEW

**Comment by evgeni** [comment]
@tbrisker did you tag this in koji? That's a stable build that won't build otherwise.

**Comment by tbrisker** [comment]
@evgeni I did not, i thought we fixed auto-tagging in stable branches?

**Comment by evgeni** [comment]
No. We fixed building. But this package won't build as the same NVR already exists in koji.

**Comment by evgeni** [comment]
Tagged now.

**Pull request merged**
