### PR TITLE
Updated foreman_discovery to 7.0.0

### PR DESCRIPTION
**Pull request by lzap**
Only nightlies.

```
Compared versions: ["6.0.0", "7.0.0"]
  DIFFERENT licenses:
    6.0.0: ["GPL-3"]
    7.0.0: ["GPL-3.0"]
  DIFFERENT files:
    6.0.0->7.0.0:
      * Added:
            app/controllers/concerns/foreman/controller/parameters/
            app/models/nic/
            app/controllers/concerns/foreman/controller/parameters/discovered_host.rb
              (!) Unexpected permissions: 100664
            app/controllers/concerns/foreman/controller/parameters/discovery_rule.rb
              (!) Unexpected permissions: 100664
            app/models/nic/managed_extensions.rb
              (!) Unexpected permissions: 100664
            app/views/discovered_hosts/_discovered_host_modal.html.erb
              (!) Unexpected permissions: 100664
            test/unit/fact_value_extensions_test.rb
              (!) Unexpected permissions: 100664
  DIFFERENT test_files:
    6.0.0->7.0.0:
      * Added:
            test/unit/fact_value_extensions_test.rb
              (!) Unexpected permissions: 100664
```

### CODE REVIEW

**Comment by lzap** [comment]
Do I file for Debian as well when I only need nightly? I vaguely remember nightly builds are different there.

**Comment by mmoll** [comment]
@lzap not for plugins, just update it against `deb/develop` and tick only the "nightly" box :ballot_box_with_check:

**Comment by domcleal** [comment]
Thanks @lzap, merged. Debian's exactly the same, file a pull request.

**Comment by lzap** [comment]
Thanks! https://github.com/theforeman/foreman-packaging/pull/1295

**Pull request merged**
