### PR TITLE
Fixes #29677 - Properly stop dynflowd on upgrade

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
will update in rpm/develop once i know this works.  mostly abusing this to get a test build

**Comment by jlsherrill** [comment]
testing this, this seemd to resolve the issue.  The dynflow_executor is now no longer running after the yum update step of the upgrade.

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
@tbrisker This will require a release of the Foreman RPMs. Are y'all OK with doing a build sign and push without a full release process?

**Comment by tbrisker** [comment]
Fine by me if we can get away with cutting the process :)

**Comment by ekohl** [comment]
@jlsherrill it would be good to at least have a Redmine issue for this. Also a post to https://community.theforeman.org/c/release-announcements/8 would be good IMHO.

**Comment by jlsherrill** [comment]
Opened https://projects.theforeman.org/issues/29677

**Comment by tbrisker** [comment]
did this also get fixed in develop and rpm/2.1?

**Comment by tbrisker** [comment]
ignore me, it is

**Pull request merged**
