### PR TITLE
Bump hammer-cli-katello to 1.11.1

### PR DESCRIPTION
**Pull request by ianballou**
I removed the pre-release bits, I don't think our  hammer gems should have "pre" in them if they're for the actual release?

### CODE REVIEW

**Comment by ekohl** [comment]
Could you rebase, because I think repoclosure was fixed already.

**Comment by zjhuntin** [comment]
[test rpm-copr]

**Comment by ianballou** [comment]
> Could you rebase, because I think repoclosure was fixed already.

Looking like I'm up-to-date with upstream.

**Comment by zjhuntin** [comment]
[test rpm-copr]

**Review by zjhuntin — APPROVED** [review]

**Pull request merged**
