### PR TITLE
make acd build on el7 and el8

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
@ekohl because I fixed the failure and then realized it only built for el8, so it won't retry

**Comment by evgeni** [comment]
we can ofcourse omit the bump and run a manual `obal release` for that one.

**Comment by pcreech** [comment]
It's probably sufficient to manually build it with obal and a specified releaser instead of version bumping.  Since it was my mistake that led to this, I don't mind being the one to obal release.

**Comment by pcreech** [comment]
eh, llooks like this brings in comps updates as well.  Just going ahead and merging

**Pull request merged**
