### PR TITLE
Update rubygem-foreman_scc_manager to 1.8.9 (Foreman 2.3)

### PR DESCRIPTION
**Pull request by nadjaheitmann**
(cherry picked from commit e84580c112cf9b472f7dc9b7ae4a2a2a69168ddf)

### CODE REVIEW

**Comment by evgeni** [comment]
2.3 currently contains a broken Katello in our buildroots, this will have to wait for the next Katello 3.18.x release.

**Comment by nadjaheitmann** [comment]
Which Katello is broken? 3.18.2?

**Comment by evgeni** [comment]
the one published is fine, the one in our internal repos (so "next 3.18.3") is broken right now.

**Comment by nadjaheitmann** [comment]
Thanks for clarifying.

**Comment by pcreech** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Review by evgeni — APPROVED** [review]

**Pull request merged**
