### PR TITLE
Update rubygem-foreman_scc_manager to 1.8.17 Foreman 2.5

### PR DESCRIPTION
**Pull request by nadjaheitmann**

### CODE REVIEW

**Comment by nadjaheitmann** [comment]
@pcreech Do you mind taking a look at this PR as well?

**Comment by pcreech** [comment]
[test rpm]

**Comment by pcreech** [comment]
[test rpm]

**Comment by pcreech** [comment]
Looks like we removed the 2.5 jobs as of today, so this would be nonpunishable even if we merge it at this point.  Is this still needed @nadjaheitmann ???

**Comment by nadjaheitmann** [comment]
Good timing! I guess, it will be fine if the package does not go into 2.5 if you removed the jobs, already.

**Comment by pcreech** [comment]
Cool, closing this PR out.

**Pull request closed without merging**
