### PR TITLE
build plugin ruby packages on el9

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
known broken:
- `rubygem-google-protobuf` (it builds, but `require 'google/protobuf'` hangs the Ruby process :shrug:)
- `rubygem-grpc` (`BuildRequires: rubygem-google-protobuf`)

**Comment by evgeni** [comment]
When releasing, I'll avoid all those google/gapic/grpc gems for now and then we'll see how it goes with them in a separate PR.

**Comment by evgeni** [comment]
loading of `google/protobuf` hangs in `pool.add_serialized_file(descriptor_data)` in `lib/google/protobuf/descriptor_pb.rb` and I have no friggin idea why (or how to debug that)

**Comment by ehelms** [comment]
Did you try newer versions of those google/gapi/grpc packages?

**Comment by evgeni** [comment]
> Did you try newer versions of those google/gapi/grpc packages?

Yes, they fail to build totally. But I found a way…

**Comment by evgeni** [comment]
this is now ready, repoclosure will be fixed once this is in and the net-ssh-* things are built

**Review by ehelms — APPROVED** [review]

**Pull request merged**
