### PR TITLE
feat: add ruby-foreman-rescue 1.0.0 plugin

### PR DESCRIPTION
**Pull request by marcdeop**
This PR adds ruby-foreman-rescue to the deb building process

### CODE REVIEW

**Comment by timogoebel** [comment]
@marcdeop: Thanks for the contribution. If this gets in, please do update the README of the plugin.

**Comment by marcdeop** [comment]
> @marcdeop: Thanks for the contribution. If this gets in, please do update the README of the plugin.

I will gladly do that submitting a PR upstream and maybe will find a way to update [this](https://projects.theforeman.org/projects/foreman/wiki/List_of_Plugins) as well.

**Comment by tbrisker** [comment]
[test packaging]

**Comment by ekohl** [comment]
It looks like our CI is confused by the username that submitted the PR and the repo differing.

**Comment by marcdeop** [comment]
The ci is trying to clone/pull from https://github.com/marcdeop/foreman-packaging.git but the repo is under my company namespace: https://github.com/erasys/foreman-packaging

**Comment by marcdeop** [comment]
Should I try to fix the CI or should I just move the fork to my namespace?

If the CI needs to be fixed, I would appreciate some guideance into where to look for the code responsable for it :-)

**Comment by ekohl** [comment]
The CI needs some major love. https://github.com/theforeman/foreman-infra/blob/master/puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/packaging_test_pull_request.yaml is the Jenkins Job Builder config for this job but it triggers other jobs. In this case https://github.com/theforeman/foreman-infra/blob/master/puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/jobs/packaging_build_deb_plugin.yaml. It uses https://github.com/theforeman/foreman-infra/blob/master/puppet/modules/jenkins_job_builder/files/theforeman.org/yaml/builders/build_deb_plugin.yaml as a builder.

The most relevant bit is https://github.com/theforeman/foreman-infra/blob/master/puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/packaging_test_pull_request_deb.sh which does the checkout. In particular:
https://github.com/theforeman/foreman-infra/blob/ed7e927bb68ec3b4785bbbbf1a1cf9787917fe01/puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/test/packaging_test_pull_request_deb.sh#L57-L62

ghprbPullAuthorLogin is probably not the right variable but I won't know what would be correct.

**Comment by ekohl** [comment]
Maybe the tl;dr is that opening a new PR from your own org is easier :)

**Comment by marcdeop** [comment]
I opened #3956 

I might submit a PR for "fixing" the CI.

**Pull request closed without merging**
