### PR TITLE
[rpm] Release 1.16.1

### PR DESCRIPTION
**Pull request by dLobatog**
For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [ ] 1.17
* [x] 1.16
* [ ] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by dLobatog** [comment]
Signatures have been uploaded at http://downloads.theforeman.org/

**Comment by ekohl** [comment]
[test packaging]

**Comment by dLobatog** [comment]
I think this is failing due to Fastly's CDN. If I ssh in yum.theforeman.org, I can clearly see http://downloads.theforeman.org/foreman/foreman-1.16.1.tar.bz2 

However the URL seems to be a 404 from my end, and from Jenkins end most likely too, as I see "10:29:49   url does not have expected file size (use --relaxed to bypass this check) http://downloads.theforeman.org/foreman-installer/foreman-installer-1.16.1.tar.bz2"

**Comment by ekohl** [comment]
I purged the cache entry
[test rpm]

**Comment by ekohl** [comment]
[test packaging]

**Comment by dLobatog** [comment]
[test rpm]
[test packaging]

**Comment by ekohl** [comment]
Are you sure you added the correct foreman tarball to annex? Locally I can't retrieve it either (and it's not a 404).

**Comment by dLobatog** [comment]
@ekohl Should be fine now, I forgot to add the `uglifierjs-webpack-plugin` to the foreman.spec

**Comment by dLobatog** [comment]
`uglifierjs-webpack-plugin` is not available in 1.16 yet even though the spec was tagged

**Comment by ekohl** [comment]
Just executed:

```
koji add-pkg --owner=kojiadm foreman-1.16-nonscl-rhel7 nodejs-uglifyjs-webpack-plugin
tito release koji-foreman
```

http://koji.katello.org/koji/taskinfo?taskID=93279

**Comment by ekohl** [comment]
Ok, should have tagged the build: `koji tag-build foreman-1.16-nonscl-rhel7 nodejs-uglifyjs-webpack-plugin-1.2.2-1.el7`: http://koji.katello.org/koji/buildinfo?buildID=25801 is now tagged
[test packaging]

**Comment by mmoll** [comment]
merged, gracias @dLobatog!

**Comment by dLobatog** [comment]
proxy - http://koji.katello.org/koji/taskinfo?taskID=93357
selinux - http://koji.katello.org/koji/taskinfo?taskID=93372
installer - http://koji.katello.org/koji/taskinfo?taskID=93371 
foreman - http://koji.katello.org/koji/taskinfo?taskID=93370

**Pull request merged**
