### PR TITLE
Update Katello GEM dependencies

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
this needs https://ci.theforeman.org/job/katello-master-source-release/ to pass :see_no_evil:

**Comment by evgeni** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by evgeni** [comment]
@ehelms you'll need a katello.gem with this commit: https://github.com/Katello/katello/commit/b236224c7de85bc0a5f0e88e1fe5da1d089c806f, doubt that Jenkins is done yet

**Comment by jlsherrill** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Pull request merged**
