### PR TITLE
Fixes #30040 - Update foreman-proxy dependencies

### PR DESCRIPTION
**Pull request by ekohl**
This uses the same scripted update mechanism as foreman, katello and other gem packages.

(cherry picked from commit accae9fd118249fc831d9c8c04e70f4a1a943314)

### CODE REVIEW

**Comment by ehelms** [comment]
It was.

**Comment by ekohl** [comment]
Yes, see the cherry pick commit. https://github.com/theforeman/foreman-packaging/pull/5483 was the PR itself.

**Comment by ekohl** [comment]
The bug was reported against 2.0 and I think the cherry pick is low risk. Should I also pick there?

**Comment by tbrisker** [comment]
@ekohl sounds good to me, though i'm guessing it won't propagate until we do another full 2.0 release cycle?

**Comment by ekohl** [comment]
Correct, unless we deem it important enough to do an async release. I think it's not needed though.

**Comment by tbrisker** [comment]
@ekohl makes sense, let's fix it so it gets in to 2.0.2 whenever it is released.

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman-packaging/pull/5503

**Pull request merged**
