### PR TITLE
Bump rubygem-foreman_rh_cloud to 3.0.17-1

### PR DESCRIPTION
**Pull request by laviro**
(cherry picked from commit 420a1cf72b5cb17e1b47709fec499c26c4b21b74)

### CODE REVIEW

**Review by evgeni — CHANGES_REQUESTED** [review]
need to backport the changes from #6335 once that's merged

**Comment by evgeni** [comment]
should not be picked without picking https://github.com/theforeman/foreman-packaging/pull/6345

**Comment by laviro** [comment]
update with the cherry-picks from develop

**Comment by laviro** [comment]
closing in favor of https://github.com/theforeman/foreman-packaging/pull/6392

**Pull request closed without merging**
