### PR TITLE
update foreman_salt to 8.0.3

### PR DESCRIPTION
**Pull request by mmoll**
this should be built into:

* [x] 1.15

### CODE REVIEW

**Comment by dLobatog** [comment]
[test]

**Comment by mmoll** [comment]
💚

**Comment by ekohl** [comment]
@dLobatog could you have another look?

**Comment by dLobatog** [comment]
f24 - http://koji.katello.org/koji/taskinfo?taskID=61074
el7 - http://koji.katello.org/koji/taskinfo?taskID=61075

**Pull request merged**
