### PR TITLE
Update rubygem-foreman_scc_manager to 1.5.1

### PR DESCRIPTION
**Pull request by m-bucher**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [X] 1.20
* [X] 1.19
* [ ] 1.18

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---
Bugfix release for SCC-Manager to work with Foreman 1.20

### CODE REVIEW

**Comment by tbrisker** [comment]
ok to test

**Comment by evgeni** [comment]
[test]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
@m-bucher can you open cherrypick PRs against the branches you want it for?

**Comment by evgeni** [comment]
build for nightly is at http://koji.katello.org/koji/taskinfo?taskID=162380

**Pull request merged**
