### PR TITLE
Add rubygem-typhoeus

### PR DESCRIPTION
**Pull request by jlsherrill**
a dependency for zest, an autogenerated pulp3 api gem

For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.21
* [ ] 1.20

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by jlsherrill** [comment]
depends on https://github.com/theforeman/foreman-packaging/pull/3502

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
FYI: we can handle runtime requirements in a single PR so you can submit those in 1. Makes it easier for everyone I think :)

**Comment by jlsherrill** [comment]
@ekohl ahh, i figured people would want smaller prs, will keep that in mind :)

**Comment by ekohl** [comment]
cc85c795845f976040d281cc3a18ee0a29febc88 added the same version so closing.

**Pull request closed without merging**
