### PR TITLE
Updated discovery hammer to 1.0.1

### PR DESCRIPTION
**Pull request by lzap**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly

---

### CODE REVIEW

**Comment by mmoll** [comment]
@lzap Is this also good for 1.22 / 1.23?

**Comment by mmoll** [comment]
[test packaging]

**Comment by lzap** [comment]
If you want it will work indeed. There was a bug in parameters which one of our major customer needed to be fixed.

**Comment by mmoll** [comment]
merged, díky @lzap!

**Pull request merged**
