### PR TITLE
New package ruby-server-sent-events (DEB)

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by lzap** [comment]
Thanks a bunch! I'd like to test the build, can I download the artifacts?

**Comment by ekohl** [comment]
https://stagingdeb.theforeman.org/ has it (and the instructions). You'll need to add `deb http://stagingdeb.theforeman.org/ buster evgeni-nightly` as a repo source (assuming you're on Debian Buster).

**Comment by lzap** [comment]
```
root@debian10:~# irb
irb(main):001:0> require "server_sent_events"
=> true
```

**Comment by lzap** [comment]
Thanks merging.

**Comment by evgeni** [comment]
build: https://ci.theforeman.org/job/packaging_build_deb_dependency/379/

**Pull request merged**
