### PR TITLE
Fixes #21188 - Add rubygem-foreman_datacenter package

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
(fails because nightly foreman is broken)

**Comment by ekohl** [comment]
This is green now.

**Comment by ekohl** [comment]
@dLobatog I think the various dependencies weren't included in the older releases so I'd be fine with just nightly for now.

**Comment by mmoll** [comment]
I'm not sure if the current code of this plugin works with current develop.

**Comment by dgoetz** [comment]
I rebased the branch, bumped to newest plugin release 1.20.0 and tested successfully.
You can find it in my branch https://github.com/dgoetz/foreman-packaging/tree/rpm/datacenter.
@ekohl: Do you want to process or should I create a new pull request based on my branch?

**Comment by ekohl** [comment]
Looking at what I have here it looks like it should be regenerated with the current template anyway. Given the state of the plugin I've been reluctant to put in more effort. It's developed against released versions instead of nightly. This is not how we work in packaging.

**Comment by ehelms** [comment]
Any updates on this PR? Should I close it?

**Comment by dgoetz** [comment]
From my side I am fine with closing. I have no actual need for packages at the moment (read no costumer using it) and with the reason @ekohl has given I do not promote it (so likely also no future customer). If something changes, I will open a new PR.

**Pull request closed without merging**
