### PR TITLE
Update pulp 3.4 bindings and katello for them

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
should i update rubygem-katello in its own pr?

**Comment by pcreech** [comment]
@jlsherrill Yes, please :D

**Comment by jlsherrill** [comment]
repoclosure will fail as https://github.com/theforeman/foreman-packaging/pull/5505 is co-dependent

**Comment by jlsherrill** [comment]
hah, maybe it won't

**Pull request merged**
