### PR TITLE
Release rubygem-qpid_messaging 1.38

### PR DESCRIPTION
**Pull request by ehelms**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.19
* [ ] 1.18
* [ ] 1.17

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ehelms** [comment]
To match EPEL and make Rails 5.2 rebuild easier

**Comment by ekohl** [comment]
Is this a result of our build root?
`DEBUG util.py:491:  Error: No Package found for qpid-cpp-client-devel = 1.38.0`

**Comment by ehelms** [comment]
Yea -- I was building with mock which has latest EPEL. So I either need to update EPEL on Koji or hold off on this change now that I think about it.

**Comment by ekohl** [comment]
I don't mind updating EPEL on Koji. It doesn't have a support policy on older releases so IMHO we can assume newer versions.

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Pull request merged**
