### PR TITLE
Update rubygem-foreman_openscap to 0.3.2

### PR DESCRIPTION
**Pull request by isimluk**
Minor bugfix release.

### CODE REVIEW

**Comment by domcleal** [comment]
[test]

**Comment by domcleal** [comment]
It seems we have a FTBFS due to some changes to asset precompilation, which happened async to this package being added.  I'm testing a fix for them now, will re-test once merged.

**Comment by isimluk** [comment]
Thank You!

**Comment by domcleal** [comment]
[test]

**Comment by domcleal** [comment]
Thanks @isimluk, sorry for the delay.  Will build it now.

**Pull request merged**
