### PR TITLE
Update rubygem-fog-proxmox to 0.11.1

### PR DESCRIPTION
**Pull request by tristanrobert**
* Nightly

### CODE REVIEW

**Comment by tristanrobert** [comment]
There's a missing foreman dep: `package: tfm-rubygem-hammer_cli_foreman_tasks-0.0.13-1.fm1_20.el7.noarch from el7-foreman-plugins-nightly
 unresolved deps:
 tfm-rubygem(hammer_cli_foreman) < 0:1.0.0`

**Comment by dgoetz** [comment]
There was a new release of the hammer_cli_foreman (version 2.0.0) which is now over the boundary  `tfm-rubygem(hammer_cli_foreman) < 0:1.0.0`.

**Comment by tristanrobert** [comment]
So these packages dependencies need to be updated:

`tfm-rubygem-hammer_cli_foreman_openscap`
`tfm-rubygem-hammer_cli_foreman_tasks`
`tfm-rubygem-hammer_cli_foreman_remote_execution`

**Comment by ekohl** [comment]
This is unrelated to your change, but I've added a post here:
https://community.theforeman.org/t/hammer-version-was-changed-to-2-0-0-please-change-the-gemspec-for-hammer-plugins/17297/2

**Comment by tristanrobert** [comment]
Thank you @ekohl

**Comment by ehelms** [comment]
[test rpm]

**Pull request merged**
