### PR TITLE
Add pulp gem deps to katello

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
requires https://github.com/theforeman/foreman-packaging/pull/3762

**Comment by jlsherrill** [comment]
[test katello]

**Comment by jlsherrill** [comment]
[test rpm]

**Comment by jlsherrill** [comment]
[test rpm]

**Comment by jlsherrill** [comment]
[test rpm]

**Comment by jlsherrill** [comment]
[test rpm]

**Comment by jlsherrill** [comment]
The latest build was green, i'm not sure why its keeping around the old red builds

**Comment by evgeni** [comment]
@jlsherrill yeah, it's not smart enough to throw them away. (it's a non-issue for non-nightly packages, where the version is always the same on rebuild, but here we have the hash in the version and you see red).

**Pull request merged**
