### PR TITLE
Update foreman-tasks to 0.9.6 [deb/1.15]

### PR DESCRIPTION
**Pull request by iNecas**
For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [ ] 1.16
* [x] 1.15
* [ ] 1.14

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by iNecas** [comment]
Please note that we're releasing 0.10.x for nightly/1.16 here https://github.com/theforeman/foreman-packaging/pull/1823, this is a backport of compatible changes to 1.15

**Comment by mmoll** [comment]
```
21:17:15 rake aborted!
21:17:15 NameError: uninitialized constant Dynflow
21:17:15 /usr/share/foreman/vendor/ruby/2.1.0/gems/foreman-tasks-core-0.1.7/lib/foreman_tasks_core/ticker.rb:2:in `<module:ForemanTasksCore>'
21:17:15 /usr/share/foreman/vendor/ruby/2.1.0/gems/foreman-tasks-core-0.1.7/lib/foreman_tasks_core/ticker.rb:1:in `<top (required)>'
21:17:15 /usr/share/foreman/vendor/ruby/2.1.0/gems/foreman-tasks-core-0.1.7/lib/foreman_tasks_core.rb:6:in `<top (required)>'
21:17:15 /usr/share/foreman/vendor/ruby/2.1.0/gems/foreman-tasks-0.9.6/lib/foreman_tasks/engine.rb:1:in `<top (required)>'
21:17:15 /usr/share/foreman/vendor/ruby/2.1.0/gems/foreman-tasks-0.9.6/lib/foreman_tasks.rb:3:in `<top (required)>'
21:17:15 /usr/share/foreman/vendor/ruby/2.1.0/gems/foreman-tasks-0.9.6/lib/foreman-tasks.rb:1:in `<top (required)>'
21:17:15 /usr/share/foreman/config/application.rb:36:in `<top (required)>'
21:17:15 /usr/share/foreman/Rakefile:1:in `require'
21:17:15 /usr/share/foreman/Rakefile:1:in `<top (required)>'
21:17:15 /usr/share/foreman/vendor/ruby/2.1.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
```
Is this 100% 1.15 compatible?

**Comment by iNecas** [comment]
It's supposed to be, the problem was I had in my local `Gemfile.local.rb` `gem :dynflow` which caused
the dynflow to be required, so I haven't hit the issues. Addressing http://projects.theforeman.org/issues/21067 now

**Comment by iNecas** [comment]
Updated core to 0.1.8 to fix http://projects.theforeman.org/issues/21067

**Comment by mmoll** [comment]
merged, díky @iNecas!

**Pull request merged**
