### PR TITLE
Update foreman_ansible to 6.0.0

### PR DESCRIPTION
**Pull request by adamruzicka**
CPs:
- [ ] 2.2

### CODE REVIEW

**Review by tbrisker — CHANGES_REQUESTED** [review]
I think this also needs an update to `plugins/ruby-foreman-ansible/debian/changelog`

**Comment by adamruzicka** [comment]
Done

**Review by evgeni — APPROVED** [review]

**Comment by evgeni** [comment]
and that fails on

```
10:11:52  pbuilder-satisfydepends-dummy : Depends: ruby-foreman-deface (< 2.0.0) which is a virtual package and is not provided by any available package
10:11:52 
10:11:52                                  Depends: ruby-foreman-remote-execution (>= 4.0.0-1) which is a virtual package and is not provided by any available package
```

**Comment by evgeni** [comment]
fixed and built

**Pull request merged**
