### PR TITLE
Release katello-host-tools 3.5.3

### PR DESCRIPTION
**Pull request by jturel**

### CODE REVIEW

**Comment by jturel** [comment]
@evgeni what should we do w.r.t the repoclosure?

```
[2020-02-17T21:51:21.211Z]     package: katello-agent-3.5.3-1.el8.noarch from downloaded_rpms

[2020-02-17T21:51:21.211Z]       unresolved deps:

[2020-02-17T21:51:21.211Z]          python3-gofer-proton

[2020-02-17T21:51:21.211Z]          gofer >= 0:2.12.1

[2020-02-17T21:51:21.211Z]     package: katello-host-tools-tracer-3.5.3-1.el8.noarch from downloaded_rpms

[2020-02-17T21:51:21.211Z]       unresolved deps:

[2020-02-17T21:51:21.211Z]          python3-tracer

[2020-02-17T21:51:21.211Z]   stdout_lines: <omitted>

```

**Comment by evgeni** [comment]
@jturel el8 client is missing a few deps. I am fixing that, but slowly :/

tracer was added in #4747, so now it's  only gofer (looking at @pcreech) that's left

on the other hand, do we even want k-agent on el8?

**Comment by jturel** [comment]
> on the other hand, do we even want k-agent on el8?

Hmm, right. Maybe we can forget about it upstream to encourage folks to migrate to REX. I wouldn't mind that.

**Comment by evgeni** [comment]
I'd leave the decision to you (or katello as a group), but I talked with Patrick today and we decided that we can move gofer to f-packaging and build it here for el8 if katello needs it. So I'd tackle that early next week and worst case we can still kill it later ;)

**Comment by evgeni** [comment]
@jturel I realized that building gofer would take more than just that one RPM, so I am waiting on your decision here :)

**Comment by jturel** [comment]
@evgeni since we haven't had it this far along and I haven't heard any requests for katello-agent on el8 we should forego building it. We're removing support for it in 2 releases so we should not be encouraging adoption of katello-agent either.

What changes do I need to make here to get repoclosure passing?

**Comment by evgeni** [comment]
in https://github.com/theforeman/foreman-packaging/blob/f7fc3a3086d466e0fc8877948d618f647907d001/packages/client/katello-host-tools/katello-host-tools.spec#L9 we need something that limits to rhel<8, maybe:
```
%global build_agent (0%{?suse_version} == 0) && ((0%{?fedora} > 28) || (0%{?rhel} > 0 && 0%{?rhel} <= 7))
```
and this line needs to be removed: https://github.com/theforeman/foreman-packaging/blob/f7fc3a3086d466e0fc8877948d618f647907d001/comps/comps-foreman-client-el8.xml#L15

**Comment by jturel** [comment]
@evgeni got it ;)

**Comment by evgeni** [comment]
@jturel will you also make the CP for rpm/2.0 please?

**Pull request merged**
