### PR TITLE
Update rubygem-foreman_openscap to 0.11.0

### PR DESCRIPTION
**Pull request by ehelms**
(cherry picked from commit c93730f5898418e36782afcd7c975d43020733f9)

For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [x] 1.20
* [ ] 1.19
* [ ] 1.18

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ehelms** [comment]
[test rpm]

**Comment by komidore64** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm]

**Comment by ares** [comment]
@ehelms what's the status here?

**Comment by evgeni** [comment]
obsoleted by https://github.com/theforeman/foreman-packaging/pull/3192

**Pull request closed without merging**
