### PR TITLE
Bump rubygem-foreman_rh_cloud to 2.0.5-1

### PR DESCRIPTION
**Pull request by ShimShtein**

### CODE REVIEW

**Comment by ShimShtein** [comment]
Waits for https://github.com/theforeman/foreman-packaging/pull/4977

**Comment by evgeni** [comment]
[test rpm]

**Comment by ShimShtein** [comment]
[test]

**Comment by ShimShtein** [comment]
[test koji]

**Comment by tbrisker** [comment]
[test rpm]

**Comment by evgeni** [comment]
@ehelms looks like I fucked up the macro?

**Comment by ehelms** [comment]
@evgeni Couldn't have said it better myself

**Comment by evgeni** [comment]
@ehelms 😻
I don't see how, tho. Any idea?

**Comment by ehelms** [comment]
Something with how its being rendered. Macro voo-doo. All I eve rcan do is update-test cycle through mock.

**Comment by evgeni** [comment]
If you have some spare cycles, please. Otherwise I'll try to understand that myself tomorrow

**Comment by ehelms** [comment]
Gonna have a look

**Comment by ehelms** [comment]
This fix worked building this PR locally in mock: https://github.com/theforeman/foreman-packaging/pull/4982

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Pull request merged**
