### PR TITLE
hammer_cli_foreman_docker 0.0.4 [deb]

### PR DESCRIPTION
**Pull request by daviddavis**

### CODE REVIEW

**Comment by mmoll** [comment]
[test] again

**Comment by mmoll** [comment]
working fine for me... should this also go into 1.11?

**Comment by daviddavis** [comment]
If we want docker registry cli functionality then yes. Otherwise, I don't think it's needed.

**Comment by mmoll** [comment]
allright, if it's needed later, it can get cherry-picked anytime...
merged into develop and building now, thanks @daviddavis!

**Pull request merged**
