### PR TITLE
Update puppetdb_foreman to 3.1.2 [deb]

### PR DESCRIPTION
**Pull request by timogoebel**
Please build for

* [x] Nightly
* [x] 1.16
* [x] 1.15
* [x] 1.14

### CODE REVIEW

**Comment by mmoll** [comment]
not working for me, setting this on hold for now

**Comment by timogoebel** [comment]
Will be investigated at https://github.com/theforeman/puppetdb_foreman/issues/44

**Comment by timogoebel** [comment]
@mmoll: Updated this as well.

**Comment by mmoll** [comment]
works fine 👍

**Comment by mmoll** [comment]
merged, danke @timogoebel!

**Pull request merged**
