### PR TITLE
Require ansible or ansible-core on EL8+

### PR DESCRIPTION
**Pull request by upadhyeammit**

### CODE REVIEW

**Comment by upadhyeammit** [comment]
For `sp-ansible: Require ansible or ansible-core on EL8+` and `collection-foreman: Require ansible or ansible-core on EL8+` I have adjusted the versions as per existing versions of plugins in 3.1. If thats incorrect or should not be done then will change it.

**Comment by evgeni** [comment]
The problem with smart proxy Ansible is, that it's actually broken with Ansible 2.12 :(

**Comment by zjhuntin** [comment]
[test rpm]

**Comment by upadhyeammit** [comment]
As per the discussion with @evgeni we are skipping sp-ansible cherry pick here, once we sort out the issue of that with ansible 2.12 we will pick that for 3.1. I have removed the commit accordingly.

**Comment by evgeni** [comment]
```console
% koji tag-build foreman-plugins-3.1-el8 ansible-collection-theforeman-operations-0.3.0-2.el8 ansiblerole-foreman_scap_client-0.2.0-2.el8 ansiblerole-insights-client-1.7.1-2.el8 ansiblerole-satellite-receptor-installer-0.6.13-2.el8                                                  
Created task 486930
Created task 486931
Created task 486932
Created task 486933
Watching tasks (this may be safely interrupted)...
486930 tagBuild (noarch): free
486931 tagBuild (noarch): free
486932 tagBuild (noarch): free
486933 tagBuild (noarch): free
486930 tagBuild (noarch): free -> closed
  3 free  0 open  1 done  0 failed
486931 tagBuild (noarch): free -> closed
  2 free  0 open  2 done  0 failed
486932 tagBuild (noarch): free -> closed
  1 free  0 open  3 done  0 failed
486933 tagBuild (noarch): free -> closed
  0 free  0 open  4 done  0 failed

486930 tagBuild (noarch) completed successfully
486931 tagBuild (noarch) completed successfully
486932 tagBuild (noarch) completed successfully
486933 tagBuild (noarch) completed successfully

% koji tag-build foreman-plugins-3.1-nonscl-rhel7 ansible-collection-theforeman-operations-0.3.0-2.el7 ansiblerole-foreman_scap_client-0.2.0-2.el7 ansiblerole-insights-client-1.7.1-2.el7 ansiblerole-satellite-receptor-installer-0.6.13-2.el7
Created task 486936
Created task 486937
Created task 486938
Created task 486939
Watching tasks (this may be safely interrupted)...
486936 tagBuild (noarch): free
486937 tagBuild (noarch): free
486938 tagBuild (noarch): free
486939 tagBuild (noarch): free
486936 tagBuild (noarch): free -> closed
  3 free  0 open  1 done  0 failed
486937 tagBuild (noarch): free -> closed
  2 free  0 open  2 done  0 failed
486938 tagBuild (noarch): free -> closed
  1 free  0 open  3 done  0 failed
486939 tagBuild (noarch): free -> closed
  0 free  0 open  4 done  0 failed

486936 tagBuild (noarch) completed successfully
486937 tagBuild (noarch) completed successfully
486938 tagBuild (noarch) completed successfully
486939 tagBuild (noarch) completed successfully
```

ansible-collection-theforeman-foreman will be built

**Pull request merged**
