### PR TITLE
Update rubygem-foreman_maintain to 0.7.5

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Review by evgeni — APPROVED** [review]

**Comment by evgeni** [comment]
@jlsherrill shall this also go to 2.4?

**Comment by jlsherrill** [comment]
@evgeni yeah, it probably should, let me open a pr for that

**Pull request merged**
