### PR TITLE
Update Rails stack to 6.0.4.7

### PR DESCRIPTION
**Pull request by ehelms**
Catches latest bug releases and at least one CVE.

### CODE REVIEW

**Comment by evgeni** [comment]
We explicitly pin to `~> 6.0.3.1` in the gemfile:
https://github.com/theforeman/foreman/blob/7a157e0156db8ff527dafe84cf78f5bc9dae2324/Gemfile#L10

So this should not work?

**Comment by ehelms** [comment]
> We explicitly pin to `~> 6.0.3.1` in the gemfile: https://github.com/theforeman/foreman/blob/7a157e0156db8ff527dafe84cf78f5bc9dae2324/Gemfile#L10
> 
> So this should not work?

*This* will work. But Foreman won't. :fireworks:

**Comment by ehelms** [comment]
Foreman PR: https://github.com/theforeman/foreman/pull/9157

**Comment by ehelms** [comment]
Given that `bundler_ext` is designed to ignore version constraints in Gemfile, I think we can safely merge this change and then merge https://github.com/theforeman/foreman/pull/9157 to produce the least amount of potential breakage time?

**Comment by evgeni** [comment]
Nope:
https://github.com/theforeman/foreman-packaging/blob/25d14bace424811f2d4e3ffec95214efd5de0889/packages/foreman/foreman/foreman.spec#L63

**Comment by ehelms** [comment]
> Nope:
> 
> https://github.com/theforeman/foreman-packaging/blob/25d14bace424811f2d4e3ffec95214efd5de0889/packages/foreman/foreman/foreman.spec#L63

Touche. There are times where bounded dependencies are nice, and times when they are really annoying.

**Review by evgeni — APPROVED** [review]

**Comment by evgeni** [comment]
https://github.com/theforeman/foreman-packaging/pull/7738

**Pull request merged**
