### PR TITLE
Updated katello gem dependencies

### PR DESCRIPTION
**Pull request by ekohl**
This used the built gem with gem2rpm to generate the requirements. By automating the conversion we can easier make sure both are in sync.

### CODE REVIEW

**Comment by ekohl** [comment]
Depends on https://github.com/theforeman/foreman-packaging/pull/3847

Generated by [fm-packaging-update-deps](https://github.com/ekohl/theforeman-plumbing/blob/master/fm-packaging-update-deps). Will need https://github.com/Katello/katello/pull/8149 to correctly build the gem from any directory.

**Comment by jlsherrill** [comment]
[test rpm]

**Comment by ekohl** [comment]
Not sure why this fails:
```
+ /usr/bin/tfm-rake 'plugin:assets:precompile[katello]' RAILS_ENV=production --trace
Gem loading error: Could not find 'foreman-tasks' (>= 0.14.1, ~> 0.13) among 121 total gem(s)
```

**Comment by ekohl** [comment]
Oh wait, I see - it's the missing build requires. I'll need to look at my script to see why it doesn't generate them.

**Comment by ekohl** [comment]
The issue was that I was building the gem from a different directory. While it does produce a gem, it doesn't include all files. That tripped up the gem2rpm template which detects whether a plugin has assets. If it doesn't, it doesn't add build dependencies.

**Comment by ekohl** [comment]
:green_heart: now

**Pull request merged**
