### PR TITLE
Update katello to 4.3.0

### PR DESCRIPTION
**Pull request by Odilhao**

### CODE REVIEW

**Review by chris1984 — APPROVED** [review]

**Comment by Odilhao** [comment]
[test rpm]

**Comment by Odilhao** [comment]
[test rpm]

**Comment by Odilhao** [comment]
[test rpm]

**Comment by Odilhao** [comment]
[test rpm]

**Comment by Odilhao** [comment]
[test rpm]

**Review by evgeni — APPROVED** [review]

**Pull request merged**
