### PR TITLE
Update hammer_cli_foreman_discovery to 0.0.3

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Comment by domcleal** [comment]
Which release(s) should this go into?  1.11+ has Discovery 5.0.2, 1.10 has 4.1.2, and both currently have this Hammer plugin version 0.0.2.

**Comment by mmoll** [comment]
Will there be a DEB PR, too? Otherwise I can open one. :cake:

**Comment by orrabin** [comment]
@mmoll I'm trying to create one :)

@domcleal not 1.10. It can be in 1.11 or even just develop and wait for 1.12.

**Comment by domcleal** [comment]
Thanks @orrabin, merged and building now.  I'll retag it to 1.11.

**Pull request merged**
