### PR TITLE
update smart_proxy_dns_powerdns to 0.2.0

### PR DESCRIPTION
**Pull request by mmoll**
Also for 1.11, please.
@ekohl, please have a look

### CODE REVIEW

**Comment by ekohl** [comment]
It looks good. I do see that ruby-pg is only in jessie and later so we may need to backport it for wheezy. Same goes for ubuntu which only has it in wily.

**Comment by mmoll** [comment]
Per https://packages.debian.org/search?keywords=ruby-pg and http://packages.ubuntu.com/search?keywords=ruby-pg it's there in all our supported distros?

**Comment by ekohl** [comment]
Oh, I guess I didn't search right. :+1:

**Comment by domcleal** [comment]
Merged, thanks @mmoll and as 086f2bf on deb/1.11.

Building at http://ci.theforeman.org/job/packaging_build_deb_proxy_plugin/150/ and http://ci.theforeman.org/job/packaging_build_deb_proxy_plugin/151/.

**Pull request merged**
