### PR TITLE
Update Hammer-Cli-Katello to 0.12.0

### PR DESCRIPTION
**Pull request by zjhuntin**
For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [x] 1.17
* [ ] 1.16
* [ ] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by zjhuntin** [comment]
[test]

**Comment by ekohl** [comment]
Needs a rebase now.

**Comment by ekohl** [comment]
Could you remove the old gem and look into why the build is failing?

**Comment by akofink** [comment]
I thought we were using 0.11.5.1 for 3.6?

**Comment by ehelms** [comment]
@zjhuntin Do we need this anymore after IRC discussions?

**Pull request closed without merging**
