### PR TITLE
Fixes #11229 (part 3): removed puppet classes cache directory creation

### PR DESCRIPTION
**Pull request by witlessbird**

### CODE REVIEW

**Comment by witlessbird** [comment]
replaces https://github.com/theforeman/foreman-packaging/pull/721

**Comment by domcleal** [comment]
Oh, I think it needs `deb/develop-` as a prefix, sorry.

**Comment by witlessbird** [comment]
ok, I'll try that.

**Comment by witlessbird** [comment]
closing in favour of https://github.com/theforeman/foreman-packaging/pull/728

**Pull request closed without merging**
