### PR TITLE
depend on ansible-core

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
I think it should be removed from `smart_proxy_ansible`. AFAIK nothing in that repo refers to it.

**Comment by evgeni** [comment]
https://github.com/theforeman/smart_proxy_ansible/blob/9fe3018710216f99c0ef6aea85cb7c05772cbe76/lib/smart_proxy_ansible/plugin.rb#L16-L17

And without -core being installed, I can't do run ansible on the proxy.

**Comment by evgeni** [comment]
Oh and RPM does the same: https://github.com/theforeman/foreman-packaging/blob/rpm/develop/packages/plugins/rubygem-smart_proxy_ansible/rubygem-smart_proxy_ansible.spec#L37

Not saying that's the perfect deployment strategy, but it at least works.

**Comment by evgeni** [comment]
Or do you mean `inventory.sh`?

**Comment by ekohl** [comment]
Yes, "it" indeed referred to `inventory.sh`. So rather than removing it in packaging, let's remove it from the source.

**Comment by evgeni** [comment]
I don't disagree, but this route is quicker to get working foreman_ansible on Debian in the meantime :)

**Comment by evgeni** [comment]
(https://github.com/theforeman/smart_proxy_ansible/pull/27 drops it from the gem)

**Review by ekohl — APPROVED** [review]
I'm ok with a workaround.

**Pull request merged**
