### PR TITLE
Update foreman_ansible to 5.1.3

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Review by tbrisker — CHANGES_REQUESTED** [review]
You need to also update `plugins/ruby-foreman-ansible/debian/gem.list` and `plugins/ruby-foreman-ansible/debian/changelog`

**Comment by adamruzicka** [comment]
Uncommited changes strike again

**Comment by evgeni** [comment]
[test packaging]

**Comment by evgeni** [comment]
[test packaging]

**Comment by evgeni** [comment]
[test packaging]

**Review by evgeni — APPROVED** [review]

**Pull request merged**
