### PR TITLE
Copy gitconfig into build container

### PR DESCRIPTION
**Pull request by ehelms**
This makes running update commands inside the container work.

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
This doesn't handle `~/.config/git/config`. Would this also work if the file doesn't exist?

**Comment by ehelms** [comment]
> This doesn't handle `~/.config/git/config`. Would this also work if the file doesn't exist?

Are you asking if we could use that path instead? or also mount it?

**Comment by ekohl** [comment]
Mostly wondering what happens if you attempt to mount a location that doesn't exist

**Comment by ehelms** [comment]
> Mostly wondering what happens if you attempt to mount a location that doesn't exist

It will yell at you:

```
Error: statfs /home/ehelms/.config/git/config: no such file or directory
```

**Pull request closed without merging**
