### PR TITLE
hammer_cli_katello 0.19.0

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
@ekohl I've pushed another commit, updating hammer_cli_foreman deps, please re-ack :)

**Comment by evgeni** [comment]
@ekohl I didn't want to introduce to many changes here, most should be in #3999 :)

**Comment by ekohl** [comment]
Fair enough, which is why I approved it :)

**Comment by evgeni** [comment]
repoclosure failures are expected because the 3.13 repo does not exist yet

**Comment by evgeni** [comment]
http://koji.katello.org/koji/taskinfo?taskID=218559

**Pull request merged**
