### PR TITLE
Updated rubygem-newt to 0.9.6

### PR DESCRIPTION
**Pull request by lzap**
```
Submitting build with: koji -c ~/.koji/katello-config build --nowait --scratch foreman-plugins-nightly-nonscl-rhel6 /tmp/tito/rubygem-newt-0.9.6-1.git.65.db11407.el6.src.rpm
Uploading srpm: /tmp/tito/rubygem-newt-0.9.6-1.git.65.db11407.el6.src.rpm
[                                    ]  00% 00:00:00     0.00 B        - B/sec
[====================================] 100% 00:00:00  15.10 KiB  21.43 KiB/sec
Created task: 322598
Task info: http://koji.katello.org/koji/taskinfo?taskID=322598

Wrote: /tmp/tito/rubygem-newt-0.9.6-1.git.65.db11407.git.65.db11407.el7.src.rpm



Submitting build with: koji -c ~/.koji/katello-config build --nowait --scratch foreman-plugins-nightly-nonscl-rhel7 /tmp/tito/rubygem-newt-0.9.6-1.git.65.db11407.git.65.db11407.el7.src.rpm
Uploading srpm: /tmp/tito/rubygem-newt-0.9.6-1.git.65.db11407.git.65.db11407.el7.src.rpm
[                                    ]  00% 00:00:00     0.00 B        - B/sec
[====================================] 100% 00:00:00  15.12 KiB  20.79 KiB/sec
Created task: 322600
Task info: http://koji.katello.org/koji/taskinfo?taskID=322600

Wrote: /tmp/tito/rubygem-newt-0.9.6-1.git.65.db11407.git.65.db11407.git.65.db11407.fc19.src.rpm



Submitting build with: koji -c ~/.koji/katello-config build --nowait --scratch foreman-plugins-nightly-fedora19 /tmp/tito/rubygem-newt-0.9.6-1.git.65.db11407.git.65.db11407.git.65.db11407.fc19.src.rpm
Uploading srpm: /tmp/tito/rubygem-newt-0.9.6-1.git.65.db11407.git.65.db11407.git.65.db11407.fc19.src.rpm
[                                    ]  00% 00:00:00     0.00 B        - B/sec
[====================================] 100% 00:00:00  15.13 KiB  19.51 KiB/sec
Created task: 322601
Task info: http://koji.katello.org/koji/taskinfo?taskID=322601
```

### CODE REVIEW

**Comment by domcleal** [comment]
The source file appears to be incorrect.

**Comment by lzap** [comment]
Submitting build with: koji -c ~/.koji/katello-config build --nowait --scratch foreman-plugins-nightly-nonscl-rhel6 /tmp/tito/rubygem-newt-0.9.6-1.git.65.6a3adbf.el6.src.rpm
Uploading srpm: /tmp/tito/rubygem-newt-0.9.6-1.git.65.6a3adbf.el6.src.rpm
[                                    ]  00% 00:00:00     0.00 B        - B/sec
[====================================] 100% 00:00:00  15.10 KiB  21.47 KiB/sec
Created task: 322604
Task info: http://koji.katello.org/koji/taskinfo?taskID=322604

Wrote: /tmp/tito/rubygem-newt-0.9.6-1.git.65.6a3adbf.git.65.6a3adbf.el7.src.rpm



Submitting build with: koji -c ~/.koji/katello-config build --nowait --scratch foreman-plugins-nightly-nonscl-rhel7 /tmp/tito/rubygem-newt-0.9.6-1.git.65.6a3adbf.git.65.6a3adbf.el7.src.rpm
Uploading srpm: /tmp/tito/rubygem-newt-0.9.6-1.git.65.6a3adbf.git.65.6a3adbf.el7.src.rpm
[                                    ]  00% 00:00:00     0.00 B        - B/sec
[====================================] 100% 00:00:00  15.12 KiB  21.25 KiB/sec
Created task: 322605
Task info: http://koji.katello.org/koji/taskinfo?taskID=322605

Wrote: /tmp/tito/rubygem-newt-0.9.6-1.git.65.6a3adbf.git.65.6a3adbf.git.65.6a3adbf.fc19.src.rpm



Submitting build with: koji -c ~/.koji/katello-config build --nowait --scratch foreman-plugins-nightly-fedora19 /tmp/tito/rubygem-newt-0.9.6-1.git.65.6a3adbf.git.65.6a3adbf.git.65.6a3adbf.fc19.src.rpm
Uploading srpm: /tmp/tito/rubygem-newt-0.9.6-1.git.65.6a3adbf.git.65.6a3adbf.git.65.6a3adbf.fc19.src.rpm
[                                    ]  00% 00:00:00     0.00 B        - B/sec
[====================================] 100% 00:00:00  15.13 KiB  20.56 KiB/sec
Created task: 322607
Task info: http://koji.katello.org/koji/taskinfo?taskID=322607

**Comment by lzap** [comment]
The file is not yet available on their mirrors: https://rubygems.org/downloads/newt-0.9.6.gem

**Comment by domcleal** [comment]
[test]

**Comment by lzap** [comment]
Oh the gem had different SHA, I built twice, so re-downloaded it from rubygems again assuming this would cause issues.

**Comment by domcleal** [comment]
Thanks, building.

**Pull request merged**
