### PR TITLE
Rebuild plugin packages for NodeJS SCL

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by pcreech** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'lodash/isEqual
```

**Comment by ehelms** [comment]
[test rpm]

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman-packaging/pull/4207 is open to bump rex to 2.0.0 but also includes NPM deps. This will break that so perhaps we should leave it out of this PR and take those two together?

**Comment by ehelms** [comment]
@ekohl I am inclined to more so merge this, ensure a working version of the plugin builds. And I'll comment updates on the 2.0.0 to bring it in right after.

**Pull request merged**
