### PR TITLE
Bump rpm rubygem-fog-proxmox version into 0.5.2

### PR DESCRIPTION
**Pull request by tristanrobert**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.19
* [ ] 1.18
* [ ] 1.17

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ekohl** [comment]
Could you rebase your patch against the current rpm/develop? There are a lot of unrelated changes in this PR.

**Comment by tristanrobert** [comment]
I agree with you. My fork tristanrobert/foreman-packaging is old indeed. My first PR are still opened. How could I rebase my fork with theforeman/foreman-packaging repo?

**Comment by ekohl** [comment]
If there is code you want to keep, `git rebase` can be used but in this case it's probably easier to use `git fetch upstream && git reset --hard upstream/rpm/develop && ./bump_rpm.sh packages/plugins/rubygem-fog-proxmox` (assuming `upstream` is the git remote with the upstream code) or start a new branch.

**Comment by tristanrobert** [comment]
I added remote theforeman/foreman-packaging in my repo and did what you suggested. tristanrobert/foreman/packaging/rpm/fog-proxmox is now up to date with theforeman/foreman-packaging/rpm/develop.

**Comment by ekohl** [comment]
Note you also need to push your changes. Because it's a non-fast forward change you need to use `git push --force`. With non-fast forward merges you can lose data but in this case we know it's correct.

**Comment by tristanrobert** [comment]
I think it would be easier to delete my fork repo and start a new fresh one.

**Comment by ekohl** [comment]
Deleting a fork shouldn't be needed. Creating a new branch is probably good enough.

**Comment by tristanrobert** [comment]
I have merged branches and resolve manually the conflicts.

**Comment by ekohl** [comment]
The thing is that we're not looking for a merge but a rebase. https://www.atlassian.com/git/tutorials/merging-vs-rebasing explains the conceptual difference

**Comment by tristanrobert** [comment]
Oops! So I need to start again from the beginning: theforeman/rpm/develop and I delete tristanrobert/rpm/fog-proxmox. It would be easier and faster to create a fresh new fork repo.

**Comment by ekohl** [comment]
There shouldn't be a need to delete repositories. That's why we have branches. Branches are full copies of a tree and you can easily start a new one. For example: `git checkout -b rpm/update-fog-proxmox theforeman/rpm/develop` should give you a fresh branch based on `theforeman/rpm/develop` (assuming `theforeman` is the remote for the upstream repository).

**Comment by tristanrobert** [comment]
You are absolutely right. I close this one and replace it by #3066

**Pull request closed without merging**
