### PR TITLE
Core projects: Release 1.15.2 [deb]

### PR DESCRIPTION
**Pull request by dLobatog**
Only meant for deb/1.15

### CODE REVIEW

**Comment by mmoll** [comment]
test failures are unrelated

**Comment by mmoll** [comment]
merged (not built, I guess you will do this with Jenkins), gracias @dLobatog!

**Comment by dLobatog** [comment]
@mmoll It needs to be tagged too I think

**Comment by mmoll** [comment]
I don't see any git tags in the this repo that seems connected to the DEB build...

**Pull request merged**
