### PR TITLE
Update foreman_remote_execution to 5.0.2

### PR DESCRIPTION
**Pull request by adamruzicka**
- Update foreman_remote_execution to 5.0.0
- Update foreman_remote_execution to 5.0.1
- Update foreman_remote_execution to 5.0.2

### CODE REVIEW

**Comment by Odilhao** [comment]
[test deb]

**Comment by adamruzicka** [comment]
I'm afraid I'll need a hint from someone who actually understands deb packaging

**Comment by Odilhao** [comment]
[test deb]

**Comment by adamruzicka** [comment]
[test deb]

**Comment by evgeni** [comment]
let's pretend this was a problem with the wrong sinatra in foreman-tasks, so:

[test deb]

**Comment by adamruzicka** [comment]
Pretending seems to work

**Review by evgeni — APPROVED** [review]

**Pull request merged**
