### PR TITLE
Update rubygem-hammer_cli_foreman to 0.17.1

### PR DESCRIPTION
**Pull request by akofink**
@mbacovsky for visibility

Signed-off-by: Andrew Kofink <akofink@redhat.com>

### CODE REVIEW

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
lookaside should be fixed by https://github.com/theforeman/foreman-packaging/pull/3942

**Comment by akofink** [comment]
Rebased

**Comment by evgeni** [comment]
Build: http://koji.katello.org/koji/taskinfo?taskID=214128

**Pull request merged**
