### PR TITLE
Fixes #7008: support config file migration for smart-proxy with dns providers

### PR DESCRIPTION
**Pull request by witlessbird**

### CODE REVIEW

**Comment by mmoll** [comment]
I think that's also needed for debs then

**Comment by domcleal** [comment]
I think this is going to get horrendously complicated when any more modules are migrated..

**Comment by witlessbird** [comment]
I was planning on working on something similar to AR migrations next. Unless you'd rather have it before dns providers...

**Comment by domcleal** [comment]
I think I would, if that's OK, as we're otherwise going to have to revert this, which could be difficult depending on which release it all lands in.

**Comment by lzap** [comment]
IMHO we should move this into external script (even the migrationscript itself) and keep this clean. Otherwise you need to maintain this twice: RPM and DEB.

**Comment by domcleal** [comment]
Closing, due to #10003 giving us a generic mechanism.  Thanks @witlessbird!

**Pull request closed without merging**
