### PR TITLE
Update clamp to 1.1.1 in Xenial (DEB)

### PR DESCRIPTION
**Pull request by mbacovsky**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.16
* [ ] 1.15
* [ ] 1.14

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by mbacovsky** [comment]
Can anyone give me some assistance with the failing tests please?

**Comment by mmoll** [comment]
@mbacovsky Which clamp version will be the minimum boundary? Ubunty/trusty is only supported for Foreman 1.15, while Debian/jessie is dropped from nightlies, but supported for 1.15 and 1.16. On The remaining supported distros we do use the upstream ruby-clamp packages (1.0.0 and 1.1.1 respectively).

**Comment by mbacovsky** [comment]
@mmoll, the minimal clamp version required for the upcoming hammer 0.12 is clamp >= 1.1.0. So this changes seems not necessary on the other hand the the release with upstream clamp 1.0.0 (Stretch?) will need update. Should I add it here?

**Comment by mmoll** [comment]
@mbacovsky In that case, I'd just take the `debian/` directory of Debian's recent ruby-clamp package (i.e. http://http.debian.net/debian/pool/main/r/ruby-clamp/ruby-clamp_1.1.1-1.debian.tar.xz) and use this for xenial.

**Comment by mbacovsky** [comment]
@mmoll, I've removed the original updates and added the Debian's package to Xenial.

**Comment by mmoll** [comment]
merged, díky @mbacovsky!

**Comment by mbacovsky** [comment]
@mmoll, já díky za pomoc! :beers:

**Pull request merged**
