### PR TITLE
Only require shim-ia32 bootloader on RHEL 8 or less

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
[test rpm-copr]

**Review by evgeni — APPROVED** [review]

**Comment by ekohl** [comment]
Why is this needed? We could build it with EL9 before

**Comment by ehelms** [comment]
For some reason an EL8 version of this package was put into Centos Stream 9 even though RHEL no longer boots on 32-bit UEFI.

**Review by evgeni — APPROVED** [review]

**Comment by evgeni** [comment]
> I also do not think anything requires and installs this package in Foreman ecosystem directly? Which means the requires probably haven't been put to the test.

Well, repoclosure catches things, but otherwise I agree

**Pull request merged**
