### PR TITLE
Bump foreman-tasks to 0.11.0

### PR DESCRIPTION
**Pull request by zjhuntin**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.16
* [ ] 1.15
* [ ] 1.14

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by akofink** [comment]
Waiting on https://github.com/theforeman/tfm-ror51-packaging/pull/39 and https://github.com/theforeman/tfm-ror51-packaging/pull/40

**Comment by zjhuntin** [comment]
Thanks for bringing that up @ekohl updated!

**Comment by ekohl** [comment]
Is this failing on https://github.com/theforeman/foreman-packaging/pull/2064 or is it something else?

**Comment by ehelms** [comment]
Correct, still working on plugins

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
This should pass now, however, I want to try to get in the base level plugin packages to ensure nothing from sclo-ror42 is still being required

**Comment by ehelms** [comment]
[test]

**Pull request merged**
