### PR TITLE
Update foreman-release to 2.5.0

### PR DESCRIPTION
**Pull request by zjhuntin**

### CODE REVIEW

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
Note those are old failures and this now failing on repoclosure (as expected on the first RC)

**Comment by evgeni** [comment]
This has git hashes in the package versions, so something is still wrong

**Comment by evgeni** [comment]
needs https://github.com/theforeman/foreman-packaging/pull/6606

**Comment by ekohl** [comment]
Rebase please

**Review by evgeni — APPROVED** [review]

**Pull request merged**
