### PR TITLE
Update foreman-chef to 0.10.0

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by mmoll** [comment]
`09:50:46 NoMethodError: undefined method 'strip_heredoc' for #<String:0x000055b8f4af8400>` This is not Rails 6 compatible... :boom:

**Comment by evgeni** [comment]
Interestingly it built correctly on EL7 (and I merged it :see_no_evil:)

**Comment by ares** [comment]
could that be old foreman-tasks (dependency of this plugin), I've seen that locally before I updated it. Also the trace looks like it's in foreman-tasks

**Comment by mmoll** [comment]
[test packaging]

**Comment by mmoll** [comment]
Merged, díky @ares!
Also for 2.1, I presume?

**Comment by ares** [comment]
yeah

**Comment by mmoll** [comment]
8e0bda40e :cherries:

**Pull request merged**
