### PR TITLE
First round of rebuilds for Rails 5.2

### PR DESCRIPTION
**Pull request by ehelms**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.19
* [ ] 1.18
* [ ] 1.17

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ehelms** [comment]
[test rpm]

**Comment by zjhuntin** [comment]
I am not 100% sure what to look for with this, but all the packages that were rebuilt and bumped seem like they should belong in this. So, LGTM.

**Comment by ekohl** [comment]
```
TASK [build_package : Watch koji task(s)] **************************************
Thursday 06 September 2018  03:31:53 +0000 (0:00:00.034)       1:49:14.292 **** 
Sending interrupt signal to process
script returned exit code 143
```

Does that mean it's taking too long to build?

**Comment by ekohl** [comment]
I think we can merge this and rebuild any failures. I do wonder if the release job won't time out as well

**Pull request merged**
