### PR TITLE
Drop Pulp 2 from katello-debug

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ehelms** [comment]
You can drop this block as well https://github.com/theforeman/foreman-packaging/pull/6315/files#diff-bd254f45063bff11a026d7ebce9ed3e8281793f0f282a8ae197d60398c36db27R81-R85

**Comment by ekohl** [comment]
That link doesn't work for me.

**Comment by ehelms** [comment]
Try this https://github.com/theforeman/foreman-packaging/blob/rpm/develop/packages/katello/katello/katello-debug.sh#L97-L99

**Comment by ekohl** [comment]
I thought I resolved this but clearly not. Updated.

**Review by evgeni — APPROVED** [review]

**Pull request merged**
