### PR TITLE
Updated discovery to 6.0.0 (DEB)

### PR DESCRIPTION
**Pull request by lzap**
Counterpart https://github.com/theforeman/foreman-packaging/pull/1251

### CODE REVIEW

**Comment by domcleal** [comment]
Please also update the control file to specify the 1.12.0 minimum.  Tests might start failing on deb/develop too, but should pass against deb/1.12.

**Comment by mmoll** [comment]
Is this also for deb/1.12?

**Comment by lzap** [comment]
> Is this also for deb/1.12?

It's actually only for 1.12. Another update for nightly soon.

@domcleal done!

-- 
Later,
 Lukas #lzap Zapletal

**Comment by domcleal** [comment]
Thanks @lzap, merged to both develop and 1.12 (as 2cdc50e) and [building on 1.12](http://ci.theforeman.org/job/packaging_build_deb_plugin/1148/) only.

**Pull request merged**
