### PR TITLE
Fixes #21662 - add foreman-proxy temp path

### PR DESCRIPTION
**Pull request by chris1984**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.16
* [ ] 1.15
* [ ] 1.14

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by chris1984** [comment]
@cfoo can I get a review when you get a chance please?

**Comment by chris1984** [comment]
@cfouant can i get a review when you get a chance please.

**Comment by ekohl** [comment]
I'm not sure the ```#Bug``` in the commit message breaks anything but it's not needed. It might also be useful to specify that it's the proxy's temporary path on katello removal because this commit message doesn't tell me much. Other than that I think this is ok.

**Comment by chris1984** [comment]
@ekohl updated the commit and pr message, to reflect that.

**Comment by cfouant** [comment]
ACK - good work, thanks @chris1984

**Comment by chris1984** [comment]
@mmoll can I get a merge please?

**Comment by mmoll** [comment]
I have no idea of katello, sorry.

**Comment by chris1984** [comment]
No worries, @ehelms can I get a merge please?

**Pull request merged**
