### PR TITLE
Update foreman-fog-proxmox to 0.12.4

### PR DESCRIPTION
**Pull request by tristanrobert**
(cherry picked from commit 37fbedc0b065ddfa6d77dc500d02e3ee62024a45)

 * 2.2

### CODE REVIEW

**Comment by tristanrobert** [comment]
It is still making a db:migrate though the plugin does not have any db schema and requires the pg driver though it is nulldb in rules. It works fine on deb/devlop but not in deb/2.2.

**Comment by evgeni** [comment]
Interesting.

@tbrisker @ekohl wasn't the core fix backported to 2.2

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman/commits/2.2-stable tells me https://github.com/theforeman/foreman/commit/22f750d8495cd1722475505894cd440ec5b01181 was merged after RC3 but at this moment RC4 hasn't been released yet. It'll need to wait for that, but it's planned for next week.

**Comment by evgeni** [comment]
Cool, thanks for checking, then this is another item on @zjhuntin's todo for next week XD

**Comment by neomilium** [comment]
@tristanrobert What about 2.1 version?

**Comment by tristanrobert** [comment]
> @tristanrobert What about 2.1 version?

@neomilium It will fail too. The [fix](https://github.com/theforeman/foreman/commit/22f750d8495cd1722475505894cd440ec5b01181) is in develop branch but not in stable branches yet.

**Comment by evgeni** [comment]
[test packaging]

**Comment by evgeni** [comment]
build: https://ci.theforeman.org/job/packaging_build_deb_plugin/616/

**Pull request merged**
