### PR TITLE
Drop rubygem-foreman_docker and rubygem-hammer_cli_foreman_docker

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
@ares Can we drop this plugin all together at this point?

**Comment by ehelms** [comment]
Based on (https://community.theforeman.org/t/ruby-2-7-moving-rpm-deployments-to-ruby-2-7/22734/5?u=ehelms) switched to a removal of foreman_docker and hammer_cli_foreman_docker. This is now a draft because this has to be removed from hammer_cli_katello as a dependency first.

**Comment by ehelms** [comment]
hammer-cli-katello removal PR: https://github.com/Katello/hammer-cli-katello/pull/792
PR to add a note to hammer_cli_foreman_docker: https://github.com/theforeman/hammer_cli_foreman_docker/pull/27

**Comment by ehelms** [comment]
Moving out of draft now that hammer-cli-katello dependencies have been fixed.

**Review by tbrisker — APPROVED** [review]
ACK, will let someone with koji access merge and do the needed cleanup

**Comment by ehelms** [comment]
I'll merge and handle clean up.

**Pull request merged**
