### PR TITLE
Bump foreman_statistics to 1.0

### PR DESCRIPTION
**Pull request by ezr-ondrej**
Removes cron job, packages version 1.0

- [x] Merge: https://github.com/theforeman/foreman_statistics/pull/19
- [x] Relase foreman_statistics, and include it here

### CODE REVIEW

**Comment by ekohl** [comment]
This will need to bump the release in `foreman.spec`, but I'd suggest to leave that till the last moment since it can easily create merge conflicts. Is this also required for 2.2 or should it wait till after branching?

**Comment by ezr-ondrej** [comment]
I'd say it would be great to get it in 2.2 as without it, we will have useless rake task.
Although it will be just logging the missing plugin error (as the rake task withouth the plugin does)

**Comment by ezr-ondrej** [comment]
This is done. Could we get this in?

**Comment by tbrisker** [comment]
ping @ekohl what's the status here?

**Comment by ezr-ondrej** [comment]
[test rpm]

**Comment by ezr-ondrej** [comment]
I believe non-existent leapp in nightlies is not my fault :thinking:

**Comment by pcreech** [comment]
[test rpm]

**Comment by ezr-ondrej** [comment]
[test rpm]

**Comment by ezr-ondrej** [comment]
:green_apple:

**Review by evgeni — APPROVED** [review]

**Pull request merged**
