### PR TITLE
Update rubygem-hammer_cli_foreman to 2.1.0

### PR DESCRIPTION
**Pull request by shiramax**

### CODE REVIEW

**Comment by tbrisker** [comment]
huh, this is odd: 
```
+ gem unpack /builddir/build/SOURCES/hammer_cli_foreman-2.1.0.gem
/var/tmp/rpm-tmp.uo7XZL: line 29: gem: command not found
``` 
@ehelms any idea why it failed?

**Comment by tbrisker** [comment]
Also EL8 failed on something else:
```
DEBUG util.py:600:  No available modular metadata for modular package 'ruby-2.5.5-105.module_el8.1.0+214+9be47fd7.x86_64', it cannot be installed on the system
DEBUG util.py:600:  No available modular metadata for modular package 'ruby-irb-2.5.5-105.module_el8.1.0+214+9be47fd7.noarch', it cannot be installed on the system
DEBUG util.py:600:  No available modular metadata for modular package 'ruby-libs-2.5.5-105.module_el8.1.0+214+9be47fd7.x86_64', it cannot be installed on the system
DEBUG util.py:600:  No available modular metadata for modular package 'rubygem-io-console-0.4.6-105.module_el8.1.0+214+9be47fd7.x86_64', it cannot be installed on the system
DEBUG util.py:600:  No available modular metadata for modular package 'rubygem-json-2.1.0-105.module_el8.1.0+214+9be47fd7.x86_64', it cannot be installed on the system
DEBUG util.py:600:  No available modular metadata for modular package 'rubygem-openssl-2.1.2-105.module_el8.1.0+214+9be47fd7.x86_64', it cannot be installed on the system
DEBUG util.py:600:  No available modular metadata for modular package 'rubygem-psych-3.0.2-105.module_el8.1.0+214+9be47fd7.x86_64', it cannot be installed on the system
DEBUG util.py:600:  No available modular metadata for modular package 'rubygem-rdoc-6.0.1-105.module_el8.1.0+214+9be47fd7.noarch', it cannot be installed on the system
DEBUG util.py:600:  No available modular metadata for modular package 'rubygems-2.7.6.2-105.module_el8.1.0+214+9be47fd7.noarch', it cannot be installed on the system
DEBUG util.py:600:  No available modular metadata for modular package 'rubygems-devel-2.7.6.2-105.module_el8.1.0+214+9be47fd7.noarch', it cannot be installed on the system
DEBUG util.py:600:  Error: No available modular metadata for modular package
DEBUG util.py:753:  Child return code was: 1

**Comment by ehelms** [comment]
[test rpm]

**Comment by tbrisker** [comment]
Looks like el7 built, but el8 is still failing

**Comment by ehelms** [comment]
[test rpm]

**Pull request merged**
