### PR TITLE
Update foreman_remote_execution to 1.3.5 [rpm]

### PR DESCRIPTION
**Pull request by iNecas**
For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [ ] 1.16
* [x] 1.15
* [ ] 1.14

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

There was an incompatibility found in combination with katello. http://projects.theforeman.org/issues/21242 fixes it by reverting one of the commits in 1.3-stable branch. Therefore, from now on, 1.3 will be kept compatible with 1.16, but master will work against nightlies only.

### CODE REVIEW

**Comment by evgeni** [comment]
i think you also should remove the 1.3.4 gem from annex?

**Comment by iNecas** [comment]
RIght, updated. I was sure I removed that :)

**Comment by evgeni** [comment]
LGTM and passed jenkins now! :sheep:

**Comment by dLobatog** [comment]
el7 - http://koji.katello.org/koji/taskinfo?taskID=37550
f24 - http://koji.katello.org/koji/taskinfo?taskID=37549

**Pull request merged**
