### PR TITLE
Fixes #32125 - only update hammer config when present

### PR DESCRIPTION
**Pull request by phess**
Thank you @wbclark for the wonderful collab work in making this patch.

### CODE REVIEW

**Review by wbclark — COMMENTED** [review]
This patch worked nicely in our ad-hoc testing

Pleasure working with you on it @phess !

**Comment by chris1984** [comment]
ok to test

**Comment by ehelms** [comment]
Can you please bump the release and add a changelog entry?

**Comment by phess** [comment]
> Can you please bump the release and add a changelog entry?

Done. Thank you @ehelms .

**Review by ehelms — APPROVED** [review]

**Pull request merged**
