### PR TITLE
Patch foreman-proxy settings.yml with defaults to listen on localhost [deb]

### PR DESCRIPTION
**Pull request by domcleal**
Under Debian Jessie with systemd, the foreman-proxy service failure is
detected during package installation and causes it to fail during
post-installation.  Configure foreman-proxy to instead listen on
localhost by default.

Also uses the settings.yml supplied in the tarball instead of keeping it in-tree.  Unfortunately I can't get the patches to apply - the resulting packages always have the original.  I do though get errors in the build if the patch is incorrect.  Any idea why it might not work?

### CODE REVIEW

**Comment by mmoll** [comment]
I used quilt to really generate the patch and it seems the patch files need to be in the following format:
```diff
diff --git a/debian/patches/settings_yml_defaults.patch b/debian/patches/settings_yml_defaults.patch
index 810d84c..dfadb64 100644
--- a/debian/patches/settings_yml_defaults.patch
+++ b/debian/patches/settings_yml_defaults.patch
@@ -1,5 +1,5 @@
---- config/settings.yml.example.old    2015-11-05 11:57:47.188754589 +0000
-+++ config/settings.yml.example        2015-11-05 11:57:50.662766481 +0000
+--- a/config/settings.yml.example
++++ b/config/settings.yml.example
 @@ -1,4 +1,7 @@
  ---
 +#replace default location of "settings.d"
```

**Comment by domcleal** [comment]
Thanks very much.  I used quilt and it generated the same as yours, useful to know!  I had to additionally set `:daemon: true` in settings.yml.

<pre>
root@foremandeb:~# apt-get install foreman-proxy                                                                                       
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  foreman-proxy
0 upgraded, 1 newly installed, 0 to remove and 4 not upgraded.
Need to get 80.5 kB of archives.
After this operation, 492 kB of additional disk space will be used.
Get:1 http://stagingdeb.theforeman.org/ jessie/domcleal-nightly foreman-proxy all 9999-jessie+scratchbuild+201511061608 [80.5 kB]
Fetched 80.5 kB in 0s (126 kB/s)   
Selecting previously unselected package foreman-proxy.
(Reading database ... 42436 files and directories currently installed.)
Preparing to unpack .../foreman-proxy_9999-jessie+scratchbuild+201511061608_all.deb ...
Unpacking foreman-proxy (9999-jessie+scratchbuild+201511061608) ...
Processing triggers for systemd (215-17+deb8u2) ...
Setting up foreman-proxy (9999-jessie+scratchbuild+201511061608) ...
Processing triggers for systemd (215-17+deb8u2) ...
root@foremandeb:~# systemctl status foreman-proxy                                                                                      
● foreman-proxy.service - Foreman Proxy
   Loaded: loaded (/lib/systemd/system/foreman-proxy.service; enabled)
   Active: active (running) since Fri 2015-11-06 16:29:20 UTC; 3s ago
 Main PID: 3479 (ruby)
   CGroup: /system.slice/foreman-proxy.service
           └─3479 ruby /usr/share/foreman-proxy/bin/smart-proxy
</pre>

Unfortunately I'm getting build failures on precise and struggling to understand what it's doing.  It appears to be trying to reverse the patch at the end of each build.  On wheezy you can see it here:

<pre>
16:10:29  dpkg-source --before-build foreman-proxy-1.11.0
16:10:29 dpkg-buildpackage: host architecture amd64
16:10:29 dpkg-source: info: applying settings_yml_defaults.patch
16:10:29  fakeroot debian/rules clean
16:10:30 dh clean
16:10:30    dh_testdir
16:10:30    dh_auto_clean
16:10:30    dh_clean
16:10:30  debian/rules build
16:10:30 rename 's/.example//' config/* config/settings.d/*
[..]
16:10:32 dpkg-deb: building package `foreman-proxy' in `../foreman-proxy_9999-wheezy+scratchbuild+201511061608_all.deb'.
16:10:33  dpkg-genchanges -b >../foreman-proxy_9999-wheezy+scratchbuild+201511061608_amd64.changes
16:10:33 dpkg-genchanges: binary-only upload - not including any source code
16:10:33  dpkg-source --after-build foreman-proxy-1.11.0
16:10:33 dpkg-source: info: unapplying settings_yml_defaults.patch
16:10:33 dpkg-buildpackage: binary only upload (no source included)
</pre>

But on precise:

<pre>
16:09:31  dpkg-source --before-build foreman-proxy-1.11.0
16:09:31 dpkg-buildpackage: host architecture amd64
16:09:32 dpkg-source: info: patches are not applied, applying them now
16:09:32 dpkg-source: info: applying settings_yml_defaults.patch
16:09:32  fakeroot debian/rules clean
16:09:32 dh clean
16:09:32    dh_testdir
16:09:32    dh_auto_clean
16:09:32    dh_clean
16:09:32  debian/rules build
16:09:32 rename 's/.example//' config/* config/settings.d/*
[..]
16:09:34 dpkg-deb: building package `foreman-proxy' in `../foreman-proxy_9999-precise+scratchbuild+201511061608_all.deb'.
16:09:35  dpkg-genchanges -b >../foreman-proxy_9999-precise+scratchbuild+201511061608_amd64.changes
16:09:35 dpkg-genchanges: binary-only upload - not including any source code
16:09:35  dpkg-source --after-build foreman-proxy-1.11.0
16:09:35 dpkg-source: info: unapplying settings_yml_defaults.patch
16:09:35 dpkg-source: error: LC_ALL=C patch -R -t -N -p1 -u -V never -g0 -E --no-backup-if-mismatch < foreman-proxy-1.11.0/debian/patches/settings_yml_defaults.patch gave error exit status 1
16:09:35 can't find file to patch at input line 3
16:09:35 Perhaps you used the wrong -p or --strip option?
16:09:35 The text leading up to this was:
16:09:35 --------------------------
16:09:35 |--- a/config/settings.yml.example
16:09:35 |+++ b/config/settings.yml.example
16:09:35 --------------------------
16:09:35 No file to patch.  Skipping patch.
16:09:35 3 out of 3 hunks ignored
16:09:35 dpkg-buildpackage: error: dpkg-source --after-build foreman-proxy-1.11.0 gave error exit status 1
</pre>

I'm slightly surprised that it can even unapply the patch on non-precise distros given the moving of config files, unless it's quietly ignoring it.

**Comment by mmoll** [comment]
precise might be too old for that quilt stuff, will look into it

**Comment by domcleal** [comment]
Here's an alternative.. I changed rules to no longer mv the config/ dir to foreman-proxy/.  Instead it now makes a copy and removes the .example extensions from that - this way the patching and reversal happens correctly against the original config/ dir before it's copied.

**Comment by mmoll** [comment]
tested only the resulting packages of jessie, but looking good, merging...

**Comment by mmoll** [comment]
thanks!

**Pull request merged**
