### PR TITLE
Update rubygem-foreman_leapp to 0.1.2

### PR DESCRIPTION
**Pull request by stejskalleos**

### CODE REVIEW

**Comment by stejskalleos** [comment]
[test rpm]

**Comment by adamruzicka** [comment]
Although not captured in gemspec yet (see https://github.com/oamg/foreman_leapp/pull/85), this release requires rex >= 3.2.0

**Comment by stejskalleos** [comment]
Added 0.1.1 version

**Comment by adamruzicka** [comment]
Rex 3.2 went in
[test rpm]

**Comment by stejskalleos** [comment]
[test rpm]

**Comment by stejskalleos** [comment]
Bumped to `0.1.2`, & `foreman_min_version 2.1`

**Comment by stejskalleos** [comment]
rpm is failing due to issues with `el8-foreman-nightly`, looks like issue is not related to changes in this PR. @ehelms could you please look at it?

**Pull request merged**
