### PR TITLE
document how to remove packages from freight

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
Should it mention that this happens on the webserver or is that obvious from `/var/www`? It is to me, but it may not be to everyone.

**Comment by evgeni** [comment]
Technically, "on the machine hosting the repository", which happens to be web01.

I refrained from it, as it might get out of sync.

**Review by upadhyeammit — APPROVED** [review]
I am not sure if we should explicitly add that these steps are not required for stable repos, otherwise looks good!

**Comment by evgeni** [comment]
> I am not sure if we should explicitly add that these steps are not required for stable repos, otherwise looks good!

They would work identically for stable repos, just doing such changes to a stable repo requires more reason than "cleanup".

**Pull request merged**
