### PR TITLE
Update rubygem-foreman_rh_cloud to 9.0.56

### PR DESCRIPTION
**Pull request by chris1984**

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
Please first make sure nightly is updated and then cherry pick all commits to stable branches.

**Comment by chris1984** [comment]
> Please first make sure nightly is updated and then cherry pick all commits to stable branches.

@ekohl here is the nightly one I just made:

https://github.com/theforeman/foreman-packaging/pull/10744

Once that goes in I will change this to a cherry-pick of that

**Comment by evgeni** [comment]
That's merged now.

Please also update rpm/3.10 :)

**Comment by chris1984** [comment]
> That's merged now.
> 
> Please also update rpm/3.10 :)

Updated and all green for 3.9 :)

**Review by ekohl — CHANGES_REQUESTED** [review]
Please pick all the relevant commits and don't squash in commits into the cherry pick commit. This maintains the proper history.

**Comment by evgeni** [comment]
3.9 is EOL and we stopped publishing updates there, sorry.

**Pull request closed without merging**
