### PR TITLE
Update rubygem-foreman_maintain to 0.1.1

### PR DESCRIPTION
**Pull request by gnurag**
Updated rubygem-foreman_maintain to 0.1.1 to push fixes related to downcasing of hammer credentials.

### CODE REVIEW

**Comment by ekohl** [comment]
Gem compare is not happy about some things. I mostly think it's unhappy about the group writable files but I don't know RPM packaging cares about this at all. The shebang should be handled in ```%install``` phase.

```
$ gem compare -b foreman_maintain 0.0.11 0.1.1
Fetching: foreman_maintain-0.0.11.gem (100%)
Fetching: foreman_maintain-0.1.1.gem (100%)
Compared versions: ["0.0.11", "0.1.1"]
  DIFFERENT files:
    0.0.11->0.1.1:
      * Added:
            bin/passenger-recycler
              (!) Unexpected permissions: 100775
              (!) Shebang found: #!/usr/bin/env ruby
            definitions/procedures/passenger_recycler.rb
              (!) Unexpected permissions: 100664
      * Changed:
            README.md 
              (!) New permissions: 100644 -> 100664
            bin/foreman-maintain 
              (!) New permissions: 100755 -> 100775
            config/foreman_maintain.yml.example 
              (!) New permissions: 100644 -> 100664
            config/foreman_maintain.yml.packaging 
              (!) New permissions: 100644 -> 100664
            definitions/checks/disk_speed_minimal.rb 
              (!) New permissions: 100644 -> 100664
            definitions/checks/foreman_proxy/verify_dhcp_config_syntax.rb 
              (!) New permissions: 100644 -> 100664
            definitions/checks/foreman_tasks/not_paused.rb 
              (!) New permissions: 100644 -> 100664
            definitions/checks/foreman_tasks/not_running.rb 
              (!) New permissions: 100644 -> 100664
            definitions/checks/hammer_ping.rb +4/-0
              (!) New permissions: 100644 -> 100664
            definitions/checks/system_registration.rb 
              (!) New permissions: 100644 -> 100664
            definitions/features/downstream.rb 
              (!) New permissions: 100644 -> 100664
            definitions/features/foreman_1_7_x.rb 
              (!) New permissions: 100644 -> 100664
            definitions/features/foreman_database.rb +1/-1
              (!) New permissions: 100644 -> 100664
            definitions/features/foreman_proxy.rb +9/-5
              (!) New permissions: 100644 -> 100664
            definitions/features/foreman_server.rb 
              (!) New permissions: 100644 -> 100664
            definitions/features/foreman_tasks.rb +1/-1
              (!) New permissions: 100644 -> 100664
            definitions/features/hammer.rb 
              (!) New permissions: 100644 -> 100664
            definitions/features/katello.rb 
              (!) New permissions: 100644 -> 100664
            definitions/features/katello_service.rb 
              (!) New permissions: 100644 -> 100664
            definitions/features/sync_plans.rb 
              (!) New permissions: 100644 -> 100664
            definitions/features/upstream.rb 
              (!) New permissions: 100644 -> 100664
            definitions/procedures/foreman_tasks/delete.rb 
              (!) New permissions: 100644 -> 100664
            definitions/procedures/foreman_tasks/fetch_tasks_status.rb +1/-1
              (!) New permissions: 100644 -> 100664
            definitions/procedures/foreman_tasks/resume.rb 
              (!) New permissions: 100644 -> 100664
            definitions/procedures/foreman_tasks/ui_investigate.rb 
              (!) New permissions: 100644 -> 100664
            definitions/procedures/hammer_setup.rb 
              (!) New permissions: 100644 -> 100664
            definitions/procedures/installer/upgrade.rb 
              (!) New permissions: 100644 -> 100664
            definitions/procedures/katello_service/restart.rb 
              (!) New permissions: 100644 -> 100664
            definitions/procedures/katello_service/start.rb 
              (!) New permissions: 100644 -> 100664
            definitions/procedures/katello_service/stop.rb 
              (!) New permissions: 100644 -> 100664
            definitions/procedures/maintenance_mode/disable.rb 
              (!) New permissions: 100644 -> 100664
            definitions/procedures/maintenance_mode/enable.rb 
              (!) New permissions: 100644 -> 100664
            definitions/procedures/packages/install.rb 
              (!) New permissions: 100644 -> 100664
            definitions/procedures/packages/update.rb 
              (!) New permissions: 100644 -> 100664
            definitions/procedures/repositories/setup.rb 
              (!) New permissions: 100644 -> 100664
            definitions/procedures/sync_plans/disable.rb 
              (!) New permissions: 100644 -> 100664
            definitions/procedures/sync_plans/enable.rb 
              (!) New permissions: 100644 -> 100664
            definitions/scenarios/upgrade_to_satellite_6_2.rb 
              (!) New permissions: 100644 -> 100664
            definitions/scenarios/upgrade_to_satellite_6_2_z.rb 
              (!) New permissions: 100644 -> 100664
            definitions/scenarios/upgrade_to_satellite_6_3.rb 
              (!) New permissions: 100644 -> 100664
            definitions/scenarios/upgrade_to_satellite_6_3_z.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/check.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/cli.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/cli/advanced/procedure/abstract_by_tag_command.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/cli/advanced/procedure/abstract_procedure_command.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/cli/advanced/procedure/by_tag_command.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/cli/advanced/procedure/run_command.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/cli/advanced/procedure_command.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/cli/advanced_command.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/cli/base.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/cli/health_command.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/cli/transform_clamp_options.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/cli/upgrade_command.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/concerns/finders.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/concerns/metadata.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/concerns/scenario_metadata.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/concerns/system_helpers.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/config.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/core_ext.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/csv_parser.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/dependency_graph.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/detector.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/error.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/executable.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/param.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/reporter.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/reporter/cli_reporter.rb +2/-1
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/runner.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/runner/execution.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/runner/stored_execution.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/scenario.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/upgrade_runner.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/utils.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/utils/curl_response.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/utils/disk/device.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/utils/disk/io/block_device.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/utils/disk/io/file_system.rb 
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/version.rb +1/-1
              (!) New permissions: 100644 -> 100664
            lib/foreman_maintain/yaml_storage.rb 
              (!) New permissions: 100644 -> 100664
  DIFFERENT extra_rdoc_files:
    0.0.11->0.1.1:
      * Changed:
            README.md 
              (!) New permissions: 100644 -> 100664
```

**Comment by evgeni** [comment]
Yeah, I think we should not change perms in the gem, but RPM (and DEB) does sanitize permissions when files are installed, so it's not a huge problem.

**Comment by gnurag** [comment]
@komidore64, pr for the version bump has been merged. you should be able to build `foreman_maintain-0.1.1` from the repo now.

**Comment by ekohl** [comment]
@gnurag I think @komidore64 wants the git tag to be pushed to github.

**Comment by gnurag** [comment]
Thanks @ekohl @komidore64, I pushed `v0.1.1` to the repo. Let me know if I missed anything else.

**Pull request merged**
