### PR TITLE
Update foreman-fog-proxmox to 0.9.1

### PR DESCRIPTION
**Pull request by tristanrobert**
* Nightly
 * 1.24
 * 1.23
 * 1.22

### CODE REVIEW

**Comment by tristanrobert** [comment]
Do I need to add `gem 'tzinfo-data'` in my [foreman_fog_proxmox.gemspec file](https://github.com/theforeman/foreman_fog_proxmox/blob/master/foreman_fog_proxmox.gemspec)? Or would it be included in foreman soon?

**Comment by mmoll** [comment]
@tristanrobert If that gem depends on the other gem, yes, independent of the RPM/DEB packaging.

**Comment by mmoll** [comment]
Hrm, where is that TZInfo stuff coming from?

**Comment by mmoll** [comment]
GH-4400

**Comment by tristanrobert** [comment]
@mmoll [GH-4400](https://github.com/theforeman/foreman-packaging/pull/4400) is now merged. This PR could be now unblocked ?

**Comment by mmoll** [comment]
We need the built debs on deb.tf.org first.

**Comment by mmoll** [comment]
[test packaging]

**Comment by mmoll** [comment]
merged, merci @tristanrobert!

**Comment by mmoll** [comment]
For 1.22 and 1.23 we'd need to wait for another release with the tzinfo dependency.

**Pull request merged**
