### PR TITLE
Updated rbovirt to 0.1.2

### PR DESCRIPTION
**Pull request by lzap**
I believe we have some issues reported on not being able to connect to oVirt
4.0. This fixes it.

### CODE REVIEW

**Comment by domcleal** [comment]
Merged and building, thanks @lzap.

**Comment by lzap** [comment]
> Merged and building, thanks @lzap.

There are couple of reports for 1.12 or even 1.11. Might worth
rebuilding it into it. Up to you, thanks!

-- 
Later,
 Lukas #lzap Zapletal

**Comment by domcleal** [comment]
I'll try and include this in the next 1.12 point release, but 1.11's EOL.

Can you review and close the appropriate tickets against Foreman? There are many conflicting reports about what does, and doesn't work.

* http://projects.theforeman.org/issues/15560
* http://projects.theforeman.org/issues/15578
* http://projects.theforeman.org/issues/15738

If fixed in this release, please close and set release to 1.12.2.

**Comment by lzap** [comment]
Sure thing.

**Pull request merged**
