### PR TITLE
plugins:foreman_ansible - Release 0.2.2

### PR DESCRIPTION
**Pull request by dLobatog**
Relevant for 1.8, 1.9, 1.10

### CODE REVIEW

**Comment by domcleal** [comment]
Thanks @dLobatog, building for nightly.

The package isn't in 1.8-1.10 at the moment, but I can cherry pick it back and build 0.2.2.

**Comment by dLobatog** [comment]
That'd be great, thanks. I'm releasing 0.3 either today or tomorrow though!

**Comment by domcleal** [comment]
I'll have it done today, it'll be easier to do it sooner before further updates.

**Comment by domcleal** [comment]
Cherry picked to 1.10, 1.9 and retagged to 1.8.

**Pull request merged**
