### PR TITLE
Add rubygem-graphql-batch package

### PR DESCRIPTION
**Pull request by xprazak2**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.21
* [ ] 1.20

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by xprazak2** [comment]
Needs https://github.com/theforeman/foreman-packaging/pull/3450

**Comment by evgeni** [comment]
This failed repoclosure, because it depends on #3452 and #3450.

But that's fine for now.

**Comment by evgeni** [comment]
```
 % koji add-pkg foreman-nightly-rhel7 tfm-rubygem-graphql-batch --owner=kojiadm
Adding 1 packages to tag foreman-nightly-rhel7
```

**Comment by evgeni** [comment]
build: http://koji.katello.org/koji/taskinfo?taskID=173760

**Pull request merged**
