### PR TITLE
Katello 3.13.0 RC1

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
I wouldn't know :)
But I can check with @jjeffers

**Comment by ekohl** [comment]
It's something that has failed for the past few releases and then only to surface at the GA release. Let's try to get it right here this time :)

**Comment by evgeni** [comment]
FTR, I see no Katello 3.13 key in the Katello keys repo, so I guess this was not updated yet.

**Comment by jjeffers** [comment]
@evgeni I'll follow up wrt to the GPG keys.

**Comment by evgeni** [comment]
@jjeffers @jlsherrill following the discussion, I've updated this to include the Foreman pubic key as the Katello public key.

This will need a section in the release announcement I guess.

**Comment by evgeni** [comment]
@ekohl yeah I thought similar, but decided not to touch it right now.

**Comment by evgeni** [comment]
repoclosure is broken, expected :)

**Pull request merged**
