### PR TITLE
Handle assets, require foreman 1.9 for foreman-tasks (RPM/develop)

### PR DESCRIPTION
**Pull request by stbenjam**
I also noticed foreman-tasks requires 1.9 or greater.

### CODE REVIEW

**Comment by domcleal** [comment]
You may need to override the precompilation rake task name, as the default based on the gem name won't be right (the plugin appears to register itself with an underscore).

    # -r<rake_task>     Overrides rake task of plugin:assets:precompile[plugin_name]

**Comment by stbenjam** [comment]
Green

**Comment by domcleal** [comment]
It looks OK to me - did you want to test the build first to check, or go ahead anyway?  If so, the 1.10 EL7 build is at http://koji.katello.org/koji/taskinfo?taskID=402914

**Comment by stbenjam** [comment]
Ah yes, good idea.  Tested - and all the assets are there and the broken pages work now.  Thanks!

**Comment by domcleal** [comment]
Thanks for checking, building now.

**Pull request merged**
