### PR TITLE
hammer-cli-katello: use main instead of master

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
[test rpm-copr]

**Comment by evgeni** [comment]
[test rpm-copr]

**Comment by evgeni** [comment]
Why does it depend on rubocop now?!

**Comment by ekohl** [comment]
> Why does it depend on rubocop now?!

https://github.com/Katello/hammer-cli-katello/pull/943#pullrequestreview-2250383991

**Comment by evgeni** [comment]
https://github.com/Katello/hammer-cli-katello/pull/950

**Comment by ehelms** [comment]
[test rpm-copr]

**Comment by evgeni** [comment]
[test rpm-copr]

**Comment by nadjaheitmann** [comment]
Do you need to update Katello in foreman-packaging for the pipeline to become green? Looks like it is still looking for the older version.

**Comment by evgeni** [comment]
Going to merge this, to unblock nighties

**Pull request merged**
