### PR TITLE
Symlink foreman_tasks sprockets assets too

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
Dashes vs underscores strikes us again ...

**Comment by evgeni** [comment]
updated the commit to include a redmine

**Comment by MariaAga** [comment]
just curious, why is this a new issue? it was working before probably

**Comment by evgeni** [comment]
> just curious, why is this a new issue? it was working before probably

It's a regression from the "assets via apache" work I did recently: https://projects.theforeman.org/issues/33956

**Comment by ekohl** [comment]
> Dashes vs underscores strikes us again ...

I was asked for clarification on this. So we have (after this change):
```console
$ rpm -ql rubygem-foreman-tasks-7.2.0-2.fm3_6.el8.noarch.rpm | grep assets
/usr/share/foreman/public/assets/foreman-tasks
/usr/share/foreman/public/assets/foreman_tasks
/usr/share/gems/gems/foreman-tasks-7.2.0/app/assets
/usr/share/gems/gems/foreman-tasks-7.2.0/app/assets/javascripts
/usr/share/gems/gems/foreman-tasks-7.2.0/app/assets/javascripts/foreman_tasks
/usr/share/gems/gems/foreman-tasks-7.2.0/app/assets/javascripts/foreman_tasks/foreman_tasks.js
/usr/share/gems/gems/foreman-tasks-7.2.0/app/assets/javascripts/foreman_tasks/trigger_form.js
/usr/share/gems/gems/foreman-tasks-7.2.0/app/assets/stylesheets
/usr/share/gems/gems/foreman-tasks-7.2.0/app/assets/stylesheets/foreman_tasks
/usr/share/gems/gems/foreman-tasks-7.2.0/app/assets/stylesheets/foreman_tasks/foreman_tasks.css
/usr/share/gems/gems/foreman-tasks-7.2.0/app/assets/stylesheets/foreman_tasks/trigger_form.css
/usr/share/gems/gems/foreman-tasks-7.2.0/public/assets/foreman-tasks
/usr/share/gems/gems/foreman-tasks-7.2.0/public/assets/foreman-tasks/foreman-tasks.json
/usr/share/gems/gems/foreman-tasks-7.2.0/public/assets/foreman_tasks
/usr/share/gems/gems/foreman-tasks-7.2.0/public/assets/foreman_tasks/foreman_tasks-5c216788114727b5e1a8ec773b6a9292eb574344e993aad8cb7dd6d655bebc94.js
/usr/share/gems/gems/foreman-tasks-7.2.0/public/assets/foreman_tasks/foreman_tasks-5c216788114727b5e1a8ec773b6a9292eb574344e993aad8cb7dd6d655bebc94.js.gz
/usr/share/gems/gems/foreman-tasks-7.2.0/public/assets/foreman_tasks/foreman_tasks-819977735d4974feaf40cb92589b85cbe3f5b19e5794f8d31debb1501031a83d.css
/usr/share/gems/gems/foreman-tasks-7.2.0/public/assets/foreman_tasks/foreman_tasks-819977735d4974feaf40cb92589b85cbe3f5b19e5794f8d31debb1501031a83d.css.gz
/usr/share/gems/gems/foreman-tasks-7.2.0/public/assets/foreman_tasks/trigger_form-5c216788114727b5e1a8ec773b6a9292eb574344e993aad8cb7dd6d655bebc94.js
/usr/share/gems/gems/foreman-tasks-7.2.0/public/assets/foreman_tasks/trigger_form-5c216788114727b5e1a8ec773b6a9292eb574344e993aad8cb7dd6d655bebc94.js.gz
/usr/share/gems/gems/foreman-tasks-7.2.0/public/assets/foreman_tasks/trigger_form-819977735d4974feaf40cb92589b85cbe3f5b19e5794f8d31debb1501031a83d.css
/usr/share/gems/gems/foreman-tasks-7.2.0/public/assets/foreman_tasks/trigger_form-819977735d4974feaf40cb92589b85cbe3f5b19e5794f8d31debb1501031a83d.css.gz
```

It generates `/usr/share/gems/gems/foreman-tasks-7.2.0/public/assets/foreman-tasks/foreman-tasks.json` because is that's the plugin name. Note how here it uses the dash:
https://github.com/theforeman/foreman-tasks/blob/b723568e71779c562cf714dc449d2fbf44838a3d/lib/foreman_tasks/engine.rb#L27

**Pull request merged**
