### PR TITLE
Update rubygem-foreman_scc_manager to 1.5.1 for 1.20

### PR DESCRIPTION
**Pull request by m-bucher**
(cherry picked from commit 40894e0c62b1dac97d36fd067dde5a94eb24ad17)
cherry-picked from #3307
For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [X] 1.20
* [ ] 1.19

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
The gem is added as a binary and not a git annex, Can you fix that?

**Comment by m-bucher** [comment]
@ehelms, done. Thanks

**Comment by ekohl** [comment]
ok to test

**Comment by m-bucher** [comment]
@ekohl thanks for starting the test-build.
Was it my fault that it failed or is the build-pipeline to blame?
Looks like [another build](http://ci.theforeman.org/blue/organizations/jenkins/foreman-packaging-rpm-pr-test/detail/foreman-packaging-rpm-pr-test/2390/pipeline) failed with the same error.

**Comment by evgeni** [comment]
@m-bucher this is an infra issue, should be fixed when https://github.com/theforeman/foreman-infra/pull/921 is merged.

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
oh, you actually changed both. damn.

**Comment by evgeni** [comment]
the actual build happened in #3420, this PR is only to sync git and tag it into 3.10 katello:

```
% koji tag-build katello-3.10-rhel7 tfm-rubygem-foreman_scc_manager-1.5.1-1.fm1_20.el7 
Created task 169967
Watching tasks (this may be safely interrupted)...
169967 tagBuild (noarch): free
169967 tagBuild (noarch): free -> closed
  0 free  0 open  1 done  0 failed

169967 tagBuild (noarch) completed successfully

```

**Pull request merged**
