### PR TITLE
bump @theforeman/vendor and builder to 4.3.0

### PR DESCRIPTION
**Pull request by evgeni**
this is to make katello deps happy for now, while we figure out further steps.

### CODE REVIEW

**Comment by evgeni** [comment]
el8 fails with `npm: command not found`, weird.

**Comment by evgeni** [comment]
let's see how this goes

**Comment by evgeni** [comment]
[test rpm]

**Comment by ekohl** [comment]
I believe half of https://github.com/theforeman/npm2rpm/pull/64 is correct and would have prevented this issue.

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
this would have built if jenkins would like me

**Comment by ehelms** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Pull request merged**
