### PR TITLE
Update rubygem-facter to 4.0.44

### PR DESCRIPTION
**Pull request by lzap**
Is the discovery image the only reason why carry Facter in our repo? It
looks like 2.x series have problems with IPv6 and I would like to know
how feasible is to make the switch to 4.x.

* Nightly

EDIT:

Dependant PRs:

* https://github.com/theforeman/foreman-packaging/pull/5699

Related PRs:

* https://github.com/theforeman/foreman-packaging/pull/5700
* https://github.com/theforeman/foreman-packaging/pull/5721

### CODE REVIEW

**Comment by ekohl** [comment]
No, it's not only discovery. Foreman itself also pulls in Facter.

**Comment by lzap** [comment]
Created https://community.theforeman.org/t/facter-and-ipv6-on-fdi/20159

Indeed it failed :-( Won't be easy upgrade.

**Comment by lzap** [comment]
It's not that bad tho:

```
Processing files: rubygem-facter-4.0.35-1.el8.x86_64
error: File not found: /builddir/build/BUILDROOT/rubygem-facter-4.0.35-1.el8.x86_64/usr/share/gems/gems/facter-4.0.35/LICENSE
warning: File not found: /builddir/build/BUILDROOT/rubygem-facter-4.0.35-1.el8.x86_64/usr/share/gems/gems/facter-4.0.35/etc
RPM build errors:
warning: File not found: /builddir/build/BUILDROOT/rubygem-facter-4.0.35-1.el8.x86_64/usr/share/gems/gems/facter-4.0.35/ext
warning: File not found: /builddir/build/BUILDROOT/rubygem-facter-4.0.35-1.el8.x86_64/usr/share/gems/gems/facter-4.0.35/install.rb
    File not found: /builddir/build/BUILDROOT/rubygem-facter-4.0.35-1.el8.x86_64/usr/share/gems/gems/facter-4.0.35/LICENSE
    File not found: /builddir/build/BUILDROOT/rubygem-facter-4.0.35-1.el8.x86_64/usr/share/gems/gems/facter-4.0.35/etc
    File not found: /builddir/build/BUILDROOT/rubygem-facter-4.0.35-1.el8.x86_64/usr/share/gems/gems/facter-4.0.35/ext
    File not found: /builddir/build/BUILDROOT/rubygem-facter-4.0.35-1.el8.x86_64/usr/share/gems/gems/facter-4.0.35/install.rb
```

**Comment by lzap** [comment]
Ok one dependency is missing:

```
[2020-08-20T11:05:56.867Z]     package: rubygem-facter-4.0.35-1.el8.x86_64 from downloaded_rpms
[2020-08-20T11:05:56.867Z]       unresolved deps:
[2020-08-20T11:05:56.867Z]         (rubygem(hocon) >= 1.3 with rubygem(hocon) < 2)
```

**Comment by lzap** [comment]
Do I need to file a different PR for the dependency?

Can you help me with the `./add_gem_package.sh` command? There's lots of tags and stuff there I am sure I will mess up.

**Comment by lzap** [comment]
I am not aware closing and deleting the branch myself. Reopening.

**Comment by raresd** [comment]
Currently working on a project in a IPv6 only environment and we hit this limitation. 

Would be highly appreciated if this could be merged.

**Comment by lzap** [comment]
This is now green, @theforeman/packaging

**Comment by lzap** [comment]
Guys this was part on IPv6 feature, I could not get this in time but I'd still appreciate if you could take another look. Thanks!

**Comment by evgeni** [comment]
Could you bump that to the latest version and also update dependencies?

https://rubygems.org/gems/facter/versions/4.0.44 lists `hocon` and `thor` but neither are in the rpm spec.

**Comment by lzap** [comment]
Finally done, all deps should be in. Bumped to 4.0.44 and added those dependencies. Crossing fingers!

**Comment by lzap** [comment]
What? It's green? Wow!

**Review by evgeni — APPROVED** [review]
ACK -- there has been a 4.0.46, want to update to that in this PR or later?

**Comment by lzap** [comment]
Later please, these guys are insane... I want to finish my Facter 4.x upgrade, thanks.

**Pull request merged**
