### PR TITLE
Update 'rubygem-angular-rails-templates' to 0.1.3

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
Local testing this seemed OK - I'll update Bastion if needed after this is merged.

**Comment by domcleal** [comment]
You will need to update bastion, as the gem deps specify ~> 0.0.4...

**Comment by ehelms** [comment]
https://github.com/theforeman/foreman-packaging/pull/525

**Comment by domcleal** [comment]
:+1:  to this otherwise.

**Pull request merged**
