### PR TITLE
Fixes #36086 - Allow openscap 1.3.7

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
Repoclosure complains about the `rubygem-openscap` in the repo, not the updated one.

**Review by ekohl — APPROVED** [review]
This doesn't break non-stream, does it?

**Comment by evgeni** [comment]
> This doesn't break non-stream, does it?

Correct, non stream just has an older version, and we have a range defined ;)

**Comment by lpramuk** [comment]
Can't we just say `openscap < 1.4` to have less work ?

**Comment by ekohl** [comment]
That's a valid question. I first assumed this compiled something, but now I question that. It loads it here:
https://github.com/OpenSCAP/ruby-openscap/blob/1aa57405bd277022e91c3763b8b7fb27e0662c70/lib/openscap/openscap.rb#L7

So now I"m questioning it. Why do we even need this?

I recall we had this for EL7 & EL8 compatibility, but I think we can simplify it. I've opened https://github.com/theforeman/foreman-packaging/pull/9051 to see if that works.

**Pull request merged**
