### PR TITLE
Update rubygem-foreman_ansible to 2.3.0

### PR DESCRIPTION
**Pull request by ares**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.20
* [ ] 1.19
* [ ] 1.18

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ares** [comment]
I suppose this was blocked on REX need of rebuild because of assets

```
DEBUG util.py:491:  Error: Package: tfm-rubygem-foreman_remote_execution-1.6.4-2.fm1_21.el7.noarch (build)
DEBUG util.py:491:             Requires: foreman-webpack-vendor-js(3b1dfdc9c8df0ab8e967)
```

I see 1.6.5 has been published, so retrying [test_rpm]

**Comment by ares** [comment]
oh I see https://github.com/theforeman/foreman-packaging/pull/3246 now

**Comment by ekohl** [comment]
[test rpm] since rex was rebuilt

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
