### PR TITLE
Release tfm-rubygem-bastion 6.1.9

### PR DESCRIPTION
**Pull request by ehelms**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.17
* [ ] 1.16
* [ ] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
@ekohl Noticed the `rpm` job is not waiting for tasks to complete. This adds a commit to use `kkoji` per most user configurations as the Koji command and relies on -- https://github.com/theforeman/foreman-infra/pull/504

**Comment by ekohl** [comment]
Should it be done in the obal definition perhaps? Since it's more how a system is configured.

**Comment by ehelms** [comment]
@ekohl What is the 'obal definition' ?

**Comment by ekohl** [comment]
@ehelms the ```obal {}``` part in jenkins job configuration.

**Comment by ehelms** [comment]
@ekohl Since most users who configure koji, setup it up according to our docs with `kkoji` alias to use, I think its better here for consistency.

http://projects.theforeman.org/projects/foreman/wiki/Koji

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Pull request merged**
