### PR TITLE
Fixes #25804 - Update rubygem-gettext_i18n_rails to 1.8.0

### PR DESCRIPTION
**Pull request by ezr-ondrej**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.20
* [ ] 1.19

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ekohl** [comment]
ok to test

**Comment by ezr-ondrej** [comment]
Probably will be better, sorry, kind of habbit - Refs in my opinion should have link the commit with Redmine, but not close the redmine issue as Fixes

**Comment by ekohl** [comment]
That is indeed the difference. In this case the issue reads as just a packaging issue so doesn't this exactly cover that?

The real reason it wasn't linked is that the commit message itself doesn't have the `Refs` nor `Fixes` part. The bot ignores the actual PR title, but I didn't see that previously. This is true for all repositories where the bot is active, but here a Redmine issue isn't required so it doesn't complain.

**Comment by ares** [comment]
So what's the status here, does the commit message need to be changed? All seems green

**Comment by ezr-ondrej** [comment]
I have amended the commit to have the Fixes #25804, I thought is not necessary as the squash commit would have done it, but I guess is better to be there right away.

**Pull request merged**
