### PR TITLE
Update rubygem-hammer_cli_foreman to 0.19.7

### PR DESCRIPTION
**Pull request by ofedoren**

### CODE REVIEW

**Comment by xprazak2** [comment]
@ofedoren, could you rebase please?

**Comment by ofedoren** [comment]
@xprazak2, done.

**Comment by xprazak2** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by zjhuntin** [comment]
[test rpm]

**Comment by pcreech** [comment]
[test rpm]

**Comment by pcreech** [comment]
Hrm, looks like `hammer_cli_foreman-0.19.6.gem` wasn't removed from the `packages/foreman/rubygem_hammer_cli_foreman/ directory` @ofedoren Can you remove that file and try again?

**Comment by ofedoren** [comment]
Oh, you're right, I've totally overlooked that.. Thanks, @pcreech!

**Pull request merged**
