### PR TITLE
Update rubygem-pulp_rpm_client to 3.9.0 for Katello 3.17.3

### PR DESCRIPTION
**Pull request by pcreech**

### CODE REVIEW

**Review by chris1984 — APPROVED** [review]
ACK

**Review by evgeni — CHANGES_REQUESTED** [review]
NACK

Please pick the commits from develop or 2.4, so that git actually matches koji: https://github.com/theforeman/foreman-packaging/commits/rpm/develop/packages/katello/rubygem-pulp_rpm_client

(You'll have to tag that in)

**Comment by pcreech** [comment]
> NACK

bleh, my brain hates me today.  SUch a silly mistake to make.  fixing.

**Comment by pcreech** [comment]
fixed

**Review by evgeni — APPROVED** [review]

**Pull request merged**
