### PR TITLE
Update foreman_openscap to 0.6.1

### PR DESCRIPTION
**Pull request by ares**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.12
* [ ] 1.11
* [ ] 1.10

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by domcleal** [comment]
Could you confirm if you want this built in the 1.13 repos as well as nightly? It came in during branching.

**Comment by domcleal** [comment]
Merged and building for nightly, thanks @ares.

**Comment by domcleal** [comment]
The builds failed as nightly builds of Foreman 1.14 are failing too, will rebuild once #1314 is merged.

**Comment by ares** [comment]
> Could you confirm if you want this built in the 1.13 repos as well as nightly?

yes please both 1.13 and nightly

**Comment by domcleal** [comment]
Cherry-picked to rpm/1.13 as 03826c4, building.

**Pull request merged**
