### PR TITLE
Fixes #25489 - Bump Foreman release for new fog-vsphere

### PR DESCRIPTION
**Pull request by chris1984**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.20
* [ ] 1.19
* [ ] 1.18

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by chris1984** [comment]
@ekohl here is the other pr

**Comment by chris1984** [comment]
@mmoll can I get a review on this, please? The fog-vsphere bump has been merged.

**Comment by chris1984** [comment]
@tbrisker can I get a review on this, please? The fog-vsphere bump has been merged.

**Comment by chris1984** [comment]
> I have no idea of the RPM side, sorry :)

Thanks for trying :beers:

**Comment by ekohl** [comment]
Superseded by https://github.com/theforeman/foreman-packaging/pull/3252

**Pull request closed without merging**
