### PR TITLE
Release Katello 3.11 RC2

### PR DESCRIPTION
**Pull request by ehelms**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.21
* [ ] 1.20

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ekohl** [comment]
This will need Foreman RC3 to be built first.

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
Gem loading error: Could not find 'runcible' (< 3.0.0, >= 2.11.0) - did find: [runcible-2.10.1]

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman-packaging/pull/3400 is probably also needed in the 1.21 branch.

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Pull request merged**
