### PR TITLE
[DEB] Update ruby-dynflow to 0.8.37

### PR DESCRIPTION
**Pull request by adamruzicka**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.17
* [ ] 1.16
* [ ] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by mmoll** [comment]
same gem2deb issue as in GH-2242

**Comment by adamruzicka** [comment]
Reusing this PR to further bump the version to `0.8.37`

**Comment by mmoll** [comment]
[test packaging]

**Comment by mmoll** [comment]
merged, díky @adamruzicka!

**Pull request merged**
