### PR TITLE
[DEB] Update foreman_remote_execution to 1.4.5

### PR DESCRIPTION
**Pull request by ares**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.17
* [ ] 1.16
* [ ] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by dLobatog** [comment]
[test default] - no reason why `rake` and `bundle` wouldn't be on the Jenkins slave

**Comment by mmoll** [comment]
see GH-2155

**Comment by mmoll** [comment]
merged, díky @ares!

**Comment by mmoll** [comment]
@ares does https://github.com/theforeman/foreman/pull/5233 need to get cherry-picked to 1.17?

**Pull request merged**
