### PR TITLE
Introduce two new package groups in package_manifest for foreman-proxy

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
My goal here is to allow easier rebuilds of top level projects. In this case the ability to entirely rebuild the foreman-proxy stack or the foreman-proxy plugin stack.

**Comment by ehelms** [comment]
@pcreech @ekohl @evgeni thoughts on this idea?

**Comment by ehelms** [comment]
In that instance, I would introduce a "common" or some other group that gets included in each group that needs it to denote those packages.

**Comment by pcreech** [comment]
@ehelms Generally, I'm in favor of breaking down large groups into smaller subgroups, to help improve interacting with packaging.  +1000 from me

**Pull request merged**
