### PR TITLE
Foreman 3.1 debian nightly updates

### PR DESCRIPTION
**Pull request by pcreech**

### CODE REVIEW

**Comment by Odilhao** [comment]
We are missing some tarballs for 3.1 
```
00:06:12 + wget http://downloads.theforeman.org/foreman-proxy/foreman-proxy-3.1.0.tar.bz2
00:06:12 --2021-08-06 03:06:12--  http://downloads.theforeman.org/foreman-proxy/foreman-proxy-3.1.0.tar.bz2
00:06:12 Resolving downloads.theforeman.org (downloads.theforeman.org)... 151.101.54.49, 2a04:4e42:d::561
00:06:12 Connecting to downloads.theforeman.org (downloads.theforeman.org)|151.101.54.49|:80... connected.
```

**Comment by pcreech** [comment]
[test deb]

**Comment by pcreech** [comment]
[test]

**Comment by pcreech** [comment]
supderceeded by https://github.com/theforeman/foreman-packaging/pull/6995

**Pull request closed without merging**
