### PR TITLE
Update katello-repos to use Pulpcore 3.49

### PR DESCRIPTION
**Pull request by sjha4**
Related PRs:
https://github.com/theforeman/foreman-packaging/pull/10658
https://github.com/theforeman/pulpcore-packaging/pull/931
https://github.com/Katello/katello/pull/10949

### CODE REVIEW

**Review by evgeni — APPROVED** [review]
ACK once #10678 is in and https://yum.theforeman.org/pulpcore/3.49/ exists (it does not, yet)

**Comment by sjha4** [comment]
Thanks @evgeni ! @theforeman/packaging I believe the rpms are pushed to yum.theforeman.org when the pulpcore nightly pipelines are green. I am not entirely sure why they're failing though.

**Comment by Odilhao** [comment]
We should probably use `nightly` as version for the repo on `develop/nightly` branchs, our plan is to branch 3.49 alongside the next katello release.

**Comment by sjha4** [comment]
Updated to use nightly pulpcore repos based on inputs from @Odilhao ..

**Review by Odilhao — APPROVED** [review]

**Pull request merged**
