### PR TITLE
[DEB] Update kafo to 2.0.2

### PR DESCRIPTION
**Pull request by ares**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.15
* [ ] 1.14
* [ ] 1.13

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by mmoll** [comment]
Working fine here, merged, díky @ares!
Is this a 1.15.2 candiate?

**Comment by ares** [comment]
That would be good, I'll wait for decision in rpm PR and then will let you know.

**Comment by ares** [comment]
@mmoll could you pls build also into 1.15?

**Comment by mmoll** [comment]
already did yesterday 🏗

**Pull request merged**
