### PR TITLE
update clamp to 1.0.0 (DEB)

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by domcleal** [comment]
Do we know if hammer_cli's i18n support is fully compatible with the patch that got merged, or if we need to make any changes first?  (@tstrachota)

**Comment by mmoll** [comment]
From what I saw in the clamp PR it's fully compatible and it works on FreeBSD (where I already updated clamp to 1.0.0) with German and Russian locale.

**Comment by domcleal** [comment]
Ah nice, hammer_cli tests pass too.

**Comment by tstrachota** [comment]
@domcleal it's fully compatible. We've been already using it as a custom patch that is now merged into clamp.

**Comment by domcleal** [comment]
Thanks @mmoll!  Building.

**Pull request merged**
