### PR TITLE
Rebuild foreman_ansible for webpack

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by evgeni** [comment]
ACK on the diff (katello was already rebuilt in https://github.com/theforeman/foreman-packaging/commit/f7e93aae56033e38515bd2cb8bdd11d4080822a6)

I think ansible needs rex to build, so you'd first have to build rex, wait for it to land in the build repo, and then build ansible (AKA: Jenkins' scratchbuild might fail)

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman-packaging/pull/3290

**Comment by ehelms** [comment]
REX can be dropped from here now, its releasing as I type this

**Comment by tbrisker** [comment]
Still failing, it tries to install the previously released rex version which depends on the 670 hash

**Comment by ekohl** [comment]
[test rpm] Probably because the build was started before the old REX was really built and released

**Pull request merged**
