### PR TITLE
Discovery 12.0.2 - RPM

### PR DESCRIPTION
**Pull request by lzap**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.18

Plus https://bugzilla.redhat.com/show_bug.cgi?id=1600621

### CODE REVIEW

**Comment by ekohl** [comment]
[test rpm]

**Comment by lzap** [comment]
Ping.

**Comment by ares** [comment]
[test rpm]

**Comment by evgeni** [comment]
APJ

**Pull request merged**
