### PR TITLE
rubygem-hammer_cli_katello-0.17.0

### PR DESCRIPTION
**Pull request by jturel**
For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [x] 1.21
* [ ] 1.20

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by jturel** [comment]
@ekohl any advice for me on how to interpret and further debug the repoclosure failure here?

**Comment by ekohl** [comment]
Katello wasn't mashed yet which meant there was no repo at http://koji.katello.org/releases/yum/katello-3.11/katello/el7/x86_64/ but now it is so [test rpm]

**Comment by ekohl** [comment]
Now that I'm trying to release it I see this doesn't include the tarball. Looks our pipeline actually downloads it and then it's built (which isn't correct).

**Comment by ekohl** [comment]
(added in de1baddb932035e7e0faddd38b865813f4a90058)

**Comment by jturel** [comment]
Ah, I was wondering about that. Thanks for correcting it.

**Pull request merged**
