### PR TITLE
Update hammer stack to 0.16.0

### PR DESCRIPTION
**Pull request by mbacovsky**
For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [x] 1.21
* [ ] 1.20

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ehelms** [comment]
Since `hammer_cli_foreman` requires `hammer_cli` can you split this into two PRs so the dependency can be merged and built first?

**Comment by mbacovsky** [comment]
@ehelms the hammer-cli-foreman update was moved to separate PR https://github.com/theforeman/foreman-packaging/pull/3373

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm]

**Pull request merged**
