### PR TITLE
Updated hammer_cli_foreman_webhooks to 0.0.3

### PR DESCRIPTION
**Pull request by ofedoren**
(cherry picked from commit e36600295486d6c0fc2fe4b6075bf198d5103049)

### CODE REVIEW

**Comment by Odilhao** [comment]
[test deb]

**Comment by Odilhao** [comment]
pbuilder is failing with:

```
/usr/lib/ruby/vendor_ruby/rubygems/dependency.rb:307:in `to_specs': Could not find 'gssapi' (>= 0) among 81 total gem(s) (Gem::MissingSpecError)
```

**Comment by ekohl** [comment]
[test deb]

**Comment by evgeni** [comment]
[test deb]

**Review by evgeni — APPROVED** [review]

**Pull request merged**
