### PR TITLE
Update rubygem-redhat_access to 2.2.9

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ekohl** [comment]
Related PR: https://github.com/theforeman/foreman-packaging/pull/4081 that also makes it easier to automatically update the dependencies.

**Comment by pcreech** [comment]
[test rpm]

**Comment by pcreech** [comment]
RPM build fails with:
`NameError: uninitialized constant RedhatAccess::Telemetry::LookUps::Katello`

**Comment by zjhuntin** [comment]
[test rpm]

**Comment by evgeni** [comment]
#4755 was merged

**Pull request closed without merging**
