### PR TITLE
[DEB] Update hammer_cli_foreman to 0.12.1

### PR DESCRIPTION
**Pull request by mbacovsky**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.17
* [ ] 1.16
* [ ] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---
Fixes for regressions with Foreman 1.17.

### CODE REVIEW

**Comment by mmoll** [comment]
merged, díky @mbacovsky!

**Comment by mbacovsky** [comment]
@xprazak2 it seems it was not included in foreman 1.17. Could this be fixed for 1.17.2?

**Comment by mmoll** [comment]
@mbacovsky it seems to be in the APT repos, what do you miss? :)

**Comment by mbacovsky** [comment]
@mmoll, you are right, I see it now. I did wrong assumption based on missing it in rpm repos. :man_facepalming:

**Pull request merged**
