### PR TITLE
Update katello to 3.17.3

### PR DESCRIPTION
**Pull request by pcreech**

### CODE REVIEW

**Review by evgeni — APPROVED** [review]

**Comment by chris1984** [comment]
ACK

**Review by chris1984 — APPROVED** [review]

**Comment by evgeni** [comment]
```
Gem loading error: Could not find 'pulp_rpm_client' (< 3.10.0, >= 3.9.0) - did find: [pulp_rpm_client-3.6.2]
```

seem like we need to backport some pulp gems?

**Comment by pcreech** [comment]
@evgeni That's quite a version jump. from 3.6 to 3.9, can we do this in the foreman 2.2/katello 3.17 line?

**Comment by evgeni** [comment]
that's up to @chris1984 and others, from the packaging side there is no reason not to do this.

guess the q is is the 3.9 gem compatible with 3.7 server which is used in 3.17?

**Comment by chris1984** [comment]
@jjeffers do you know if it is compatible?

**Comment by jjeffers** [comment]
> @evgeni this commit was made, so I am guessing yes?
> 
> [Katello/katello@acda546](https://github.com/Katello/katello/commit/acda546a67282da6bd0e843e70fa9786457c6dab)

It looks as if it is, based on the tests passing in 3.17 for that change.

**Comment by pcreech** [comment]
here's the PR updating pulp-rpm-client https://github.com/theforeman/foreman-packaging/pull/6432

**Comment by pcreech** [comment]
[test rpm]

**Review by chris1984 — APPROVED** [review]

**Comment by pcreech** [comment]
[test rpm]

**Comment by pcreech** [comment]
Repoclosure is on pulp_2to3_migration_client.  repo hasn't been mashed yet.  Will be updated when we publish katello.  Merging.

**Pull request merged**
