### PR TITLE
Update hammer_cli_foreman_admin to 0.0.6

### PR DESCRIPTION
**Pull request by lzap**
And no work for Debian as this is a dependency.

### CODE REVIEW

**Comment by domcleal** [comment]
Please indicate which releases this should be built for, it should have been in the PR template.

> And no work for Debian as this is a dependency.

It isn't packaged for Debian, I don't think it's a dependency of anything.

**Comment by lzap** [comment]
I don't mind 1.13 but nightly is ok. I don't use github for filing PRs, sorry haven't noticed that.

**Comment by domcleal** [comment]
Merged, thanks @lzap - building for nightly only. Not sure what you mean by don't mind, if you want it in 1.13 or 1.14, please say so.

**Comment by lzap** [comment]
Thanks, not important updates in this one.

**Pull request merged**
