### PR TITLE
Bump nodejs-patternfly-react to 2.19.0

### PR DESCRIPTION
**Pull request by ohadlevy**
trying out another build based on latest pf version (which works fine with foreman too)

For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.19
* [ ] 1.18
* [ ] 1.17

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ekohl** [comment]
@ohadlevy it looks like my way of dealing with the `/` in package names isn't compatible and I need to flatten it. I was sure I tested it and it worked, but I'll have a stab at this in `npm2rpm` where the real fix must be done.

**Comment by ohadlevy** [comment]
@ekohl is that something you currently work on? this is blocking multiple PR's on foreman that I would hate to miss 1.20 release...

**Comment by ekohl** [comment]
Not yet, mostly because I was away on PTO for a week + a public holiday which means I've only spent time catching up until now. It is good that you reminded me though.

**Comment by ohadlevy** [comment]
what should we do? block foreman PR's or merge and break nightly ? (I would
hope to get this work for 1.20 if possible)...

**Comment by ekohl** [comment]
I'll have a stab at changing npm2rpm to replace `/` with `-` to flatten the file structure.

**Comment by ohadlevy** [comment]
thanks, will this also solve https://github.com/dLobatog/npm2rpm/issues/40#issuecomment-423162407 ? (needed for https://github.com/theforeman/foreman/pull/6056)

**Comment by ekohl** [comment]
In all likeliness yes. I was at least planning on having a look a that as well.

**Comment by ehelms** [comment]
For the time being, you could manually update this PR to try what is being scripted. Which I think would be:

 * modify all paths that look like `nodejs-patternfly-react/@babel/runtime-corejs2-7.0.0.tgz` to instead look like `nodejs-patternfly-react/@babel-runtime-corejs2-7.0.0.tgz`
 * update the spec file sources to reflect that change
 * push updates and see what the scratch build does

This is a bit manual but would allow us to get this moving and unblock the dependent code PRs.

**Comment by ekohl** [comment]
It's possible that with my rewrite this is already solved. I'm going to try to do the same thing and see if it works.

**Comment by ekohl** [comment]
Replacement PR https://github.com/theforeman/foreman-packaging/pull/3063

**Pull request closed without merging**
