### PR TITLE
Update foreman package dependencies

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ohadlevy** [comment]
could you also add nodejs-jed as a dependency ? imho https://github.com/theforeman/foreman/pull/5342 will be merged today.

**Comment by ekohl** [comment]
It fails with a compilation error that I can't quite explain:

```
ERROR in ./webpack/assets/javascripts/react_app/components/AutoComplete/auto-complete.scss
Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve 'react-bootstrap-typeahead/css/Typeahead.css' in '/builddir/build/BUILD/foreman-1.20.0-develop/webpack/assets/javascripts/react_app/components/AutoComplete'
    at factoryCallback (/usr/lib/node_modules/webpack/lib/Compilation.js:282:40)
    at factory (/usr/lib/node_modules/webpack/lib/NormalModuleFactory.js:237:20)
    at resolver (/usr/lib/node_modules/webpack/lib/NormalModuleFactory.js:60:20)
    at asyncLib.parallel.e (/usr/lib/node_modules/webpack/lib/NormalModuleFactory.js:127:20)
    at /usr/lib/node_modules/webpack/node_modules/async/dist/async.js:3888:9
    at /usr/lib/node_modules/webpack/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/usr/lib/node_modules/webpack/node_modules/async/dist/async.js:1062:13)
    at /usr/lib/node_modules/webpack/node_modules/async/dist/async.js:969:16
    at /usr/lib/node_modules/webpack/node_modules/async/dist/async.js:3885:13
    at resolvers.normal.resolve (/usr/lib/node_modules/webpack/lib/NormalModuleFactory.js:119:22)
    at onError (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:65:10)
    at loggingCallbackWrapper (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/usr/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:252:11)
    at /usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/usr/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:252:11)
    at innerCallback (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:144:11)
    at loggingCallbackWrapper (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/usr/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:249:35)
    at resolver.doResolve.createInnerCallback (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6)
    at loggingCallbackWrapper (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:166:11)
    at loggingCallbackWrapper (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/usr/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:249:35)
 @ ./webpack/assets/javascripts/react_app/components/AutoComplete/index.js 51:0-31
 @ ./webpack/assets/javascripts/react_app/components/SearchBar/SearchBar.js
 @ ./webpack/assets/javascripts/react_app/components/SearchBar/index.js
 @ ./webpack/assets/javascripts/react_app/components/componentRegistry.js
 @ ./webpack/assets/javascripts/react_app/common/MountingService.js
 @ ./webpack/assets/javascripts/bundle.js
```

**Comment by Laviro** [comment]
Interesting.. I will look more into it tomorrow :)

**Comment by ohadlevy** [comment]
any chance this is similar to #6043 ? /cc @sharvit

**Comment by ohadlevy** [comment]
@ekohl does the node_modules directory contain ```node_modules/react-bootstrap-typeahead/css/Typeahead.css``` ?

**Comment by ekohl** [comment]
@ohadlevy no, it's an indirect dependency that's bundled via patternfly.

**Comment by ohadlevy** [comment]
@ekohl where can I find the resulting node_modules directory? is it available on koji somewhere?

**Comment by Laviro** [comment]
`react-bootstrap-typeahead/css/Typeahead.css`
is being added to `patternfly TypeaheadSelect` and seem to work there,
maybe it is something with  `foreman css-loaders` ?

There is a small diff between patternfly and foreman scss loaders, but I am not sure it is causing the problem:

Foreman:
```{
      test: /\.css$/,
      loaders: ['style-loader', 'css-loader']
    },
    {
      test: /\.scss$/,
      loaders: ['style-loader', 'css-loader', 'sass-loader']
    },
```

Patternfly:
```{
      test: /\.css$/,
      loaders: ['style-loader', 'css-loader'],
     ...
    },
    // Sass
    {
      test: /\.scss$/,
      use: [
        { loader: 'style-loader' },
        { loader: 'css-loader' },
        ...
      ]
    }
```

**Comment by tbrisker** [comment]
looks like thie is the offensive code: https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-3/patternfly-react/sass/patternfly-react/_type-ahead-select.scss#L1 - patternfly-react seems to expect that on the top level. 
if we can't fix it by tomorrow i'd rather we revert the search change and postpone it to after branching rather than delay branching or branch with broken code.

**Comment by ohadlevy** [comment]
On Tue, Oct 9, 2018 at 11:32 AM Tomer Brisker <notifications@github.com>
wrote:

> looks like thie is the offensive code:
> https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-3/patternfly-react/sass/patternfly-react/_type-ahead-select.scss#L1
> - patternfly-react seems to expect that on the top level.
> if we can't fix it by tomorrow i'd rather we revert the search change and
> postpone it to after branching rather than delay branching or branch with
> broken code.
>
in that case, can't we simply package it as a top level?

**Comment by ohadlevy** [comment]
@tbrisker I find it odd, as patternfly require a lot of packages, and so far we had no problems with yet, I assume here there is something to do with how the node_modules we generate looks like using packages, if we have a way to get a sample of it, maybe we can figure out whats exactly wrong. regardless, I would hope just packaging it as top level can solve the issue?

**Comment by ekohl** [comment]
I do think packaging it at the top level would be a short term fix. Previously the package was unbundled so perhaps that's why we weren't seeing it. Perhaps the `~package` import always expects things to be at the top level though I wonder why that isn't the case with a `npm install`.

**Comment by ekohl** [comment]
I stand corrected: after `npm install` it does show at the top level of `node_modules`. It looks like npm prefers to install at the top level but only bundle if there's a conflict. I've tried to keep as much packages unbundled because I thought it was cleaner. Looks like that approach is closer to matching what npm does already.

**Comment by ohadlevy** [comment]
@ekohl are you suggesting the package is on the top level already? (and that webpack can't find it regardless?)
@tbrisker another work around we can do is simply copying the relevant css to our code, and drop the import statement, removing the entire search feature imho should be last resort... :(

**Comment by ekohl** [comment]
> @ekohl are you suggesting the package is on the top level already? (and that webpack can't find it regardless?)

No, I'm saying we have most packages at top level but with patternfly we switched from unbundled to bundled in the latest update. That's why we might be seeing this now and not before.

**Comment by ohadlevy** [comment]
> No, I'm saying we have most packages at top level but with patternfly we switched from unbundled to bundled in the latest update. That's why we might be seeing this now and not before.

so in this case, maybe even reverting won't help as its just the first error out of a few others...?

**Comment by tbrisker** [comment]
OK, what is the next step than? Should we return patternfly-react to be unbundled?

**Comment by Laviro** [comment]
In case we don't want the `SearchBar styles` to block this PR
and until we decide whether to change patternfly-react bundle or not,
I've created this [PR](https://github.com/theforeman/foreman/pull/6125), 
where we save locally that css file we need to import.

**Comment by ekohl** [comment]
> OK, what is the next step than? Should we return patternfly-react to be unbundled?

I am leaning to that yes.

**Comment by tbrisker** [comment]
@ekohl let's do that then, we need to have working nightlies prior to branching.

**Comment by ekohl** [comment]
For completeness: https://github.com/theforeman/foreman-packaging/pull/3077

**Comment by tbrisker** [comment]
[test rpm]

**Comment by ekohl** [comment]
Looks like our repoclosure check doesn't take repositories into account. nodejs-invariant is in the katello repository but Foreman can't use that. Going to do some shuffling

**Comment by ekohl** [comment]
I stand corrected, it was a release issue. foreman-packaging-release can't deal with a package already existing and http://koji.katello.org/koji/buildinfo?buildID=27723 was already built. It was skipped but is tagged to the wrong repo. During the PR it was built locally as a scratch and so repoclosure passed.

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
Since it's green now, I'm going to merge this. Haven't verified the actual in UI functionality but it'll at least unblock our builds.

**Comment by tbrisker** [comment]
Thanks for all the hard effort @ekohl !

**Comment by ohadlevy** [comment]
+1 thanks!

**Pull request merged**
