### PR TITLE
set the prerelease of katello to master

### PR DESCRIPTION
**Pull request by evgeni**
This technically breaks upgrades between nightlies, but I am not sure we care? :)

For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.20
* [ ] 1.19
* [ ] 1.18

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ekohl** [comment]
Weren't we waiting for 3.10 to do this?

**Comment by evgeni** [comment]
Why? The current nightlies represent the state of "to be 3.10", no?

**Comment by ekohl** [comment]
Not sure we actually clean nightly directories and we decided to avoid this problem by only applying this change until after 3.10 was branched. So technically we'd start doing this on 3.11.

**Comment by evgeni** [comment]
oh ok, shall I close this then for now?

**Pull request closed without merging**
