### PR TITLE
Update nightly versions to 3.0

### PR DESCRIPTION
**Pull request by tbrisker**
This will likely fail until all source pipelines finish running.

### CODE REVIEW

**Comment by ekohl** [comment]
Odd failure for the F29 failure:
DEBUG util.py:600:    Status code: 404 for http://koji.katello.org/kojifiles/external-repos/www/fedora29-x86_64/RPMS.os/audit-libs-3.0-0.4.20180831git0047a6c.fc29.x86_64.rpm (IP: 172.30.3.224)

**Comment by tbrisker** [comment]
possible network glitch?

**Comment by ehelms** [comment]
> Odd failure for the F29 failure:
> DEBUG util.py:600: Status code: 404 for http://koji.katello.org/kojifiles/external-repos/www/fedora29-x86_64/RPMS.os/audit-libs-3.0-0.4.20180831git0047a6c.fc29.x86_64.rpm (IP: 172.30.3.224)

I think sometimes this is intermittent or just means we need to regen the repo for the build tag.

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
I regenerated the repository and things look good now.

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
Fails repoclosure as expected

**Review by ehelms — APPROVED** [review]

**Pull request merged**
