### PR TITLE
plugins:foreman_ansible - 1.0 (RPM)

### PR DESCRIPTION
**Pull request by dLobatog**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.12
* [ ] 1.11
* [ ] 1.10

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

Limited to 1.12 because of ActiveJob (Rails 4.2)

### CODE REVIEW

**Comment by domcleal** [comment]
Please add `%foreman_db_migrate` and `%foreman_db_seed` to the %posttrans scriptlet, as this version now includes DB migrations and seed files.

**Comment by dLobatog** [comment]
Added the %posttrans section

**Comment by domcleal** [comment]
Merged and will build for both releases, thanks @dLobatog.

**Comment by domcleal** [comment]
Oh, don't forget to add/push a tag for the project release.

**Comment by dLobatog** [comment]
Sure, thanks :smile:  - I normally build whatever is on master so I forgot

**Pull request merged**
