### PR TITLE
Updating abrt packages

### PR DESCRIPTION
**Pull request by lzap**
Two commits in one PR

### CODE REVIEW

**Comment by domcleal** [comment]
You'll need to re-add foreman_abrt to comps, it was removed due to the incompatibility.

**Comment by lzap** [comment]
Done!

**Comment by domcleal** [comment]
Thanks @lzap!  I'll build them now for nightly.

**Comment by lzap** [comment]
Debians too, or is this also automatic?

**Comment by domcleal** [comment]
I don't think either plugin has been packaged for Debian.

**Comment by domcleal** [comment]
Should both packages be built for the 1.11 repos as well as nightly?  http://projects.theforeman.org/issues/15259 suggests foreman_abrt is required, and is the proxy update compatible/required with 1.11?

**Comment by lzap** [comment]
Yup it was broken for some time now.

**Comment by lzap** [comment]
This fixed it: https://github.com/theforeman/foreman_abrt/pull/7

**Comment by domcleal** [comment]
OK, I've cherry picked this to rpm/1.11 and will retag the smart proxy build.

**Pull request merged**
