### PR TITLE
Pulpcore 3.11 client bindings

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
needs to wait on https://github.com/Katello/katello/pull/9255

**Comment by evgeni** [comment]
Needs rebase after Erics mass rebuild.

Why does it remove `rubygem-pulp_2to3_migration_client`? Because there will be no more migrations in 4.0→4.1?

**Comment by evgeni** [comment]
Should something (f-m content remove-pulp2) also purge the package from systems then?

**Comment by jlsherrill** [comment]
so the remove rake task will be run on 4.0, but this gem isn't actually removed until 4.1 (unless we backport the removal).  Would obsoleting it in the rubygem-katello rpm for a few releases be a bad idea?

**Comment by jlsherrill** [comment]
also, we will need to keep shipping and updating the server component of the migration plugin until we have a 'removal process' from the pulp team.

**Comment by evgeni** [comment]
Yeah, `Obsoletes` in `rubygem-katello` is probably not a great but a workable solution.

@ehelms @pcreech? What do y'all think?

**Comment by pcreech** [comment]
I can't think of a better process currently.

**Comment by ekohl** [comment]
I think traditionally we've used the `tfm` package to obsolete packages in the SCL. If it's only EL7 that could also be a solution. Wouldn't work on EL8 though.

**Comment by evgeni** [comment]
It is on EL8 with Katello 4.0 ;)

**Comment by ehelms** [comment]
Sounds like `rubyem-katello` it is.

**Comment by jlsherrill** [comment]
Katello PR here: https://github.com/theforeman/foreman-packaging/pull/6517  

i think this is good to go?

**Comment by evgeni** [comment]
With https://github.com/Katello/katello/pull/9255 now merged: yes.

Thanks!

**Review by evgeni — APPROVED** [review]

**Pull request merged**
