### PR TITLE
Update repository urls

### PR DESCRIPTION
**Pull request by xprazak2**
For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [x] 1.17
* [ ] 1.16
* [ ] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

This slipped through the cracks somehow.

### CODE REVIEW

**Comment by ekohl** [comment]
Should the foreman-release package also be bumped?

**Comment by xprazak2** [comment]
I do not follow, the [release](https://github.com/theforeman/foreman-packaging/blob/rpm/1.17/foreman/foreman.spec#L18) should be [0.1](http://projects.theforeman.org/projects/foreman/wiki/Release_Process#Packaging-a-release) for RCs and URL should point to 1.17 according to [main repos release docs](http://projects.theforeman.org/projects/foreman/wiki/Release_Process#Main-code-repos), step 5.

**Comment by ekohl** [comment]
http://koji.katello.org/koji/buildinfo?buildID=23903 has already been built with the old repos. I believe the next steps will use this built RPM so you need to be sure that gets rebuilt with these new files. Bumping to 0.2 is a sure way to do so.

**Comment by xprazak2** [comment]
Oh, I see.

**Comment by ekohl** [comment]
While you're at it: I also noticed an error: https://github.com/theforeman/foreman-packaging/blob/873ab2e6115b1646829e715657f6d75e9479db2a/foreman/foreman.spec#L756

This needs to be ```3.23.0``` to match https://github.com/theforeman/foreman/blob/157f5e653d870c552bde0b67bcf86c12190d801a/bundler.d/assets.rb#L3

**Pull request merged**
