### PR TITLE
Require puppet-agent 6.15.0+ in foreman-installer

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by evgeni** [comment]
This should be updated to 6.15 to match #6675?

Not that we need modularity support on Debian, but given we don't test anything older…

**Comment by ekohl** [comment]
I'd say the same thing. In fact, it'll fail otherwise:
https://github.com/theforeman/kafo/blob/a45b1ebedda66cdf460c3fe5bfbb3696f2bd198f/lib/kafo/puppet_command.rb#L86-L99
We do ship all modules (even unused ones) to Debian and that glob version check will ensure it fails if any module doesn't match. That's why I suggested to go straight to 6.15.0 in https://github.com/theforeman/foreman-installer/blob/3cbb7bd7201654a491a927cbb3d6867f50523c99/spec/puppet_version_spec.rb#L5.

**Comment by ehelms** [comment]
Yea, I was just waiting for agreement over here https://github.com/theforeman/foreman-packaging/pull/6675 before I updated everywhere.

**Comment by ehelms** [comment]
Updated to 6.15.0

**Review by ekohl — CHANGES_REQUESTED** [review]
Code wise :+1: but the commit message should reflect the version number. Also, is there a Redmine issue?

**Comment by ehelms** [comment]
Updated commit message with a Redmine

**Review by ekohl — APPROVED** [review]

**Pull request merged**
