### PR TITLE
[1.22] Update rubygem-foreman_ansible to 3.0.3

### PR DESCRIPTION
**Pull request by ares**
(cherry picked from commit 1036fbc4501b546e6f728d4fdf7379897cbbf13e)

### CODE REVIEW

**Comment by ekohl** [comment]
In cherry picking to 1.22 I missed 996828154aef5d8b93f2785bf974927cf8bb7a4a and that breaks rebuilds. Would you mind squashing it into this PR?

**Comment by evgeni** [comment]
Also, should this be updated to 3.0.5?

**Comment by ehelms** [comment]
@ares is this still a valid PR?

**Comment by ares** [comment]
last released version in the repo is 3.0.2, so this is still good to have if noone will cherry-pick https://github.com/theforeman/foreman-packaging/pull/3936 instead (3.0.5)

**Pull request merged**
