### PR TITLE
[CP] Katello 3.7 picks

### PR DESCRIPTION
**Pull request by jturel**

### CODE REVIEW

**Comment by jturel** [comment]
[test rpm]

**Comment by jturel** [comment]
@ehelms is this failure expected / known?

**Comment by ekohl** [comment]
@jturel we need a few cherry picks, we're talking about it *right* now

**Comment by jturel** [comment]
@ekohl looks like #2753  was merged - good here then?

**Comment by ekohl** [comment]
[test rpm]

**Pull request merged**
