### PR TITLE
Bump rubygem-redhat_access to 2.2.11-1

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
@ares @ekohl mind having a look at this?

**Comment by evgeni** [comment]
should obsolete #4521 and #4081

**Comment by evgeni** [comment]
not sure we actually need apipie and assets as added by the template?

**Comment by ares** [comment]
I was able to verify the plugin installs and generally works, however the planner and manage page are still making the menu disappear. :+1: for this version though.

**Comment by evgeni** [comment]
You're saying "still", so that error existed before and is not something I introduced by  slightly changing how the package is built? Cool.

**Comment by ares** [comment]
yes, I've seen that before (https://bugzilla.redhat.com/show_bug.cgi?id=1805141)

**Comment by evgeni** [comment]
> I think `%{gem_instdir}/public` in files is now redundant.

No, because `foreman_assets_plugin` resolves to `%{gem_instdir}/public/assets/%{gem_name}`, so only a part of `public`, but we install into `public/assets/insights`, not `public/assets/redhat_access`

**Comment by evgeni** [comment]
@ares shall we backport that to any stable releases?

**Comment by ares** [comment]
I'd wait until some user asks for it, something tells me, we won't see such request

**Pull request merged**
