### PR TITLE
Release 1.16.2 [rpm]

### PR DESCRIPTION
**Pull request by dLobatog**
Signatures already uploaded. Please make sure tests are green before merging

### CODE REVIEW

**Comment by dLobatog** [comment]
@ekohl Looks like there's a problem with kafo & foreman-installer, have you ever seen this? http://koji.katello.org/kojifiles/work/tasks/1823/101823/build.log

**Comment by ekohl** [comment]
@dLobatog I have - @xprazak2 ran into it too last time. The problem was that the tarball actually contained no modules. Please be careful when removing it though ;) Also, the CDN caches download.theforeman.org so I may need to purge the cache for you. I'll have a look.

**Comment by ekohl** [comment]
[test packaging]

**Comment by dLobatog** [comment]
@ekohl Updated with the new tarball

**Comment by mmoll** [comment]
merged, gracias @dLobatog!

**Comment by dLobatog** [comment]
http://koji.katello.org/koji/taskinfo?taskID=102002 - foreman
http://koji.katello.org/koji/taskinfo?taskID=102004 - foreman-selinux
http://koji.katello.org/koji/taskinfo?taskID=102007 - foreman-proxy
http://koji.katello.org/koji/taskinfo?taskID=102006 - foreman-installer

**Pull request merged**
