### PR TITLE
Update rubygem-foreman_google to 1.0.2

### PR DESCRIPTION
**Pull request by stejskalleos**

### CODE REVIEW

**Comment by stejskalleos** [comment]
TODO: Cherry-pick to it to `rpm/3.5`

**Review by evgeni — APPROVED** [review]

**Comment by evgeni** [comment]
same for debian?

**Comment by stejskalleos** [comment]
> same for debian?

I'll wait with debian until 6.13 is finished

**Comment by evgeni** [comment]
> > same for debian?
> 
> I'll wait with debian until 6.13 is finished

why?

**Comment by stejskalleos** [comment]
Because the rpm release is mainly for 6.13, and I guess there will be  more fixes after testathon, so doing 4 package PRs for each 1.0.x version (including cherry-picks to 3.5) is something I **really** don't want to do.

**Pull request merged**
