### PR TITLE
Bump plugin releases

### PR DESCRIPTION
**Pull request by ehelms**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.16
* [ ] 1.15
* [ ] 1.14

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ehelms** [comment]
First set of failures was due to buildroot needing updating. Going to re-run after I update it.

**Comment by ehelms** [comment]
[test]

**Comment by ekohl** [comment]
Something isn't quite right yet in the build env:
```
DEBUG util.py:439:  Error: Package: tfm-build-4.0-1.el7.x86_64 (build)
DEBUG util.py:439:             Requires: tfm-ror51-scldevel
DEBUG util.py:439:   You could try using --skip-broken to work around the problem
DEBUG util.py:439:   You could try running: rpm -Va --nofiles --nodigest
DEBUG util.py:439:  Error: Package: tfm-runtime-4.0-1.el7.x86_64 (build)
DEBUG util.py:439:             Requires: tfm-ror51-runtime
```

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
@ekohl this first round of updates is passing, my goal after this would be to figure out which plugins pass today and get those updated

**Pull request merged**
