### PR TITLE
Update katello package dependencies

### PR DESCRIPTION
**Pull request by ekohl**
This will probably fail to build since master has been bumped to 3.16 causing a version mismatch, but this should be included in 3.15.0 RC1.

### CODE REVIEW

**Comment by ekohl** [comment]
Fails due to https://github.com/Katello/katello/pull/8558

**Comment by tbrisker** [comment]
can you please reopen this against `rpm/2.0`?

**Comment by ehelms** [comment]
@ekohl needs a rebase

**Comment by ekohl** [comment]
Regenerated

**Pull request merged**
