### PR TITLE
Add get_process_mem package

### PR DESCRIPTION
**Pull request by ShimShtein**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.15
* [ ] 1.14
* [ ] 1.13

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by iNecas** [comment]
[test]

**Comment by domcleal** [comment]
What is this, how is it used? It doesn't appear to be a plugin.

**Comment by ShimShtein** [comment]
It will be used in [foreman-tasks](https://github.com/theforeman/foreman-tasks/pull/216) to monitor memory consumption of dynflow executor.

**Comment by domcleal** [comment]
Oh right, but if it's not even merged and released, then I'll leave this until a more useful point in time. Please fix the "FIXME" comments before then.

**Comment by iNecas** [comment]
We have a chicken&egg problem here and once merged, we want to have the packaging ready, so this is not that bad time.

**Comment by ShimShtein** [comment]
Removed the FIXME comment: no action was needed (it should be in foreman scl)

**Comment by iNecas** [comment]
The more useful in time happened now https://github.com/theforeman/foreman-packaging/pull/1659

**Comment by ShimShtein** [comment]
Changes according to @domcleal's review.

**Comment by ShimShtein** [comment]
Now the package builds correctly using local tito and mock.

**Comment by domcleal** [comment]
[test] as Koji appears to be online again.

**Comment by ShimShtein** [comment]
[test] The failure does not seem to be related to the PR.

**Comment by iNecas** [comment]
The builds are passing now

**Pull request merged**
