### PR TITLE
Update katello to 4.4.0-rc2

### PR DESCRIPTION
**Pull request by zjhuntin**

### CODE REVIEW

**Comment by evgeni** [comment]
seems it tried to build nightly bits, as there are still references to it in the config.

raised https://github.com/theforeman/foreman-packaging/pull/7668 to fix it

**Comment by ekohl** [comment]
That's merged, please rebase.

**Comment by ekohl** [comment]
```
Gem loading error: Could not find 'pulp_rpm_client' (>= 3.17.0, < 3.18.0) - did find: [pulp_rpm_client-3.16.1]
```

**Comment by zjhuntin** [comment]
[test rpm]

**Comment by ekohl** [comment]
@zjhuntin cat we get the correct RC version in the commit message? latest obal should do this already.

**Pull request merged**
