### PR TITLE
update foreman_templates to 2.0.3 (DEB)

### PR DESCRIPTION
**Pull request by GregSutcliffe**
Deb changes for templates 2.0.2. Should be suitable for 1.10 / 1.9 but currently untested by me.

### CODE REVIEW

**Comment by mmoll** [comment]
that should wait for 2.0.3, because of theforeman/foreman_templates#21

**Comment by GregSutcliffe** [comment]
Apologies, I pushed this to theforeman instead of to my fork when updating. I've not started any builds, just in case there's still issues.

**Comment by mmoll** [comment]
6fac47b for reference

**Comment by mmoll** [comment]
built and tested, seems fine to me, thanks @GregSutcliffe!

**Pull request closed without merging**
