### PR TITLE
backport pulp 3.4 to 2.1

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
Jenkins doesn't seem to like the the backport (wants a release reset to 1).  I guess typically we just merge this stuff and tag them back to 3.16?

**Comment by evgeni** [comment]
@jlsherrill yeah, but also https://github.com/theforeman/foreman-infra/pull/1392 because I was annoyed by this check in the past :)

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
old files are not deleted, thus the build fails

**Comment by jlsherrill** [comment]
[test rpm]   grrrrr centos 8

**Comment by jlsherrill** [comment]
still a 404, i guess we have to wait? 


DEBUG util.py:600:  Error: Error downloading packages:
DEBUG util.py:600:    Status code: 404 for http://mirror.centos.org/centos/8/BaseOS/x86_64/os/Packages/audit-libs-3.0-0.13.20190507gitf58ec40.el8.x86_64.rpm (IP: 67.219.148.138)

**Comment by evgeni** [comment]
Maybe try a regen-repo?

**Comment by pcreech** [comment]
[test rpm]

**Comment by pcreech** [comment]
[test rpm]

**Comment by evgeni** [comment]
Why is it trying to build sub man on el8? Did we forget to configure tito to exclude that package there?

**Comment by jlsherrill** [comment]
yep, forgot a tito.props update, fixed

**Comment by jlsherrill** [comment]
thanks, will start the tagging!

**Pull request merged**
