### PR TITLE
Update Rails stack to 6.0.6

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
> https://github.com/theforeman/foreman/blob/3.3-stable/Gemfile#L10 should also be updated? :)

Blast it, I thought we had stopped being that restrictive.

**Comment by evgeni** [comment]
> Although, I thought bundler_ext mean that it did not enforce the version constraints -- guess I'd have to check that.

That'll might be correct for RPM (which you're adjusting here), but we also could update Debian is the same go? :)

**Comment by ehelms** [comment]
> Not to derail the conversation, but I think we should reconsider the use of `bundler_ext`. Nowadays we actually respect the Bundler/gemspec dependencies and patch them if needed. I'm not sure what else it actually does for us.

Sounds like we should file an issue so we can take a more dedicated look.

**Comment by ehelms** [comment]
> That'll might be correct for RPM (which you're adjusting here), but we also could update Debian is the same go? :)

Pfffft, that's fair, having two different styles gets hard to remember sometimes. To @ekohl, not using bundler_ext, if that will work for us, would help keep that alignment to some degree. 

I shall also have to update the Foreman RPM which has it's dependencies locked down due to the Gemfile.

**Review by evgeni — APPROVED** [review]
Same comment as in #8760, this doesn't update the `Requires` lines, rendering the packages uninstallable in the end.

**Review by evgeni — CHANGES_REQUESTED** [review]
Err, wrong button, of course

**Comment by ekohl** [comment]
Given 3.3 is EOL, should we close this?

**Comment by evgeni** [comment]
> Given 3.3 is EOL, should we close this?

Yes.

**Pull request closed without merging**
