### PR TITLE
Update foreman_ansible to 1.3.1 [rpm]

### PR DESCRIPTION
**Pull request by dLobatog**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.14
* [x] 1.13
* [ ] 1.12

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

Thanks!

### CODE REVIEW

**Comment by domcleal** [comment]
[test] Koji client config fixed.

**Comment by dLobatog** [comment]
This one is failing because foreman 1.14 develop asks for scoped_search < 4.0 but the one available is 4.0

**Comment by domcleal** [comment]
[test] with an override in place.

**Comment by domcleal** [comment]
[test] override fixed.

**Comment by domcleal** [comment]
Merged and building, thanks @dLobatog.

**Pull request merged**
