### PR TITLE
fixes #4841 - add tfm SCL source package

### PR DESCRIPTION
**Pull request by domcleal**
For review/example purposes only right now, ~~waiting on a release of RHSCL 1.1 and rebuilds~~.

The spec file will build a new top level SCL package using whichever Ruby and v8 packages it finds in the buildroot (else it'll default to ruby193/v8314).  So you'd set up a buildroot containing:

* ruby193-scldevel
* v8314-scldevel

You'd build tfm inside that buildroot and you'd get a set of binary packages out:

* tfm: top-level package which is supposed to install every other package in the collection (meh..) & dependency collections
* tfm-runtime: contains the enable snippet to set correct paths and loads our dependency collections automatically (so no more hacks in ruby-wrapper) using the scl_source command (new in 1.1)
* tfm-build: gets added to our own buildroot for building subsequent 'tfm' packages, we shouldn't publish this
* tfm-scldevel: published so others (katello?) can create new collections that depend on ours by referencing %{scl_prefix_tfm} in their spec files

If we ever want to start using ruby200 (which'll be possible once we move to ror40), then we just swap ruby193-scldevel for ruby200-scldevel in our buildroot, rebuild tfm and then mass-rebuild all packages inside tfm and we'll get it automatically.  We can also start using other collections like postgresql9* or mariadb/mysql55.

Note that I haven't elected to use a version number inside the SCL name.  The simple reason is that I don't see us ever wanting multiple versions of tfm installed simultaneously, because tfm isn't designed for direct consumption by users.  We publish packages like Foreman that depend on it, which aren't really SCL'd themselves and can only be installed once.  Not having the version in the name also means users don't get multiple versions of tfm installed as they move through Foreman releases.

I included an example of updating an existing spec file (discovery) to reference the correct SCL for its ruby193 dependencies, which relies on the macros defined in in RHSCL 1.1.  It also obsoletes the old 'ruby193' version we built inside that collection.

TODO:

1. foreman.spec should use `Requires: %scl_require tfm`, perhaps specific versions too
1. packages inside tfm should all have `%{?scl:Requires: %{scl}-runtime}`
1. convert every tfm package to use scl_prefix_ruby where applicable
1. adopt ruby-wrapper inside tfm, perhaps in -runtime?
1. update foreman-selinux for non-ruby193 paths
1. may need to add a vendor prefix, as SCL folks are preferring this now

(https://access.redhat.com/site/documentation/en-US/Red_Hat_Developer_Toolset/2/html-single/Software_Collections_Guide/index.html for futher reading)

### CODE REVIEW

**Comment by domcleal** [comment]
A little update for anybody following along at home.  I've converted all spec files to point to the right collections, obsoleted the old packages, changed /opt/rh to /opt/theforeman and fixed a few more issues.

The mass rebuild of the entire repository appears to work, including plugins that are built on Foreman.  Remarkably, the [yum upgrade transaction also appears correct](http://paste.fedoraproject.org/182435/32342351), though I haven't tested it yet due to lack of Passenger.  Some items remain:

1. move ruby-wrapper inside tfm-runtime
1. update foreman-selinux for non-ruby193 paths
1. update puppet-foreman for non-ruby193 prefix
1. get rubygem-passenger to build and work
1. update comps, rel-eng

**Comment by domcleal** [comment]
Me rambling for 36 minutes on the subject, if anybody wants an intro and walkthrough of the changes: https://www.youtube.com/watch?v=gSEw6w2wem8

**Comment by ehelms** [comment]
@domcleal 

1) I wanted to double check that any packages building into the current ruby193 SCL (such as some of the ones Katello maintains) should still work after this change? I'd prefer we do this in lockstep or follow closely, but history says there will be a delay.
2) Can you let me know once you have a testable scenario so that I may do some testing of our own as early as I can with respect to installs and upgrades? 
3) Is there a policy around what builds into `tfm-` that you would like to attempt to enforce? I ask for the sake of Katello, 'official' plugins and third party developers.

**Comment by domcleal** [comment]
1) other ruby193 packages will _only_ work if they depend on packages that are part of the original ruby193 collection or are also extras.  Other packages that depend on Foreman-produced ruby193 packages wouldn't resolve deps, as ours are renamed.  (We'll supply "Obsoletes", but I don't intend to continue "Providing" ruby193.)
2) sure!  I hope to get back to this in a couple of weeks and get the last build issues sorted and publish a test repo.  What I have isn't of much use to others right now.
3) no, and I don't intend to restrict the distribution of our tfm-build package to curb it (as RHSCL does).  However I'd strongly encourage Katello and other layered things to layer on top again, as it'll let you add dependencies as you want (e.g. Pulp might want a newer Python or something) and will prevent any package name conflicts.

**Comment by domcleal** [comment]
The last major issues - incorrect Obsoletes in non-SCL and subpackages, Passenger builds - are fixed and I've now tested the upgrade successfully, with every Foreman plugin and ruby193 package installed (not recommended!).

There's a repo of EL7 builds at https://fedorapeople.org/~domcleal/foreman/tfm_repo/ - use 1.8 as a base (nightly might be newer than those builds), add the repo and `yum upgrade ruby193\* foreman\*`.

The other change is that I deleted ruby193-ruby-wrapper and simply incorporated it into tfm-runtime, with a compatibility symlink for ruby193-ruby because it's configured as people's PassengerRuby.  We can get rid of that later - otherwise /usr/bin/tfm-{rake,ruby} will be used automatically by other packages.

tfm as a prefix seemed to be preferred on foreman-dev: https://groups.google.com/forum/#!topic/foreman-dev/oj-TLTgLcQs

Before merge, I need to fix the Foreman versioning stuff in #627, which depends on a new release of tito (soon).  Then a small couple of updates to puppet-foreman & foreman-selinux, a sed in comps/ and it's ready.

**Comment by domcleal** [comment]
I'm ready to merge this now - mass rebuild still seems to work fine (repo was refreshed today), and the other part about #627 above has been resolved - plugins now have fm1_10 etc in the release field, and tag_suffix is set in tito.  This'll let us build plugins under the old SCL configuration on the rpm/1.9 branch without duplicate tags or NVRs breaking.

It'll probably take a week or so to build it all and sort out any remaining issues.  @ehelms when's convenient for you for me to start?  I'd like to do this by the end of the month.

**Comment by ehelms** [comment]
I was wanting to run through a test of some of the packages from https://fedorapeople.org/~domcleal/foreman/tfm_repo/ but looks like it contains f22 packages.

**Comment by domcleal** [comment]
Ignore those tags, they're just from the SRPMs I generated.  Click through into the individual dir and you'll see the mock results are actually for el7 :)

**Comment by ehelms** [comment]
I'd like to accomplish the following:

1. Add missing packages to katello-packaging that will have to be converted (PRs open already as well as some to straight remove some old dependencies)
2. Do some updating and testing of katello packages since we include a number of plugins by default and this may find early issues (i.e. get a close to "go" ready as I can get things)

Assuming I can get reviews on my additions and changes, I'd say you could start as early as Wednesday the 19th. Would that work for you?

**Comment by domcleal** [comment]
Sure, that's great, thanks.

**Comment by ehelms** [comment]
I started testing this combined with built Katello packages for installation purposes and ran into the following output:

```
---> Package rubygem-ansi.noarch 0:1.4.3-2.el7 will be installed
---> Package rubygem-hashie.noarch 0:2.0.5-1.el7 will be installed
---> Package rubygem-little-plugger.noarch 0:1.1.3-18.el7 will be installed
---> Package rubygem-mime-types.noarch 0:1.19-3.el7 will be installed
---> Package rubygem-multi_json.noarch 0:1.10.1-1.el7 will be installed
---> Package rubygem-netrc.noarch 0:0.7.7-5.el7 will be installed
---> Package tfm-rubygem-fastercsv.noarch 0:1.5.4-7.git.1396.e8fcc41.el7.centos will be installed
--> Processing Dependency: /opt/theforeman/tfm/root/usr/bin/ruby for package: tfm-rubygem-fastercsv-1.5.4-7.git.1396.e8fcc41.el7.centos.noarch
---> Package tfm-rubygem-hashie.noarch 0:2.0.5-2.git.67.e8fcc41.el7.centos will be installed
--> Processing Dependency: /opt/theforeman/tfm/root/usr/bin/ruby for package: tfm-rubygem-fastercsv-1.5.4-7.git.1396.e8fcc41.el7.centos.noarch
--> Finished Dependency Resolution
Error: Package: tfm-rubygem-fastercsv-1.5.4-7.git.1396.e8fcc41.el7.centos.noarch (foreman-tfm)
           Requires: /opt/theforeman/tfm/root/usr/bin/ruby
```

I believe this is due to the files below having their shebangs automatically replaced with the scl root which ends up pointing into tfm instead of ruby193:

```
[root@katello-centos7 tmp]# grep -r ruby opt/theforeman/tfm/root/usr/share/gems/gems/
opt/theforeman/tfm/root/usr/share/gems/gems/fastercsv-1.5.4/test/tc_csv_writing.rb:#!/opt/theforeman/tfm/root/usr/bin/ruby -w
opt/theforeman/tfm/root/usr/share/gems/gems/fastercsv-1.5.4/test/tc_serialization.rb:#!/opt/theforeman/tfm/root/usr/bin/ruby -w
opt/theforeman/tfm/root/usr/share/gems/gems/fastercsv-1.5.4/test/tc_features.rb:#!/opt/theforeman/tfm/root/usr/bin/ruby -w
opt/theforeman/tfm/root/usr/share/gems/gems/fastercsv-1.5.4/test/tc_interface.rb:#!/opt/theforeman/tfm/root/usr/bin/ruby -w
opt/theforeman/tfm/root/usr/share/gems/gems/fastercsv-1.5.4/test/tc_interface.rb:  def test_long_line # ruby's regex parser may have problems with long rows
opt/theforeman/tfm/root/usr/share/gems/gems/fastercsv-1.5.4/test/tc_row.rb:#!/opt/theforeman/tfm/root/usr/bin/ruby -w
opt/theforeman/tfm/root/usr/share/gems/gems/fastercsv-1.5.4/test/tc_speed.rb:#!/opt/theforeman/tfm/root/usr/bin/ruby -w
opt/theforeman/tfm/root/usr/share/gems/gems/fastercsv-1.5.4/test/tc_table.rb:#!/opt/theforeman/tfm/root/usr/bin/ruby -w
opt/theforeman/tfm/root/usr/share/gems/gems/fastercsv-1.5.4/test/tc_data_converters.rb:#!/opt/theforeman/tfm/root/usr/bin/ruby -w
opt/theforeman/tfm/root/usr/share/gems/gems/fastercsv-1.5.4/test/ts_all.rb:#!/opt/theforeman/tfm/root/usr/bin/ruby -w
opt/theforeman/tfm/root/usr/share/gems/gems/fastercsv-1.5.4/test/tc_csv_parsing.rb:#!/opt/theforeman/tfm/root/usr/bin/ruby -w
opt/theforeman/tfm/root/usr/share/gems/gems/fastercsv-1.5.4/test/tc_csv_parsing.rb:  # Pulled from:  http://www.ruby-lang.org/cgi-bin/cvsweb.cgi/ruby/test/csv/test_csv.rb?rev=1.12.2.2;content-type=text%2Fplain
opt/theforeman/tfm/root/usr/share/gems/gems/fastercsv-1.5.4/test/tc_csv_parsing.rb:  # From:  http://ruby-talk.org/cgi-bin/scat.rb/ruby/ruby-core/6496
opt/theforeman/tfm/root/usr/share/gems/gems/fastercsv-1.5.4/test/tc_encodings.rb:#!/opt/theforeman/tfm/root/usr/bin/ruby -w
opt/theforeman/tfm/root/usr/share/gems/gems/fastercsv-1.5.4/test/tc_headers.rb:#!/opt/theforeman/tfm/root/usr/bin/ruby -w
opt/theforeman/tfm/root/usr/share/gems/gems/fastercsv-1.5.4/examples/csv_table.rb:#!/opt/theforeman/tfm/root/usr/bin/ruby -w
opt/theforeman/tfm/root/usr/share/gems/gems/fastercsv-1.5.4/examples/csv_converters.rb:#!/opt/theforeman/tfm/root/usr/bin/ruby -w
opt/theforeman/tfm/root/usr/share/gems/gems/fastercsv-1.5.4/examples/csv_writing.rb:#!/opt/theforeman/tfm/root/usr/bin/ruby -w
opt/theforeman/tfm/root/usr/share/gems/gems/fastercsv-1.5.4/examples/csv_reading.rb:#!/opt/theforeman/tfm/root/usr/bin/ruby -w
opt/theforeman/tfm/root/usr/share/gems/gems/fastercsv-1.5.4/examples/csv_filter.rb:#!/opt/theforeman/tfm/root/usr/bin/ruby -w
opt/theforeman/tfm/root/usr/share/gems/gems/fastercsv-1.5.4/examples/shortcut_interface.rb:#!/opt/theforeman/tfm/root/usr/bin/ruby -w
opt/theforeman/tfm/root/usr/share/gems/gems/fastercsv-1.5.4/lib/faster_csv.rb:#!/opt/theforeman/tfm/root/usr/bin/ruby -w
opt/theforeman/tfm/root/usr/share/gems/gems/fastercsv-1.5.4/lib/fastercsv.rb:#!/opt/theforeman/tfm/root/usr/bin/ruby -w
```

**Comment by domcleal** [comment]
Thanks for spotting that, I've updated fastercsv in the repo now.  Sorry, I hadn't found time to test that latest rebase, will do properly today.

**Comment by domcleal** [comment]
Fixed a 1.9 upgrade issue, but otherwise looks to be working properly now.

**Comment by ehelms** [comment]
I started testing obsoletes with upgrading the 1.9 Foreman and Katello 2.3 release to the test repo and a test repo of packages in katello-packaging (https://github.com/Katello/katello-packaging/pull/50) and ran into the output below. Since it's towards the end of my day and I am currently perplexed, I thought I'd add it here in case you had thoughts. This seems to be related to the fact that 1.9/2.3 include the non-SCL hammer packages.

```
--> Finished Dependency Resolution
Error: Package: rubygem-hammer_cli_katello-0.0.17-2.el7.noarch (@katello)
           Requires: rubygem(hammer_cli_foreman_bootdisk)
           Removing: rubygem-hammer_cli_foreman_bootdisk-0.1.3-1.el7.noarch (@foreman-plugins)
               rubygem(hammer_cli_foreman_bootdisk) = 0.1.3
           Obsoleted By: tfm-rubygem-hammer_cli_foreman_bootdisk-0.1.3-2.git.61.e8fcc41.el7.centos.noarch (foreman-scl)
               Not found
Error: Package: ruby193-rubygem-hpricot-0.8.6-11.el7.x86_64 (@katello)
           Requires: ruby193-ruby-wrapper
           Removing: ruby193-ruby-wrapper-0.0.2-5.el7.noarch (@foreman)
               ruby193-ruby-wrapper = 0.0.2-5.el7
           Obsoleted By: tfm-runtime-1.1-1.git.0.e8fcc41.el7.centos.x86_64 (foreman-scl)
               Not found
Error: Package: rubygem-hammer_cli_katello-0.0.17-2.el7.noarch (@katello)
           Requires: rubygem(hammer_cli) >= 0.1.3
           Removing: rubygem-hammer_cli-0.3.0-1.el7.noarch (@foreman)
               rubygem(hammer_cli) = 0.3.0
           Obsoleted By: tfm-rubygem-hammer_cli-0.3.0-1.git.28.f38b470.el7.centos.noarch (foreman-scl)
               Not found
           Available: rubygem-hammer_cli-0.2.0-1.el7.noarch (foreman)
               rubygem(hammer_cli) = 0.2.0
Error: Package: rubygem-hammer_cli_katello-0.0.17-2.el7.noarch (@katello)
           Requires: rubygem(hammer_cli_foreman_docker)
           Removing: rubygem-hammer_cli_foreman_docker-0.0.3-2.el7.noarch (@foreman-plugins)
               rubygem(hammer_cli_foreman_docker) = 0.0.3
           Obsoleted By: tfm-rubygem-hammer_cli_foreman_docker-0.0.3-3.git.59.e8fcc41.el7.centos.noarch (foreman-scl)
               Not found
Error: Package: rubygem-hammer_cli_katello-0.0.17-2.el7.noarch (@katello)
           Requires: rubygem(hammer_cli_foreman_tasks) >= 0.0.3
           Removing: rubygem-hammer_cli_foreman_tasks-0.0.7-1.el7.noarch (@foreman-plugins)
               rubygem(hammer_cli_foreman_tasks) = 0.0.7
           Obsoleted By: tfm-rubygem-hammer_cli_foreman_tasks-0.0.7-1.git.30.f38b470.el7.centos.noarch (foreman-scl)
               Not found
           Available: rubygem-hammer_cli_foreman_tasks-0.0.6-1.el7.noarch (foreman-plugins)
               rubygem(hammer_cli_foreman_tasks) = 0.0.6
```

**Comment by domcleal** [comment]
> Error: Package: rubygem-hammer_cli_katello-0.0.17-2.el7.noarch (@katello) Requires: rubygem(hammer_cli_foreman_docker)

Looks like all of these errors might be because rubygem-hammer_cli_katello is not being obsoleted by a newer SCL-enabled version.

Ah yes: https://github.com/ehelms/katello-packaging/blob/support-tfm/rubygem-hammer_cli_katello/rubygem-hammer_cli_katello.spec#L21 (`Obsoletes: rubygem-%{gem_name} < 0.0.16-2`) should  cover version 0.0.17-2, e.g. `< 0.0.17-3`.

> Error: Package: ruby193-rubygem-hpricot-0.8.6-11.el7.x86_64 (@katello) Requires: ruby193-ruby-wrapper Removing: ruby193-ruby-wrapper-0.0.2-5.el7.noarch (@foreman) ruby193-ruby-wrapper = 0.0.2-5.el7

Probably an explicit dependency on the wrapper, which isn't usually required.  If you have packages with shebang lines, they'll get an auto-require on the filename in the shebang.  No need to add -wrapper as an explicit dep.

**Comment by domcleal** [comment]
> Error: Package: ruby193-rubygem-hpricot-0.8.6-11.el7.x86_64 (katello) Requires: ruby193-ruby-wrapper Removing: ruby193-ruby-wrapper-0.0.2-5.el7.noarch (foreman) ruby193-ruby-wrapper = 0.0.2-5.el7
> 
> Probably an explicit dependency on the wrapper

Actually, probably the same case as the Hammer plugin, it's not getting obsoleted by a new package.

**Comment by domcleal** [comment]
Repo refreshed again, and an EL6 repo is available at https://fedorapeople.org/~domcleal/foreman/tfm_repo6/ (though frankly, it'll have near zero difference with the EL7 one).

**Comment by ehelms** [comment]
I am good to start this whenever you are. I am going to try to resolve my hpricot issue by removing haml and haml-rails all together as a dependency from Katello.

**Comment by domcleal** [comment]
Thanks, I'll merge this tomorrow and start rebuilding.

**Comment by domcleal** [comment]
Rebuild status:

- [x] Remove ruby193 builds from foreman-nightly-* tags
- [x] Build tfm (stage 1 bootstrap) and update buildroot groups
- [ ] Build core dependencies (stage 2, 97 packages)
- [ ] Build core dependencies (stage 3, 7 packages)
- [ ] Build core dependencies (stage 4, 4 packages)
- [ ] Build core Foreman package (stage 5, 1 package)
- [ ] Remove ruby193 builds from plugin tags, update buildroot groups
- [ ] Build plugin dependencies (stage 1, 53 packages)
- [ ] Build plugins (stage 2, 7 packages)
- [ ] Build plugins (stage 3, 2 packages)

**Comment by domcleal** [comment]
Foreman's repos are pretty much ready, please let me know you're done @ehelms.  All our Koji nightly SCL tags only contain tfm builds now.

**Comment by ehelms** [comment]
The checklist mentions updating buildroot groups, after hitting an initial failure trying to build in koji, I wondered if I needed to update our buildroots in some way as well?

**Comment by domcleal** [comment]
Yes, you'd need to replace ruby193-build with tfm-build by doing something like:

    kkoji block-group-pkg your-tag-build build ruby193-build
    kkoji block-group-pkg your-tag-build srpm-build ruby193-build
    kkoji add-group-pkg your-tag-build build tfm-build
    kkoji add-group-pkg your-tag-build srpm-build tfm-build

**Comment by domcleal** [comment]
And probably then use `kkoji regen-repo your-tag-build` to update it, if kojira doesn't do it automatically.

**Comment by ehelms** [comment]
That did the trick and got me past that error. I am now hitting an EL6 only issue (the EL7 version of the package built fine). The error is below. I tried things like ensuring our buildroot matched the equivalent Foreman nightly type, ensuring that the external repos were up to date but to no avail.

http://koji.katello.org/koji/getfile?taskID=331536&name=root.log
```
EBUG backend.py:912:  ['/usr/bin/yum', '--installroot', '/var/lib/mock/katello-nightly-rhel6-build-74723-57558/root/', 'groupinstall', 'build']
DEBUG util.py:314:  Executing command: ['/usr/bin/yum', '--installroot', '/var/lib/mock/katello-nightly-rhel6-build-74723-57558/root/', 'groupinstall', 'build', '--setopt=tsflags=nocontexts'] with env {'LANG': 'en_US.UTF-8', 'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOSTNAME': 'mock', 'PROMPT_COMMAND': 'echo -n "<mock-chroot>"', 'HOME': '/builddir', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin'}
DEBUG util.py:264:  Error: Package: tfm-runtime-1.1-1.el6.x86_64 (build)
DEBUG util.py:264:             Requires: /usr/bin/scl_source
DEBUG util.py:264:   You could try using --skip-broken to work around the problem
DEBUG util.py:264:   You could try running: rpm -Va --nofiles --nodigest
```

**Comment by domcleal** [comment]
The repo was inheriting an old version of scl-utils that happened to be in EPEL6 rather than the newer version in the rhel-6.6 external repo because of the external repo priorities.  The ordering of the external repos between rhel6/7 was also different, so I've sorted them to match the rhel7-build tag (which had a more logical order) and rebuilt it.

<pre>
$ kkoji taginfo katello-nightly-rhel6-build
..
External repos:
   15 epel-6 (file:///mnt/tmp/external-repos/www/epel6-$arch/RPMS.epel/)
   20 jpackage-5.0-generic-free (file:///mnt/tmp/external-repos/www/jpackage-$arch/RPMS.jpackage/)
   30 rhel-6.6-server (file:///mnt/tmp/external-repos/rhel6-$arch/6.6/)
   35 rhel-6.6-server-optional (file:///mnt/tmp/external-repos/rhel6-$arch/6.6-optional/)
   40 rhscl-1.1-rhel-6 (file:///mnt/tmp/external-repos/rhscl-rhel6-x86_64/1.1/)
</pre>

Now:

<pre>
External repos:
    5 rhel-6.6-server (file:///mnt/tmp/external-repos/rhel6-$arch/6.6/)
   10 rhel-6.6-server-optional (file:///mnt/tmp/external-repos/rhel6-$arch/6.6-optional/)
   18 rhscl-1.1-rhel-6 (file:///mnt/tmp/external-repos/rhscl-rhel6-x86_64/1.1/)
   20 jpackage-5.0-generic-free (file:///mnt/tmp/external-repos/www/jpackage-$arch/RPMS.jpackage/)
   25 epel-6 (file:///mnt/tmp/external-repos/www/epel6-$arch/RPMS.epel/)
</pre>

I did a test build in the tag, it seems OK now.

**Comment by ehelms** [comment]
All our packages are fully built and mashed with an install test against foreman & katello koji repositories. I am still going to have to figure out/deal with the upgrade issue for older ruby193 packages no longer included but feel free to release as fresh installs do pass.

**Comment by domcleal** [comment]
Thanks, I'm beginning to push the packages out, it'll take a little while.

**Comment by domcleal** [comment]
All done.

**Pull request merged**
