### PR TITLE
Refs #24754 - update react requirement to 16.4

### PR DESCRIPTION
**Pull request by mmoll**
this should be built into:

* [x] Nightly

### CODE REVIEW

**Comment by mmoll** [comment]
See https://github.com/theforeman/foreman/pull/6012

**Comment by mmoll** [comment]
rebased. :green_heart:

**Comment by ekohl** [comment]
In https://github.com/theforeman/foreman-packaging/pull/2950 I updated all dependencies based on the scripts.

**Comment by mmoll** [comment]
allright, closing!

**Pull request closed without merging**
