### PR TITLE
Include nodejs packages from Foreman in list of updateable packages

### PR DESCRIPTION
**Pull request by ehelms**
Adding Katello will depend upon https://github.com/theforeman/jenkins-jobs/pull/347

### CODE REVIEW

**Comment by ehelms** [comment]
Related PR to handle the updates to see why some of the new structure is needed: https://github.com/theforeman/foreman-packaging/pull/9618

**Comment by ehelms** [comment]
Example output:

```
packages/katello/rubygem-foreman_rh_cloud 8.0.48
packages/katello/rubygem-foreman_virt_who_configure 0.5.16
packages/plugins/rubygem-foreman_netbox 1.2.0
packages/plugins/rubygem-foreman_salt 15.2.0
packages/plugins/rubygem-smart_proxy_container_gateway 1.0.8
packages/foreman/rubygem-concurrent-ruby CONFLICT
packages/foreman/rubygem-fast_gettext CONFLICT
packages/foreman/rubygem-gettext 3.4.6
packages/foreman/rubygem-net-ssh 7.2.0
packages/foreman/rubygem-nokogiri 1.15.3
packages/foreman/rubygem-prometheus-client 4.2.0
packages/foreman/rubygem-public_suffix CONFLICT
packages/foreman/rubygem-rack CONFLICT
packages/foreman/rubygem-unicode-display_width CONFLICT
packages/foreman/rubygem-websocket-driver 0.7.6
packages/foreman/rubygem-zeitwerk 2.6.10
packages/katello/rubygem-pulp_container_client 2.14.7
packages/katello/rubygem-pulp_deb_client 2.20.3
packages/katello/rubygem-pulp_rpm_client 3.19.9
packages/katello/rubygem-pulpcore_client 3.22.12
packages/foreman/nodejs-babel-core 7.22.9
packages/foreman/nodejs-babel-plugin-syntax-object-rest-spread 7.8.3
packages/foreman/nodejs-babel-preset-env 7.9.5
packages/foreman/nodejs-babel-preset-react 7.16.7
packages/foreman/nodejs-babel-runtime 7.22.6
packages/foreman/nodejs-theforeman-builder 12.2.0
packages/foreman/nodejs-theforeman-vendor 12.2.0
packages/foreman/nodejs-babel-loader 8.3.0
packages/foreman/nodejs-c3 0.4.24
packages/foreman/nodejs-compression-webpack-plugin 1.1.12
packages/foreman/nodejs-core-js 2.6.12
packages/foreman/nodejs-graphql 15.8.0
packages/foreman/nodejs-graphql-tag 2.12.6
packages/foreman/nodejs-harmony-reflect 1.6.2
packages/foreman/nodejs-js-tokens 4.0.0
packages/foreman/nodejs-lodash 4.17.21
packages/foreman/nodejs-lodash-es 4.17.21
packages/foreman/nodejs-loose-envify 1.4.0
packages/foreman/nodejs-node-gyp DOWNGRADE
packages/foreman/nodejs-node-sass 4.14.1
packages/foreman/nodejs-optimize-css-assets-webpack-plugin 3.2.1
packages/foreman/nodejs-performance-now DOWNGRADE
packages/foreman/nodejs-react-ellipsis-with-tooltip 1.1.1
packages/foreman/nodejs-react-intl 2.9.0
packages/foreman/nodejs-regenerator-runtime 0.13.11
packages/foreman/nodejs-sortabular 1.6.0
packages/foreman/nodejs-symbol-observable 4.0.0
packages/foreman/nodejs-table-resolver 3.3.0
packages/foreman/nodejs-uglifyjs-webpack-plugin 1.3.0
packages/foreman/nodejs-url-loader 1.1.2
packages/foreman/nodejs-uuid 3.4.0
```

**Comment by ehelms** [comment]
This is ready for review.

**Comment by ekohl** [comment]
I first want to do a cleanup of unused packages. My script (from https://github.com/theforeman/foreman-packaging/pull/8361#issue-1341419276) says:
```
Unused package nodejs-babel-plugin-syntax-object-rest-spread
Unused package nodejs-babel-runtime
Unused package nodejs-lodash-es
Unused package nodejs-loose-envify
Unused package nodejs-node-gyp
Unused package nodejs-performance-now
Unused package nodejs-symbol-observable
```

However, earlier I tried it and nodejs-node-gyp was still needed according to https://github.com/theforeman/foreman-packaging/pull/9327. Still, I have a hard time seeing why (https://github.com/theforeman/foreman-packaging/pull/9327#issuecomment-1669927519).

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman-packaging/pull/9636

**Comment by ehelms** [comment]
@ekohl Ready for this now that the cleanup is merged?

**Comment by ehelms** [comment]
I am gonna merge and then monitor the update job to see that it functions correct.

**Pull request merged**
