### PR TITLE
[RPM] Update rubygem-hammer_cli_foreman to 0.12.1

### PR DESCRIPTION
**Pull request by mbacovsky**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.17
* [ ] 1.16
* [ ] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---
Added fixes for regressions present with Foreman 1.17

### CODE REVIEW

**Comment by xprazak2** [comment]
:+1:

**Comment by mbacovsky** [comment]
@ekohl updated. Is this temporary change? Might be worth mentioning in README.md

**Comment by ekohl** [comment]
@mbacovsky no, it's related to https://community.theforeman.org/t/tito-tag-workflow-no-longer-needed-for-rpm-develop-packaging/8505/4. We should add it to the readme.

**Comment by mbacovsky** [comment]
@xprazak2 it seems it was not included in foreman 1.17. Could this be fixed for 1.17.2?

**Comment by xprazak2** [comment]
I have it on my list, thanks!

**Pull request merged**
