### PR TITLE
Update bootdisk to 18.0

### PR DESCRIPTION
**Pull request by lzap**
For plugin updates, please indicate which repos this should be built into:

* Nightly
* 3.0

Will do the PR.

### CODE REVIEW

**Comment by evgeni** [comment]
[test packaging]

sorry, PR looks good, I just need a guinea pig

**Comment by evgeni** [comment]
[test deb]

**Comment by evgeni** [comment]
[test deb]

**Comment by evgeni** [comment]
[test deb]

**Comment by evgeni** [comment]
[test deb]

**Comment by lzap** [comment]
TY

**Review by evgeni — APPROVED** [review]

**Comment by lzap** [comment]
Thank you for your contribution, commits a66430678 were cherry-picked into the 'rpm/3.0' branch.

**Pull request merged**
