### PR TITLE
Bump rubygem-foreman_rh_cloud to 3.0.17-1

### PR DESCRIPTION
**Pull request by laviro**
(cherry picked from commit 420a1cf72b5cb17e1b47709fec499c26c4b21b74)

### CODE REVIEW

**Comment by evgeni** [comment]
According to Shimon, this version conflicts with redhat_access 2.2.18, please add that to the RPM metadata. (Something like `Conflicts: %{?scl_prefix}rubygem-redhat_access < 2.2.19`)

**Comment by laviro** [comment]
Thanks @evgeni @shimshtein, updated

**Comment by ShimShtein** [comment]
@evgeni, thanks for the tip! The restriction sounds reasonable.

**Comment by evgeni** [comment]
Just so that I understand the change correctly: the redhat_access plugin is not completely obsolete, you just take over a specific part of the functionality and users shall keep .19 installed for other features, right?

**Comment by ShimShtein** [comment]
Correct. We took one part of its functionality (handling insights-client uploads) into rh_cloud. redhat_access is still responsible for adding "Insights" menu in foreman and all the pages there.

**Comment by laviro** [comment]
After this will get in I will update the 2.4 and 2.3 cherry picks

**Comment by evgeni** [comment]
Who will update the `redhat_access` package so that users can actually use both together?

**Comment by ShimShtein** [comment]
I'll talk to @rexwhite, and we'll figure it out.

**Comment by ShimShtein** [comment]
@evgeni, created PR for redhat access too. Should I consolidate them both?

**Review by evgeni — APPROVED** [review]

**Pull request merged**
