### PR TITLE
refs #16599 - update npm to latest release [deb]

### PR DESCRIPTION
**Pull request by domcleal**
Required to read a partial shrinkwrap file.

--

develop only for now, please. Should be harmless by itself, may even speed up installation.

### CODE REVIEW

**Comment by domcleal** [comment]
I removed the change from xenial as it already has npm 3 available, should only be needed on the older OSes with 1.x.

**Comment by domcleal** [comment]
[test] as I think it tested against an older version of develop.

**Comment by mmoll** [comment]
I did restart the build after the core PR went in as http://ci.theforeman.org/job/packaging_build_deb_coreproject/3657/ and it came back green :green_heart:

**Comment by mmoll** [comment]
merged, thanks @domcleal!

**Pull request merged**
