### PR TITLE
Bump foreman-installer kafo requires to 5.0.0

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
Here ya go -- https://github.com/theforeman/foreman-installer/pull/558

**Comment by ehelms** [comment]
[test rpm]

**Comment by tbrisker** [comment]
[test rpm]

**Comment by tbrisker** [comment]
el7 is failling with:
```

W, [2020-08-09T13:26:53.248688 #2030]  WARN -- : Parser cache ./_build/parser_cache/foreman.yaml is from a different version of Kafo, skipping setup
/opt/theforeman/tfm/root/usr/share/gems/gems/kafo-5.0.0/lib/kafo/puppet_module.rb:69:in `parse': No Puppet module parser is installed and no cache of the file /builddir/build/BUILD/foreman-installer-2.2.0-develop/_build/modules/foreman/manifests/init.pp is available. Please check debug logs and install optional dependencies for the parser. (Kafo::ParserError)
	from /opt/theforeman/tfm/root/usr/share/gems/gems/kafo-5.0.0/lib/kafo/configuration.rb:110:in `block in modules'
	from /opt/theforeman/tfm/root/usr/share/gems/gems/kafo-5.0.0/lib/kafo/configuration.rb:110:in `map'
	from /opt/theforeman/tfm/root/usr/share/gems/gems/kafo-5.0.0/lib/kafo/configuration.rb:110:in `modules'
	from /opt/theforeman/tfm/root/usr/share/gems/gems/kafo-5.0.0/bin/kafo-export-params:152:in `print_out'
	from /opt/theforeman/tfm/root/usr/share/gems/gems/kafo-5.0.0/bin/kafo-export-params:54:in `execute'
	from /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.1.2/lib/clamp/command.rb:63:in `run'
	from /opt/theforeman/tfm/root/usr/share/gems/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
	from /opt/theforeman/tfm/root/usr/share/gems/gems/kafo-5.0.0/bin/kafo-export-params:158:in `<top (required)>'
	from /opt/theforeman/tfm/root/usr/bin/kafo-export-params:23:in `load'
	from /opt/theforeman/tfm/root/usr/bin/kafo-export-params:23:in `<main>'
rake aborted!
```

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
This points to a problem with a bug fix for puppet symlinks. The fix is I am releasing a new kafo and kafo_parsers with the bug fix reverted:

 * https://github.com/theforeman/kafo_parsers/pull/43
 * https://github.com/theforeman/kafo/pull/265

I'll then build those RPMs and update this PR to re-test against it.

**Comment by ehelms** [comment]
Needs -- https://github.com/theforeman/foreman-packaging/pull/5655  (kafo_parsers 1.1.1 was untagged from nightly tags).

**Comment by ehelms** [comment]
Passing now

**Comment by ehelms** [comment]
Indeed it is.

**Pull request merged**
