### PR TITLE
Add foreman_pipeline package

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by domcleal** [comment]
This looks like it has a hard dependency on Katello, but isn't declared in the gemspec.  If so, could you submit it to their repositories instead?  We wouldn't be able to build it in Foreman or resolve its deps.

**Comment by xprazak2** [comment]
@domcleal: OK, I will close this and resubmit to Katello.

**Comment by domcleal** [comment]
Thanks, and the same for the other PRs?

**Comment by xprazak2** [comment]
@domcleal: No problem, I will move them as well.

**Pull request closed without merging**
