### PR TITLE
Release rubygem-foreman_scap_client 0.5.2

### PR DESCRIPTION
**Pull request by ofedoren**
`./bump_rpm` did a lot of weird updates, so I've used `obal` instead. Hopefully that's legal too :)

CP:
 - 3.9: https://github.com/theforeman/foreman-packaging/pull/10138

### CODE REVIEW

**Review by ekohl — APPROVED** [review]

**Comment by ekohl** [comment]
[test rpm-copr]

**Comment by evgeni** [comment]
repoclosure should be fixed via https://github.com/theforeman/foreman-packaging/pull/10150

**Comment by ekohl** [comment]
Merged that. @ofedoren please rebase.

**Comment by evgeni** [comment]
[test rpm-copr]

I think it should be able to pick up the merged result w/o rebase

**Comment by evgeni** [comment]
I love it when a plan comes together.

**Pull request merged**
