### PR TITLE
Bump foreman_datacenter to 0.1.45

### PR DESCRIPTION
**Pull request by Zenya**
For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [ ] 1.17
* [x] 1.16
* [x] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by mmoll** [comment]
[test]

**Comment by mmoll** [comment]
[test default]

**Comment by mmoll** [comment]
Merged, спасибо Женя!

As mentioned in the test PR, please update the plugin to be compatible with 1.17 and best also current develop.

**Comment by Zenya** [comment]
@mmoll hi. this version isn't available to install via apt

**Pull request merged**
