### PR TITLE
Remote Execution - Iteration 5 - 1.10 (DEB)

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by stbenjam** [comment]
```
The following packages have unmet dependencies:
 pbuilder-satisfydepends-dummy : Depends: ruby-foreman-tasks (>= 0.7.11) which is a virtual package.
                                 Depends: ruby-foreman-tasks (< 0.8.0) which is a virtual package.
                                 Depends: ruby-foreman-deface which is a virtual package.
```

Tasks seems to be in the 1.10 deb repo tho

**Comment by mmoll** [comment]
[test]

**Comment by mmoll** [comment]
I tried to fix this by deleting the 9999 versioned foreman-tasks package but failed.

**Comment by mmoll** [comment]
[test] again

**Comment by mmoll** [comment]
I didn't do runtime testing, as my only instance with rex is running nightly packages, but this is looking sane.

**Comment by mmoll** [comment]
merged and building, thanks @stbenjam!

**Pull request merged**
