### PR TITLE
remove el5 remains

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
repoclosure errors unrelated

**Review by ekohl — COMMENTED** [review]
Did you keep the EL5 bits in https://github.com/theforeman/foreman-packaging/blob/rpm/develop/packages/client/katello-host-tools/katello-host-tools.spec on purpose?

**Comment by evgeni** [comment]
> Did you keep the EL5 bits in https://github.com/theforeman/foreman-packaging/blob/rpm/develop/packages/client/katello-host-tools/katello-host-tools.spec on purpose?

nope, I must admit I just grepped for `el5`, not things like `%{rhel} == 5` :)

**Review by ekohl — COMMENTED** [review]
I think this can also be dropped:
https://github.com/theforeman/foreman-packaging/blob/a475b3131edda206b4de188813c391ca423633bf/packages/client/katello-host-tools/katello-host-tools.spec#L26

**Review by pcreech — APPROVED** [review]
ACK

**Pull request merged**
