### PR TITLE
Fixes #22551 - use runuser instead of sudo in k-backup

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by sean797** [comment]
I suspect not, but do we care about ?
https://github.com/theforeman/foreman-packaging/blob/3c16b215cd7ce77d14e3cb6ae460291fed9dbe26/katello/katello/restore.rb#L101

**Comment by evgeni** [comment]
not really, unless you run restore from cron? ;)

but I think I'd still align this to match the backup code

**Comment by evgeni** [comment]
Right. I think I'll just use `sudo` for the restore then.

Or I could do as the installer and use `su - apache -s /bin/bash -c pulp-manage-db`

Or I pretend to port the `su` call to `runuser` and use `runuser - apache -s /bin/bash pulp-manage-db`

@johnpmitsch @sean797 what would you prefer?

**Comment by sean797** [comment]
+1 to `su - apache -s /bin/bash -c pulp-manage-db`. Lets do what the installer does

**Comment by evgeni** [comment]
@johnpmitsch @sean797 updated

**Comment by ekohl** [comment]
@johnpmitsch could you have another look?

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
