### PR TITLE
Bump postgresql-evr version to 0.0.2

### PR DESCRIPTION
**Pull request by ianballou**
Need this new version of postgresql-evr that removes the superuser requirement in postgresql for creating the evr extension.

### CODE REVIEW

**Comment by ianballou** [comment]
el8 is working but not el7. Found this in the el7 root.log that might be relevant:
```
DEBUG util.py:598:  Error: No Package found for rh-postgresql12-postgresql-devel
DEBUG util.py:598:  Error: No Package found for rh-postgresql12-runtime
```

**Comment by ianballou** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test prm]

**Comment by ehelms** [comment]
@ianballou I assume you need this updated on Jenkins nodes as well?

**Comment by ianballou** [comment]
@ehelms I do need it updated on the Jenkins nodes, yeah.

**Pull request merged**
