### PR TITLE
Deb/develop foreman fog proxmox 0.12.1

### PR DESCRIPTION
**Pull request by tristanrobert**
* Nightly

### CODE REVIEW

**Comment by tristanrobert** [comment]
Same errors :-(

1. I don't know which is the new correct permission syntax: https://github.com/theforeman/foreman_fog_proxmox/blob/53a433554974807d522b937904c1256789a03274/lib/foreman_fog_proxmox/engine.rb#L48
2. My debian rules includes `DATABASE_URL=nulldb://nohost` so I don't understand why pg driver is needed.

Have you any ideas? Build was successful last release (0.11.1) and I didn't changed this code (rules and permission). I think these are foreman changes.

**Comment by sbernhard** [comment]
>     1. I don't know which is the new correct permission syntax: https://github.com/theforeman/foreman_fog_proxmox/blob/53a433554974807d522b937904c1256789a03274/lib/foreman_fog_proxmox/engine.rb#L48

Try to remove the quotations marks (') from 

    { :'foreman_fog_proxmox/compute_resources' 

so that it looks like 

    { :foreman_fog_proxmox/compute_resources

**Comment by sbernhard** [comment]
I guess, it would make sense to have a look at 
https://github.com/theforeman/foreman-packaging/pull/5064
https://github.com/theforeman/foreman-packaging/pull/5058
https://github.com/theforeman/foreman-packaging/pull/5095

**Comment by tristanrobert** [comment]
Fixed in : https://projects.theforeman.org/projects/foreman/repository/revisions/a4f4c1307e97a0c0dc2f633a0307c411844de011
Could you reload the checks ?

**Comment by dgoetz** [comment]
[test packaging]

**Comment by tristanrobert** [comment]
RPM works but DEB still fails with pg driver required

**Comment by tristanrobert** [comment]
Ok now it's fixed!

**Comment by evgeni** [comment]
@tristanrobert should this be updated to 0.12.4 to match RPM?

**Comment by tristanrobert** [comment]
These two releases are iso features and 0.12.4 fixes only deb and rpm packaging. But if you prefer I add the 0.12.4 PR too.

**Comment by tristanrobert** [comment]
0.12.4 PR is: https://github.com/theforeman/foreman-packaging/pull/5861

**Comment by evgeni** [comment]
Thanks! Yeah, even if there are no changes that affect users, I still prefer having rpm and deb in sync :)

**Comment by tristanrobert** [comment]
Then you can merge 0.12.4 and close 0.12.1. Thanx @evgeni !

**Pull request closed without merging**
