### PR TITLE
Update ansible-collection-theforeman-foreman to 0.4.1

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
@pcreech el8 build broken by outside influence (I think)

**Comment by pcreech** [comment]
@evgeni Yup, looks like bash was updated on the mirror

**Comment by pcreech** [comment]
[test]

**Comment by pcreech** [comment]
[test rpm]

**Comment by pcreech** [comment]
[test rpm]

**Comment by pcreech** [comment]
ACK

**Pull request merged**
