### PR TITLE
Add zest dependency to katello

### PR DESCRIPTION
**Pull request by tbrisker**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.21
* [ ] 1.20

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by tbrisker** [comment]
[test rpm]

**Comment by tbrisker** [comment]
[test rpm]

**Comment by evgeni** [comment]
the repoclosure failure is expected, as zest is not yet in the published repos. merging as is now.

**Comment by jlsherrill** [comment]
Thanks @tbrisker !!!

**Pull request merged**
