### PR TITLE
Update rubygem-foreman_openscap to 0.11.4

### PR DESCRIPTION
**Pull request by evgeni**
(cherry picked from commit 5983698d50455cc362e127dab132aff8f3273cf1)

For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [ ] 1.21
* [x] 1.20

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by ekohl** [comment]
```
DEBUG util.py:491:  Getting requirements for tfm-rubygem-foreman_openscap-0.11.4-1.fm1_20.el7.src
DEBUG util.py:491:   --> Already installed : scl-utils-build-20130529-18.el7_4.x86_64
DEBUG util.py:491:   --> foreman-assets-1.20.1-1.el7.noarch
DEBUG util.py:491:   --> foreman-plugin-1.20.1-1.el7.noarch
DEBUG util.py:491:   --> tfm-rubygem-deface-1.3.2-1.el7.noarch
DEBUG util.py:491:   --> Already installed : rh-ruby25-ruby-libs-2.5.0-5.el7.x86_64
DEBUG util.py:491:   --> Already installed : rh-ruby25-ruby-2.5.0-5.el7.x86_64
DEBUG util.py:491:   --> rh-ruby25-rubygems-devel-2.7.3-5.el7.noarch
DEBUG util.py:491:  Error: Package: 1:tfm-rubygem-concurrent-ruby-edge-0.2.4-2.el7.noarch (build)
DEBUG util.py:491:             Requires: tfm-ror52-rubygem(concurrent-ruby) < 1.1.0
DEBUG util.py:491:             Installing: tfm-ror52-rubygem-concurrent-ruby-1.1.4-1.el7.noarch (build)
DEBUG util.py:491:                 tfm-ror52-rubygem(concurrent-ruby) = 1.1.4
```

**Comment by evgeni** [comment]
This is because [tfm-ror52-rubygem-concurrent-ruby-1.1.4-1.el7](http://koji.katello.org/koji/buildinfo?buildID=37871) is built into `tfm-ror52-rhel7` and the 1.20 plugin builds inherit that.

```
% koji list-tag-inheritance foreman-plugins-1.20-rhel7-build
foreman-plugins-1.20-rhel7-build (427)
  ├─foreman-plugins-1.20-rhel7-override (428)
  │  └─foreman-plugins-1.20-rhel7 (426)
  ├─tfm-ror52-rhel7 (333)
  ├─foreman-plugins-1.20-nonscl-rhel7 (423)
  ├─foreman-1.20-rhel7 (417)
  └─foreman-1.20-nonscl-rhel7 (420)
```

I'd argue that we require a `foreman-rails-1.20-rhel7` (like it exists for `foreman-rails-1.21-rhel7`) and use that for building 1.20 stuff.

**Comment by ekohl** [comment]
Yesterday I reached the same conclusion but didn't have time to act on it.

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
:green_heart:

**Comment by evgeni** [comment]
build: http://koji.katello.org/koji/taskinfo?taskID=168083

**Pull request merged**
