### PR TITLE
Refs #26440 - install katello-tracer-upload wrapper for dnf

### PR DESCRIPTION
**Pull request by evgeni**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.21
* [ ] 1.20

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

Depends on https://github.com/Katello/katello-host-tools/pull/93

### CODE REVIEW

**Comment by jturel** [comment]
@evgeni FYI https://github.com/Katello/katello-host-tools/releases/tag/3.4.3

**Comment by evgeni** [comment]
@jturel merci, updated the PR to include the new version :)

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
this builds fine, it's just the notification to GH that's making this red.

**Comment by evgeni** [comment]
this had changes since the approval by @ehelms, so I'd like a second ack please :)

**Comment by jturel** [comment]
@evgeni looks like there will be one more change in host-tools which I'm reviewing, so I'll be doing another release - may want to hold off here to reduce extra work https://github.com/Katello/katello-host-tools/pull/96/files

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
closed in favor of #3575

**Pull request closed without merging**
