### PR TITLE
Update smart_proxy_remote_execution_ssh to 0.0.10 (RPM)

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by domcleal** [comment]
Thanks @stbenjam, merged and building now.  It probably won't get pushed to nightly repos for a while yet.

**Comment by domcleal** [comment]
Shall I retag this to 1.10 too?

**Comment by stbenjam** [comment]
Yes please, everything from https://github.com/theforeman/foreman-packaging/pull/929 should be in 1.10

**Comment by domcleal** [comment]
OK, this is retagged for EL7.  Will look at the Hammer plugin, probably will need foremandist again.

**Pull request merged**
