### PR TITLE
Update rubygem-foreman-tasks to 3.0.3

### PR DESCRIPTION
**Pull request by adamruzicka**
CPs:
- [ ] 2.3

### CODE REVIEW

**Comment by pcreech** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
You need to drop the `BuildRequires: %{?scl_prefix}npm(@theforeman/builder) < 5.0.0` as we're at v6 now.

**Review by evgeni — CHANGES_REQUESTED** [review]
doesn't build due to node deps

**Review by evgeni — APPROVED** [review]

**Pull request merged**
