### PR TITLE
Update foreman-tasks to 0.7.2 (including related gems)

### PR DESCRIPTION
**Pull request by iNecas**

### CODE REVIEW

**Comment by domcleal** [comment]
The gem.list needs updating for foreman-tasks, which causes the build error.  There are some questions as well on the other PR that we should answer before merging this one.

**Comment by iNecas** [comment]
Thanks, I always forget something… I've answered the questions on #718 , how does that translate to changes on this PR?

**Comment by domcleal** [comment]
We just updated the README to contain some instructions, should help next time!

In this one, you should be able to a) mv/cp the example file in `rules` to remove the extension, then b) add a line to plugins/ruby-foreman-tasks/debian/install to copy config/foreman-tasks.yaml to the final location (see debian/jessie/foreman/{rules,foreman.install} for an example).

**Comment by iNecas** [comment]
Updated 
no-idea

**Comment by domcleal** [comment]
Hm, not sure config/ is going to work actually for this case, since the package isn't using gem2deb.  We don't seem to have any other ruby-foreman-* plugins that do this, only the regular gem2deb type packages (dependencies, ruby-smart-proxy-*).  The config might have to be copied into the packaging, like ruby-foreman-default-hostgroup and then just refer to it as foreman-tasks.yaml in `install`.  Do you agree @mmoll?

**Comment by mmoll** [comment]
Yes, this needs to go into -packaging, as we don't unpack the gems for core plugins.

**Comment by iNecas** [comment]
Thanks for the pointers, lets see how this one goes…

**Comment by domcleal** [comment]
Thanks @iNecas!  Building.

**Pull request closed without merging**
