### PR TITLE
Revert "Keep a copy of DB schema in foreman-plugin"

### PR DESCRIPTION
**Pull request by iNecas**
This reverts commit 248db50fb9740c0d4a0af531763e0870e3927c31.

### CODE REVIEW

**Comment by iNecas** [comment]
Given this commit breaks the plugin releases for various reasons (see  https://github.com/theforeman/foreman/pull/4396, https://github.com/theforeman/foreman-packaging/pull/1561#issuecomment-288560211, https://github.com/theforeman/foreman-packaging/pull/1542#issuecomment-283368790), I'm reverting the commit that introduced the regressions, as this things needs to bee addressed before re-introducing it.

**Comment by iNecas** [comment]
[test]

**Comment by domcleal** [comment]
Affected plugins were fixed a while ago by http://projects.theforeman.org/issues/18977, I don't think this is necessary.

**Comment by iNecas** [comment]
I did it based on @ehelms comment https://github.com/theforeman/foreman-packaging/pull/1561#issuecomment-288560211. Waiting for https://github.com/theforeman/foreman-packaging/pull/1588 to be green to confirm the issue is resolved

**Comment by domcleal** [comment]
The PR that comment was in was not merged, I don't see the relevance.

**Comment by iNecas** [comment]
Thanks @domcleal for closing this: the green release prove this was an issue with the PR, rather than the original change

**Pull request closed without merging**
