### PR TITLE
Update rubygem-foreman_scc_manager to 1.8.17

### PR DESCRIPTION
**Pull request by nadjaheitmann**

### CODE REVIEW

**Comment by nadjaheitmann** [comment]
@theforeman/packaging Can anyone tell what is wrong with the rpm test, please?

**Comment by nadjaheitmann** [comment]
@Odilhao Do you mind taking a look here?

**Comment by nadjaheitmann** [comment]
[test rpm]

**Comment by pcreech** [comment]
[test]

**Comment by pcreech** [comment]
[test rpm]

**Review by pcreech — APPROVED** [review]

**Comment by nadjaheitmann** [comment]
Thanks @pcreech

**Comment by nadjaheitmann** [comment]
Thanks @pcreech for taking care of all the related PRs! How long does it take until the package appears in nightly? I am still missing it there.

**Comment by ekohl** [comment]
https://ci.theforeman.org/job/foreman-plugins-nightly-rpm-pipeline/ is for nightly and if you look at the URLs it won't surprise you that https://ci.theforeman.org/job/foreman-plugins-3.1-rpm-pipeline/ is for 3.1.

**Comment by evgeni** [comment]
That's true, but scc_manager lives in the Katello namespace, so it's only pushed out when katello is pushed, not when plugins…

**Comment by nadjaheitmann** [comment]
> That's true, but scc_manager lives in the Katello namespace, so it's only pushed out when katello is pushed, not when plugins…

I wasn't aware of that but makes sense. I see that they have not run the Katello pipeline in a couple of days.

**Comment by evgeni** [comment]
The nighly pipeline does, the release one doesn't, as it assumes that there are no changes on a daily basis and running it is quite expensive in terms of compute.

**Comment by nadjaheitmann** [comment]
It's this one, right? https://ci.theforeman.org/job/katello-nightly-rpm-pipeline/
It actually did run, but the run failed.

**Comment by evgeni** [comment]
Yes

**Pull request merged**
