### PR TITLE
Rebuild rubygem-foreman_remote_execution for webpack

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ekohl** [comment]
[test rpm]

**Comment by tbrisker** [comment]
odd, repoclosure is failing on missing `foreman-webpack-vendor-js(9cba589aa9b597d337bb)` but that is the vendor hash in RC1?

**Comment by ekohl** [comment]
Right, that was also what I noticed yesterday evening but wasn't going to figure out anymore. Can't really explain it at this point.

**Comment by tbrisker** [comment]
Looks like RC1 doesn't have the correct provides:
```
 $ rpm -q --provides /tmp/mozilla_tbrisker0/foreman-1.21.0-0.8.RC1.el7.noarch.rpm 
warning: /tmp/mozilla_tbrisker0/foreman-1.21.0-0.8.RC1.el7.noarch.rpm: Header V4 RSA/SHA256 Signature, key ID 19d72d85: NOKEY
config(foreman) = 1.21.0-0.8.RC1.el7
foreman = 1.21.0-0.8.RC1.el7

**Comment by tbrisker** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
Oh, it'll fail until we build RC3

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm]

**Pull request merged**
