### PR TITLE
Update rubygem-foreman_maintain to 0.6.12

### PR DESCRIPTION
**Pull request by upadhyeammit**

### CODE REVIEW

**Comment by upadhyeammit** [comment]
rpm build on el8 is failing because of zlib old version is not available : http://koji.katello.org/kojifiles/releases/split/yum/koji-modules/koji/staged/x86_64/RHEL-8-001/non_modular/zlib-1.2.11-13.el8.x86_64.rpm 

I do see updated versions available, but unable to understand why dnf transaciton referring to old zlib ?

**Comment by evgeni** [comment]
because koji is stupid like that sometimes ;-) (I'll fix it)

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
develop has been updated, thanks!

**Pull request merged**
