### PR TITLE
Update rubygem-katello and katello to 4.0.0

### PR DESCRIPTION
**Pull request by zjhuntin**

### CODE REVIEW

**Comment by zjhuntin** [comment]
[test rpm]

**Comment by zjhuntin** [comment]
[test rpm]

**Comment by evgeni** [comment]
I think you need to update the gem requirements based on https://github.com/Katello/katello/blob/KATELLO-4.0/katello.gemspec

**Comment by zjhuntin** [comment]
Repoclosure errors expected

**Pull request merged**
