### PR TITLE
Update rubygem-pulp_python_client to 3.7.3

### PR DESCRIPTION
**Pull request by ianballou**
Merge https://github.com/Katello/katello/pull/10181 first.

### CODE REVIEW

**Comment by ekohl** [comment]
Marking as draft until the Katello side has been merged. Please mark it as ready for review once it's ready.

**Comment by ianballou** [comment]
I tried 3.7.2 but it seems the faraday requirements have changed...

**Review by ekohl — COMMENTED** [review]
I think these were generated using an older template and we should ask for a new release.

**Comment by ianballou** [comment]
I'm seeing this in the build log:
```
Checking for unpackaged file(s): /usr/lib/rpm/check-files /builddir/build/BUILDROOT/rubygem-pulp_python_client-3.7.1-1.el8.noarch
error: Installed (but unpackaged) file(s) found:
   /usr/share/gems/gems/pulp_python_client-3.7.1/git_push.sh
    Installed (but unpackaged) file(s) found:
   /usr/share/gems/gems/pulp_python_client-3.7.1/git_push.sh
```

**Comment by ianballou** [comment]
Is  faraday >= 0.17, < 1.9.0  okay for our purposes? That's the requirement on 3.7.2 that I tried, but building failed. I recall the build failed due to the faraday version.  Do we need to ask for any changes with the new release?

**Comment by ekohl** [comment]
No, all 3.7.x are wrong. Yesterday I asked for a new release. We'll need to wait for that.

**Comment by sjha4** [comment]
@ianballou @ekohl : I have a PR here https://github.com/theforeman/foreman-packaging/pull/8567 to upgrade to pulpcore 3.21 and updated plugin gems. Feel free to assess the need of this given the other PR.

**Comment by ekohl** [comment]
https://rubygems.org/gems/pulp_python_client/versions/3.7.3 was released. @sjha4 your PR doesn't have that yet.

**Comment by ianballou** [comment]
I can bump this up to 3.7.3

**Comment by ianballou** [comment]
@ekohl we're green! 3.7.3

**Review by ekohl — APPROVED** [review]

**Pull request merged**
