### PR TITLE
Update kafo to 0.7.5

### PR DESCRIPTION
**Pull request by ares**
into 1.11 please

### CODE REVIEW

**Comment by domcleal** [comment]
The fix in this update hasn't been released to nightly or 1.12 yet, are you going to be doing that too (first)?

**Comment by ares** [comment]
yes, I'll likely do 0.9.1 today, I suppose 0.7.5 would not get into repos before new 1.11.x release so I though we have some time

**Comment by domcleal** [comment]
I'm part way through a 1.11.3 release right now, so it's probably best to wait until at least tomorrow (I expect) before merging this and #1189, so we can get the change into the later releases before pushing straight into 1.11.

**Comment by ares** [comment]
Ok, I opened https://github.com/theforeman/foreman-packaging/pull/1192 with 0.9.1 release.

**Comment by domcleal** [comment]
Merged as 5b4cbdb, thanks @ares, and building at http://ci.theforeman.org/job/packaging_build_deb_dependency/1287/.

**Pull request closed without merging**
