### PR TITLE
Add rubygem-ffi-compiler package

### PR DESCRIPTION
**Pull request by laugmanuel**

### CODE REVIEW

**Comment by laugmanuel** [comment]
@dgoetz do you know how to overcome the obal lint error? Looks to me like this happens because the gem is new to the repo?

**Comment by dgoetz** [comment]
It has to be added to in package_manifest.yaml in section foreman_plugin_packages to fix the error.

Also for some reason the script changed the order in the comps when executed by you, which should be avoided.

**Comment by laugmanuel** [comment]
I'll reorder the changes and add the package to the manifest.

**Review by dgoetz — APPROVED** [review]
Looks good to me, but not sure if anything else is required for a new package, so I hope for a second approval.

**Review by ekohl — APPROVED** [review]
I think obal should do that by itself now, but I'll check after merging if CI fails and otherwise fix it.

**Pull request merged**
