### PR TITLE
Update foreman_remote_execution{,_core} to 4.5.4/1.4.7

### PR DESCRIPTION
**Pull request by adamruzicka**
- Update rubygem-foreman_remote_execution to 4.5.2
- Update rubygem-foreman_remote_execution_core to 1.4.5

Requires https://github.com/theforeman/foreman-packaging/pull/6913

### CODE REVIEW

**Comment by Odilhao** [comment]
[test rpm]

**Comment by Odilhao** [comment]
[test rpm]

**Comment by Odilhao** [comment]
Testing the RPM again since #6913 was merged

**Comment by adamruzicka** [comment]
Waiting on https://github.com/theforeman/foreman-packaging/pull/6951 and its CP into 2.5

**Comment by adamruzicka** [comment]
Requires https://github.com/theforeman/foreman-packaging/pull/6983

**Comment by zjhuntin** [comment]
[test]

**Pull request merged**
