### PR TITLE
Update katello packages for Rails 5.1

### PR DESCRIPTION
**Pull request by ehelms**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.16
* [ ] 1.15
* [ ] 1.14

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ehelms** [comment]
This will require some plugin rebuilds first.

**Comment by ekohl** [comment]
Looks like it pulls in two build roots:

DEBUG util.py:439:    file /etc/rpm/macros.ruby-scldevel conflicts between attempted installs of rh-ruby24-scldevel-2.4-2.el7.x86_64 and rh-ruby22-scldevel-2.0-6.sc1.el7.x86_64
DEBUG util.py:439:    file /etc/rpm/macros.ror-scldevel conflicts between attempted installs of tfm-ror51-scldevel-1.1-1.el7.centos.x86_64 and sclo-ror42-scldevel-3.0-2.el7.x86_64

**Comment by ehelms** [comment]
Yep - got to fully update the buildroots

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
[test]

**Pull request merged**
