### PR TITLE
Update katello package dependencies

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by tbrisker** [comment]
`Error: No Package found for tfm-rubygem(pulp_container_client) <= 1.1.0.dev01574357179` - i guess this is blocked by missing pulp client packaging?

**Comment by jlsherrill** [comment]
@tbrisker yes, working on that now!

**Comment by jlsherrill** [comment]
https://github.com/theforeman/foreman-packaging/pull/4436

**Comment by ehelms** [comment]
[test rpm]

**Comment by ekohl** [comment]
Now fails on the NPM vendor package. Will need https://github.com/Katello/katello/pull/8430 to be merged.

**Comment by ekohl** [comment]
Updated. May fail until https://ci.theforeman.org/job/katello-master-source-release/595 has passed and there's a new tarball available though.

**Pull request merged**
