### PR TITLE
Fixes #20018 - Backport ProxyCommand patch for net-ssh

### PR DESCRIPTION
**Pull request by adamruzicka**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.15
* [ ] 1.14
* [ ] 1.13

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ehelms** [comment]
Please go ahead and bump the release. I assume based on including a patch here, they do not plan to do a release that includes this fix anytime soon?

**Comment by adamruzicka** [comment]
@ehelms Although its maintainer said to release "ASAP", we still wouldn't just jump over to latest 4.1.x release since it brings some major changes against the 4.0.x release we use

**Comment by iNecas** [comment]
I would suggest taking the patched version now, rebase to latest upstream once it's released upstream (https://github.com/net-ssh/net-ssh/issues/522), also note that this is targeting 1.15 still, and I would not recommend rebasing to new net-ssh in there.

**Comment by ehelms** [comment]
Thanks @adamruzicka !

**Comment by lzap** [comment]
For the record, Net:SSH 4.2.0 is still pending release (currently rc2), so this backport patch is still valid. Thanks guys.

**Pull request merged**
