### PR TITLE
Refs #30578: Only generate en_US Apipie docs

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
[test rpm]

**Comment by ekohl** [comment]
This is not the command you're looking for
[test packaging]

**Comment by ehelms** [comment]
This is not the PR I was looking for!

**Comment by tbrisker** [comment]
This failed because your branch name must start with `deb/ `

**Comment by ehelms** [comment]
I always forget that bit of silliness.

**Comment by ehelms** [comment]
Closing in favor of -- https://github.com/theforeman/foreman-packaging/pull/5642

**Pull request closed without merging**
