### PR TITLE
Update foreman_discovery to 9.1.0 (RPM)

### PR DESCRIPTION
**Pull request by lzap**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.15

We need to clean tags, I am not sure if that blocks this.

---

### CODE REVIEW

**Comment by lzap** [comment]
Forgot to push the gem, how do I retest in this repo? [test] ?

**Comment by lzap** [comment]
[test packaging]

**Comment by komidore64** [comment]
:+1:

**Comment by lzap** [comment]
Would like to ask for merge @domcleal or @ehelms just a version bump, some major issues solved from 9.0. If there is an issue with this PR please help me to push it through @ares as I won't be available this week. I will file debian PR shortly, thanks.

**Comment by lzap** [comment]
Ok DEB has been commited already: https://github.com/theforeman/foreman-packaging/commit/c9145eb3553b0b857a1903f3270daf37c09a0904

**Comment by lzap** [comment]
Thanks, can you guys build into 1.15?

**Pull request merged**
