### PR TITLE
Add python pbr

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
This is now building against Python 3.9 and passing.

**Comment by evgeni** [comment]
The same package is also built in `pulpcore-packaging` and due to same NEVR we'll have to cross-tag it over. Is that how we want to handle that? Not against it, just wanted to point out that this will require syncing between the repos every now and then.

**Comment by ehelms** [comment]
> The same package is also built in `pulpcore-packaging` and due to same NEVR we'll have to cross-tag it over. Is that how we want to handle that? Not against it, just wanted to point out that this will require syncing between the repos every now and then.

That works for me, I am not sure how else to handle it given this is a limitation of the build system.

**Pull request merged**
