### PR TITLE
Update to vendor deps

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
the builds obviously fail as the vendor stuff is not packaged yet :)

**Comment by tbrisker** [comment]
please update now that vendor packaging and core change are merged :)

**Comment by ekohl** [comment]
Would you mind dropping my WIP commit?

**Comment by evgeni** [comment]
> Would you mind dropping my WIP commit?

the commit or the WIP from it?

**Comment by ekohl** [comment]
You have a commit that updates it again later so just make sure it's one commit. I don't care if that means dropping mine and updating yours.

**Comment by evgeni** [comment]
[test rpm]

**Comment by tbrisker** [comment]
[test rpm]

**Comment by tbrisker** [comment]
build itself passed, repoclosure failed on:
```
[2019-07-16T14:42:16.529Z]     package: foreman-assets-1.23.0-0.14.develop.20190716142718git0220eaa.el7.noarch from downloaded_rpms
[2019-07-16T14:42:16.529Z]       unresolved deps:
[2019-07-16T14:42:16.529Z]          npm(@theforeman/vendor) < 0:1.0.0
[2019-07-16T14:42:16.529Z]          npm(@theforeman/vendor) >= 0:0.1.0
```
is this expected?

**Pull request merged**
