### PR TITLE
Update rubygem-foreman_scc_manager to 3.1.0 in Foreman 3.11

### PR DESCRIPTION
**Pull request by nadjaheitmann**
(cherry picked from commit 2e892f702155512bd581aa753e0465a9628aa1e5)

### CODE REVIEW

**Review by ehelms — APPROVED** [review]

**Comment by nadjaheitmann** [comment]
@theforeman/packaging Any idea why this package is not in https://yum.theforeman.org/katello/4.13/katello/el8/x86_64/ ?

**Comment by evgeni** [comment]
I think there was no Katello release since. I can try to remember to run one tomorrow

**Comment by nadjaheitmann** [comment]
Thanks!

**Comment by nadjaheitmann** [comment]
@evgeni Just in case - trying to help you remember ;)

**Pull request merged**
