### PR TITLE
Update foreman_m2 to 0.0.2

### PR DESCRIPTION
**Pull request by ianballou**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.19
* [ ] 1.18
* [ ] 1.17

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
@ianballou Please add a changelog entry, then this will be ready to go

**Comment by ianballou** [comment]
@ehelms I've added the changelog entry

**Comment by ehelms** [comment]
[test rpm]

**Pull request merged**
