### PR TITLE
Update foreman-fog-proxmox to 0.13.3

### PR DESCRIPTION
**Pull request by tristanrobert**
* Nightly
 Fixes #6454

### CODE REVIEW

**Comment by evgeni** [comment]
Seems your `debian/rules` has lines indented with spaces, not tabs, and Makefiles don't like that.

If you want to play guinea-pig with me, I had prepared a common makefile for forman plugins, as you can see in https://github.com/theforeman/foreman-packaging/pull/6240/files

So your `debian/rules` would bcome

```make
PLUGIN = foreman_fog_proxmox
PLUGIN_HAS_ASSETS = true
PLUGIN_HAS_WEBPACK = false
PLUGIN_HAS_PACKAGE_JSON = false
PLUGIN_HAS_API = true

include /usr/share/foreman/foreman-plugin.mk
```

**Comment by tristanrobert** [comment]
> Seems your `debian/rules` has lines indented with spaces, not tabs, and Makefiles don't like that. -- seems you fixed that now, thanks!
> 
> If you want to play guinea-pig with me, I had prepared a common makefile for forman plugins, as you can see in https://github.com/theforeman/foreman-packaging/pull/6240/files
> 
> So your `debian/rules` would become
> 
> ```makefile
> PLUGIN = foreman_fog_proxmox
> PLUGIN_HAS_ASSETS = true
> PLUGIN_HAS_WEBPACK = false
> PLUGIN_HAS_PACKAGE_JSON = false
> PLUGIN_HAS_API = true
> 
> include /usr/share/foreman/foreman-plugin.mk
> ```
> 
> I plan to update all plugins to this layout in the future, but would not rush it.

I would like to. Your PR is very interesting. Meanwhile, I have fixed debian/rules syntax and it has succeeded.

**Comment by evgeni** [comment]
> I would like to. Your PR is very interesting. Meanwhile, I have fixed debian/rules syntax and it has succeeded.

Given it builds fine now and contains important fixes, lets get that released and then switch `debian/rules` in a follow up?

**Comment by tristanrobert** [comment]
> > I would like to. Your PR is very interesting. Meanwhile, I have fixed debian/rules syntax and it has succeeded.
> 
> Given it builds fine now and contains important fixes, lets get that released and then switch `debian/rules` in a follow up?

Ok!

**Review by evgeni — APPROVED** [review]

**Pull request merged**
