### PR TITLE
Update foreman_monitoring to 0.1.2 [deb]

### PR DESCRIPTION
**Pull request by timogoebel**
Please build for

* [ ] Nightly
* [x] 1.16
* [x] 1.15
* [ ] 1.14

### CODE REVIEW

**Comment by mmoll** [comment]
0.1.x is not compatible with current nightlies, please open a PR for 0.1.2 against deb/1.16 for 1.15 & 1.16 and one for 0.2.0 against deb/deb/develop.

**Comment by timogoebel** [comment]
@mmoll: 0.2.0 hasn't been released, yet. But I can definitely point this PR to `deb/1.16`.

**Comment by mmoll** [comment]
@timogoebel yes, please.

**Comment by timogoebel** [comment]
@mmoll: Done.

**Comment by mmoll** [comment]
merged, danke @timogoebel!

**Pull request merged**
