### PR TITLE
Updated dhcp_remote_isc to 0.0.4

### PR DESCRIPTION
**Pull request by witlessbird**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.17
* [x] 1.16
* [ ] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by witlessbird** [comment]
> It also looks like you added rsec to the requirements but only as development dependencies. The code implies it should be a runtime dependency. Is that correct? How about concurrent-ruby? Is that also supposed to be a runtime dependency?

Both rsec and concurrent-ruby are smart-roxy dependencies and provided by it. These only need to be installed to be able to run tests.

**Comment by ekohl** [comment]
> Both rsec and concurrent-ruby are smart-proxy dependencies, provided by smart-proxy. These only need to be installed to be able to run tests.

Ok. If you just bump the foreman-proxy requirement to 1.16 then it should be good to go.

**Comment by witlessbird** [comment]
> Ok. If you just bump the foreman-proxy requirement to 1.16 then it should be good to go.

done.

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
