### PR TITLE
1.17.0-RC1 Release

### PR DESCRIPTION
**Pull request by xprazak2**
For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [x] 1.17
* [ ] 1.16
* [ ] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

I removed jessie completely as it will not be supported in 1.17

### CODE REVIEW

**Comment by mmoll** [comment]
the versions must be `1.17.0~rc1-1`

**Comment by mmoll** [comment]
Also, please open a PR to delete the jessie stuff against `deb/develop`, I'll cherry-pick it, then.

**Comment by xprazak2** [comment]
I synced the changelogs and added correct versions.

**Comment by mmoll** [comment]
The branch name must start with `deb/1.17` in your fork. Maybe you can even change it via GH's UI once you created the branch. Otherwise please re-open a new PR.

**Pull request closed without merging**
