### PR TITLE
Update rubygem-foreman_openscap to 0.3.3

### PR DESCRIPTION
**Pull request by isimluk**
Minor bugfix release.

### CODE REVIEW

**Comment by domcleal** [comment]
The path to the new .gem looks wrong, it's in the top level dir but should be inside the rubygem-* dir.

**Comment by isimluk** [comment]
Embarrassing, fixed.

**Comment by domcleal** [comment]
[test]

**Comment by domcleal** [comment]
Thanks @isimluk, building for nightlies now.  (And 1.8 if you wish.)

**Pull request merged**
