### PR TITLE
Package pre-compiled python files

### PR DESCRIPTION
**Pull request by sbernhard**
This fixes the following issue:

error: Installed (but unpackaged) file(s) found:
  /usr/lib/yum-plugins/foreman-protector.pyc
  /usr/lib/yum-plugins/foreman-protector.pyo

Installed (but unpackaged) file(s) found:
  /usr/lib/yum-plugins/foreman-protector.pyc
  /usr/lib/yum-plugins/foreman-protector.pyo

### CODE REVIEW

**Comment by sbernhard** [comment]
Best practice is to package pre compiled files:

https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/#Byte_Compiled_Files

**Comment by sbernhard** [comment]
[test rpm]

**Comment by ekohl** [comment]
In the resulting RPM I don't see any .pyc files and I think that's because it's not a Python package. https://docs.fedoraproject.org/en-US/packaging-guidelines/Python_Appendix/#manual-bytecompilation suggests you can do it manually.

**Comment by sbernhard** [comment]
I guess, this depends. In our build workflow the *.pyc / *.pyo are created. Changing it to "_protector.py*" shouldn't harm.

**Comment by ehelms** [comment]
@sbernhard this needs a rebase

**Comment by evgeni** [comment]
@sbernhard as Eric said this needs a rebase, but even then it requires manual compilation as Ewoud writes, as the files are in a custom folder where the normal build process does not build them.

However, I don't see a huge benefit of providing this versus making Python generate that on demand? It's not like it's a lot of code that takes long to compile.

**Comment by dgoetz** [comment]
@evgeni: Problem is not compile time, it leaves a file that will not be uninstalled if the package gets removed and depending on SELinux and permissions something can go wrong during compile.

**Comment by evgeni** [comment]
@dgoetz see, the PR description didn't say what it tries to fix :)

**Comment by evgeni** [comment]
repoclosure errors unrelated. however, the package still does not contain byte compiled files.

**Comment by sbernhard** [comment]
ping!?

**Comment by evgeni** [comment]
@sbernhard the built RPMs still don't contain the byte compiled files as nothing compiles them.

**Comment by sbernhard** [comment]
This depends on the RPM build configuration. In other environments (like our internal one) this issue happens. Therefore it would be nice to merge this as it doesn't break anything.

**Comment by evgeni** [comment]
Which configuration (and how) would I need to change?
I'd prefer if the package would do it, so the change is fully self contained.
Otherwise this is environment dependent and the changelog entry is kinda misleading for users of this repository.

**Comment by sbernhard** [comment]
Use "rpm --showrc | less"

In a "default" centos installations, this is included: 
-14: __os_install_post  
    /usr/lib/rpm/redhat/brp-compress 
    %{!?__debug_package:
    /usr/lib/rpm/redhat/brp-strip %{__strip} 
    /usr/lib/rpm/redhat/brp-strip-comment-note %{__strip} %{__objdump} 
    } 
    /usr/lib/rpm/redhat/brp-strip-static-archive %{__strip} 
    /usr/lib/rpm/brp-python-bytecompile %{__python} %{?_python_bytecompile_errors_terminate_build} 
    /usr/lib/rpm/redhat/brp-python-hardlink 
    %{!?__jar_repack:/usr/lib/rpm/redhat/brp-java-repack-jars} 
%{nil}

I guess, on the build host which is used to create the foreman/katello packages this is turned off.

**Comment by ekohl** [comment]
I'd suggest to explicitly do this. In Fedora there's https://fedoraproject.org/wiki/Changes/No_more_automagic_Python_bytecompilation so this is likely to be going away. Have you verified it also works on EL8?

The correct way is:
```
%py_byte_compile %{__python2} %{buildroot}%{_datadir}/mypackage/foo
%py_byte_compile %{__python3} %{buildroot}%{_datadir}/mypackage/bar
```

**Comment by sbernhard** [comment]
@ekohl, I guess you mean to change the foreman build environment and "byte compile" every python file? 
I would love to get this done. Don't want to do another rebase :)

**Comment by evgeni** [comment]
I (personally) think the foreman-maintain packaging should take care of the byte compilation.

**Comment by sbernhard** [comment]
Nobody interested in this change? :(

**Comment by evgeni** [comment]
Not before the byte compilation is in this PR, no.

**Comment by evgeni** [comment]
This seems to have worked on EL7, thanks!

```
-rw-r-----    1 root     root                     2707 Aug  3 13:21 /usr/lib/yum-plugins/foreman-protector.py
-rw-r--r--    2 root     root                     3318 Aug  3 13:21 /usr/lib/yum-plugins/foreman-protector.pyc
-rw-r--r--    2 root     root                     3318 Aug  3 13:21 /usr/lib/yum-plugins/foreman-protector.pyo
```

On EL8 however, it fails now:

```
+ xargs -0 /usr/libexec/platform-python -O -m py_compile
+ find ./usr/lib/yum-plugins/foreman-protector.py -type f -a -name '*.py' -print0
  File "./usr/lib/yum-plugins/foreman-protector.py", line 29
    except urlgrabber.grabber.URLGrabError, e:
                                          ^
SyntaxError: invalid syntax
+ failure=1
+ xargs -0 /usr/libexec/platform-python -m py_compile
+ find ./usr/lib/yum-plugins/foreman-protector.py -type f -a -name '*.py' -print0
  File "./usr/lib/yum-plugins/foreman-protector.py", line 29
    except urlgrabber.grabber.URLGrabError, e:
                                          ^
SyntaxError: invalid syntax
```

Seems f-maintain's code is not Python 3 compatible :scream: (it needs to be `except Exc as e`)

**Comment by sbernhard** [comment]
Disable python3 byte compile til https://github.com/theforeman/foreman_maintain/pull/382 is available?

**Comment by evgeni** [comment]
Let me ping foreman maintain people if they plan a release *soon*, otherwise this sounds like a plan.

**Comment by tbrisker** [comment]
This has been incorporated into https://github.com/theforeman/foreman-packaging/pull/5618, thanks @sbernhard and all!

**Comment by sbernhard** [comment]
Thanks!

**Pull request closed without merging**
