### PR TITLE
Update foreman_remote_execution to 1.6.4 [rpm]

### PR DESCRIPTION
**Pull request by iNecas**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.19
* [ ] 1.18
* [ ] 1.17

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by iNecas** [comment]
Seems like the test failures are unrelated:

```
DEBUG util.py:491:  Error: Package: foreman-1.20.0-0.201810070944gite50e4ff0.9.develop.el7.noarch (build)
DEBUG util.py:491:             Requires: tfm-rubygem(secure_headers) < 6.0
DEBUG util.py:491:             Available: tfm-rubygem-secure_headers-6.0.0-1.el7.noarch (build)
DEBUG util.py:491:                 tfm-rubygem(secure_headers) = 6.0.0
DEBUG util.py:491:  Error: Package: foreman-assets-1.20.0-0.201810070944gite50e4ff0.9.develop.el7.noarch (build)
DEBUG util.py:491:             Requires: npm(patternfly-react) = 2.5.1
DEBUG util.py:491:             Available: nodejs-patternfly-react-2.19.1-1.el7.noarch (build)
DEBUG util.py:491:                 npm(patternfly-react) = 2.19.1
DEBUG util.py:491:  Error: Package: foreman-1.20.0-0.201810070944gite50e4ff0.9.develop.el7.noarch (build)
DEBUG util.py:491:             Requires: tfm-rubygem(secure_headers) < 6.0
DEBUG util.py:491:             Installing: tfm-rubygem-secure_headers-6.0.0-1.el7.noarch (build)
DEBUG util.py:491:                 tfm-rubygem(secure_headers) = 6.0.0
```

@ehelms / @ekohl known issue?

**Comment by tbrisker** [comment]
@iNecas 'םרלןמע םמ ןאת דקק GH-3070

**Comment by ehelms** [comment]
[test rpm]

**Comment by tbrisker** [comment]
Looks like this is now failing on webpack compilation:
```
BUILDSTDERR: /builddir/build/BUILD/rubygem-foreman_remote_execution-1.6.4/usr/share/foreman/node_modules/webpack/bin/webpack.js --config /builddir/build/BUILD/rubygem-foreman_remote_execution-1.6.4/usr/share/foreman/config/webpack.config.js --bail --env.pluginName=foreman_remote_execution
Hash: 773e59843d979c7cf2f4
Version: webpack 3.12.0
Time: 104277ms
 10 assets
[../../../../../BUILDROOT/tfm-rubygem-foreman_remote_execution-1.6.4-1.fm1_20.el7.noarch/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_remote_execution-1.6.4/webpack/index.js] /builddir/build/BUILDROOT/tfm-rubygem-foreman_remote_execution-1.6.4-1.fm1_20.el7.noarch/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_remote_execution-1.6.4/webpack/index.js 1.44 kB {1} [built]
[./webpack/assets/javascripts/bundle.js] ./webpack/assets/javascripts/bundle.js 2.18 kB {0} [built]
[./webpack/assets/javascripts/bundle_datatables.js] ./webpack/assets/javascripts/bundle_datatables.js 104 bytes {0} [built]
[./webpack/assets/javascripts/bundle_lodash.js] ./webpack/assets/javascripts/bundle_lodash.js 705 bytes {0} [built]
[./webpack/assets/javascripts/bundle_multiselect.js] ./webpack/assets/javascripts/bundle_multiselect.js 84 bytes {0} [built]
[./webpack/assets/javascripts/bundle_novnc.js] ./webpack/assets/javascripts/bundle_novnc.js 1.98 kB {0} [built]
[./webpack/assets/javascripts/bundle_select2.js] ./webpack/assets/javascripts/bundle_select2.js 110 bytes {0} [built]
[./webpack/assets/javascripts/foreman_advanced_fields.js] ./webpack/assets/javascripts/foreman_advanced_fields.js 921 bytes {0} [built]
[./webpack/assets/javascripts/foreman_auth_source.js] ./webpack/assets/javascripts/foreman_auth_source.js 2.95 kB {0} [built]
[./webpack/assets/javascripts/foreman_compute_resource.js] ./webpack/assets/javascripts/foreman_compute_resource.js 4.94 kB {0} [built]
[./webpack/assets/javascripts/foreman_editor.js] ./webpack/assets/javascripts/foreman_editor.js 13.6 kB {0} {1} [built]
[./webpack/assets/javascripts/foreman_hostgroups.js] ./webpack/assets/javascripts/foreman_hostgroups.js 1.3 kB {0} [built]
[./webpack/assets/javascripts/foreman_hosts.js] ./webpack/assets/javascripts/foreman_hosts.js 4.83 kB {0} [built]
[./webpack/assets/javascripts/foreman_http_proxies.js] ./webpack/assets/javascripts/foreman_http_proxies.js 1.24 kB {0} [built]
   [0] multi babel-polyfill react react-dom react-bootstrap react-debounce-input react-ellipsis-with-tooltip react-numeric-input react-onclickoutside react-password-strength patternfly-react react-redux redux redux-form redux-form-validators redux-logger redux-thunk prop-types seamless-immutable isomorphic-fetch jquery jquery.cookie select2 multiselect jquery-ujs datatables.net-bs jquery-flot/excanvas jquery-flot jquery-flot/jquery.flot.pie jquery-flot/jquery.flot.selection jquery-flot/jquery.flot.stack jquery-flot/jquery.flot.time brace brace/mode/ruby brace/mode/html_ruby brace/mode/json brace/mode/sh brace/mode/xml brace/mode/yaml brace/mode/diff brace/theme/twilight brace/theme/clouds brace/keybinding/vim brace/keybinding/emacs brace/ext/searchbox axios diff ipaddr.js jstz urijs uuid @novnc/novnc/core/rfb.js 628 bytes {2} [built]
    + 1142 hidden modules
ERROR in ./webpack/assets/javascripts/react_app/components/Layout/layout.scss
Module build failed: ModuleBuildError: Module build failed: 
@import '../../../../../../app/assets/stylesheets/colors.scss';
^
      File to import not found or unreadable: ../../../../../../app/assets/stylesheets/colors.scss.
Parent style sheet: stdin
      in /builddir/build/BUILD/rubygem-foreman_remote_execution-1.6.4/usr/share/foreman/webpack/assets/javascripts/react_app/components/Layout/layout.scss (line 1, column 1)
    at runLoaders (/usr/lib/node_modules/webpack/lib/NormalModule.js:195:19)
    at /usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/usr/lib/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.done [as callback] (/usr/lib/node_modules/sass-loader/node_modules/neo-async/async.js:7974:18)
    at options.error (/usr/lib/node_modules/node-sass/lib/index.js:294:32)
 @ ./webpack/assets/javascripts/react_app/components/Layout/Layout.js 33:0-24
 @ ./webpack/assets/javascripts/react_app/components/Layout/index.js
 @ ./webpack/assets/javascripts/react_app/components/componentRegistry.js
 @ /builddir/build/BUILDROOT/tfm-rubygem-foreman_remote_execution-1.6.4-1.fm1_20.el7.noarch/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_remote_execution-1.6.4/webpack/index.js
ERROR in ./webpack/assets/javascripts/react_app/components/Layout/layout.scss
Module build failed: ModuleBuildError: Module build failed: 
@import '../../../../../../app/assets/stylesheets/colors.scss';
^
      File to import not found or unreadable: ../../../../../../app/assets/stylesheets/colors.scss.
Parent style sheet: stdin
      in /builddir/build/BUILD/rubygem-foreman_remote_execution-1.6.4/usr/share/foreman/webpack/assets/javascripts/react_app/components/Layout/layout.scss (line 1, column 1)
    at runLoaders (/usr/lib/node_modules/webpack/lib/NormalModule.js:195:19)
    at /usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/usr/lib/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.done [as callback] (/usr/lib/node_modules/sass-loader/node_modules/neo-async/async.js:7974:18)
    at options.error (/usr/lib/node_modules/node-sass/lib/index.js:294:32)
 @ ./webpack/assets/javascripts/react_app/components/Layout/layout.scss
 @ ./webpack/assets/javascripts/react_app/components/Layout/Layout.js
 @ ./webpack/assets/javascripts/react_app/components/Layout/index.js
 @ ./webpack/assets/javascripts/react_app/components/componentRegistry.js
 @ /builddir/build/BUILDROOT/tfm-rubygem-foreman_remote_execution-1.6.4-1.fm1_20.el7.noarch/opt/theforeman/tfm/root/usr/share/gems/gems/foreman_remote_execution-1.6.4/webpack/index.js
Child extract-text-webpack-plugin ../../../../../../../usr/lib/node_modules/extract-text-webpack-plugin/dist ../../../../../../../usr/lib/node_modules/css-loader/index.js!../../../../../../../usr/lib/node_modules/select2/select2-bootstrap.css:
       2 modules
Child extract-text-webpack-plugin ../../../../../../../usr/lib/node_modules/extract-text-webpack-plugin/dist ../../../../../../../usr/lib/node_modules/css-loader/index.js!../../../../../../../usr/lib/node_modules/datatables.net-bs/css/dataTables.bootstrap.css:
       2 modules
Child extract-text-webpack-plugin ../../../../../../../usr/lib/node_modules/extract-text-webpack-plugin/dist ../../../../../../../usr/lib/node_modules/css-loader/index.js!../../../../../../../usr/lib/node_modules/sass-loader/lib/loader.js!webpack/assets/javascripts/react_app/components/Pagination/pagination.scss:
       2 modules
Child extract-text-webpack-plugin ../../../../../../../usr/lib/node_modules/extract-text-webpack-plugin/dist ../../../../../../../usr/lib/node_modules/css-loader/index.js!webpack/assets/javascripts/react_app/components/common/MessageBox/MessageBox.css:
       2 modules
Child extract-text-webpack-plugin ../../../../../../../usr/lib/node_modules/extract-text-webpack-plugin/dist ../../../../../../../usr/lib/node_modules/css-loader/index.js!../../../../../../../usr/lib/node_modules/sass-loader/lib/loader.js!webpack/assets/javascripts/react_app/components/notifications/notifications.scss:
       2 modules
Child extract-text-webpack-plugin ../../../../../../../usr/lib/node_modules/extract-text-webpack-plugin/dist ../../../../../../../usr/lib/node_modules/css-loader/index.js!../../../../../../../usr/lib/node_modules/sass-loader/lib/loader.js!webpack/assets/javascripts/react_app/components/statistics/StatisticsChartsListStyles.scss:
       2 modules
Child extract-text-webpack-plugin ../../../../../../../usr/lib/node_modules/extract-text-webpack-plugin/dist ../../../../../../../usr/lib/node_modules/css-loader/index.js!../../../../../../../usr/lib/node_modules/sass-loader/lib/loader.js!webpack/assets/javascripts/react_app/components/AuditsList/audit.scss:
       2 modules
Child extract-text-webpack-plugin ../../../../../../../usr/lib/node_modules/extract-text-webpack-plugin/dist ../../../../../../../usr/lib/node_modules/css-loader/index.js!../../../../../../../usr/lib/node_modules/sass-loader/lib/loader.js!webpack/assets/javascripts/react_app/components/Layout/layout.scss:
       1 module
    
    ERROR in /usr/lib/node_modules/css-loader!/usr/lib/node_modules/sass-loader/lib/loader.js!./webpack/assets/javascripts/react_app/components/Layout/layout.scss
    Module build failed: 
    @import '../../../../../../app/assets/stylesheets/colors.scss';
    ^
          File to import not found or unreadable: ../../../../../../app/assets/stylesheets/colors.scss.
    Parent style sheet: stdin
          in /builddir/build/BUILD/rubygem-foreman_remote_execution-1.6.4/usr/share/foreman/webpack/assets/javascripts/react_app/components/Layout/layout.scss (line 1, column 1)
Child extract-text-webpack-plugin ../../../../../../../usr/lib/node_modules/extract-text-webpack-plugin/dist ../../../../../../../usr/lib/node_modules/css-loader/index.js!../../../../../../../usr/lib/node_modules/sass-loader/lib/loader.js!webpack/assets/javascripts/react_app/components/hosts/powerStatus/powerStatusInner/PowerStatusInner.scss:
       2 modules
Child extract-text-webpack-plugin ../../../../../../../usr/lib/node_modules/extract-text-webpack-plugin/dist ../../../../../../../usr/lib/node_modules/css-loader/index.js!webpack/assets/javascripts/react_app/components/common/Loader/Loader.css:
       2 modules
Child extract-text-webpack-plugin ../../../../../../../usr/lib/node_modules/extract-text-webpack-plugin/dist ../../../../../../../usr/lib/node_modules/css-loader/index.js!../../../../../../../usr/lib/node_modules/select2/select2.css:
       5 modules
Child extract-text-webpack-plugin ../../../../../../../usr/lib/node_modules/extract-text-webpack-plugin/dist ../../../../../../../usr/lib/node_modules/css-loader/index.js!../../../../../../../usr/lib/node_modules/multiselect/css/multi-select.css:
       3 modules
Child extract-text-webpack-plugin ../../../../../../../usr/lib/node_modules/extract-text-webpack-plugin/dist ../../../../../../../usr/lib/node_modules/css-loader/index.js!../../../../../../../usr/lib/node_modules/sass-loader/lib/loader.js!webpack/assets/javascripts/react_app/components/hosts/storage/vmware/StorageContainer.scss:
       2 modules
Child extract-text-webpack-plugin ../../../../../../../usr/lib/node_modules/extract-text-webpack-plugin/dist ../../../../../../../usr/lib/node_modules/css-loader/index.js!../../../../../../../usr/lib/node_modules/sass-loader/lib/loader.js!webpack/assets/javascripts/react_app/components/BreadcrumbBar/components/BreadcrumbSwitcherPopover.scss:
       2 modules
Child extract-text-webpack-plugin ../../../../../../../usr/lib/node_modules/extract-text-webpack-plugin/dist ../../../../../../../usr/lib/node_modules/css-loader/index.js!../../../../../../../usr/lib/node_modules/sass-loader/lib/loader.js!../../../../../../../usr/lib/node_modules/patternfly-react/dist/sass/_breadcrumb.scss:
       2 modules
Child extract-text-webpack-plugin ../../../../../../../usr/lib/node_modules/extract-text-webpack-plugin/dist ../../../../../../../usr/lib/node_modules/css-loader/index.js!../../../../../../../usr/lib/node_modules/sass-loader/lib/loader.js!webpack/assets/javascripts/react_app/components/common/SearchInput/searchInput.scss:
       2 modules
Child extract-text-webpack-plugin ../../../../../../../usr/lib/node_modules/extract-text-webpack-plugin/dist ../../../../../../../usr/lib/node_modules/css-loader/index.js!../../../../../../../usr/lib/node_modules/sass-loader/lib/loader.js!webpack/assets/javascripts/react_app/components/PasswordStrength/PasswordStrength.scss:
       2 modules
Child extract-text-webpack-plugin ../../../../../../../usr/lib/node_modules/extract-text-webpack-plugin/dist ../../../../../../../usr/lib/node_modules/css-loader/index.js!../../../../../../../usr/lib/node_modules/sass-loader/lib/loader.js!webpack/assets/javascripts/react_app/components/hosts/storage/vmware/controller/controller.scss:
       2 modules
Child extract-text-webpack-plugin ../../../../../../../usr/lib/node_modules/extract-text-webpack-plugin/dist ../../../../../../../usr/lib/node_modules/css-loader/index.js!../../../../../../../usr/lib/node_modules/sass-loader/lib/loader.js!webpack/assets/javascripts/react_app/components/AutoComplete/auto-complete.scss:
       3 modules
Child extract-text-webpack-plugin ../../../../../../../usr/lib/node_modules/extract-text-webpack-plugin/dist ../../../../../../../usr/lib/node_modules/css-loader/index.js!../../../../../../../usr/lib/node_modules/sass-loader/lib/loader.js!webpack/assets/javascripts/react_app/components/hosts/storage/vmware/controller/disk/disk.scss:
       2 modules
Child extract-text-webpack-plugin ../../../../../../../usr/lib/node_modules/extract-text-webpack-plugin/dist ../../../../../../../usr/lib/node_modules/css-loader/index.js!../../../../../../../usr/lib/node_modules/sass-loader/lib/loader.js!webpack/assets/javascripts/react_app/components/Layout/layout.scss:
       1 module
    
    ERROR in /usr/lib/node_modules/css-loader!/usr/lib/node_modules/sass-loader/lib/loader.js!./webpack/assets/javascripts/react_app/components/Layout/layout.scss
    Module build failed: 
    @import '../../../../../../app/assets/stylesheets/colors.scss';
    ^
          File to import not found or unreadable: ../../../../../../app/assets/stylesheets/colors.scss.
    Parent style sheet: stdin
          in /builddir/build/BUILD/rubygem-foreman_remote_execution-1.6.4/usr/share/foreman/webpack/assets/javascripts/react_app/components/Layout/layout.scss (line 1, column 1)
BUILDSTDERR: rake aborted!
BUILDSTDERR: Command failed with status (2): [/builddir/build/BUILD/rubygem-foreman_remo...]
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/file_utils.rb:67:in `block in create_shell_runner'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/file_utils.rb:57:in `sh'
BUILDSTDERR: /builddir/build/BUILD/rubygem-foreman_remote_execution-1.6.4/usr/share/foreman/lib/tasks/plugin_assets.rake:56:in `compile'
BUILDSTDERR: /builddir/build/BUILD/rubygem-foreman_remote_execution-1.6.4/usr/share/foreman/lib/tasks/plugin_assets.rake:66:in `block in <top (required)>'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/ruby/monitor.rb:226:in `mon_synchronize'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/bin/rake:23:in `load'
BUILDSTDERR: /opt/rh/rh-ruby25/root/usr/bin/rake:23:in `<main>'
BUILDSTDERR: Tasks: TOP => plugin:assets:precompile
```
can someone from @theforeman/ui-ux please take a look?

**Comment by iNecas** [comment]
Rebasing the PR, just in case, the link to last failing jenkins is here http://koji.katello.org/koji/taskinfo?taskID=140114

**Comment by amirfefer** [comment]
@tbrisker it seems this error occurs because a wrong import from rails assets pipeline (`color.scss`)

**Comment by tbrisker** [comment]
[test rpm]

**Comment by tbrisker** [comment]
@ekohl is this also the same issue as katello?

**Comment by iNecas** [comment]
image

but I've inspired by https://github.com/theforeman/foreman-packaging/pull/3083, lets see what happens.

I wonder if that should not be part of `%foreman_precompile_plugin` macro

**Comment by iNecas** [comment]
Ok, I've read https://github.com/theforeman/foreman-packaging/pull/3083#pullrequestreview-163882877 and I guess this is the right approach at the moment.

**Comment by iNecas** [comment]
Everything is :green_apple: now

**Comment by ekohl** [comment]
Yes, we probably want to fix it in the webpack config or transform the paths so they don't leak internal details.

**Pull request merged**
