### PR TITLE
Update rubygem-foreman_bootdisk to 17.1.0

### PR DESCRIPTION
**Pull request by lzap**
For plugin updates, please indicate which repos this should be built into:

* Nightly
* 2.4

Better later than never :-) Will do the CP PR.

### CODE REVIEW

**Comment by zjhuntin** [comment]
Currently failing because it's finding the rubocop file and it's not mentioned in the spec:

`RPM build errors:
    Installed (but unpackaged) file(s) found:
   /opt/theforeman/tfm/root/usr/share/gems/gems/foreman_bootdisk-17.1.0/.github/workflows/rubocop.yaml`

**Comment by lzap** [comment]
Oh damn thanks for comment, that was helpful I tend to not return to PRs gh notification system is not good.

**Comment by lzap** [comment]
I think this was not caused by this patch:

```
DEBUG util.py:598:  Error: Package: foreman-2.5.0-0.6.develop.20210428151714gitcaf6e08.el7.noarch (build)
DEBUG util.py:598:             Requires: tfm-rubygem(activerecord-session_store) < 2
DEBUG util.py:598:             Installing: tfm-rubygem-activerecord-session_store-2.0.0-1.el7.noarch (build)
DEBUG util.py:598:                 tfm-rubygem(activerecord-session_store) = 2.0.0
DEBUG util.py:598:  Error: Package: foreman-2.5.0-0.6.develop.20210428151714gitcaf6e08.el7.noarch (build)
DEBUG util.py:598:             Requires: tfm-rubygem(activerecord-session_store) < 2
DEBUG util.py:598:             Available: tfm-rubygem-activerecord-session_store-2.0.0-1.el7.noarch (build)
```

**Comment by lzap** [comment]
I think I need to wait for: https://github.com/theforeman/foreman-packaging/pull/6572

**Comment by evgeni** [comment]
[test rpm]

**Comment by lzap** [comment]
Thank you, it is green now!

**Review by evgeni — APPROVED** [review]

**Comment by evgeni** [comment]
It's purple now.

**Comment by lzap** [comment]
CP: https://github.com/theforeman/foreman-packaging/pull/6578

**Pull request merged**
