### PR TITLE
Release 1.21.3

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by tbrisker** [comment]
Looks like this is failing on some installer deps?

**Comment by ekohl** [comment]
Yes, pretty sure it's because our repoclosure process is broken due to mixing of SCL and non-SCL. @evgeni is working on improving this, but it's harder than it looks.

**Comment by tbrisker** [comment]
how do we proceed then?

**Comment by ekohl** [comment]
Just merge it.

**Pull request merged**
