### PR TITLE
Update DHCP Infoblox plugin changelog 

### PR DESCRIPTION
**Pull request by timdeluxe**
due to recent control file dependency section change

(cherry picked from commit 088cf800d3be9e232c6c38345fbd9250c0511958)

Please triple check, if i selected/used the correct commit now!

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
Awesome, thanks! https://deb.theforeman.org/pool/plugins/nightly/r/ruby-smart-proxy-dhcp-infoblox/ does show the 0.0.17-2 build for nightly, so that worked.

**Comment by timdeluxe** [comment]
...but https://deb.theforeman.org/pool/plugins/3.5/r/ruby-smart-proxy-dhcp-infoblox/ still shows 0.0.17-1 😕
Am i too impatient?

**Comment by ekohl** [comment]
No, this is yet another "fun" thing. Our CDN caches things, which includes the directory index. If you try to retrieve the file by the exact URL it does show up. We purge some entries, but really only so apt can work.

**Comment by timdeluxe** [comment]
Okay, confirmed, that worked (on our system):
`Preparing to unpack .../12-ruby-smart-proxy-dhcp-infoblox_0.0.17-2_all.deb ...`
Thanks for your support on my journey to fix it. 👍

**Comment by ekohl** [comment]
And thank you for taking the time to follow it through.

**Pull request merged**
