### PR TITLE
Update Katello to 4.4.0.1

### PR DESCRIPTION
**Pull request by ianballou**
One commit for a migration issue and one revert for a UI issue caused need for a quick new release of Katello. Since it's so small it didn't make sense to bother with a full 4.4.1.

It sounds like this might get blocked on the qpid_proton issues.

### CODE REVIEW

**Comment by zjhuntin** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Review by evgeni — APPROVED** [review]

**Pull request merged**
