### PR TITLE
Rpm/foreman tasks 0.10.3 [rpm]

### PR DESCRIPTION
**Pull request by iNecas**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.16
* [ ] 1.15
* [ ] 1.14

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

Requires https://github.com/theforeman/foreman-packaging/pull/1820

### CODE REVIEW

**Comment by iNecas** [comment]
rebased

**Comment by iNecas** [comment]
@dLobatog It seems dynflow 0.8.30 is in foreman 1.15, but not in 1.16 or nightly http://koji.katello.org/koji/buildinfo?buildID=17046, some missing tags maybe?

**Comment by ehelms** [comment]
Built for nightly -- http://koji.katello.org/koji/taskinfo?taskID=34149

**Comment by ehelms** [comment]
[test]

**Comment by ekohl** [comment]
The tags list appears to be somewhat inconsistent.

```
$ kkoji list-tags --package tfm-rubygem-dynflow
foreman-1.16-rhel7
foreman-nightly-rhel7
foreman-plugins-1.15-rhel7
foreman-plugins-nightly-rhel7
```

**Comment by iNecas** [comment]
That's probably due to fact that dynflow was made as foreman dependency lately., therefore the transition from plugins

**Comment by iNecas** [comment]
[test]

**Comment by iNecas** [comment]
It seems the new version of dynflow is still not available in the build root

**Comment by ehelms** [comment]
[test]

**Comment by ehelms** [comment]
@iNecas dependencies fixed -- you should see this fail in the build.log with no file bin/foreman-tasks

**Comment by iNecas** [comment]
Ah, we need to finalize https://github.com/theforeman/foreman-packaging/pull/1549/files first.

**Comment by mmoll** [comment]
hrm, why does this work on Debian as it currently is then? Does this mean, the whole tasks executor integration needs to get finished in the 1.16.0 timeframe?

**Comment by iNecas** [comment]
If feasible yes, otherwise, I would need to revert the changes in the tasks that removed the service script. I need to check this, but I suspect that the package built, but would not work properly, as the bin script is missing from the sources.

**Comment by iNecas** [comment]
Closing in favor of https://github.com/theforeman/foreman-packaging/pull/1985/files

**Pull request closed without merging**
