### PR TITLE
Rebuild foreman_templates

### PR DESCRIPTION
**Pull request by ares**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.20
* [ ] 1.19

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

we need newer git dependency, we now bundle 1.3.0, more details at https://github.com/theforeman/foreman_templates/issues/107

### CODE REVIEW

**Comment by mmoll** [comment]
@ares sorry for the delay... Why is this relevant only for nighly?

**Comment by ares** [comment]
to get the newer git bundled and let people test before we push to stable releases, I got only one user confirmed it works

**Comment by mmoll** [comment]
@ares :ok:

**Comment by mmoll** [comment]
merged, díky @ares!

**Pull request merged**
