### PR TITLE
Deb/add foreman_fog_proxmox plugin

### PR DESCRIPTION
**Pull request by tristanrobert**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.19
* [x] 1.18
* [x] 1.17
See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ekohl** [comment]
ok to test

**Comment by tristanrobert** [comment]
I think I have to add first a ruby-fog-proxmox deb packaging and then to depend on it.

**Comment by tristanrobert** [comment]
Hello, could anybody test it?

**Comment by mmoll** [comment]
merged with minor modifications as GH-3251

**Pull request closed without merging**
