### PR TITLE
Update Rails stack to 6.1.7

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
Can be cherry picked to 3.4 and 3.5

**Comment by ekohl** [comment]
Reading through the changes via https://rubyonrails.org/2022/9/9/Rails-7-0-4-6-1-7-6-0-6-have-been-released now.

**Review by ekohl — APPROVED** [review]
The only changes that can affect us are https://github.com/rails/rails/blob/v6.1.7/activerecord/CHANGELOG.md#rails-617-september-09-2022 and I don't think that will have any (negative) effects.

**Comment by evgeni** [comment]
Who is updating https://github.com/theforeman/foreman/blob/develop/Gemfile#L6? :)

**Comment by ehelms** [comment]
For develop branch -- https://github.com/theforeman/foreman/pull/9511

**Comment by evgeni** [comment]
packaging boundary update in https://github.com/theforeman/foreman-packaging/pull/8787

**Review by evgeni — CHANGES_REQUESTED** [review]
This PR did not update the dependencies, so that e.g actioncable still depends on:

```
Requires: %{?scl_prefix}rubygem(activesupport) = 6.1.6.1
Requires: %{?scl_prefix}rubygem(actionpack) = 6.1.6.1
```

I am going to use the ones generated by the automation, as they did update the specs to the latest template too ;)

**Comment by evgeni** [comment]
And closing, as the others are merged and I opened a CP for 3.5 in https://github.com/theforeman/foreman-packaging/pull/8788

**Pull request closed without merging**
