### PR TITLE
Update ruby-foreman-tasks to 7.1.0

### PR DESCRIPTION
**Pull request by adamruzicka**
CPs:
- 3.5

### CODE REVIEW

**Review by evgeni — APPROVED** [review]

**Comment by evgeni** [comment]
> 3.5

Will you do the CP PR? :)

**Comment by adamruzicka** [comment]
Of course, I try to do them whenever I can

**Comment by adamruzicka** [comment]
Eh, what did I do wrong this time?

**Comment by evgeni** [comment]
Nothing. Not that I understand the failure, but it was not you.

**Comment by ekohl** [comment]
```
[2022-11-10T12:20:09.231Z] make[1]: Entering directory '/home/jenkins/workspace/foreman-packaging-deb-pr-test/plugins/build-ruby-foreman-tasks/ruby-foreman-tasks'
[2022-11-10T12:20:09.231Z] cp -r /usr/share/foreman/vendor/ruby/*/gems/foreman-tasks-*/extra ./
[2022-11-10T12:20:09.231Z] cp: cannot stat '/usr/share/foreman/vendor/ruby/*/gems/foreman-tasks-*/extra': No such file or directory
[2022-11-10T12:20:09.231Z] make[1]: *** [debian/rules:15: override_dh_auto_install] Error 1
[2022-11-10T12:20:09.231Z] make[1]: Leaving directory '/home/jenkins/workspace/foreman-packaging-deb-pr-test/plugins/build-ruby-foreman-tasks/ruby-foreman-tasks'
[2022-11-10T12:20:09.231Z] make: *** [/usr/share/foreman/foreman-plugin.mk:40: binary] Error 2
[2022-11-10T12:20:09.231Z] dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
```

The the `extra` directory is in the gem so I wonder why it can't find it.

**Pull request merged**
