### PR TITLE
Update Katello pulp_rpm_client requirement to 3.10.0

### PR DESCRIPTION
**Pull request by ianballou**

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test rpm]

**Comment by jlsherrill** [comment]
lets wait for this to finish: https://ci.theforeman.org/job/katello-master-source-release/1341/  and then i think we will get a green rpm build (repoclosure will still likely fail)

**Comment by ianballou** [comment]
[test rpm]

**Comment by jlsherrill** [comment]
merging as we likely need nightly mashing to occur before repoclsoure will pass

**Review by jlsherrill — APPROVED** [review]

**Pull request merged**
