### PR TITLE
[deb] Bump foreman_ansible to 2.1

### PR DESCRIPTION
**Pull request by dLobatog**
For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [x] 1.17

----------

I think this might be the first debian plugin with webpack assets, do you have any ideas on how would it be best to compile them?

### CODE REVIEW

**Comment by mmoll** [comment]
the version needs to be 2.1.0, like the gem

**Comment by mmoll** [comment]
if this is not compatible with foreman-tasks 0.12, that would be 1.17 only, at least for the moment

**Comment by mmoll** [comment]
please open against deb/1.17 then :)

**Comment by mmoll** [comment]
Also, as mentioned in GH-2256, DEB and RPM probably need some work to deal with the new webpack assets, I guess the packaging team needs at least input from the frontend guys here?

**Comment by ehelms** [comment]
[test packaging]

**Comment by komidore64** [comment]
please ignore the `default` pending check.

**Comment by mmoll** [comment]
waiting on GH-2442

**Comment by mmoll** [comment]
@dLobatog could you update this to 2.1.2 and point to (and rebase onto) `deb/1.17`?

**Comment by mmoll** [comment]
does 1.17 bring all the things for webpack assets? And does foreman_ansible 2.1.x use webpack assets?

**Pull request closed without merging**
