### PR TITLE
Add rubygem-foreman_wreckingball package

### PR DESCRIPTION
**Pull request by dgoetz**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.18
* [x] 1.17
* [ ] 1.16

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by dgoetz** [comment]
Added it to the manifests and tests re-run successfully.

Entry in packages_mainfests is the only thing missing when running the new `add_gem_package.sh` script, thanks for this helpful script.

**Comment by ekohl** [comment]
I've merged this and released to nighly but then I realized this uses the `scl` template rather than the `foreman_plugin`. We should fix that and then backport it.

**Comment by dgoetz** [comment]
Does this require more than changing the spec (and a new pull request)?

**Comment by ekohl** [comment]
No, just change the spec. `add_gem_package.sh` can do that nowadays. It's very recent though so have a good look at what it generates.

**Pull request merged**
