### PR TITLE
Update smart_proxy_ansible to 2.1.1

### PR DESCRIPTION
**Pull request by ares**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.21
* [ ] 1.20

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by mmoll** [comment]
merged, díky @ares!

**Comment by xprazak2** [comment]
Somehow, the 2.1.1 version did not make it into [1.21](http://deb.theforeman.org/pool/plugins/1.21/r/ruby-smart-proxy-ansible/), though I can see it in [nightly](http://deb.theforeman.org/pool/plugins/nightly/r/ruby-smart-proxy-ansible/)...

**Comment by ares** [comment]
I guess people noticed :-) https://github.com/theforeman/foreman-packaging/pull/3393 @mmoll do you want me to open PR with CP or is that just some jenkins job that needs to be triggered?

**Comment by mmoll** [comment]
seems like I forgot to trigger the build, should be fixed now

**Pull request merged**
