### PR TITLE
build nodejs packages using node 18 on el9

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
Does this mean we need a foreman-devel:el9 as well?

**Comment by evgeni** [comment]
> Does this mean we need a foreman-devel:el9 as well?

technically, yeah. but that's unrelated to this PR (we only really need devel for packit and friends), so I was slacking off on this topic

**Comment by ekohl** [comment]
Which is why I approved. Just something that came up in the review

**Comment by ehelms** [comment]
> > Does this mean we need a foreman-devel:el9 as well?
> 
> technically, yeah. but that's unrelated to this PR (we only really need devel for packit and friends), so I was slacking off on this topic

What is meant by this question?

**Pull request merged**
