### PR TITLE
Update foreman package dependencies

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ekohl** [comment]
Will need https://github.com/theforeman/foreman-packaging/pull/3458

**Comment by timogoebel** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
Looks like we merged roadie-rails but haven't built a new foreman tarball yet

**Comment by ekohl** [comment]
Merging because there's no way to test this since the job that builds the tarball now fails.

**Pull request merged**
