### PR TITLE
Introducing puppet-foreman_scap_client

### PR DESCRIPTION
**Pull request by isimluk**
Tested on rhel6 box. After rpm installation we get:

```
# puppet module list
/usr/share/puppet/modules
├── isimluk-foreman_scap_client (v0.3.2)
└── stdlib (???)
```

And the module is recognized by foreman (using the refresh button on the `/enviroments` page.

### CODE REVIEW

**Comment by ares** [comment]
[test]

**Comment by domcleal** [comment]
It appears the source URL is redirecting, which git-annex doesn't like.  Is there a more direct URL available?

**Comment by ohadlevy** [comment]
@isimluk ping ?

**Comment by isimluk** [comment]
I cannot verify the redirect issue. But perhaps I missed some step during new package set-up? Ideas?

```
$ wget -d --verbose https://forgeapi.puppetlabs.com/v3/files/isimluk-foreman_scap_client-0.3.3.tar.gz
Setting --verbose (verbose) to 1
DEBUG output created by Wget 1.16.1 on linux-gnu.

URI encoding = ‘UTF-8’
--2015-02-11 10:19:50--  https://forgeapi.puppetlabs.com/v3/files/isimluk-foreman_scap_client-0.3.3.tar.gz
Resolving forgeapi.puppetlabs.com (forgeapi.puppetlabs.com)... 23.236.57.230
Caching forgeapi.puppetlabs.com => 23.236.57.230
Connecting to forgeapi.puppetlabs.com (forgeapi.puppetlabs.com)|23.236.57.230|:443... connected.
Created socket 3.
Releasing 0x000000000117c000 (new refcount 1).
Initiating SSL handshake.
Handshake successful; connected socket 3 to SSL handle 0x00000000011a5360
certificate:
  subject: CN=forge.puppetlabs.com,OU=Operations,O=Puppet Labs,L=Portland,ST=Oregon,C=US
  issuer:  CN=GeoTrust SSL CA - G2,O=GeoTrust Inc.,C=US
X509 certificate successfully verified and matches host forgeapi.puppetlabs.com

---request begin---
GET /v3/files/isimluk-foreman_scap_client-0.3.3.tar.gz HTTP/1.1
User-Agent: Wget/1.16.1 (linux-gnu)
Accept: */*
Accept-Encoding: identity
Host: forgeapi.puppetlabs.com
Connection: Keep-Alive

---request end---
HTTP request sent, awaiting response... 
---response begin---
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 11 Feb 2015 09:19:50 GMT
Content-Type: application/octet-stream
Transfer-Encoding: chunked
Connection: keep-alive
Status: 200 OK
Cache-Control: public
content-disposition: attachment; filename=isimluk-foreman_scap_client-0.3.3.tar.gz
ETag: "8f5039e082611e10d0acbf38875e91b1"
X-Node: forge-app04-prod
X-Revision: bee3573
X-Content-Type-Options: nosniff

---response end---
200 OK
Registered socket 3 for persistent reuse.
Length: unspecified [application/octet-stream]
Saving to: ‘isimluk-foreman_scap_client-0.3.3.tar.gz’

isimluk-foreman_scap_client-0.3.3.tar.gz               [ <=>                                                                                                             ]   9.71K  --.-KB/s   in 0s     

2015-02-11 10:19:51 (68.0 MB/s) - ‘isimluk-foreman_scap_client-0.3.3.tar.gz’ saved [9948]

```

**Comment by shlomizadok** [comment]
[test]

**Comment by shlomizadok** [comment]
I have ran this locally and it seems to work. Not sure why it fails on Jenkins

**Comment by isimluk** [comment]
I am not sure what i can do here.

Is the problem really with the redirection? What can I do to workaround it?

Shall I upload the puppet module tarball to my scratch space at isimluk.fedorapeople.org?

**Comment by mmoll** [comment]
what's the status here?

**Pull request closed without merging**
