### PR TITLE
katello-host-tools 3.3.0

### PR DESCRIPTION
**Pull request by jturel**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.18
* [ ] 1.17
* [ ] 1.16
* [ ] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

The changes here correspond to the refactoring of the goferd plugin in host-tools

### CODE REVIEW

**Comment by ekohl** [comment]
Looks like it failed on f27 and f28. Could you have a look?

**Comment by jturel** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Pull request merged**
