### PR TITLE
Update foreman_openscap to 0.7.11

### PR DESCRIPTION
**Pull request by ares**
For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [ ] 1.16
* [x] 1.15
* [ ] 1.14

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ekohl** [comment]
Package builds are failing because the repos are incorrect after the update. @ehelms could you do the same magic again?

**Comment by ekohl** [comment]
[test]

**Comment by ekohl** [comment]
Build fails because there's no koji-katello releaser. Looking into fixing that since we'll need the same thing for 1.16.

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman-infra/pull/391

**Comment by evgeni** [comment]
diff LGTM, ACK pending it actually builds fine ;)

**Comment by ekohl** [comment]
I suppose we could just ignore the katello failure since that's a false positive

**Comment by dLobatog** [comment]
1.15 f24 - http://koji.katello.org/koji/buildinfo?buildID=20072
1.15 el7 - http://koji.katello.org/koji/buildinfo?buildID=20073

**Pull request merged**
