### PR TITLE
Plugin cherrypicks for 2.0

### PR DESCRIPTION
**Pull request by adamruzicka**
I wasn't doing cherrypicks to 2.0 for EL* as diligently as @mmoll did for debs. This PR should make package versions of tasks, rex and dynflow on EL* match the versions available on debs.

### CODE REVIEW

**Comment by tbrisker** [comment]
Looks like tasks failed to build due to missing package:
```
DEBUG util.py:598:  Error: No Package found for tfm-npm(react-html-parser) < 3.0.0
DEBUG util.py:598:  Error: No Package found for tfm-npm(react-html-parser) >= 2.0.2
```

**Comment by adamruzicka** [comment]
Added htmlparser related cherrypicks

**Comment by evgeni** [comment]
@adamruzicka no, that is a build dependency, so needs to be in an own PR, sorry.

**Comment by adamruzicka** [comment]
Requires:
- [ ] https://github.com/theforeman/foreman-packaging/pull/5258

**Comment by evgeni** [comment]
merged, it's being built here: https://ci.theforeman.org/job/foreman-packaging-rpm-2.0-release/58/ -- when that passes, you can re-kick this one and it should work.

**Comment by evgeni** [comment]
[test rpm]

**Comment by adamruzicka** [comment]
```
DEBUG util.py:598:  Error: No Package found for tfm-npm(react-html-parser) < 3.0.0
DEBUG util.py:598:  Error: No Package found for tfm-npm(react-html-parser) >= 2.0.2
```
Looks like I've missed something

**Comment by evgeni** [comment]
seems concurrent is too old?

**Comment by adamruzicka** [comment]
```
[2020-05-19T15:45:17.963Z]     package: tfm-rubygem-foreman-tasks-1.1.1-1.fm2_0.el7.noarch from downloaded_rpms
[2020-05-19T15:45:17.963Z]       unresolved deps:
[2020-05-19T15:45:17.963Z]         tfm-rubygem(parse-cron) >= 0.1.4
[2020-05-19T15:45:17.963Z]         tfm-rubygem(parse-cron) < 0.2
```

What am I missing? We have had tfm-rubygem-parse-cron-0.1.4 for ages now

**Comment by adamruzicka** [comment]
:green_apple:

**Comment by evgeni** [comment]
@adamruzicka yupp, I had issues publishing the 2.0 core repo (stupid dns on our CI env), so I didn't merge this yet. now all good!

**Pull request merged**
