### PR TITLE
Update rubygem-fog-aws to 3.6.5

### PR DESCRIPTION
**Pull request by apuntamb**
Update fog-aws to 3.6.5.

### CODE REVIEW

**Comment by evgeni** [comment]
Seems bin/setup and bin/console are new files, could you please exclude them?

**Comment by apuntamb** [comment]
> Seems bin/setup and bin/console are new files, could you please exclude them?

You mean something like: `%exclude %{gem_instdir}/bin/setup` and same for `bin/console`?

But just a query - the new files in a new version should be included, right?

**Comment by evgeni** [comment]
Yes, exactly.

And yeah, normally we would include new files, but console and setup are generic things rubygems adds and is usually without value to us.

**Comment by evgeni** [comment]
See https://github.com/fog/fog-aws/commit/6fb9c3c80793a0532595df5b3eec0614feaa0aaf#diff-c1111bd512b29e821b120b86446026b8 for details, those files are only useful for development.

**Pull request merged**
