### PR TITLE
Update rubygem-foreman_virt_who_configure to 0.3.2

### PR DESCRIPTION
**Pull request by evgeni**
(cherry picked from commit c81b0e2295aa6cb8f9d3547264be47372066156c)

For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [x] 1.21
* [ ] 1.20

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm]

**Comment by evgeni** [comment]
cp only change, merging

**Pull request merged**
