### PR TITLE
Added foreman_datacenter

### PR DESCRIPTION
**Pull request by Zenya**

### CODE REVIEW

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
Can you please add `rubygem-foreman_datacenter` to the `whitelist` of `foreman-plugins-nightly-el8` in `rel-eng/tito.props` and a `<packagereq type="default">rubygem-foreman_datacenter</packagereq>` line to the list in `comps/comps-foreman-plugins-el8.xml`? Our scripts currently don't handle the fact that we build for 2 target OSes again properly.

**Comment by evgeni** [comment]
Other than that I'd say this is good to go! :)

**Comment by pcreech** [comment]
@Zenya this could use a rebase, as well as addressing evgeni's comments

**Comment by ehelms** [comment]
@Zenya Planning to re-visit this?

**Comment by evgeni** [comment]
this is quite outdated, I'll close it and follow up with what we have in #5335

**Pull request closed without merging**
