### PR TITLE
Update foreman_templates to 6.0.0

### PR DESCRIPTION
**Pull request by ares**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.17
* [ ] 1.16
* [ ] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by mmoll** [comment]
Could you please reopen this from a branch which name starts with "deb/develop"? :bowtie:

**Comment by ares** [comment]
is that some temporary problem or a permanent change I've missed? Reopened as https://github.com/theforeman/foreman-packaging/pull/2387

**Comment by ekohl** [comment]
It's something we've had for ages in Debian packaging. We should fix that Jenkins job to use the target branch rather than the source branch to determine if it's Debian.

**Comment by ares** [comment]
seems I just forgot my habits then :-)

**Comment by ekohl** [comment]
I think https://github.com/theforeman/foreman-infra/pull/583 should improve the experience. Too often we've seen it fail because someone has to remember some arbitrary rule.

**Pull request closed without merging**
