### PR TITLE
Update rubygem-foreman_kubevirt to 0.1.4

### PR DESCRIPTION
**Pull request by shiramax**

### CODE REVIEW

**Comment by evgeni** [comment]
@shiramax thanks! should this also go into any of the stable branches? if so, please open an PR against them, cherry picking this. or ping me on IRC and I can do it for you. :)

**Comment by shiramax** [comment]
thanks @evgeni ,
I can't find you in IRC, I need this to be in the next sanp, should I create this PR agains 1.22?

**Comment by evgeni** [comment]
Oh, sorry, I'm Zhenech on IRC.

You don't need to do anything for the downstream snap, I'll handle that part. 

It's just important if you also want the same fixes to go into existing Foreman releases.

**Comment by shiramax** [comment]
@evgeni, I don't need it to be in the existing releases. thanks!

**Pull request merged**
