### PR TITLE
Update discovery to 10.0.0 (DEB)

### PR DESCRIPTION
**Pull request by lzap**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.16

### CODE REVIEW

**Comment by mmoll** [comment]
As this is no longer compatible with Foreman 1.15, the control file needs an update.

**Comment by lzap** [comment]
Just like that?

**Comment by mmoll** [comment]
merged, díky @lzap!

**Comment by lzap** [comment]
Internet conn drop? Worst nightmare! :-) Thanks

**Pull request merged**
