### PR TITLE
Set proper download URLs for rubygems

### PR DESCRIPTION
**Pull request by komidore64**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.15
* [ ] 1.14
* [ ] 1.13

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by domcleal** [comment]
Er, why?

**Comment by komidore64** [comment]
To have unified URLs across rubygems. I agree that it's small change, but It still has merit in terms of shooting for unified and similar style specs in the long run.

**Comment by dLobatog** [comment]
I'd 👎  this change, it's going to be irrelevant unless the packages are rebuilt for a new version. I appreciate the concern but maybe a suitable alternative that actually impacts the RPMs is to ensure we use the `/gems` path on new gems.

[gem2rpm](https://github.com/fedora-ruby/gem2rpm/blob/master/lib/gem2rpm.rb#L59) defaults to the `/gems` path. This is the tool most people would be using to construct these specs, so I'd rather standardize over that (on new gems or rebuilds, not old specs).

**Comment by komidore64** [comment]
@dLobatog ah that's good to know!

I could switch all URLs to `/gems` if that's more desired. There are a few specs that contain `/downloads`.

```
$ git grep -l 'Source[0-9]\+:\s\+.*/downloads/.*\.gem' -- '*.spec' | wc -l
87
```

**Comment by ehelms** [comment]
@komidore64 planning to make the updated change to use `/gems` consistently?

**Comment by komidore64** [comment]
Yes, apologies. Got side tracked with other tasks. Should hopefully have this PR updated within a week's time.

**Comment by komidore64** [comment]
updated

**Comment by ehelms** [comment]
@komidore64 needs a rebase please

**Comment by komidore64** [comment]
rebased

**Pull request merged**
