### PR TITLE
add tracer package [2.0]

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
@ekohl this is intentional, as there is no hosted tarball for tracer :/

**Comment by ekohl** [comment]
Could the Github tarballs be used? https://github.com/FrostyX/tracer/releases

**Comment by evgeni** [comment]
Technically yes. Fedora uses the tito generated tarball, and I have no idea what's different.

**Comment by evgeni** [comment]
```
% koji add-pkg foreman-client-2.0-fedora29 tracer --owner=kojiadm
Adding 1 packages to tag foreman-client-2.0-fedora29

% koji add-pkg foreman-client-2.0-el8 tracer --owner=kojiadm
Adding 1 packages to tag foreman-client-2.0-el8

% koji add-pkg foreman-client-2.0-rhel7 tracer --owner=kojiadm
Adding 1 packages to tag foreman-client-2.0-rhel7
koji tag-build foreman-client-2.0-rhel7 tracer-0.7.1-2.el7     
Created task 286338
Watching tasks (this may be safely interrupted)...
286338 tagBuild (noarch): free
286338 tagBuild (noarch): free -> closed
  0 free  0 open  1 done  0 failed

286338 tagBuild (noarch) completed successfully

% koji tag-build foreman-client-2.0-el8 tracer-0.7.1-2.el8 
Created task 286340
Watching tasks (this may be safely interrupted)...
286340 tagBuild (noarch): free
286340 tagBuild (noarch): free -> closed
  0 free  0 open  1 done  0 failed

286340 tagBuild (noarch) completed successfully

% koji tag-build foreman-client-2.0-fedora29 tracer-0.7.1-2.fc29
Created task 286344
Watching tasks (this may be safely interrupted)...
286344 tagBuild (noarch): free
286344 tagBuild (noarch): free -> closed
  0 free  0 open  1 done  0 failed

286344 tagBuild (noarch) completed successfully
```

**Pull request merged**
