### PR TITLE
Update puppet-foreman_scap_client to 0.3.21

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by ares** [comment]
LGTM but the job failed 
```
RPM build errors:
BUILDSTDERR:     File not found: /builddir/build/BUILDROOT/puppet-foreman_scap_client-0.3.21-1.el7.noarch/usr/share/puppet/modules/foreman_scap_client/checksums.json
Child return code was: 1
EXCEPTION: [Error()]
```

**Comment by dgoetz** [comment]
Seems like checksums.json does no longer exist so line [39 ](https://github.com/theforeman/foreman-packaging/blob/2668a1744cf311b39f80657010031d4b6142624f/packages/plugins/puppet-foreman_scap_client/puppet-foreman_scap_client.spec#L39) (`%{puppet_foreman_scap_client_dir}/checksums.json`) has to be removed.

**Comment by sbernhard** [comment]
Thanks Dirk. Can you have a look on it again @xprazak2, please?

**Comment by xprazak2** [comment]
Rebased

**Pull request merged**
