### PR TITLE
Remove fedora29 from releasers config

### PR DESCRIPTION
**Pull request by zjhuntin**

### CODE REVIEW

**Comment by pcreech** [comment]
Can we include the removal of fedora29 from tito.props/package_manifetst.yaml, etc... as well in this pr?

**Comment by zjhuntin** [comment]
@pcreech updated with removal of a other instances I noticed.

**Review by pcreech — APPROVED** [review]

**Comment by pcreech** [comment]
TY!

**Comment by ekohl** [comment]
Since this was merged https://ci.theforeman.org/job/foreman-client-nightly-rpm-pipeline/ has been red. Could you please fix this?

**Pull request merged**
