### PR TITLE
fix build errors seens with with node-sass (DEB)

### PR DESCRIPTION
**Pull request by mmoll**
this should be built into:

* [x] Nightly

### CODE REVIEW

**Comment by mmoll** [comment]
This fixes the initial node-sass related build error on Debian/jessie. The others point to lacking isolation of the i386 build from the x86_64 one, but maybe we do want to drop i386 builds for 1.15 anyway?

**Comment by domcleal** [comment]
I don't think dropping support is necessary, the node_modules dir can either be deleted or node-sass reinstalled before `npm install` is run again.

**Comment by mmoll** [comment]
Allright, let's see, where this build is going now.

**Comment by mmoll** [comment]
💚 again. Compiling the C++ stuff on ARM adds about tens minutes to the build, but I guess we don't have any alternative until node-sass provides prebuilt binaries also for these architectures.

**Comment by domcleal** [comment]
Merged, thanks @mmoll.

**Pull request merged**
