### PR TITLE
Updated rubygem-hammer_cli_foreman_admin to 0.0.7

### PR DESCRIPTION
**Pull request by lzap**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.16
* [ ] 1.15
* [ ] 1.14

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by lzap** [comment]
Hey @ehelms you asked for release of this component. Here it is.

**Comment by ehelms** [comment]
@lzap Looks like https://rubygems.org/gems/hammer_cli_foreman_admin is missing this gem release.

**Comment by ehelms** [comment]
[test]

**Comment by lzap** [comment]
Sorry pushed it there.

**Pull request merged**
