### PR TITLE
Update foreman package dependencies

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ekohl** [comment]
Needs https://github.com/theforeman/foreman-packaging/pull/3774 & https://github.com/theforeman/foreman-packaging/pull/3780

**Comment by tbrisker** [comment]
[test rpm]

**Comment by tbrisker** [comment]
The build is failing with:
```
DEBUG util.py:491:  Error: Package: nodejs-patternfly-react-extensions-2.18.8-1.el7.noarch (build)
DEBUG util.py:491:             Requires: npm(unidiff) >= 1.0.1
DEBUG util.py:491:             Installing: nodejs-unidiff-0.0.4-1.el7.noarch (build)
DEBUG util.py:491:                 npm(unidiff) = 0.0.4
```
Also, looks like we'll need to update react-redux to 5.1.1 to fix https://projects.theforeman.org/issues/26830

**Comment by ekohl** [comment]
[test rpm] unidiff was bumped as part of 0641b9ec5ca051567f584f45e47f965631d88b81 but you probably started the test before it was released.

**Comment by ekohl** [comment]
Oh, the unidiff is part of package.json: https://github.com/theforeman/foreman/blob/bfce9f2d7891d0d816a1e24c02f5db294d0d3895/package.json#L119

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman/pull/6774

**Comment by tbrisker** [comment]
core change for unidiff has been merged, can you please update this pr @ekohl ?

**Comment by tbrisker** [comment]
Also please update react-redux while you're at it :)

**Comment by tbrisker** [comment]
the package built now but errors on repoclosure:
```
[2019-05-20T18:18:12.780Z]     package: foreman-assets-1.23.0-0.9.develop.201905201808gitbfce9f2.el7.noarch from downloaded_rpms

[2019-05-20T18:18:12.780Z]       unresolved deps:

[2019-05-20T18:18:12.780Z]          npm(unidiff) >= 0:1.0.0

[2019-05-20T18:18:12.780Z]          npm(react-redux) >= 0:5.1.1

[2019-05-20T18:18:12.780Z]          npm(react-ace) < 0:7.0.0

[2019-05-20T18:18:12.780Z]          npm(react-ace) >= 0:6.3.2

[2019-05-20T18:18:12.780Z]          npm(patternfly-react-extensions) < 0:3.0.0

[2019-05-20T18:18:12.780Z]          npm(patternfly-react-extensions) >= 0:2.18.8

**Comment by ekohl** [comment]
[test rpm]

**Pull request merged**
