### PR TITLE
Fixes #26631 - configure MALLOC_ARENA_MAX to reduce long term RSS

### PR DESCRIPTION
**Pull request by mccun934**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.21
* [ ] 1.20

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by mccun934** [comment]
@iNecas thoughts on this?

**Comment by iNecas** [comment]
@mccun934 conceptually I'm good with this: it would be good to have some data from the perf team to compare how the system behaves with/without it though

**Comment by ehelms** [comment]
@mccun934 @iNecas state of this PR in terms of if we should proceed?

**Comment by iNecas** [comment]
Not sure if this was taken to the perf team, but my recommendation getting in touch with them still applies.

**Comment by mccun934** [comment]
We have this deployed in multiple large user production environments for months with zero negative effects and stable memory over time. I'll reach out to the perf team to see if they have the resources to test this, if not, I'd recommend merging

**Comment by ehelms** [comment]
We got a greenlight from the perf team today on this. It will need a release bump to go with it. https://github.com/theforeman/foreman-packaging/pull/4189 replaces this PR.

**Pull request closed without merging**
