### PR TITLE
[rpm] Update foreman_ansible to 1.4.6

### PR DESCRIPTION
**Pull request by dLobatog**
For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [x] 1.16
* [ ] 1.15

### CODE REVIEW

**Comment by mmoll** [comment]
nightly and 1.16 only please: https://github.com/theforeman/foreman_ansible/issues/102

**Comment by ekohl** [comment]
@dLobatog ping

**Comment by ekohl** [comment]
@dLobatog ping

**Comment by ekohl** [comment]
Oh, I can add my own commit to your branch. Let's see if this builds and then I'll merge it.

**Comment by ares** [comment]
> Should we only include this in 1.16 and wait for a 1.17+ compatible release?

sounds reasonable to me, leaving up to @dLobatog though

**Comment by ekohl** [comment]
Replaced by https://github.com/theforeman/foreman-packaging/pull/2146

**Pull request closed without merging**
