### PR TITLE
Update rubygem-hammer_cli_foreman_scc_manager to 0.2.0

### PR DESCRIPTION
**Pull request by nadjaheitmann**
@ekohl Addressing spec file updates requested in https://github.com/theforeman/foreman-packaging/pull/10750 . If this PR is gonna be merged, https://github.com/theforeman/foreman-packaging/pull/10750 can be closed.

### CODE REVIEW

**Comment by nadjaheitmann** [comment]
Not sure why rpm-copr is failing, though.

**Comment by nadjaheitmann** [comment]
@theforeman/packaging Any input on this one? I think the poor bot has been force-pushing the branch in https://github.com/theforeman/foreman-packaging/pull/10750 for some time by now.

**Comment by pcreech** [comment]
[test rpm-copr]

**Comment by nadjaheitmann** [comment]
Closing this because w need to release a new version of the gem with updated dependencies.

**Pull request closed without merging**
