### PR TITLE
Update smart_proxy_chef to 0.1.4

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by domcleal** [comment]
Please also update plugins/smart_proxy_chef/chef.rb, plugins/ruby-foreman-chef/foreman_chef.rb and plugins/ruby-foreman-chef/debian/gem.list.

**Comment by domcleal** [comment]
We ought to write a list of steps in deb/develop's README, as it has some unique constructs for each type of plugin.

**Comment by ares** [comment]
fixed, thanks @domcleal 
+1 to what you suggest if it's too hard to unify all packages

**Comment by domcleal** [comment]
Thanks @ares, building both for nightlies.

I don't think it'd be hard to unify.

**Pull request merged**
