### PR TITLE
Add rhel8 support for pulpcore

### PR DESCRIPTION
**Pull request by zjhuntin**

### CODE REVIEW

**Comment by zjhuntin** [comment]
[test rpm]

**Comment by zjhuntin** [comment]
[test rpm]

**Comment by zjhuntin** [comment]
[test rpm]

**Comment by zjhuntin** [comment]
[test rpm]

**Comment by zjhuntin** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by zjhuntin** [comment]
Dropping in favor of a more piece meal approach.

**Pull request closed without merging**
