### PR TITLE
Update rubygem-foreman_maintain to 0.8.2

### PR DESCRIPTION
**Pull request by upadhyeammit**
(cherry picked from commit 7b1dd67c08f4f17b818dd0b7d2b80e243c652211)

### CODE REVIEW

**Comment by upadhyeammit** [comment]
[test-rpm]

**Comment by upadhyeammit** [comment]
[test rpm]

**Comment by upadhyeammit** [comment]
Failing to retrieve packages from local `build` repo. Maybe its temporary issue?

**Comment by evgeni** [comment]
[test rpm]

**Review by evgeni — APPROVED** [review]

**Comment by evgeni** [comment]
```console
evgeni@yatsu ~ % koji tag-build foreman-2.4-nonscl-rhel7 rubygem-foreman_maintain-0.8.2-1.el7
Created task 432226
Watching tasks (this may be safely interrupted)...
432226 tagBuild (noarch): free
432226 tagBuild (noarch): free -> closed
  0 free  0 open  1 done  0 failed

432226 tagBuild (noarch) completed successfully
evgeni@yatsu ~ % koji tag-build foreman-2.4-el8 rubygem-foreman_maintain-0.8.2-1.el8        
Created task 432236
Watching tasks (this may be safely interrupted)...
432236 tagBuild (noarch): free
432236 tagBuild (noarch): free -> closed
  0 free  0 open  1 done  0 failed

432236 tagBuild (noarch) completed successfully
```

**Pull request merged**
