### PR TITLE
speedup installation of foreman by multi-threading bundle install

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
the (unscientific) tests on my laptop (in a buster container) say:
* current `foreman` nightly installs in 50-52 seconds
* `foreman` from this PR installs in 43-45 seconds

So not *a lot*, but I'd expect more if we add things like `postgresql` or `libvirt` which pulls in native extensions, will re-test

**Review by ekohl — APPROVED** [review]
I was reminded of https://projects.theforeman.org/issues/7988 by this.

**Comment by evgeni** [comment]
> I was reminded of https://projects.theforeman.org/issues/7988 by this.

it's on my pile of "Evgeni is angry enough to look at our Debian packaging" things

**Comment by evgeni** [comment]
* `apt install foreman foreman-postgresql foreman-libvirt` takes ~2:30 from nightly
* and ~2:20 from this PR :(

Meh, I hoped it's more. But I think I'd still try that and see what e.g. happens on our CI?

**Comment by ekohl** [comment]
Does it actually compile those on a real system or are there "wheels" with precompiled cache files? If it does compile, it wouldn't surprise me if there's no concurrency within a build. https://nokogiri.org/tutorials/installing_nokogiri.html suggests there is such a thing.

That said, there's https://nokogiri.org/tutorials/installing_nokogiri.html#installing-using-standard-system-libraries which suggests `bundle config build.nokogiri --use-system-libraries`. Perhaps there's more like that?

**Comment by evgeni** [comment]
It does compile on the target system. But my expectation was that it can compile e.g. nokogiri and libvirt in parallel

**Comment by ekohl** [comment]
Probably, but I suspect it's still tied to the longest one and that's likely nokogiri.

**Review by ekohl — APPROVED** [review]
I don't see a good place to set env vars, but otherwise we could `export BUNDLE_JOBS=4` for the same effect. Though I don't know how well that would work with wrappers and it'd be hard to verify since it would be silently ignored. The difference would be speed but we don't have any test on that.

I also think 4 is probably safe. While we may have VMs with just 1 or 2 cores, we don't have that high concurrency that it'd overload machines. Maximum memory consumption is probably also not a problem.

**Pull request merged**
