### PR TITLE
Update rubygem-hammer_cli_katello to 1.11.2

### PR DESCRIPTION
**Pull request by chris1984**

### CODE REVIEW

**Comment by chris1984** [comment]
@pcreech can this get a merge?

**Review by ianballou — COMMENTED** [review]
Just want some confirmation that the SCL related deletions are expected.

**Comment by chris1984** [comment]
> Just want some confirmation that the SCL related deletions are expected.

I just ran the bump rpm script, let's see if that was intended it passed green so that is a plus. Let's see what Patrick says, worst case I can go back and put those how they were.

**Comment by chris1984** [comment]
> > Just want some confirmation that the SCL related deletions are expected.
> 
> We are indeed slowly dropping those in spec files, but I'd leave them here just for consistency. Or drop them in the whole file, but I wouldn't do that in a patch release.

Sounds good, will push up a change to make the spec file change just the version bump

**Comment by chris1984** [comment]
@ekohl updated

**Review by ekohl — APPROVED** [review]

**Pull request merged**
