### PR TITLE
Update foreman_discovery to 4.2.0 (RPM)

### PR DESCRIPTION
**Pull request by lzap**
For a nightly build...

```
Submitting build with: koji -c ~/.koji/katello-config build --nowait --scratch foreman-plugins-nightly-fedora21 /tmp/tito/rubygem-foreman_discovery-4.2.0-1.fm1_11.git.480.863cce3.fc21.src.rpm
Uploading srpm: /tmp/tito/rubygem-foreman_discovery-4.2.0-1.fm1_11.git.480.863cce3.fc21.src.rpm
[                                    ]  00% 00:00:00     0.00 B        - B/sec
[====================================] 100% 00:00:00 131.11 KiB 132.85 KiB/sec
Created task: 412526
Task info: http://koji.katello.org/koji/taskinfo?taskID=412526
Wrote: /tmp/tito/tfm-rubygem-foreman_discovery-4.2.0-1.fm1_11.git.480.863cce3.git.480.863cce3.el6.src.rpm



Submitting build with: koji -c ~/.koji/katello-config build --nowait --scratch foreman-plugins-nightly-rhel6 /tmp/tito/tfm-rubygem-foreman_discovery-4.2.0-1.fm1_11.git.480.863cce3.git.480.863cce3.el6.src.rpm
Uploading srpm: /tmp/tito/tfm-rubygem-foreman_discovery-4.2.0-1.fm1_11.git.480.863cce3.git.480.863cce3.el6.src.rpm
[                                    ]  00% 00:00:00     0.00 B        - B/sec
[====================================] 100% 00:00:01 131.15 KiB 125.87 KiB/sec
Created task: 412528
Task info: http://koji.katello.org/koji/taskinfo?taskID=412528
Wrote: /tmp/tito/tfm-rubygem-foreman_discovery-4.2.0-1.fm1_11.git.480.863cce3.git.480.863cce3.git.480.863cce3.el7.src.rpm



Submitting build with: koji -c ~/.koji/katello-config build --nowait --scratch foreman-plugins-nightly-rhel7 /tmp/tito/tfm-rubygem-foreman_discovery-4.2.0-1.fm1_11.git.480.863cce3.git.480.863cce3.git.480.863cce3.el7.src.rpm
Uploading srpm: /tmp/tito/tfm-rubygem-foreman_discovery-4.2.0-1.fm1_11.git.480.863cce3.git.480.863cce3.git.480.863cce3.el7.src.rpm
[                                    ]  00% 00:00:00     0.00 B        - B/sec
[====================================] 100% 00:00:01 131.17 KiB 130.50 KiB/sec
Created task: 412529
Task info: http://koji.katello.org/koji/taskinfo?taskID=412529
[lzap@lzapx rubygem-foreman_discovery]$ gem compare -b foreman_discovery 4.1.2 4.2.0
Fetching: foreman_discovery-4.1.2.gem (100%)
Fetching: foreman_discovery-4.2.0.gem (100%)
Compared versions: ["4.1.2", "4.2.0"]
  DIFFERENT files:
    4.1.2->4.2.0:
      * Added:
            locale/ca/
            locale/ca/LC_MESSAGES/
            app/services/foreman_discovery/node_api/power_service.rb
              (!) Unexpected permissions: 100664
            app/services/foreman_discovery/node_api/power_legacy_direct_service.rb
              (!) Unexpected permissions: 100664
            app/services/foreman_discovery/node_api/power_legacy_proxied_service.rb
              (!) Unexpected permissions: 100664
            locale/ca/foreman_discovery.po
              (!) Unexpected permissions: 100664
            locale/ca/LC_MESSAGES/foreman_discovery.mo
              (!) Unexpected permissions: 100664

```

### CODE REVIEW

**Comment by domcleal** [comment]
1) Add the package back to comps/ so it can be built/released.

2) The .gem must be added via git-annex, not as a binary file.

3) The minimum version of Foreman has increased to 1.11, please update the dependencies.  (I'd advise in future to bump the major version too, thought that was [how Discovery was versioned](http://theforeman.org/plugins/foreman_discovery/4.0/index.html#1.1ReleaseNotes).)

**Comment by lzap** [comment]
Oh my .. fixed. My idea was to release 4.2 for nightlies only and then bump to 5.0.0 so it has a clean number, but that does not sound like a good idea to me now. Gem users might get broken. I can perhaps pull back from rubygems, this would not be my first time... ;-)

**Comment by domcleal** [comment]
Entirely your call, I'm just commenting.  The third point about min version numbers doesn't seem fixed, could you update both Requires and BuildRequires please?

**Comment by lzap** [comment]
Yanked 4.2.0, long live 5.0.0.

**Comment by domcleal** [comment]
The .gem seems to be back to a binary file again, please use git-annex for it.

**Comment by lzap** [comment]
I can't believe I do this for living...

**Comment by domcleal** [comment]
I couldn't possibly comment.

**Comment by domcleal** [comment]
Thanks @lzap, merged and building now.

**Pull request merged**
