### PR TITLE
Update rubygem-foreman_templates to 9.0.2

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
@pcreech you playin'?

```
DEBUG util.py:600:  Error: 
DEBUG util.py:600:   Problem 1: package git-2.27.0-1.el8.x86_64 requires perl(Term::ReadKey), but none of the providers can be installed
DEBUG util.py:600:    - conflicting requests
DEBUG util.py:600:    - nothing provides perl(:MODULE_COMPAT_5.26.3) needed by perl-TermReadKey-2.37-7.el8.x86_64
DEBUG util.py:600:    - nothing provides libperl.so.5.26()(64bit) needed by perl-TermReadKey-2.37-7.el8.x86_64
DEBUG util.py:600:   Problem 2: package rubygem-git-1.5.0-1.el8.noarch requires git >= 1.6.0.0, but none of the providers can be installed
DEBUG util.py:600:    - package git-2.27.0-1.el8.x86_64 requires perl(Term::ReadKey), but none of the providers can be installed
DEBUG util.py:600:    - conflicting requests
DEBUG util.py:600:    - nothing provides perl(:MODULE_COMPAT_5.26.3) needed by perl-TermReadKey-2.37-7.el8.x86_64
DEBUG util.py:600:    - nothing provides libperl.so.5.26()(64bit) needed by perl-TermReadKey-2.37-7.el8.x86_64
```

**Comment by evgeni** [comment]
[test rpm]

**Comment by zjhuntin** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Review by evgeni — APPROVED** [review]

**Pull request merged**
