### PR TITLE
Pulpcore 3.49 bindings

### PR DESCRIPTION
**Pull request by sjha4**
Bumping versions following https://github.com/Katello/katello/pull/10949 

Related:
https://github.com/theforeman/foreman-packaging/pull/10667
https://github.com/theforeman/pulpcore-packaging/pull/931
https://github.com/Katello/katello/pull/10949
https://github.com/theforeman/foreman-packaging/pull/10678

### CODE REVIEW

**Comment by sjha4** [comment]
Will update pulp-rpm to 3.25.2 when that's out soon.

**Comment by ianballou** [comment]
We'll also need PRs for updating:
- https://github.com/theforeman/foreman-packaging/blob/rpm/develop/packages/katello/katello-repos/katello-repos.spec#L1
- https://github.com/theforeman/foreman-packaging/blob/rpm/develop/packages/katello/rubygem-katello/rubygem-katello.spec#L48-L56
- https://github.com/theforeman/forklift/blob/4c2e830e83597f1e2276447eee4bbafee8ee245e/roles/pulpcore_repositories/defaults/main.yml#L2

**Comment by sjha4** [comment]
Just saw the merge conflict on this one..Will update..

**Comment by sjha4** [comment]
Rebased.

**Comment by sjha4** [comment]
@evgeni : Could I borrow your eyes for this and related pulp upgrade PRs in description.. 😺 👁️

**Review by evgeni — APPROVED** [review]
Assuming certguard and file clients have huge version jumps because those are now built from pulpcore source and thus following that versioning, ACK

**Comment by sjha4** [comment]
I believe the rpms are pushed to yum.theforeman.org when the pulpcore nightly pipelines are green. I am not entirely sure why they're failing though.

**Comment by evgeni** [comment]
I think pulpcore nightlies are gated via puppet-pulpcore, and that needs https://github.com/theforeman/puppet-pulpcore/pull/336 to work with the new merged plugins

**Pull request merged**
