### PR TITLE
Update rubygem-pulp_deb_client to 2.18.0

### PR DESCRIPTION
**Pull request by quba42**
This is needed to continue work on this feature: https://github.com/Katello/katello/pull/10072

The corresponding pulp_deb version is already available in: https://yum.theforeman.org/pulpcore/3.17/

I need help with when/how to change this: https://github.com/Katello/katello/blob/master/katello.gemspec#L61

The new client should be made available for nightly Katello ASAP, but not for any released versions.

### CODE REVIEW

**Comment by pcreech** [comment]
@jlsherrill can you get someone to assist with the katello changes?

**Comment by quba42** [comment]
Added a Katello PR, but I am not sure if it is sufficient, or in what order and when things need to be merged.

**Comment by ianballou** [comment]
We'll also need a PR to update the pulp_deb bindings in rubygem-katello: https://github.com/theforeman/foreman-packaging/blob/rpm/develop/packages/katello/rubygem-katello/rubygem-katello.spec

Check out step 9 here: https://projects.theforeman.org/projects/katello/wiki/Pulp_3_Integration#Updating-to-a-New-Pulp-Version-in-master-amp-nightly

**Comment by quba42** [comment]
> We'll also need a PR to update the pulp_deb bindings in rubygem-katello: https://github.com/theforeman/foreman-packaging/blob/rpm/develop/packages/katello/rubygem-katello/rubygem-katello.spec
> 
> Check out step 9 here: https://projects.theforeman.org/projects/katello/wiki/Pulp_3_Integration#Updating-to-a-New-Pulp-Version-in-master-amp-nightly

The way I understood it, this needs to be a separate PR, that is merged after this one, so here goes:

- https://github.com/theforeman/foreman-packaging/pull/7856

**Comment by ianballou** [comment]
I'm all cool with this! We just need an ACK from someone official like @pcreech or @evgeni.

Once this is ready to go, we'll merge the Katello one (already green) and then this one. Afterwards we'll merge the rubygem-katello PR.

**Review by evgeni — APPROVED** [review]
LGTM!

**Comment by evgeni** [comment]
@ianballou FWIW, you can ping `@theforeman/packaging` to reach the right team ;-)

Please yell when you got the PR to katello itself merged, so this can go in.

**Pull request merged**
