### PR TITLE
Update foreman_remote_execution to 5.0.1

### PR DESCRIPTION
**Pull request by adamruzicka**
CPs:
- 3.1

### CODE REVIEW

**Comment by zjhuntin** [comment]
[test deb]

**Comment by Odilhao** [comment]
@adamruzicka here we have the same problem 

```
[2021-11-24T17:27:36.507Z] node --max_old_space_size=2048 /usr/share/foreman/node_modules/webpack/bin/webpack.js --config /usr/share/foreman/config/webpack.config.js --bail --env.pluginName=foreman_remote_execution

[2021-11-24T17:27:46.662Z] ModuleNotFoundError: Module not found: Error: Can't resolve 'graphql-tag/loader' in '/usr/share/foreman'
```
graphql-tag is missing as well.

**Comment by adamruzicka** [comment]
To be honest I don't really know what to do here. We can't really use the same trick we used in rpm (or can we?), since we don't package npm deps separately.

**Comment by evgeni** [comment]
If it's not in your `package.json`, Debian builds won't pull it.

**Comment by adamruzicka** [comment]
https://github.com/theforeman/foreman_remote_execution/pull/674

**Comment by evgeni** [comment]
huh, NOW I don't understand the failure :(

**Comment by evgeni** [comment]
ah, well, I do, we never call `npm i` on the plugin `package.json` in Debian…

**Comment by Odilhao** [comment]
Closing this one, #7375 will be merged instead.

**Pull request closed without merging**
