### PR TITLE
drop rubygem-mimemagic

### PR DESCRIPTION
**Pull request by evgeni**
it's unused since fd6a14311c1f132d541be91fd042c7952b8eec82

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
This is unused since fd6a14311c1f132d541be91fd042c7952b8eec82.

**Comment by evgeni** [comment]
@ehelms @ekohl do we want to pick that to 2.5 which got that new marcel via https://github.com/theforeman/foreman-packaging/commit/5cee56445860a72f58a2854f229961258ff5119e

**Comment by ekohl** [comment]
It feels a bit odd since the mimemagic gem is in the yum repo but at runtime the user will have the benefit of having fewer files on disk so I'd be open to it.

Perhaps you can include the commit ID that made it obsolete in the commit message.

**Comment by evgeni** [comment]
updated the commit msg

**Review by ekohl — APPROVED** [review]

**Pull request merged**
