### PR TITLE
Update gem dependencies of Katello

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Review by Odilhao — APPROVED** [review]

**Comment by evgeni** [comment]
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'use-deep-compare-effect' in '/builddir/build/BUILDROOT/rubygem-katello-4.2.0-0.2.pre.master.20210705115003git393d07d.el8.noarch/usr/share/gems/gems/katello-4.2.0.pre.master/webpack/scenes/ContentViews/Table'
```

:disappointed:

**Comment by evgeni** [comment]
https://github.com/theforeman/foreman-packaging/pull/6844 …

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Pull request merged**
