### PR TITLE
Update rubygem-foreman_openscap to 4.0.3

### PR DESCRIPTION
**Pull request by evgeni**
(cherry picked from commit 450aee631fef28d88a5436433076bb6737fa35b4)

### CODE REVIEW

**Comment by evgeni** [comment]
@ares there is no reason this wasn't picked to 2.2 (and maybe even 2.1?) earlier, right?

**Comment by evgeni** [comment]
[test rpm]

**Comment by tbrisker** [comment]
I would hold on merging this one, we'll want another release with https://github.com/theforeman/foreman_openscap/pull/453 in it (since right now openscap is broken when katello is installed) cc: @xprazak2

**Comment by tbrisker** [comment]
closing for #5928

**Pull request closed without merging**
