### PR TITLE
Small foreman_salt/smart_proxy_salt update (DEB)

### PR DESCRIPTION
**Pull request by stbenjam**
Nightly + 1.10 please

### CODE REVIEW

**Comment by mmoll** [comment]
see https://github.com/theforeman/foreman-packaging/pull/855#discussion_r42464134 for the -1 suffix I'd like to see (and yes, we should fix the script...).

**Comment by domcleal** [comment]
Also please update the dependency on the Foreman to 1.10 or higher in foreman_salt.

I've fixed the -1 problem in #867, sorry for the hassle.

**Comment by stbenjam** [comment]
Updated

**Comment by mmoll** [comment]
merged as 9d7f4fb & 090f347 for develop and 24fc7c9 & d51500f for 1.10, thanks @stbenjam!

**Comment by stbenjam** [comment]
Thanks!   :snowman:

**Pull request closed without merging**
