### PR TITLE
Release katello-host-tools 4.3.0

### PR DESCRIPTION
**Pull request by wbclark**

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
Looks like you added the file directly instead of via git-annex. I'd recommend to use `./bump_rpm.sh packages/client/katello-host-tools 4.3.0`. For me that fails because the tarball isn't found. That usually happens when the git tag wasn't pushed, and https://github.com/Katello/katello-host-tools/tags says that's also the case here.

**Comment by wbclark** [comment]
@ekohl thanks, I've made the requested change

**Comment by Odilhao** [comment]
```
+ cd /builddir/build/BUILD
+ cd katello-host-tools-4.3.0
+ rm -r src/apt_plugins
+ rm src/katello/deb_tracer.py
rm: cannot remove 'src/katello/deb_tracer.py': No such file or directory
```

From koji logs, looks like deb_tracer.py was removed from 4.2.3 to 4.3.0, this need to be removed from %build

**Comment by wbclark** [comment]
```
Processing files: katello-host-tools-tracer-4.3.0-1.el9.noarch
error: File not found: /builddir/build/BUILDROOT/katello-host-tools-4.3.0-1.el9.noarch/usr/lib/python3.9/site-packages/katello/tracer.py
error: File not found: /builddir/build/BUILDROOT/katello-host-tools-4.3.0-1.el9.noarch/usr/lib/python3.9/site-packages/katello/__pycache__/tracer.cpython-39{,.opt-?}.pyc
    File not found: /builddir/build/BUILDROOT/katello-host-tools-4.3.0-1.el9.noarch/usr/lib/python3.9/site-packages/katello/tracer.py
    File not found: /builddir/build/BUILDROOT/katello-host-tools-4.3.0-1.el9.noarch/usr/lib/python3.9/site-packages/katello/__pycache__/tracer.cpython-39{,.opt-?}.pyc
    File not found: /builddir/build/BUILDROOT/katello-host-tools-4.3.0-1.el9.noarch/usr/lib/python3.9/site-packages/katello/tracer.py
    File not found: /builddir/build/BUILDROOT/katello-host-tools-4.3.0-1.el9.noarch/usr/lib/python3.9/site-packages/katello/__pycache__/tracer.cpython-39{,.opt-?}.pyc
RPM build errors:
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.9/site-packages/mockbuild/util.py", line 599, in do_with_status
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
```

**Comment by wbclark** [comment]
It's related to https://github.com/Katello/katello-host-tools/commit/eab28c632e014bd3624a74a3b685ce1f1fc911cc I think

**Review by ekohl — COMMENTED** [review]
Correct. I think this should help:

```patch
diff --git a/packages/client/katello-host-tools/katello-host-tools.spec b/packages/client/katello-host-tools/katello-host-tools.spec
index a1fa409ce..85b2e840d 100644
--- a/packages/client/katello-host-tools/katello-host-tools.spec
+++ b/packages/client/katello-host-tools/katello-host-tools.spec
@@ -180,7 +180,7 @@ rm src/katello/tracer/zypper.py
 sed -i '/katello-tracer-upload=katello.scripts:tracer_upload/d' src/setup.py
 %endif
 %else
-rm src/katello/tracer.py
+rm -r src/katello/tracer
 sed -i '/katello-tracer-upload=katello.scripts:tracer_upload/d' src/setup.py
 rm etc/yum/pluginconf.d/tracer_upload.conf
 %endif
@@ -324,13 +324,10 @@ exit 0
 
 %if %{build_tracer}
 # TODO pycached unavailable on SuSE - what to do with cache files?
-%if %{zypper_install}
-%exclude %{katello_libdir}/tracer.py
-%else
-%if %{yum_install}
-%exclude %{katello_libdir}/tracer.py*
+%if %{zypper_install} || %{yum_install}
+%exclude %{katello_libdir}/tracer
 %else
-%pycached %exclude %{katello_libdir}/tracer.py
+%pycached %exclude %{katello_libdir}/tracer
 %endif
 %endif
 
@@ -364,17 +361,17 @@ exit 0
 %files tracer
 %defattr(-,root,root,-)
 %if %{zypper_install}
-%{katello_libdir}/tracer.py
+%{katello_libdir}/tracer
 %dir %{_usr}/lib/zypp
 %dir %{_usr}/lib/zypp/plugins
 %dir %{plugins_dir}
 %{plugins_dir}/tracer_upload.py
 %else
 %if %{yum_install}
-%{katello_libdir}/tracer.py*
+%{katello_libdir}/tracer
 %{plugins_dir}/tracer_upload.py*
 %else
-%pycached %{katello_libdir}/tracer.py
+%pycached %{katello_libdir}/tracer
 %pycached %{plugins_dir}/tracer_upload.py
 %endif
 %endif
```

**Comment by wbclark** [comment]
It's not quite right yet... `DEBUG util.py:444:  error: %pycached can only be used with paths explicitly ending with .py`

**Comment by ekohl** [comment]
@wbclark slight note of priority: it is really important to wrap up Katello branching and release RC1. You do not need to release katello-host-tools before doing that and we've already branched packaging so you'll need a cherry pick regardless.

**Comment by ekohl** [comment]
There's a very good chance the whole `%pycached` statement is no longer needed, and I think that was the motivation for https://github.com/Katello/katello-host-tools/commit/eab28c632e014bd3624a74a3b685ce1f1fc911cc

Let's see if this works.

**Comment by wbclark** [comment]
@ekohl thanks, so what is needed for the item labeled "Bump Katello related packages to their next versions " ?

**Comment by ekohl** [comment]
You can see it's a link to a previous result of that step. So pretty much that. For Foreman I used this:

```
sed -i '/^Version:/ s/3.7/3.8/ ; /^%global release/ s/[0-9]\+/1/' packages/foreman/foreman{,-{installer,proxy,release,selinux}}/*.spec packages/foreman/rubygem-hammer_cli{,_foreman}/*.spec
obal changelog --message '- Bump version to 3.8-develop' foreman{,-{installer,proxy,release,selinux}} rubygem-hammer_cli{,_foreman}
```

Though next time I'd probably replace the old version with a regex so it becomes easier to provide instructions in the procedure:
```
sed -i '/^Version:/ s/[0-9]\+\.[0-9]\+/3.8/ ; /^%global release/ s/[0-9]\+/1/' packages/foreman/foreman{,-{installer,proxy,release,selinux}}/*.spec packages/foreman/rubygem-hammer_cli{,_foreman}/*.spec
```

**Comment by wbclark** [comment]
Thanks. I opened https://github.com/theforeman/foreman-packaging/pull/9437

**Comment by ekohl** [comment]
This is also a perfect example of where there's room for improvement in the release procedure: https://github.com/theforeman/tool_belt/blob/ece8bde8ee0fbb3c3d19b6be9b5e273ed70a4eaa/procedures/katello/branch.md.erb#L70-L71 can either be more descriptive or some script could be written.

I'd suggest something like:
```
- [] Bump Katello related packages in foreman-packaging to their next versions ([example](https://github.com/theforeman/foreman-packaging/pull/8729/files))
- ```

**Comment by evgeni** [comment]
I think timing wise, it would be beneficial if all those releases (anything that is not rubygem-katello/rubygem-hammer-cli-katello) would happen not during branching, but in the weeks before. So probably in the "two weeks before" chapter?

**Comment by ekohl** [comment]
Technically katello-host-tools has its own release cycle and should remain compatible with multiple versions. So IMHO it's independent. I just wanted to indicate that focusing on the Katello branching and RC1 release is higher priority. The goal should be same day Foreman & Katello branching + RC1, rather than stretching it over a week. We've never achieved that (I have done it just for Foreman), but it should be with better instructions and more scripts. Also some simplifications here & there.

**Comment by sbernhard** [comment]
> It's related to [Katello/katello-host-tools@eab28c6](https://github.com/Katello/katello-host-tools/commit/eab28c632e014bd3624a74a3b685ce1f1fc911cc) I think

Agree.

It requires at least this change. Otherwise the package upload scripts for suse are missing:
```
 %if %{dnf_install}
 %pycached %exclude %{plugins_dir}/__init__.py
-%else
-%exclude %{plugins_dir}
-%endif
 %endif
 
+%endif # end build_tracer
+
 %attr(750, root, root) %{_sbindir}/katello-package-upload
 %attr(750, root, root) %{_sbindir}/katello-enabled-repos-upload
 
@@ -357,11 +356,16 @@ exit 0
 %dir %{_sysconfdir}/yum
 %dir %{plugins_confdir}
 %exclude %{python_libdir}/zypper_plugins
+%{plugins_dir}/package_upload.py
+%{plugins_dir}/enabled_repos_upload.py
 %endif
 ```

**Comment by sbernhard** [comment]
@ekohl mentioned this PR in #10663. I guess, this PR is required before we proceed with #10663. Can we proceed with this or should we have another PR to cleanup the katello-host-tools spec file a little bit?

**Comment by wbclark** [comment]
[test]

**Pull request closed without merging**
