### PR TITLE
[DON'T MERGE] - foreman + npm with Webpack

### PR DESCRIPTION
**Pull request by dLobatog**
This PR is just a convenience for anyone who wants to test the nodejs packages & the changes made to the Foreman package. This allows foreman to use npm assets and compile them using webpack.

### CODE REVIEW

**Comment by dLobatog** [comment]
Feel free to take the rpms from http://ci.theforeman.org/job/packaging_test_pull_request/1334/

**Comment by domcleal** [comment]
Is this meant just to show the commits in a single series, or is it also the PR containing changes to the Foreman package? I don't see the changes from f5bef88 up for review anywhere else.

**Comment by dLobatog** [comment]
@domcleal It's just mean to show the commits, make it easy in case someone want to chainbuild it too, and also to show the changes that #1174 had to have. I'll submit the changes to foreman.spec in a separate one

**Comment by dLobatog** [comment]
https://github.com/theforeman/foreman-packaging/pull/1261 contains these changes now

**Comment by dLobatog** [comment]
Closing as this is not going to be merged anyway - the packages also had some small changes

**Pull request closed without merging**
