### PR TITLE
Add rubygem-redis package

### PR DESCRIPTION
**Pull request by lzap**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly

---

### CODE REVIEW

**Comment by lzap** [comment]
Repoclojure seem to be unrelated (puppet-client?)

**Comment by lzap** [comment]
```
[root@rc ~]# foreman-rake console
Loading production environment (Rails 5.2.1)
irb(main):001:0> require "redis"
=> true
irb(main):002:0> 
irb(main):003:0> redis = Redis.new
=> #<Redis client v4.1.2 for redis://127.0.0.1:6379/0>

irb(main):005:0> redis.set("mykey", "hello world")
=> "OK"
irb(main):006:0> redis.get("mykey")
=> "hello world"
```

**Comment by tbrisker** [comment]
This needs adding to foreman.spec now, nightlies are failing to build

**Comment by ekohl** [comment]
RPM side is done. Debian side still needs to happen.

**Comment by lzap** [comment]
Hmmm sorry you should have pinged me my GH backlog is huge. Lemme check.

**Comment by lzap** [comment]
https://github.com/theforeman/foreman-packaging/pull/3844/files

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman-packaging/commit/f5bffd1e525c8c4e08e3f94f87405df2eddae634 is the debian side btw.

**Pull request merged**
