### PR TITLE
update foreman_salt to 9.0.0

### PR DESCRIPTION
**Pull request by mmoll**
this should be built into:

* [x] nightly
* [x] 1.16

### CODE REVIEW

**Comment by mmoll** [comment]
adjusted the `BuildRequirements` to reflect the current `Requirements` 😹

**Comment by ekohl** [comment]
> Tests are failing because this is trying to release in koji-katello.. any recent changes that could've caused that?

@dLobatog that's what https://github.com/theforeman/foreman-infra/pull/391 is for.

**Comment by ekohl** [comment]
[test]

**Comment by ekohl** [comment]
Updated the koji 1.16 build tags to use centos like we've done for nightly and 1.15 so that build should pass too.

**Comment by dLobatog** [comment]
[test]

**Comment by mmoll** [comment]
💚

**Comment by ekohl** [comment]
Looks good, but what about nightly? Shouldn't that be 9.0.0 too (and then tagged into 1.16)?

**Comment by mmoll** [comment]
there will be a 10.x version later (maybe).

**Comment by ekohl** [comment]
IMHO we should always have at least the same version in nightly as in a release

**Comment by mmoll** [comment]
we can build 9.0.0 into nightly, but I guess it's not 100% compatible with core 1.17 (prepend vs. alias_method_chain)

**Comment by ekohl** [comment]
You'd think it's at least better than 8.0.3 ;)

**Comment by mmoll** [comment]
Aure, my plan was to wait for the Rails 5.1 stuff to land in core and check if I can update _salt again to some working point.

**Comment by mmoll** [comment]
re-done aginst rpm/develop

**Comment by mmoll** [comment]
[test]

**Comment by ekohl** [comment]
@dLobatog could you have another look?

**Comment by dLobatog** [comment]
nightly - http://koji.katello.org/koji/buildinfo?buildID=20954
1.16 - http://koji.katello.org/koji/buildinfo?buildID=20955

**Pull request merged**
