### PR TITLE
Update bootdisk to 19.0.0

### PR DESCRIPTION
**Pull request by lzap**
For plugin updates, please indicate which repos this should be built into:

* Nightly
* 3.1

Can do a PR or if you want to CP right away, let me know.

### CODE REVIEW

**Review by Odilhao — APPROVED** [review]

**Comment by Odilhao** [comment]
@lzap can we close #7253 to merge this one?

**Comment by evgeni** [comment]
Doesn't 19 come with new nodejs/webpack stuff and needs adjustments for that?

**Comment by lzap** [comment]
Sorry the deb PR is passing now.

> Doesn't 19 come with new nodejs/webpack stuff and needs adjustments for that?

Very possible, my plan was to make build on time and test it in production. Well, guess what - I did not make it in time. @ofedoren would you mind making the JS stack package changes for the feature ? I am assuming this would be the same/similar as in discovery

**Comment by lzap** [comment]
Ok I asked Oleh to do a new PR.

**Comment by lzap** [comment]
For the record, @evgeni already fixed RPM for us, so the remaining work is just the DEB package: https://github.com/theforeman/foreman-packaging/pull/7400

Thanks!

**Comment by evgeni** [comment]
@ofedoren please ping me on IRC, then we can collab on the debian stuff too, which should make your life in Future easier ;)

**Pull request closed without merging**
