### PR TITLE
Katello: Update pulp_deb gem dependency

### PR DESCRIPTION
**Pull request by quba42**
Split out from this PR: https://github.com/theforeman/foreman-packaging/pull/9773

Also Requires:

- https://github.com/Katello/katello/pull/10723
- https://github.com/theforeman/pulpcore-packaging/pull/715

### CODE REVIEW

**Comment by Odilhao** [comment]
[test rpm]

**Comment by quba42** [comment]
@Odilhao Does https://github.com/Katello/katello/pull/10723 need to be merged first?

**Comment by Odilhao** [comment]
Yes, it need to be merged 1st, the RPM error is solved, the one now that we see is from because the Gemlock is expecting <= 3

**Comment by Odilhao** [comment]
[test rpm]

**Comment by Odilhao** [comment]
[test rpm]

**Comment by Odilhao** [comment]
[test rpm]

**Comment by Odilhao** [comment]
Now it's a repoclosure problem, that this PR will fix. Merging

```
[2023-09-14T13:26:59.702Z]     Error: Repoclosure ended with unresolved dependencies.

[2023-09-14T13:26:59.702Z]     package: rubygem-katello-4.11.0-0.2.pre.master.el8.noarch from downloaded_rpms

[2023-09-14T13:26:59.702Z]       unresolved deps:

[2023-09-14T13:26:59.702Z]         (rubygem(pulp_deb_client) >= 3.0.0 with rubygem(pulp_deb_client) < 3.1.0)
```

**Pull request merged**
