### PR TITLE
Update nightly version to 3.0

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by tbrisker** [comment]
[test packaging]

**Comment by ehelms** [comment]
This is blocked on web01 again out of space and cannot complete these test builds

**Comment by ehelms** [comment]
Maybe @evgeni or @ekohl have an idea of what we could clear off or if we can expand the disk space available

**Comment by evgeni** [comment]
[test packaging]

**Comment by evgeni** [comment]
I cleared out a few things, there is now ~9G free. I'll add another disk to the VM and split the storage a bit.

**Review by evgeni — APPROVED** [review]

**Pull request merged**
