### PR TITLE
Update rubygem-newt to 0.9.5

### PR DESCRIPTION
**Pull request by lzap**
Version bump

### CODE REVIEW

**Comment by domcleal** [comment]
Thanks @lzap, building.

**Comment by lzap** [comment]
Thank you, new features for todays demo hopefully...

**Comment by lzap** [comment]
Do you know why this haven't appeared in http://yum.theforeman.org/plugins/nightly/el7/x86_64/ yet?

**Comment by lzap** [comment]
I do see the build, I assume we don't generate plugins nightly repos that often... http://koji.katello.org/koji/buildinfo?buildID=23811

**Comment by domcleal** [comment]
> Do you know why this haven't appeared in http://yum.theforeman.org/plugins/nightly/el7/x86_64/ yet?

A problem with satyr (its removal from EPEL6 after RHEL 6.7 was released, but before CentOS 6.7) is causing plugin tests to fail at the moment, so I'm having to manually check the test results and trigger a push manually.  There's a second issue in today's tests, so I'll fix that and push them if it's OK then.

**Comment by lzap** [comment]
Oh thanks, I will workaround this for the demo.

**Comment by domcleal** [comment]
Other issue's fixed, new repo being pushed now.

**Pull request merged**
