### PR TITLE
Remove unused nodejs packages

### PR DESCRIPTION
**Pull request by ekohl**
Found via:

```
podman run --rm -it centos:stream8
dnf install https://yum.theforeman.org/releases/nightly/el8/x86_64/foreman-release.rpm https://yum.theforeman.org/katello/nightly/katello/el8/x86_64/katello-repos-latest.rpm -y
dnf module enable -y katello
packages=... # packages/foreman/nodejs-*
for package in $packages ; do
        output=$(dnf repoquery --cacheonly --quiet --alldeps --whatrequires $package | grep -v ${package}-doc)
        if [[ -z $output ]] ; then
                echo "Unused package $package"
        fi
done
```

There's a good chance that there are more unused packages after this.

### CODE REVIEW

**Comment by ekohl** [comment]
> output=$(dnf repoquery --cacheonly --quiet --alldeps --whatrequires $package | grep -v ${package}-doc)

This doesn't check for BuildRequires. Marking as draft so I can revisit this.

**Comment by ekohl** [comment]
Note to self: these are still needed as `BuildRequires`:
```
npm(babel-plugin-transform-class-properties)
npm(babel-preset-env)
npm(babel-preset-react)
npm(c3)
npm(identity-obj-proxy)
npm(react-bootstrap)
npm(react-ellipsis-with-tooltip)
npm(react-intl)
npm(react-json-tree)
npm(sortabular)
npm(table-resolver)
```

**Comment by ekohl** [comment]
> This doesn't check for BuildRequires. Marking as draft so I can revisit this.

The trick is to enable the source repositories so it checks the BuildRequires. Remember to do so for all repos: foreman, plugins & katello after the initial `dnf install` and before `dnf module`. Then it works as expected.

Removal automated using:
```
for package in $packages ; do
    removed_in=$(git log rpm/develop -S "npm(${i/nodejs-/})" -n 1 --pretty='format:%H')
  ./remove_package $i
  git commit -a -m "Remove unused package $i" -m "Fixes: $removed_in"
done
```

Then manually fixed up nodejs-redhat-cloud-services-frontend-components since it couldn't be found using the automation. It was added in c25bcadc5ef90b8f4cd1d74f9e1ca1be955f6729 but never used.

**Review by ehelms — APPROVED** [review]

**Comment by ekohl** [comment]
Foreman:
```console
$ git log --oneline 9da06eafe97eb6c698e0d26ab46b66c0b0e5b57a..HEAD packages/foreman/ | awk '{ print $NF }' | xargs echo
nodejs-warning nodejs-urijs nodejs-typed-styles nodejs-seamless-immutable nodejs-reselect nodejs-redux-thunk nodejs-redux nodejs-redhat-cloud-services-frontend-components nodejs-react-redux nodejs-react-lifecycles-compat nodejs-react-is nodejs-react-dom nodejs-react nodejs-raf nodejs-popper.js nodejs-object-assign nodejs-node-gyp nodejs-invariant nodejs-humanize-duration nodejs-babel-register nodejs-babel-polyfill nodejs-babel-plugin-transform-object-rest-spread nodejs-babel-plugin-transform-object-assign nodejs-babel-plugin-syntax-dynamic-import nodejs-babel-plugin-lodash nodejs-babel-cli
$ git log --oneline 9da06eafe97eb6c698e0d26ab46b66c0b0e5b57a..HEAD packages/foreman/ | awk '{ print $NF }' | xargs koji -p katello untag-build --all foreman-nightly-el8
$ git log --oneline 9da06eafe97eb6c698e0d26ab46b66c0b0e5b57a..HEAD packages/foreman/ | awk '{ print $NF }' | xargs koji -p katello block-pkg foreman-nightly-el8
```
Plugins:
```console
$ git log --oneline 9da06eafe97eb6c698e0d26ab46b66c0b0e5b57a..HEAD packages/plugins/ | awk '{ print $NF }' | xargs echo
nodejs-patternfly-react-catalog-view-extension nodejs-babel-plugin-module-resolver
$ git log --oneline 9da06eafe97eb6c698e0d26ab46b66c0b0e5b57a..HEAD packages/plugins/ | awk '{ print $NF }' | xargs koji -p katello untag-build --all foreman-plugins-nightly-el8
$ git log --oneline 9da06eafe97eb6c698e0d26ab46b66c0b0e5b57a..HEAD packages/plugins/ | awk '{ print $NF }' | xargs koji -p katello block-pkg foreman-plugins-nightly-el8
```

**Comment by ekohl** [comment]
As I said: there's now a new set of unused packages. For example, since 1a72e3b0bf7cc20d3528f36f06212281169214ec `nodejs-performance-now` is also unused. Once the new repositories are published the same scripts can be used again to prune more.

**Pull request merged**
