### PR TITLE
Cherrypick - Bump nodejs-theforeman-vendor/builder to 13.0.1 to 3.10

### PR DESCRIPTION
**Pull request by chris1984**

### CODE REVIEW

**Comment by chris1984** [comment]
@theforeman/packaging here is the CP for 3.10

**Comment by evgeni** [comment]
I think we also should pick the `nodejs-theforeman-builder` changes from develop, I have no idea what happens if those two get out of sync.

**Comment by chris1984** [comment]
Brought in the builder cherrypick too, scratch builds passed but failing on repoclosure?

**Comment by chris1984** [comment]
@theforeman/packaging any help here would be appreciated

**Review by evgeni — APPROVED** [review]
should be merged whenever the next 3.10.z is being prepared (otherwise it'll break plugin building until then).

**Pull request closed without merging**
