### PR TITLE
Update rubygem-foreman_virt_who_configure to 0.5.13

### PR DESCRIPTION
**Pull request by chris1984**

### CODE REVIEW

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
It can't even build a scratch build. This fails because Katello hasn't been branched on the packaging side: https://community.theforeman.org/t/katello-4-8-branching-process/32012#release-engineer-10

This is going to be messy to clean up since there have already been nightly builds.

**Comment by Odilhao** [comment]
[test]

**Comment by Odilhao** [comment]
[test rpm]

**Comment by Odilhao** [comment]
[test rpm]

**Comment by Odilhao** [comment]
[test rpm]

**Comment by Odilhao** [comment]
@ekohl now it's failing on repoclosure, I had to tag [rubygem-katello-4.8.0-0.2.pre.master.20230221200252gita5e9405.el8](http://koji.katello.org/koji/buildinfo?buildID=74189)

**Comment by ekohl** [comment]
@Odilhao I'd prefer to get https://github.com/theforeman/foreman-packaging/pull/9114 in first. If you tag in a git build that will be synced in the yum repo for the whole release. We always try to avoid that.

**Comment by chris1984** [comment]
I thought we did do tags here: https://github.com/Katello/katello/releases/tag/4.8.0.rc1

**Comment by chris1984** [comment]
> Git tags and Koji tags are different things.

Ah Koji, ok ignore me.

**Comment by Odilhao** [comment]
> @Odilhao I'd prefer to get #9114 in first. If you tag in a git build that will be synced in the yum repo for the whole release. We always try to avoid that.

Ack, merging #9114 and this one later.

**Comment by Odilhao** [comment]
[test rpm]

**Pull request merged**
