### PR TITLE
Update bindings requirements for rubygem-katello

### PR DESCRIPTION
**Pull request by ianballou**
Update bindings to match with:

https://github.com/theforeman/foreman-packaging/pull/9957

https://github.com/Katello/katello/pull/10791

### CODE REVIEW

**Comment by ianballou** [comment]
Wait for https://github.com/Katello/katello/pull/10791 to be ACK'd

**Comment by evgeni** [comment]
[test rpm-copr]

**Comment by evgeni** [comment]
[test rpm]

(no idea if that still works)

**Comment by evgeni** [comment]
replaced by #10024

**Pull request closed without merging**
