### PR TITLE
Release katello-selinux 3.2.0

### PR DESCRIPTION
**Pull request by jturel**
(cherry picked from commit 2ad2b6fd0b6d473240b36e4b6d21ec56b9739bc9)

This is needed since the foreman-selinux version has the new foreman_rails_t type: https://github.com/theforeman/foreman-selinux/commit/3087a3f799d112211c9eae35b2fe92a3e718621f

### CODE REVIEW

**Comment by jturel** [comment]
[test rpm]

**Comment by pcreech** [comment]
[test]

**Comment by pcreech** [comment]
[test rpm]

**Comment by pcreech** [comment]
[test rpm]

**Comment by evgeni** [comment]
@pcreech needs tagging

**Pull request merged**
