### PR TITLE
hammer plugin CPs for 3.9

### PR DESCRIPTION
**Pull request by ofedoren**

### CODE REVIEW

**Comment by ekohl** [comment]
Test is still queued, but I suspect it may be due to the GH errors (as reported on GH's status page). [test rpm-copr]

**Comment by ofedoren** [comment]
Didn't want to spam GHA, but I've also included `virt-who`, thanks @ekohl fro merging that one!

**Comment by evgeni** [comment]
Thanks! Are you planning to do the same for debian?

**Comment by ofedoren** [comment]
No... But I'll note myself to do it :)

**Comment by evgeni** [comment]
You can also tell me to bugger off and I'll do it tomorrow :)

**Pull request merged**
