### PR TITLE
foreman-rescue: use foreman-plugin.postinst-lib

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
Tests are still running (and we don't have automerge enabled on this repo).

**Comment by evgeni** [comment]
tests are actually failing, old debian/rules is old.

**Review by ekohl — CHANGES_REQUESTED** [review]
Looks like they just failed after I submitted the build. Looks like there's a gem issue. Should it depend on foreman-postgresql?

**Comment by evgeni** [comment]
> Looks like they just failed after I submitted the build. Looks like there's a gem issue. Should it depend on foreman-postgresql?

No, the actual error is further up. But TL;DR: this needs to use the nulldb setup, which it doesn't yet.

**Review by ekohl — APPROVED** [review]
Yay even more lines removed.

**Pull request merged**
