### PR TITLE
Release foreman_salt 3.0.0 (DEB)

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by mmoll** [comment]
we probably need to update tasks/dynflow for debian also? I'll do that anyway very soon (at least the first step. There will be a second step needed to get rex going on Debian.).

**Comment by domcleal** [comment]
Yeah, we need to update tasks and dynflow.  @iNecas mentioned it in #697, but I don't know if he's started or not.

What's rex?

**Comment by mmoll** [comment]
Remote EXecution

**Comment by mmoll** [comment]
#704 for dynflow/-tasks, the -tasks version dependency should be reflected in the control file also. :+1: visually else.

**Comment by domcleal** [comment]
[test]

**Comment by domcleal** [comment]
[test] as a Jenkins job assumed you'd have a deb/develop branch on your fork.  Now fixed.

**Comment by stbenjam** [comment]
Oh, I'm sure I did at one point, I must have pruned it somehow. It's back, although seems you fixed it anyway  :)

**Comment by domcleal** [comment]
@stbenjam not sure if you realise or not, but as per @mmoll's comment above, please add to the control file the version pinning on ruby-foreman-tasks to match the gemspec

**Comment by stbenjam** [comment]
@domcleal no, I missed it thanks.


@mmoll Like this?

**Comment by domcleal** [comment]
@stbenjam yep, and also a `<` condition please, see https://github.com/theforeman/foreman-packaging/blob/deb/develop/plugins/ruby-foreman-chef/debian/control#L11

**Comment by domcleal** [comment]
Merged as 3348fc0, thanks @stbenjam!

**Pull request closed without merging**
