### PR TITLE
Rebuild foreman_ygg_worker to see EL7 client builds work

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ekohl** [comment]
This failed on SuSE, not EPEL7 with this message:
```
/usr/lib64/go/1.21/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
gcc: error: /usr/lib/rpm/redhat/redhat-hardened-ld: No such file or directory
```

**Comment by ekohl** [comment]
@sbernhard any idea? Do you build `foreman_ygg_worker` for SLES or should we stop doing that? I have some vague recollection of a PR to make it build, but perhaps I'm confusing it with another package.

**Comment by sbernhard** [comment]
> @sbernhard any idea? Do you build `foreman_ygg_worker` for SLES or should we stop doing that? I have some vague recollection of a PR to make it build, but perhaps I'm confusing it with another package.

Thank you very much to bring this up. Yes, we have some enhancements to build this for SUSE. 
@maximiliankolb can you have a look at this and open a PR to make this RPM spec ready to build on SUSE?

**Comment by evgeni** [comment]
I found https://github.com/theforeman/foreman-packaging/pull/10553 and opened https://github.com/theforeman/foreman-packaging/pull/11116 based on it

**Pull request closed without merging**
