### PR TITLE
Update katello to 4.10.0

### PR DESCRIPTION
**Pull request by pcreech**

### CODE REVIEW

**Comment by pcreech** [comment]
[test rpm]

**Review by ekohl — CHANGES_REQUESTED** [review]
The dependencies need to be regenerated:
```
DEBUG util.py:634:  No matching package to install: 'rubygem(pulp_deb_client) < 2.22.0'
```

You can include https://github.com/theforeman/foreman-packaging/pull/9810 here.

This isn't reflected in nightly either, but you should also drop `qpid-proton`: https://github.com/Katello/katello/commit/ea06f3d103587765413c3427b776a836cab6520e#diff-21cb8426e694930953a1fb66d2f1e4c0c4021bcadd760d9582423094a4dcaace

**Comment by pcreech** [comment]
Ok, to sum up the changes requested:

* We need to also modify the gemspec to depend on a newer rubygem-pulp-deb-client version.  We can a) patch it with the spec for 4.10.0 or b) release a new katello gem.  Givin timings, i'm for option A personally.

* Drop qpid-proton from the spec as well based on https://github.com/Katello/katello/commit/ea06f3d103587765413c3427b776a836cab6520e#diff-21cb8426e694930953a1fb66d2f1e4c0c4021bcadd760d9582423094a4dcaace and ensure such in nightly as well

**Comment by pcreech** [comment]
[test rpm]

**Comment by pcreech** [comment]
Ok, i'm embarassed that I was lost in the weeds for so long on what turned out to be me not actually updating the spec and having unmerged changes locally.  So...  :D i've fixed deb, removing qpid proton

**Review by ekohl — APPROVED** [review]

**Comment by ekohl** [comment]
Is this an outdated cache?
```
DEBUG util.py:444:  Error: Error downloading packages:
DEBUG util.py:444:    Status code: 404 for http://koji.katello.org/kojifiles/releases/split/yum/koji-modules/koji/staged/x86_64/RHEL-8-001-mod/ruby:2.7/ruby-2.7.4-137.module_el8.4.0%2b875%2b807aec38.x86_64.rpm (IP: 172.30.3.224)
```

**Comment by pcreech** [comment]
indeed, pester @ehelms

**Comment by pcreech** [comment]
Repoclosure issue "        (rubygem(pulp_deb_client) >= 3.0.0 with rubygem(pulp_deb_client) < 3.1.0)" should be resolved alongside publishing this rpm.  Ignoring this failure for this pr

**Comment by ekohl** [comment]
I think that is indeed correct, because they've been built but not pushed to staging. Merging so this can start to build.

**Pull request merged**
