### PR TITLE
Katello 3.17.0 RC2

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
```
DEBUG util.py:598:  Error: No Package found for tfm-rubygem(scoped_search) >= 4.1.9
```

cool cool.

**Comment by evgeni** [comment]
picked scoped in https://github.com/theforeman/foreman-packaging/pull/5857

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
repoclsoure is failing because it needs the repo to be mashed, which it isn't yet

**Comment by ekohl** [comment]
> repoclsoure is failing because it needs the repo to be mashed, which it isn't yet

Isn't scoped search in the base repo? Meaning the main Foreman pipeline needs to run first. Other than that I think it looks good.

**Comment by evgeni** [comment]
> Isn't scoped search in the base repo? Meaning the main Foreman pipeline needs to run first. Other than that I think it looks good.

Correct. But this won't pass tests anyways, as it needs installer changes that aren't released yet. I just want to get the packaging part sorted for @zjhuntin on monday ;)

**Comment by evgeni** [comment]
and I want to get https://github.com/theforeman/foreman-packaging/pull/5846 built, which is blocked on Katello being uninstallable right now in 2.2 koji

**Comment by tbrisker** [comment]
[test rpm] foreman rc4 is out now

**Comment by evgeni** [comment]
Closure expected, can we get an ack?

**Comment by tbrisker** [comment]
During the release meeting today it was pointed out there's a rc2.1 gem out there, so this pr should probably be updated to use that.

**Comment by evgeni** [comment]
@zjhuntin can you take care of that, or should I tomorrow?

**Comment by zjhuntin** [comment]
I'll get it done.

**Comment by zjhuntin** [comment]
Closing in favor of https://github.com/theforeman/foreman-packaging/pull/5894

**Pull request closed without merging**
