### PR TITLE
Add uglifyjs-webpack-plugin

### PR DESCRIPTION
**Pull request by xprazak2**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.17
* [x] 1.16
* [ ] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

After:
https://github.com/theforeman/foreman/pull/5289
https://github.com/theforeman/foreman/pull/5288
https://github.com/theforeman/foreman/pull/5287

### CODE REVIEW

**Comment by xprazak2** [comment]
All the linked PRs are merged now.

**Comment by ehelms** [comment]
That's a lot of binary files being committed. I think those should all be added via `git annex add` ? I missed seeing this PR but its the current build blocker.

**Comment by ehelms** [comment]
@ekohl That works for me, but more so up to @xprazak2 if he has the time given this will unblock the next step.

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman-packaging/pull/2260

**Comment by xprazak2** [comment]
Thanks @ekohl, closing in favour of #2260

**Pull request closed without merging**
