### PR TITLE
Katello 3.10

### PR DESCRIPTION
**Pull request by ehelms**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.20
* [ ] 1.19
* [ ] 1.18

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ekohl** [comment]
Does `obal release katello` now release both 3.9 and 3.10 packages?

**Comment by ehelms** [comment]
@ekohl aye, it would, which sounds bad but we ought to be OK since the builds would already exist and it would skip past them. The alternative is renaming every single directory as well.

**Comment by ehelms** [comment]
Hrmm, other operations would get a little weird as well. Maybe I gotta do both.

**Comment by ekohl** [comment]
I'd say that an explicit note about this in obal itself would be good. Preferably an actual test to see how it behaves.

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
I updated this to make 3.9 and 3.10 unique for katello packages.

@ekohl @tbrisker  3.10 requires updating apipie-rails (http://koji.katello.org/koji/buildinfo?buildID=36149) would you be OK with bringing this in via tagging, signing and releasing into 1.20?

**Comment by tbrisker** [comment]
> @ekohl @tbrisker 3.10 requires updating apipie-rails (http://koji.katello.org/koji/buildinfo?buildID=36149) would you be OK with bringing this in via tagging, signing and releasing into 1.20?

fine by me, I don't think there should be any breaking changes in it.

**Comment by ehelms** [comment]
@ekohl Please ping me here whenever apipie-rails has been tagged, signed and pushed out. Thanks!

**Comment by ehelms** [comment]
This only fails repoclosure so good to go. @ekohl ok with the direction I went to make this work?

**Comment by ehelms** [comment]
I considered that and  went this troute for now. I don't expect to update any dependency, but I think I already may have to.

**Pull request merged**
