### PR TITLE
Release foreman_remote_execution 0.0.7 (RPM)

### PR DESCRIPTION
**Pull request by stbenjam**
All are for nightly and 1.9, please. Merging in this order should make the next one green if it isn't already.

- [x] dynflow 0.8.6 https://github.com/theforeman/foreman-packaging/pull/819
- [x] tasks 0.7.6 https://github.com/theforeman/foreman-packaging/pull/820
- [x] smart_proxy_dynflow 0.0.4 https://github.com/theforeman/foreman-packaging/pull/818
- [ ] smart_proxy_remote_execution_ssh 0.0.6 https://github.com/theforeman/foreman-packaging/pull/821
- [ ] This PR

### CODE REVIEW

**Comment by stbenjam** [comment]
Trying this in one PR, but will it even work? As one package has build deps on another...

**Comment by stbenjam** [comment]
Yea, that didn't work.  One at a time it is.

**Comment by domcleal** [comment]
[test]

**Comment by domcleal** [comment]
[test]

**Comment by domcleal** [comment]
Thanks, building.

**Comment by domcleal** [comment]
All five builds should be rebuilt or retagged into 1.9 now, please let me know if anything's missing.

**Pull request merged**
