### PR TITLE
Regenerate rubygem-foreman_remote_execution based on the current template

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ekohl** [comment]
Will need https://github.com/theforeman/foreman-packaging/pull/2555

**Comment by ekohl** [comment]
Will need https://github.com/theforeman/foreman-packaging/pull/2568

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Pull request closed without merging**
