### PR TITLE
Update GEM/NPM depds of foreman

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
[test rpm-copr]

always better to wait for the other job to finish

**Comment by evgeni** [comment]
repoclosure failing, as the new foreman-js packages are not published yet. that's fine

**Review by ekohl — APPROVED** [review]

**Comment by ekohl** [comment]
Is the `depds` intentional or did you mean to write `deps`?

**Comment by evgeni** [comment]
It's a typo

**Pull request merged**
