### PR TITLE
Fix katello-host-tools rpmbuild

### PR DESCRIPTION
**Pull request by jturel**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.17
* [ ] 1.16
* [ ] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

Wasn't working:

```
RPM build errors:
+ cd katello-agent-3.1.0
/var/tmp/rpm-tmp.XXNDLR: line 37: cd: katello-agent-3.1.0: No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.XXNDLR (%prep)
    Bad exit status from /var/tmp/rpm-tmp.XXNDLR (%prep)
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 89, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/mockbuild/util.py", line 582, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
Error: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target noarch --nodeps /builddir/build/SPECS/katello-host-tools.spec
```

Now it works :)

### CODE REVIEW

**Comment by ekohl** [comment]
Was the file changed on Github? git-annex is not happy

**Comment by jturel** [comment]
@ekohl Not sure, but I wouldn't think so? I have had mixed success locally running setup_sources for this package resulting in the same error most of the time. Sometimes it works => seems intermittent.

**Comment by ehelms** [comment]
I think that the rename of the git repository changed the source tarball thats output. I think we need to redownload and git annex add it again.

**Comment by jturel** [comment]
@ekohl @ehelms fixed!

**Comment by jturel** [comment]
@ekohl make sense - added changelog entry for it.

**Comment by jturel** [comment]
@ekohl @ehelms I think this is ready for a merge

**Pull request merged**
