### PR TITLE
Remove foreman-installer-katello-devel sub-package

### PR DESCRIPTION
**Pull request by ehelms**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.17
* [ ] 1.16
* [ ] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ekohl** [comment]
Depends on https://github.com/Katello/katello-installer/pull/602

**Comment by ehelms** [comment]
[test rpm]

**Comment by ekohl** [comment]
There the releaser is incorrect in `package_manifest.yaml`. I'd prefer to include the sorting PR from https://github.com/theforeman/foreman-packaging/pull/2172 before we make other modifications to it.

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
This is passing now with updates to the `package_manifest.yml`

**Comment by ehelms** [comment]
Good catch -- comps updated

**Pull request merged**
