### PR TITLE
drop smart_proxy_salt_core

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
cc @bastian-src @sbernhard

feel free to revert the `smart_proxy_salt` commit once there is a version that works without `*_core` packages, until then this blocks packaging automation/cleanup.

**Comment by sbernhard** [comment]
Thanks @evgeni. This would not be necessary if we solve https://github.com/theforeman/foreman-packaging/pull/6968 (open since Aug 2)

**Comment by evgeni** [comment]
Sure, please solve it ;-)

(but it then still would require cloning the work to the Debian side of things)

**Comment by sbernhard** [comment]
Lets try this one: https://github.com/theforeman/foreman-packaging/pull/7422

**Comment by evgeni** [comment]
cool, dropped the "drop salt" commit, we can continue in #7429 on that, droping salt-core now, as that's really "gone"

**Pull request merged**
