### PR TITLE
Update foreman_scc_manager to 1.4.0

### PR DESCRIPTION
**Pull request by mdellweg**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.19
* [x] 1.18
* [ ] 1.17

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by dLobatog** [comment]
nightly - http://koji.katello.org/koji/taskinfo?taskID=117530
1.19 - http://koji.katello.org/koji/taskinfo?taskID=117536
1.18 - http://koji.katello.org/koji/taskinfo?taskID=117539

**Comment by mdellweg** [comment]
@ekohl Hi, thanks for merging this. Is there an obstruction that hinders the package to land in the 3.7 archive? I still see the broken (in f1.18) version 1.3.1 in `https://fedorapeople.org/groups/katello/releases/yum/3.7/katello/el7/x86_64/`.

**Comment by ekohl** [comment]
@mdellweg the katello repository (like the foreman core repository) is only updated on a release. It'd be part of katello 3.7.1. I'll defer to @jturel what's the plan for that since he also has to sign the package.

**Comment by jturel** [comment]
I'll make sure this package is in the upcoming katello 3.7.1!

**Pull request merged**
