### PR TITLE
1.17.0-RC1 Release

### PR DESCRIPTION
**Pull request by xprazak2**
For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [x] 1.17
* [ ] 1.16
* [ ] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

Continues where #2145 left off.

### CODE REVIEW

**Comment by xprazak2** [comment]
[test]

**Comment by ekohl** [comment]
There's a failure:

```
08:20:14 The following packages have unmet dependencies:
08:20:14  pbuilder-satisfydepends-dummy : Depends: puppet-agent-puppet-strings which is a virtual package and is not provided by any available package.
08:20:14 
08:20:14                                  Depends: ruby-kafo (>= 1.0.5) which is a virtual package and is not provided by any available package.
```

**Comment by xprazak2** [comment]
[test default]

**Comment by dLobatog** [comment]
http://ci.theforeman.org/view/Release%20pipeline/ - I've triggered release_packages

**Pull request merged**
