### PR TITLE
build kafo for bullseye

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
[test deb]

**Comment by evgeni** [comment]
note to self: document how to add new dists ;)

**Comment by evgeni** [comment]
[test deb]

**Comment by evgeni** [comment]
[test deb]

**Comment by evgeni** [comment]
this is the first PR to get bullseye packaging going.

once that is in, I intend to do the same for *all* `dependencies`, and then go over to `foreman` ;)

**Review by ehelms — APPROVED** [review]

**Pull request merged**
