### PR TITLE
Update katello to 4.8.0

### PR DESCRIPTION
**Pull request by Odilhao**

### CODE REVIEW

**Comment by ekohl** [comment]
This fails because the 4.8 tags do not exist yet in Katello. It should have been branched, but that hasn't happened. This means we need to take additional care when branching and untag any packages that have incorrect versions.

**Comment by Odilhao** [comment]
[test rpm]

**Comment by Odilhao** [comment]
@ekohl this repoclosure failure is expect for Katello?

**Comment by ekohl** [comment]
I suspect you haven't mashed the repositories yet, so it can't do repoclosure. But before you do that, please fix the branching.

If we look at http://koji.katello.org/koji/buildinfo?buildID=74232 then that shouldn't be in the 4.8 tag. Essentially https://github.com/theforeman/foreman-packaging/commit/73513de4cdd08c2cb7d930c3e83d0b3003e93192 and https://github.com/theforeman/foreman-packaging/commit/fdf43f104abee2f177657f3d4466270f078b99ee, though https://github.com/theforeman/foreman-packaging/pull/9101 is open to include that in 4.8.

**Comment by Odilhao** [comment]
Untagged `katello-repos-4.9-0.1.nightly.el8` running one scratch for #9101

**Pull request merged**
