### PR TITLE
Foreman tasks 1.0.1

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
This update will break three plugins:

```
[2020-01-17T13:45:52.371Z]     package: tfm-rubygem-foreman_probing-0.0.2-1.fm1_22.el7.noarch from el7-foreman-plugins-nightly

[2020-01-17T13:45:52.371Z]       unresolved deps:

[2020-01-17T13:45:52.371Z]          tfm-rubygem(foreman-tasks) < 0:1

[2020-01-17T13:45:52.371Z]     package: tfm-rubygem-foreman_remote_execution-2.0.4-1.fm1_25.el7.noarch from el7-foreman-plugins-nightly

[2020-01-17T13:45:52.371Z]       unresolved deps:

[2020-01-17T13:45:52.371Z]          tfm-rubygem(foreman-tasks) < 0:1.0.0

[2020-01-17T13:45:52.371Z]     package: tfm-rubygem-foreman_salt-13.2.0-1.fm1_25.el7.noarch from el7-foreman-plugins-nightly

[2020-01-17T13:45:52.372Z]       unresolved deps:

[2020-01-17T13:45:52.372Z]          tfm-rubygem(foreman-tasks) < 0:1

[2020-01-17T13:45:52.372Z]   stdout_lines: <omitted>
```

@sbernhard -- can this dependency be updated for salt plugin?
@dgoetz -- can this dependency be updated for probing plugin?
@ares -- can this dependency be updated for REX plugin?

**Comment by ekohl** [comment]
Rex should drop it, already done in https://github.com/theforeman/foreman_remote_execution/commit/fdd23500b17fa2d48218f2c1102a56eda7d341d7 but oddly enough not done in https://github.com/theforeman/foreman-packaging/pull/4529. Probably ran `bump_rpm.sh` on 3.0.0 and manually modified to 3.0.1. We need a 3.0.2 release and then it shouldn't be an issue.

**Comment by ehelms** [comment]
@tbrisker Note we can build this, but it won't land in the nightly repositories given repoclosure will fail.

**Comment by tbrisker** [comment]
@ehelms ok, in that case i guess i should push for new releases asap :)

**Comment by tbrisker** [comment]
probing and salt have been updated, rex is failing to build on some js issue - https://github.com/theforeman/foreman-packaging/pull/4347

**Pull request merged**
