### PR TITLE
Drop EL7 koji tags and EL7 only packages

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
@theforeman/packaging please review, there are a number of other PRs in this area but this is the big one that will get the ball rolling in terms of packaging and allow other PRs to take advantage

https://github.com/theforeman/foreman-packaging/pull/8078 follows up on this to cleanup and streamline our package manifest

**Comment by evgeni** [comment]
The diff reads sane to me.
Should comps be dropped in this PR or in another? (I don't mind either way, but they should go)

**Comment by ehelms** [comment]
> The diff reads sane to me. Should comps be dropped in this PR or in another? (I don't mind either way, but they should go)

Got your comps cleanup over here -- https://github.com/theforeman/foreman-packaging/pull/8074

**Comment by ehelms** [comment]
Also repoclosure and mock:

 - https://github.com/theforeman/foreman-packaging/pull/8075
 - https://github.com/theforeman/foreman-packaging/pull/8076

**Review by ekohl — COMMENTED** [review]
In `package_manifest.yaml` there's still a lot of `rhel7` in `repoclosure_target_repos` and `repoclosure_lookaside_repos`. Shouldn't we also get rid of those?

**Comment by ekohl** [comment]
Oh, of course I now see https://github.com/theforeman/foreman-packaging/pull/8075 even though you linked it. Won't that give a lot of merge conflicts?

**Comment by ehelms** [comment]
> Oh, of course I now see #8075 even though you linked it. Won't that give a lot of merge conflicts?

Nope! Good to go here

**Pull request merged**
