### PR TITLE
Bump version of smart proxy for salt

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by sbernhard** [comment]
somebody know how to fix this (if this is even possible)

**Comment by dgoetz** [comment]
repoclosure fails because of missing `salt-master`, which is provided by another repository which could be added to `repoclosure/yum.conf` like ansible and puppet.

**Comment by sbernhard** [comment]
Thanks @dgoetz

**Comment by sbernhard** [comment]
ping (@evgeni )

**Comment by evgeni** [comment]
> ping (@evgeni )

Why?

**Comment by adamruzicka** [comment]
Repoclosure fails because of missing `salt-master`, didn't this PR previously have something to address this issue?

**Comment by m-bucher** [comment]
> Repoclosure fails because of missing `salt-master`, didn't this PR previously have something to address this issue?

fixed :wink:

**Pull request merged**
