### PR TITLE
smart_proxy_openscap version 0.5.1

### PR DESCRIPTION
**Pull request by shlomizadok**

### CODE REVIEW

**Comment by domcleal** [comment]
This (patch) update looks like it's only compatible with 1.11.  Should the minimum version be raised?

**Comment by shlomizadok** [comment]
Update to 1.11, thanks

**Comment by domcleal** [comment]
Thanks, merged to rpm/develop only.  I'd suggest reconsidering the versioning scheme for future updates to prevent users getting the wrong update, or to allow you to update older releases more easily.

**Comment by shlomizadok** [comment]
kk, will do

2015-12-10 11:46 GMT+02:00 Dominic Cleal <notifications@github.com>:

**Pull request merged**
