### PR TITLE
Add Katello-3.6.0rc1

### PR DESCRIPTION
**Pull request by zjhuntin**
For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [x] 1.17
* [ ] 1.16
* [ ] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by zjhuntin** [comment]
[test]

**Comment by ehelms** [comment]
[test]

**Comment by zjhuntin** [comment]
[test]

**Comment by ehelms** [comment]
This is what worked for me locally:

```
diff --git a/katello/rubygem-katello/rubygem-katello.spec b/katello/rubygem-katello/rubygem-katello.spec
index e4100a2..aeaf902 100644
--- a/katello/rubygem-katello/rubygem-katello.spec
+++ b/katello/rubygem-katello/rubygem-katello.spec
@@ -2,21 +2,21 @@
 %{!?scl:%global pkg_name %{name}}
 
 %global gem_name katello
-# %%global prever .rc1
+%global prever .rc1
 %global mainver 3.6.0
-%global release 1.nightly
+%global release 1
 
 %define katello_ostree %{?scl_prefix}rubygem-%{gem_name}_ostree
 
 Name:    %{?scl_prefix}rubygem-%{gem_name}
 Summary: Katello
 
-Version: %{mainver}
+Version: %{mainver}%{?prever}
 Release: %{?prever:0.}%{release}%{?prever}%{?dist}
 Group:   Development/Ruby
 License: Distributable
 URL:     https://theforeman.org/plugins/katello
-Source0: https://rubygems.org/downloads/%{gem_name}-%{version}%{?prever}.gem
+Source0: https://rubygems.org/downloads/%{gem_name}-%{version}.gem
 
 Requires: katello-selinux
 Requires: foreman >= 1.17.0
```

**Comment by zjhuntin** [comment]
[test]

**Pull request merged**
