### PR TITLE
don't install thor, fetching it is sufficient

### PR DESCRIPTION
**Pull request by pcreech**
(cherry picked from commit 6e43b178823461ab05683e117c4ce5b6d5d9a506)

### CODE REVIEW

**Comment by pcreech** [comment]
@evgeni since this is your commit, mind double checking me real quick?

**Comment by evgeni** [comment]
This is exactly the opposite of what I've expected. Will check in detail tomorrow

**Comment by evgeni** [comment]
Like this: https://github.com/theforeman/foreman-packaging/commit/62560ba5b2afcf4ba553aa06476ea319cc02afe7

**Comment by upadhyeammit** [comment]
@pcreech request to do changes mentioned by @evgeni , so we can unblock the 3.0.2 release of Foreman.

**Comment by pcreech** [comment]
@evgeni updated

**Comment by evgeni** [comment]
can you add a changelog entry please, otherwise builds won't get triggered.

**Comment by evgeni** [comment]
and I think `debian/bionic/foreman/rules` needs a similar change, which you omitted?

**Comment by pcreech** [comment]
I retried the pick.  For some reason, looks like bionic didn't have a "rules" file change come along with it.  I updated the thor line along the same basis as the rest of the rules changes.

Updated changelogs this time around as well.

**Review by evgeni — APPROVED** [review]

**Comment by evgeni** [comment]
probably because bionic is not supported on newer releases

**Comment by evgeni** [comment]
let's try to get *all* changes from newer branches: https://github.com/theforeman/foreman-packaging/pull/7676

**Comment by pcreech** [comment]
@evgeni I'm considering this obsoleted by your PRs and closing.

**Pull request closed without merging**
