### PR TITLE
Refs #20960 - mirror activerecord-session_store in Gemfile

### PR DESCRIPTION
**Pull request by mmoll**
this should be built into:

* [x] Nightly

### CODE REVIEW

**Comment by dLobatog** [comment]
http://koji.katello.org/koji/taskinfo?taskID=32736

**Comment by mmoll** [comment]
seems still not to be where it should:
```
DEBUG util.py:439:  Error: Package: tfm-rubygem-activerecord-session_store-1.1.0-1.el7.noarch (build)
DEBUG util.py:439:             Requires: sclo-ror42-rubygem(multi_json) >= 1.11.2
DEBUG util.py:439:             Installing: sclo-ror42-rubygem-multi_json-1.10.1-3.el7.noarch (build)
DEBUG util.py:439:                 sclo-ror42-rubygem(multi_json) = 1.10.1
```

**Comment by mmoll** [comment]
aw, ok...

**Comment by mmoll** [comment]
This is now only the change to ar-session_store. If this is OK, it seems cherry-picking and building in the tfm SCL is neededm then I can push the change to foreman.spec again here

**Comment by dLobatog** [comment]
@mmoll Looks good!

**Comment by mmoll** [comment]
added the foreman.spec change again.

**Comment by dLobatog** [comment]
@mmoll It looks like it still has the same problem, Jenkins doesn't know about dependencies so I believe it builds the packages in any random order, best to submit separate package specs separately, sorry 😞  http://koji.katello.org/kojifiles/work/tasks/2877/32877/mock_output.log

**Comment by mmoll** [comment]
these are two commits, so one could cherry-pick the first and build ar-session_store, then I'd re-trigger the test here.

**Comment by ehelms** [comment]
[test]

**Comment by mmoll** [comment]
💚

**Comment by mmoll** [comment]
should be good to go now.

**Pull request merged**
