### PR TITLE
Refs #21736 - Bump mail gem to 2.7[rpm]

### PR DESCRIPTION
**Pull request by tbrisker**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.16
* [ ] 1.15
* [ ] 1.14

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ekohl** [comment]
This is just the dependency rather than the actual package bump

**Comment by tbrisker** [comment]
hmph, looks like we were using the scl version of the gem, I guess we will now need to build our own?

**Comment by ekohl** [comment]
Related core PR: https://github.com/theforeman/foreman/pull/5023

And we indeed need to import it into our packaging.

**Comment by tbrisker** [comment]
@ekohl since this is only targeted at 1.17, the correct version of the mail gem should already be in tfm-ror51 - https://github.com/theforeman/tfm-ror51-packaging/blob/master/packages/tfm-ror51-rubygem-mail/tfm-ror51-rubygem-mail.spec
What should we do if any in the foreman-packaging?

**Comment by ekohl** [comment]
I think it's fine to wait for bumping the SCL to tfm-ror51

**Comment by tbrisker** [comment]
Makes sense, we'll get the new gem with the new scl anyways, no need for a separate pr for it.

**Pull request closed without merging**
