### PR TITLE
Add qpid-dispatch for Katello on EL8

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by evgeni** [comment]
```
DEBUG util.py:600:  No matching package to install: 'libuv-devel'
```

I remember we had issues with that in the past. Something about an extra devel repo? @pcreech

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
Splt out the libwebsockets part to here -- https://github.com/theforeman/foreman-packaging/pull/6259

**Comment by ehelms** [comment]
[test rpm]

**Comment by pcreech** [comment]
unrelated repoclosure failure.  ACK

**Review by pcreech — APPROVED** [review]

**Pull request merged**
