### PR TITLE
Refs #35409 - Include sprockets assets

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by ekohl** [comment]
Looks like chef is broken:
```
NameError: undefined local variable or method `belongs_to_host' for ForemanChef::CachedRunList(Table doesn't exist):Class
Did you mean?  belongs_to
/usr/share/gems/gems/activerecord-6.1.6.1/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
```

Just for completeness, all plugins:
```console
$ rg 'template: foreman_plugin' packages/*/*/*.spec -l | sort
packages/katello/rubygem-foreman_kernel_care/rubygem-foreman_kernel_care.spec
packages/katello/rubygem-foreman_rh_cloud/rubygem-foreman_rh_cloud.spec
packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
packages/katello/rubygem-foreman_virt_who_configure/rubygem-foreman_virt_who_configure.spec
packages/katello/rubygem-katello/rubygem-katello.spec
packages/plugins/rubygem-foreman_acd/rubygem-foreman_acd.spec
packages/plugins/rubygem-foreman_ansible/rubygem-foreman_ansible.spec
packages/plugins/rubygem-foreman_azure_rm/rubygem-foreman_azure_rm.spec
packages/plugins/rubygem-foreman_bootdisk/rubygem-foreman_bootdisk.spec
packages/plugins/rubygem-foreman_chef/rubygem-foreman_chef.spec
packages/plugins/rubygem-foreman_column_view/rubygem-foreman_column_view.spec
packages/plugins/rubygem-foreman_concrete/rubygem-foreman_concrete.spec
packages/plugins/rubygem-foreman_datacenter/rubygem-foreman_datacenter.spec
packages/plugins/rubygem-foreman_default_hostgroup/rubygem-foreman_default_hostgroup.spec
packages/plugins/rubygem-foreman_dhcp_browser/rubygem-foreman_dhcp_browser.spec
packages/plugins/rubygem-foreman_discovery/rubygem-foreman_discovery.spec
packages/plugins/rubygem-foreman_dlm/rubygem-foreman_dlm.spec
packages/plugins/rubygem-foreman_expire_hosts/rubygem-foreman_expire_hosts.spec
packages/plugins/rubygem-foreman_fog_proxmox/rubygem-foreman_fog_proxmox.spec
packages/plugins/rubygem-foreman_git_templates/rubygem-foreman_git_templates.spec
packages/plugins/rubygem-foreman_graphite/rubygem-foreman_graphite.spec
packages/plugins/rubygem-foreman_hooks/rubygem-foreman_hooks.spec
packages/plugins/rubygem-foreman_host_extra_validator/rubygem-foreman_host_extra_validator.spec
packages/plugins/rubygem-foreman_host_reports/rubygem-foreman_host_reports.spec
packages/plugins/rubygem-foreman_kubevirt/rubygem-foreman_kubevirt.spec
packages/plugins/rubygem-foreman_leapp/rubygem-foreman_leapp.spec
packages/plugins/rubygem-foreman_m2/rubygem-foreman_m2.spec
packages/plugins/rubygem-foreman_memcache/rubygem-foreman_memcache.spec
packages/plugins/rubygem-foreman_monitoring/rubygem-foreman_monitoring.spec
packages/plugins/rubygem-foreman_netbox/rubygem-foreman_netbox.spec
packages/plugins/rubygem-foreman_noenv/rubygem-foreman_noenv.spec
packages/plugins/rubygem-foreman_omaha/rubygem-foreman_omaha.spec
packages/plugins/rubygem-foreman_openscap/rubygem-foreman_openscap.spec
packages/plugins/rubygem-foreman_probing/rubygem-foreman_probing.spec
packages/plugins/rubygem-foreman_puppet/rubygem-foreman_puppet.spec
packages/plugins/rubygem-foreman_remote_execution/rubygem-foreman_remote_execution.spec
packages/plugins/rubygem-foreman_rescue/rubygem-foreman_rescue.spec
packages/plugins/rubygem-foreman_salt/rubygem-foreman_salt.spec
packages/plugins/rubygem-foreman_setup/rubygem-foreman_setup.spec
packages/plugins/rubygem-foreman_snapshot_management/rubygem-foreman_snapshot_management.spec
packages/plugins/rubygem-foreman_spacewalk/rubygem-foreman_spacewalk.spec
packages/plugins/rubygem-foreman_statistics/rubygem-foreman_statistics.spec
packages/plugins/rubygem-foreman_supervisory_authority/rubygem-foreman_supervisory_authority.spec
packages/plugins/rubygem-foreman-tasks/rubygem-foreman-tasks.spec
packages/plugins/rubygem-foreman_templates/rubygem-foreman_templates.spec
packages/plugins/rubygem-foreman_vault/rubygem-foreman_vault.spec
packages/plugins/rubygem-foreman_vmwareannotations/rubygem-foreman_vmwareannotations.spec
packages/plugins/rubygem-foreman_webhooks/rubygem-foreman_webhooks.spec
packages/plugins/rubygem-foreman_wreckingball/rubygem-foreman_wreckingball.spec
```

Not all of them have assets though.

**Comment by evgeni** [comment]
FTR, adding of the macro was done using: `git grep -l 'foreman_assets_plugin' packages/ | xargs -n1 sed -i '/foreman_assets_plugin/a %{foreman_assets_foreman}'`, so only packages that already used `foreman_assets_plugin` got `foreman_assets_foreman` added ;)

I'll drop chef for now from this PR.

**Review by ekohl — APPROVED** [review]
:+1: if it's green.

**Comment by evgeni** [comment]
I like how you said "if", not "when" ;-)

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
repoclosure is confused on katello/non-katello packages :roll_eyes:

**Pull request merged**
