### PR TITLE
Update foreman_openscap to 0.8.6

### PR DESCRIPTION
**Pull request by ares**
For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [x] 1.17
* [x] 1.16
* [ ] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by akofink** [comment]
Is the failure in Foreman or foremana_openscap? Seems the former.

**Comment by ares** [comment]
Hm, it seems that the Foreman DB was not fully migrated and seeded, the plugin then fails on missing anonymous admin user - http://koji.katello.org/kojifiles/work/tasks/6353/86353/build.log 

[test]

**Comment by ekohl** [comment]
[test packaging]

**Comment by ekohl** [comment]
@ares looks like that's still an issue

**Comment by ares** [comment]
yeah, it seems it fails since the admin is not yet seeded in DB, working on fix, it will need another releases

**Comment by ares** [comment]
pushed fixed version

**Comment by ekohl** [comment]
You also marked this as 1.17 but that already contains 0.9.2 so I think that's no longer needed.

**Pull request merged**
