### PR TITLE
Update rubygem-foreman_virt_who_configure to 0.3.2

### PR DESCRIPTION
**Pull request by evgeni**
(cherry picked from commit c81b0e2295aa6cb8f9d3547264be47372066156c)

For plugin updates, please indicate which repos this should be built into:

* [ ] Nightly
* [ ] 1.21
* [x] 1.20

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm]

**Comment by ares** [comment]
Still red, something I need to fix?

**Comment by ekohl** [comment]
I've been told that https://github.com/theforeman/foreman-infra/pull/921 is supposed to fix this.

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
:thinking: why does it try to build into `katello-3.9-rhel7-build` and not `katello-3.10-rhel7-build` and that seems to have the concurrent issue again :(

**Comment by evgeni** [comment]
fixing the later in https://github.com/theforeman/tool_belt/pull/153

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
finally :green_apple:

**Comment by evgeni** [comment]
built into 3.9: http://koji.katello.org/koji/taskinfo?taskID=168501
tagged into 3.10: http://koji.katello.org/koji/taskinfo?taskID=168506

**Pull request merged**
