### PR TITLE
Update smart-proxy-ansible to 2.0.2

### PR DESCRIPTION
**Pull request by ekohl**
This is a bundling of various changes that happened in rpm/develop and since it's a non-trivial cherry-pick I'd prefer a PR.

### CODE REVIEW

**Comment by ekohl** [comment]
[test packaging]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test packaging]

**Comment by ekohl** [comment]
Looks like it failed because https://github.com/theforeman/foreman-infra/commit/9cf09d3335079073b9cb45cf342dcf4273a3583b hadn't been applied yet or a script outside of version control is still calling kkoji. The actual build http://koji.katello.org/koji/taskinfo?taskID=85556 did pass.

**Pull request merged**
