### PR TITLE
Refs #24704 - Update Foreman to depend on fog-vsphere >= 2.3.0

### PR DESCRIPTION
**Pull request by chris1984**
@tbrisker here is the packaging pr

### CODE REVIEW

**Comment by chris1984** [comment]
@tbrisker here is the packaging pr

**Comment by chris1984** [comment]
[test rpm]

**Comment by ekohl** [comment]
[test rpm]

**Comment by chris1984** [comment]
[test rpm]

**Comment by ekohl** [comment]
It fails because 2.3.0 is not present in the repo. It will need to be tagged in again as it was removed. I'll revisit this when the core PR has been merged.

**Comment by xprazak2** [comment]
This was merged in core.

**Comment by chris1984** [comment]
@ekohl updated

**Pull request closed without merging**
