### PR TITLE
Updated rubygem-ruby2ruby to 2.4.0

### PR DESCRIPTION
**Pull request by witlessbird**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.17
* [x] 1.16
* [ ] 1.15

See Foreman's [plugin maintainer documentation](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by witlessbird** [comment]
This requires rubygem-sexp_processor v4.10.0 and rubygem-ruby_parser v3.10.1

**Comment by dLobatog** [comment]
[test]

**Comment by ekohl** [comment]
@mmoll I think @witlessbird released a new version that is compatible, but core does need a corresponding PR to remove the pin. So far I've just merged the compatible PR.

**Comment by ekohl** [comment]
Needs https://github.com/theforeman/foreman-packaging/pull/2103 & https://github.com/theforeman/foreman-packaging/pull/2104 (both merged now)

**Pull request merged**
