### PR TITLE
Update rubygem-foreman_virt_who_configure to 0.4.3

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ekohl** [comment]
There's files added that I can't place:
```
Compared versions: ["0.4.1", "0.4.2"]
  DIFFERENT files:
    0.4.1->0.4.2:
      * Added:
            locale/en/foreman_virt_who_configure.edit.po
              (!) Unexpected permissions: 100664
            locale/en/foreman_virt_who_configure.po.time_stamp
              (!) Unexpected permissions: 100664
```

Are these intended?

**Comment by ares** [comment]
oh, there's missing .gitignore and I accidentally pushed that to the gem, we can ignore these in spec for now

**Comment by ekohl** [comment]
I think gem build ignores .gitignore and just takes what's in the gemspec and on the filesystem.

**Comment by ares** [comment]
ah yeah, I extracted strings this time from release repo, that's why, do you need me to release new version?

**Comment by ekohl** [comment]
It would be cleaner.

**Comment by ares** [comment]
that will have to wait at least one week, I can't connect to my host in VPN from here :-(

**Comment by ares** [comment]
updated to 0.4.3 which shouldn't have any extra files

**Pull request merged**
