### PR TITLE
add foreman-proxy-journald meta package

### PR DESCRIPTION
**Pull request by mmoll**
this should be built into:

* [x] Nightly

### CODE REVIEW

**Comment by ekohl** [comment]
If we're going to introduce a subpackage for RPMs, I'd like to have it too for Debs so the installer doesn't have to know. Is that hard to do?

**Comment by mmoll** [comment]
> Is that hard to do?

Nope, will do it later.

**Comment by lzap** [comment]
Just probing how far this is in your TODO @mmoll as I am trying to hit with the logging feature 1.20 ;-)

**Comment by ekohl** [comment]
Does anything needs to happen in the bundler config to ensure it's installed is that irrelevant because it's a system gem?

**Comment by mmoll** [comment]
> is that irrelevant because it's a system gem?

exactly.

**Pull request merged**
