### PR TITLE
Update rubygem-katello to use pulp_rpm_client 3.10.0

### PR DESCRIPTION
**Pull request by ianballou**
To support https://projects.theforeman.org/issues/32301

### CODE REVIEW

**Comment by ianballou** [comment]
Should merge after https://github.com/theforeman/foreman-packaging/pull/6532

**Comment by ianballou** [comment]
[test rpm]

**Comment by ianballou** [comment]
[test rpm]

**Comment by ianballou** [comment]
[test rpm]

**Comment by jlsherrill** [comment]
[test rpm]

**Comment by jlsherrill** [comment]
DEBUG util.py:598:  Error: No Package found for tfm-rubygem(pulp_2to3_migration_client) < 0.8.0

mind going ahead and updating the spec based on https://github.com/Katello/katello/blob/KATELLO-3.18/katello.gemspec#L59

i think it'll pass then

**Comment by ianballou** [comment]
@jlsherrill okay, I've updated it

**Comment by ianballou** [comment]
Closing since this will need to happen at Katello packaging time.

**Pull request closed without merging**
