### PR TITLE
Rails 6.1.7.7 for 3.9

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by ekohl** [comment]
[test rpm-copr]

**Comment by pcreech** [comment]
Good question...  I haven't done the singing dance yet, i'll hold off till we have a decision.  I'm a "yes" given it's a small version bump.

Don't have time at the moment to review.  if it's not reviewed by my AM, i'll merge and move forward.

**Comment by evgeni** [comment]
[test rpm-copr]

**Comment by evgeni** [comment]
repoclosure can be ignored, will fix itself once all 6.1.7.7 packages are available

**Review by pcreech — APPROVED** [review]

**Pull request merged**
