### PR TITLE
Bump nodejs-theforeman-{vendor,builder} to 10.1.7

### PR DESCRIPTION
**Pull request by Ron-Lavi**

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
I'd like to get https://github.com/theforeman/npm2rpm/pull/68 merged and use that. It saves a lot of space in the repository.

I'm also interested to know why you picked 10.1.7 while version 12.0.0 is out as well.

**Comment by Ron-Lavi** [comment]
> I'm also interested to know why you picked 10.1.7 while version 12.0.0 is out as well.

Looks like the foreman develop uses `"@theforeman/vendor": "^10.1.0"` in https://github.com/theforeman/foreman/blob/develop/package.json#L27
which already accepts v10.1.7, it just wasn't reflected in the packaging.

there was also a fix in v10.1.1 that I would like to get in, discussed in https://github.com/theforeman/foreman-packaging/pull/8446

I would also like to cherry-pick it to `rpm/3.3` branch if possible.

as for upgrading to v12.0.0, we first need to update the foreman core - and I pinged @mariaaga offline to check if we can already do that. Overall there are only 2 commits that differ between v10.1.7 and v12.0.0.

> I'd like to get https://github.com/theforeman/npm2rpm/pull/68 merged and use that. It saves a lot of space in the repository.

I see you just merged this one, should I rebase my local `npm2rpm` and update this PR?

**Comment by ekohl** [comment]
> I see you just merged this one, should I rebase my local `npm2rpm` and update this PR?

Please do

**Comment by Ron-Lavi** [comment]
Thanks @ekohl, updated 👍🏼

**Review by ekohl — APPROVED** [review]

**Pull request merged**
