### PR TITLE
Rpm/2.1 cherry pick

### PR DESCRIPTION
**Pull request by sjha4**
Supported Versions:
 * 2.1

### CODE REVIEW

**Comment by jlsherrill** [comment]
[test rpm]

404 from centos

**Comment by jlsherrill** [comment]
@evgeni repoclosure for el8 seems pretty messed up on 3.16, any objection to this as is?

**Comment by evgeni** [comment]
the python things were indeed missing, so I tagged them.

faraday should be there, this is probably because it's testing different tags (pulpcore vs ruby)

**Comment by evgeni** [comment]
Given we won't release 3.16 on EL8 anyways (right?), we could also completely disable building and closure there?

@ehelms ?

**Comment by sjha4** [comment]
Might need to hold off for a bit on this one..I am checking on this PR to cherry-pick a change we need in pulp_rpm 3.5..https://github.com/pulp/pulp_rpm/pull/1796 ..

**Comment by jlsherrill** [comment]
@sjha4 lets go forward with this and then backport https://github.com/theforeman/foreman-packaging/pull/5634  when its merged

**Comment by jlsherrill** [comment]
i think we should disable building and repoclosure for 3.16 el8

**Pull request merged**
