### PR TITLE
Fixes #28941 - Fix dynflowd shebang

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ekohl** [comment]
This is untested. It's going straight to 1.24 since 2.0 has dropped dynflowd in favor of the sidekiq approach.

**Comment by evgeni** [comment]
nope:

```
18:35:42 /bin/sed -ri '1sXenv rubyXenv foreman-rubyX' bin/* extras/dynflowd
18:35:42 /bin/sed: can't read extras/dynflowd: No such file or directory
```

**Comment by ekohl** [comment]
Ha, so I first did it on Buster, then wrong on the next one and copied the incorrect one over. Updated.

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Pull request merged**
