### PR TITLE
Only generate post scripts when building for upstream Foreman

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
@sbernhard would that affect your workflows in any way?

**Review by ekohl — COMMENTED** [review]
We talked about splitting the packages, creating `foreman-installer-scenario-{foreman,katello,foreman-proxy-content}`. Perhaps that would be a better solution?

**Comment by evgeni** [comment]
Technically? Maybe. But that would require more work ;)

**Comment by ehelms** [comment]
This does certainly help the situation as an easy solution. The core package + scenario per sub-package has some fun implications and niceness to it. I suppose you'd then need macros per sub-package to allow toggling them off and on.

**Comment by ekohl** [comment]
I'd think that every sub package would have its own `%post` for the migration.

**Comment by sbernhard** [comment]
> @sbernhard would that affect your workflows in any way?

first of all, thank you very much that you think about "us". 
No, it doesn't affect us.

**Comment by evgeni** [comment]
What would pull in these new packages? Or would we tell the users "install foo-scenario" as the main entry point?

**Comment by ekohl** [comment]
The latter IMHO. The only question is the migration. One way to solve that is to have:
* `foreman-installer-base` all modules and shared config (hiera)
* `foreman-installer-scenario-$scenario` a package for each scenario (depends on `foreman-installer-base`
* `foreman-installer` a transitional meta package that depends on `foreman-installer-scenario-foreman`
* `foreman-installer-katello` a transitional meta package that depends on `foreman-installer-scenario-foreman` and `foreman-installer-scenario-katello` and `foreman-installer-scenario-content-proxy`.

Then if you want to produce a custom installer, you would create a package, make it depend on `foreman-installer-base` and include your scenario files.

The upside of it is that if you only have a single scenario installed, you don't need to pass `--scenario`. This simplifies instructions for users.

**Comment by evgeni** [comment]
Today, Katello users have both `foreman-installer` and `foreman-installer-katello` installed, so the transitional `foreman-installer` package would pull in "the wrong" `foreman-installer-scenario-foreman`. On the other hand you say `f-i-k` should pull in three scenarios? Then you again need `--scenario`?

So we would make `kafo` (it's kafo who handles scenarios, right?) behave like this:
* if only one scenario is available, `--scenario` becomes optional (but accepted to allow old automation to work)
* if multiple are available (because multiple packages are installed), `--scenario` remains required as it is today?

**Comment by ekohl** [comment]
> Today, Katello users have both `foreman-installer` and `foreman-installer-katello` installed, so the transitional `foreman-installer` package would pull in "the wrong" `foreman-installer-scenario-foreman`. On the other hand you say `f-i-k` should pull in three scenarios? Then you again need `--scenario`?

Correct, but from RPMs we can't decide which is the right scenario so we can't cleanly migrate. This is also the situation today for Katello users.

> So we would make `kafo` (it's kafo who handles scenarios, right?) behave like this:
> 
>     * if only one scenario is available, `--scenario` becomes optional (but accepted to allow old automation to work)
>     * if multiple are available (because multiple packages are installed), `--scenario` remains required as it is today?

Correct. This is how Kafo behaves (and always has):

https://github.com/theforeman/kafo/blob/35a70342e2cc99d8ee9d58129e91efae66e98187/lib/kafo/scenario_manager.rb#L98-L112

This is why you don't see `--scenario` anywhere in the Foreman manual (which only ships a single scenario).

My argument is to also bring this to Katello. For fresh installations an up front selection should be made by choosing the right RPM. For existing installations you will have multiple scenarios available but since there is already a selection, it's already an optional argument.

**Comment by evgeni** [comment]
I can't remember when I deployed a pure Foreman last time without Ansible, so I never noticed that :rofl:

**Comment by evgeni** [comment]
However, I must admit I don't have the time to work on the "split the scenarios in own packages" proposal right now.

**Comment by ekohl** [comment]
Is this only relevant when we branch in downstream or continuous? In other words: is there value if we merge it now or can we postpone to 3.1?

**Comment by evgeni** [comment]
This is only relevant for downstream consumers, so 3.0 won't benefit from this PR (but would from your proposal, as it'd be cleaner overall)

**Comment by ekohl** [comment]
So that was what I was getting at. I'd be in favor of planning and executing my proposal in the 3.1 timeframe.

**Comment by evgeni** [comment]
Closing then.

**Pull request closed without merging**
