### PR TITLE
Foreman 3.10 branching updates - DEB edition

### PR DESCRIPTION
**Pull request by pcreech**

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
Did we generate a new GPG key for Debian? We normally don't do that for every release. AFAIK with Debian we have a single GPG key for deb.theforeman.org.

**Review by ekohl — APPROVED** [review]
They match https://deb.theforeman.org/foreman.asc so perhaps we just have it wrong in nightly?

**Comment by evgeni** [comment]
I think both are fine, they are just exports at different times :woman_shrugging:

**Comment by pcreech** [comment]
For the simplicity of not re-hashing this conversation next branching, I'd say we merge it, so it'll become a no-op in the future.

**Pull request merged**
