### PR TITLE
Bump rubygem-hammer_cli_foreman_tasks to 0.0.18-1

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
@adamruzicka or was it intentional that 0.0.18 was never packaged?

**Comment by adamruzicka** [comment]
No, I just did a release to rubygems and hoped the automation would kick in and bump the packaging? Shouldn't that have happened?

**Comment by evgeni** [comment]
It should, if the package would have had the `template: hammer_plugin` header, which this PR adds ;)

**Comment by adamruzicka** [comment]
Ah, TIL, thank you

**Review by ekohl — APPROVED** [review]

**Pull request merged**
