### PR TITLE
drop foreman-compute require from foreman-one

### PR DESCRIPTION
**Pull request by evgeni**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.21
* [ ] 1.20

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ekohl** [comment]
Does this even work? 0.4 is from 2015.

**Comment by evgeni** [comment]
:see_no_evil: I don't know

**Comment by dgoetz** [comment]
I do not think so and because of our Managed Service team moving to Openstack, I think there will be no development from our site any longer. :cry:

**Comment by evgeni** [comment]
@dgoetz time to archive the source repo and remote the rpm then?

**Comment by dgoetz** [comment]
If it causes problems, yes. I already mentioned it in the fog upgrade discussion and noone reacted, so I think user base is low to non existing.

**Comment by ekohl** [comment]
Should we sunset it? I think the procedure should be:
* Post to discourse
* Remove from nightly
* Update the README in the git repo pointing to the discourse post
* Archive the git repo

**Comment by evgeni** [comment]
We can also merge this PR and wait till someone complains it's not actually working?

**Comment by ares** [comment]
If we know it does not work, let's set the right expectation. I vote for sunset.

**Pull request closed without merging**
