### PR TITLE
Update Webhooks to 3.0.0

### PR DESCRIPTION
**Pull request by lzap**
For plugin updates, please indicate which repos this should be built into:

* Nightly

### CODE REVIEW

**Comment by evgeni** [comment]
[test packaging]

**Comment by lzap** [comment]
Green thanks!

**Review by evgeni — APPROVED** [review]

**Comment by lzap** [comment]
Update: I want this in 3.0 so I will file CP shortly.

Just for the record, I will file 2.0.1 version for 2.5 only with a patch for a BZ I have on my plate (https://bugzilla.redhat.com/show_bug.cgi?id=1977840)

**Comment by lzap** [comment]
CP: https://github.com/theforeman/foreman-packaging/pull/7070

**Pull request merged**
