### PR TITLE
Bump Katello related packages to their 4.10 versions

### PR DESCRIPTION
**Pull request by wbclark**

### CODE REVIEW

**Comment by ekohl** [comment]
This depends on https://ci.theforeman.org/job/katello-master-source-release/2200/ but I wonder why it's been running for 2 days. That isn't right. I'm cancelling and kick off a fresh build.

**Comment by ekohl** [comment]
`bump_rpm.sh` doesn't work with nightly packages for which it needs to retrieve the source via Jenkins, which pretty much all these packages are.

**Comment by pcreech** [comment]
[test rpm]

**Review by ekohl — APPROVED** [review]
Repoclosure failure is from the old RPM.

**Pull request merged**
