### PR TITLE
Add nodejs-patternfly-react-catalog-view-extension package

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Review by ekohl — APPROVED** [review]

**Review by ekohl — CHANGES_REQUESTED** [review]
This is only needed by a plugin, right? So it should live in `packages/plugins`.

**Comment by evgeni** [comment]
> This is only needed by a plugin, right? So it should live in `packages/plugins`.

Technically? Yeah. But we have almost all node things for plugins in "foreman".

**Comment by ekohl** [comment]
I still think it's cleaner to add it to plugins but it doesn't matter that much.

**Comment by evgeni** [comment]
moved

**Pull request merged**
