### PR TITLE
Update rubygem-smart_proxy_discovery_image to 1.2.0

### PR DESCRIPTION
**Pull request by lzap**
For plugin updates, please indicate which repos this should be built into:

* Nightly
* 2.1

### CODE REVIEW

**Comment by lzap** [comment]
Will do CP PR. There is no debian package for this one, this is FDI only plugin.

**Comment by lzap** [comment]
GJ TY CP PR: https://github.com/theforeman/foreman-packaging/pull/5436

**Comment by lzap** [comment]
@evgeni do you know why it's not yet build? it's been 20 hours and I don't see it yet: http://yum.theforeman.org/plugins/nightly/el7/x86_64/ thanks

**Comment by evgeni** [comment]
@lzap huh? http://yum.theforeman.org/plugins/nightly/el7/x86_64/tfm-rubygem-smart_proxy_discovery_image-1.2.0-1.fm2_2.el7.noarch.rpm is there

**Pull request merged**
