### PR TITLE
Bumped katello nightly to 4.6

### PR DESCRIPTION
**Pull request by parthaa**

### CODE REVIEW

**Comment by ehelms** [comment]
Is it intended for this to catch updates to all of Katello packages? i.e. rubygem-katello and katello

**Comment by ehelms** [comment]
Looks like https://github.com/theforeman/foreman-packaging/pull/7884/files#diff-ea1969cc98962976d79819fceee9455b08e0f99c44e5071fa281f3718bb8e3f8R6 will need to be updated to 3.5

**Comment by ehelms** [comment]
Looks like https://github.com/theforeman/foreman-packaging/pull/7884/files#diff-ea1969cc98962976d79819fceee9455b08e0f99c44e5071fa281f3718bb8e3f8R6 will need to be updated to 3.5

**Review by ehelms — APPROVED** [review]

**Comment by evgeni** [comment]
this has been merged before @theforeman/packaging cloned the 4.5 tags from nightly, so had to be untagged from 4.5:

```console
% koji untag-build katello-4.5-el8 katello-4.6.0-0.1.master.el8  katello-repos-4.6-0.1.nightly.el8 rubygem-katello-4.6.0-0.1.pre.master.20220512200144git68b2cc9.el8
% koji untag-build katello-4.5-rhel7 katello-4.6.0-0.1.master.el7 katello-repos-4.6-0.1.nightly.el7 tfm-rubygem-katello-4.6.0-0.1.pre.master.20220512200144git68b2cc9.el7
```

**Pull request merged**
