### PR TITLE
Update to smart_proxy_discovery_image-1.1.0

### PR DESCRIPTION
**Pull request by lzap**
For plugin updates, please indicate which repos this should be built into:

* Nightly

### CODE REVIEW

**Comment by evgeni** [comment]
@lzap the gem version seems not to exist on rubygems.org?

**Comment by lzap** [comment]
Successfully registered gem: smart_proxy_discovery_image (1.1.0)

You guys have automated everything, haven't you? :-) Pushed ^^

**Comment by lzap** [comment]
Da fak, I no longer see the result.

**Comment by lzap** [comment]
[test] just trying...

**Comment by evgeni** [comment]
[test rpm]

Yeah the results get rotated too quickly sometimes

**Comment by lzap** [comment]
Newer version went out: https://github.com/theforeman/foreman-packaging/pull/5434

**Pull request closed without merging**
