### PR TITLE
bump openscap compatibility again - 1.3.6 is OK

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Review by upadhyeammit — APPROVED** [review]

**Comment by upadhyeammit** [comment]
:| not sure how to fix the non matching rpmdb hash in koji

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
@theforeman/packaging this is still failing and is breaking the openscap plugin and testing of our plugins.

**Comment by upadhyeammit** [comment]
@pcreech hello any progress on this? My search says we can do something like below on koji,
~~~
> If you feel that there was a legitimate reason for the rpm in the
> external repo to change then the workaround is, as Mike B wrote, to
> create a new external repo entry (with a new name) pointing to the same
> url and replace the old external with that in your tag hierarchy. The
> reason this works is that Koji does allow different external repos to
> disagree about the contents of a particular nvr.
~~~

The source is: https://www.mail-archive.com/buildsys@lists.fedoraproject.org/msg00223.html

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
```console
% koji tag-build foreman-plugins-nightly-el8 rubygem-openscap-0.4.9-7.el8
Created task 486494
Watching tasks (this may be safely interrupted)...
486494 tagBuild (noarch): free
486494 tagBuild (noarch): free -> closed
  0 free  0 open  1 done  0 failed

486494 tagBuild (noarch) completed successfully

% koji tag-build foreman-plugins-nightly-rhel7 tfm-rubygem-openscap-0.4.9-7.el7
Created task 486497
Watching tasks (this may be safely interrupted)...
486497 tagBuild (noarch): free
486497 tagBuild (noarch): free -> closed
  0 free  0 open  1 done  0 failed

486497 tagBuild (noarch) completed successfully
```

(tagging, as the build already happened for 3.1 :eyes: )

**Pull request merged**
