### PR TITLE
Remote execution iteration 3 (DEB)

### PR DESCRIPTION
**Pull request by stbenjam**
For 1.10 and nightly

### CODE REVIEW

**Comment by domcleal** [comment]
Do you need to set a min version of Foreman of 1.10 on the main plugin?

**Comment by stbenjam** [comment]
Yes, thank you.  Did I get the tilda's right? I don't quite understand why one does the `~rcX` thing.

**Comment by mmoll** [comment]
1.2.3~rc1 is < 1.2.3, while 1.2.3rc1 or 1.2.3.rc1 would be >1.2.3 for the dpkg/apt version comparator.

**Comment by domcleal** [comment]
Thanks @stbenjam, merged as cba1bf5, 9c0209d for develop and f48b5ea, 2283113 for 1.10.  Packages are now building.

**Pull request closed without merging**
