### PR TITLE
Update hammer_cli_foreman_admin to 0.0.9

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
this is not a full rgen based on the template, as the diff was quite large and I didn't have the time to analyze it

**Comment by evgeni** [comment]
@ekohl the repoclosure seems related to things you removed:

```

[2019-11-21T09:50:58.015Z]     package: tfm-rubygem-foreman_custom_parameters-doc-0.0.2-6.fm1_20.el7.noarch from el7-foreman-plugins-nightly

[2019-11-21T09:50:58.015Z]       unresolved deps:

[2019-11-21T09:50:58.015Z]          tfm-rubygem-foreman_custom_parameters = 0:0.0.2-6.fm1_20.el7
```

**Comment by ekohl** [comment]
[test rpm]

**Comment by evgeni** [comment]
@ekohl updated

**Pull request merged**
