### PR TITLE
Update katello-selinux to 4.0.1

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by evgeni** [comment]
```
katello.te:79:ERROR 'unknown type systemd_unit_file_t' at token ';' on line 3729:
allow foreman_rails_t systemd_unit_file_t:dir search;
```

I guess there is a `require` missing somewhere

**Comment by ekohl** [comment]
I opened https://github.com/Katello/katello-selinux/pull/35 so that next time we'll at least know it compiles.

**Comment by lzap** [comment]
Yeah sorry!

**Comment by lzap** [comment]
Fix here: https://github.com/Katello/katello-selinux/pull/36

**Comment by evgeni** [comment]
@ehelms should this be updated to 4.0.2 (which needs to be released) with the fixes included?

**Comment by ehelms** [comment]
Replaced by https://github.com/theforeman/foreman-packaging/pull/6831

**Pull request closed without merging**
