### PR TITLE
Update rubygem-foreman_abrt to 0.0.6

### PR DESCRIPTION
**Pull request by mmilata**
rhel6+scl: http://koji.katello.org/koji/taskinfo?taskID=210752
f19: http://koji.katello.org/koji/taskinfo?taskID=210754

Please build only for nightly as this version requires foreman-1.8 API.

### CODE REVIEW

**Comment by domcleal** [comment]
[test]

**Comment by domcleal** [comment]
Thanks @mmilata, building now to nightlies.

**Comment by mmilata** [comment]
Hm, is the builder slow today or am I looking in the wrong place? The plugin's not in http://yum.theforeman.org/plugins/nightly/el6/x86_64/ yet.

**Comment by domcleal** [comment]
@mmilata I appear to have tagged it, but not build it.  Sorry, trying again now.

**Comment by mmilata** [comment]
It's built now. Thank you!

**Pull request merged**
