### PR TITLE
Bump changelog to 1.23.0 to match VERSION

### PR DESCRIPTION
**Pull request by evgeni**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.21
* [ ] 1.20

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by evgeni** [comment]
[test deb]

**Comment by evgeni** [comment]
[test]

**Comment by evgeni** [comment]
[test packaging]

**Comment by evgeni** [comment]
branching is done now :)

**Comment by evgeni** [comment]
@ekohl @ehelms @mmoll @tbrisker this fails to build because `*-develop-release` jobs fail because packaging is at 1.22 when they try to build, and thus there are no 1.23 artifacts yet. kinda a deadlock. do we need separate `*-develop-source-release` jobs for installer, proxy, etc?

**Comment by mmoll** [comment]
Will merge for DEB now, as it will be needed for now anyway...

**Comment by mmoll** [comment]
merged, спасибо Женя!

**Pull request merged**
