### PR TITLE
Added hammer_cli_foreman_admin (RPM)

### PR DESCRIPTION
**Pull request by lzap**
Do we need Debian patch or is this also automatic?

### CODE REVIEW

**Comment by mmoll** [comment]
A Debian PR would be needed also, you can use gem2deb on a Debian system and have a look at the other hammer plugins in deb/devlop to see, what to adjust, or just shout here an I'll do it. ;)

**Comment by lzap** [comment]
Oh the package was missing locales, added and amended. Well if you could do the Debian package for me it would be big help @mmoll !

**Comment by lzap** [comment]
Huh forgot to push the gem, [test]

**Comment by lzap** [comment]
Solved few issues with config file and bumped to the final 0.0.4. Tests should be finally green now.

**Comment by lzap** [comment]
Looks like rubygems.org were slow to update. [test]

```
07:37:28 addurl rubygem-hammer_cli_foreman_admin/hammer_cli_foreman_admin-0.0.4.gem 
07:37:29   failed to verify url: http://rubygems.org/gems/hammer_cli_foreman_admin-0.0.4.gem
```

**Comment by domcleal** [comment]
Merged and building for nightlies, thanks @lzap.

**Pull request merged**
