### PR TITLE
[WIP] Update rubygem-pulpcore_client to 3.4.0

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
Do not merge yet, i needed an rpm for testing :)

**Comment by snecklifter** [comment]
@jlsherrill Am currently running nightlies and need this to resolve broken docker repos, happy to test also if it helps

**Comment by snecklifter** [comment]
@jlsherrill anywhere I can grab a 3.4 test rpm from ?

**Comment by evgeni** [comment]
closing in favor of #5366

**Pull request closed without merging**
