### PR TITLE
Add rubygem-journald-logger package

### PR DESCRIPTION
**Pull request by lzap**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly

The second one.

---

### CODE REVIEW

**Comment by lzap** [comment]
I just pushed missing tags [test].

**Comment by lzap** [comment]
Rebased.

**Comment by lzap** [comment]
Rebased.

**Comment by ekohl** [comment]
I fixed the conflicts in the Github UI since they were trivial anyway. Thanks!

**Comment by lzap** [comment]
Thanks a bunch!

**Pull request merged**
