### PR TITLE
Update rubygem-foreman_fog_proxmox to 0.13.3 (#6462)

### PR DESCRIPTION
**Pull request by evgeni**
(cherry picked from commit 776d4240aab3b5f813e980539730bb6450212f0d)

### CODE REVIEW

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
@tristanrobert based on your debian PR, I *assume* you want 0.13.3 also in 2.4 RPM, right?

Wanted to see if it fails similarly to Debian…

**Comment by evgeni** [comment]
Which it does, interesting.

**Comment by evgeni** [comment]
repoclosure expected, I just tagged that build in (it was merged, but not tagged before)

**Review by tristanrobert — APPROVED** [review]

**Comment by tristanrobert** [comment]
> unresolved deps:
[2021-03-25T14:03:22.125Z]         tfm-rubygem(fog-proxmox) >= 0.14

It says rubygem-fog-proxmox 0.14.0 is missing in rpm/2.4 but it is not.

**Comment by evgeni** [comment]
> It says rubygem-fog-proxmox 0.14.0 is missing in rpm/2.4 but it is not.

it's missing from the *published* repo, and *that* is correct, no need to worry here.

**Comment by evgeni** [comment]
@tristanrobert FWIW, I excluded the apipie cache folder from the build, as it seems 2.4 and 2.5(nightly) build stuff slightly differently.

the plugin itself doesn't really have an API, right? it just hooks into the regular compute resource API Foreman already has

**Comment by tristanrobert** [comment]
> @tristanrobert FWIW, I excluded the apipie cache folder from the build, as it seems 2.4 and 2.5(nightly) build stuff slightly differently.
> 
> the plugin itself doesn't really have an API, right? it just hooks into the regular compute resource API Foreman already has

Indeed, I have an API to have ajax calls in my forms like storages, isos, etc

**Pull request merged**
