### PR TITLE
rubygem-bigdecimal is required to start a foreman-proxy

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
How did you reproduce this? I wonder if it's also something that belongs in the gemspec/gemfile in the repo itself.

**Comment by sbernhard** [comment]
We tested a lot on EL8 operating systems and only recognized this issue on Oracle 8. 
On Rocky 8, rubygem-bigdecimal is installed - but no package requires it (--whatrequires) which is very strange for me.

After some tests on Oracle 8 proxy I found out, that smart-proxy-dynflow is the package on this system which prevents the proxy to be started. So, smart-proxy-dynflow does really require the bigdecimal rubygem. My thought is, that bigdecimal is used often and I'm pretty sure, that another smart proxy plugin requires bigdecimal, too. As bigdecimal isn't a very big package I think it's better to install it on every smart proxy - better than to have it in multiple smart proxy plugin and forgetting it on certain plugins...

activesupport and acticemodel both have a 'require bigdecimal', too.

**Comment by ekohl** [comment]
At least on CentOS Stream 8 it's a weak dependency:
```console
# rpm -q --whatrecommends 'rubygem(bigdecimal)'
ruby-2.7.6-138.module_el8.6.0+1192+2a73603d.x86_64
```

Is the host using `install_weak_deps=False` in the DNF config? You may find it in `/etc/dnf/dnf.conf`, but perhaps it's somewhere else.

**Comment by sbernhard** [comment]
> At least on CentOS Stream 8 it's a weak dependency:
> 
> ```
> # rpm -q --whatrecommends 'rubygem(bigdecimal)'
> ruby-2.7.6-138.module_el8.6.0+1192+2a73603d.x86_64
> ```
> 
> Is the host using `install_weak_deps=False` in the DNF config? You may find it in `/etc/dnf/dnf.conf`, but perhaps it's somewhere else.

Make sense. Maybe it's false on Oracle. 
But, actually it's not a weak dep, it needs to be a hard one because otherwise proxy doesn't start.

**Review by ekohl — CHANGES_REQUESTED** [review]
IMHO it should be as close as the actual package as possible. Putting it on the Smart Proxy is wrong, because it works perfectly fine without it. On my system I have foreman-proxy installed, but rubygem-bigdecimal isn't so this is the wrong place.

I do wonder where it really is because I don't see bigdecimal in `smart_proxy_dynflow`. Could you provide a stack trace?

> activesupport and acticemodel both have a 'require bigdecimal', too.

I too have noticed that Foreman does have it implicitly, but never traced it down. Perhaps some upstream PR we should submit.

**Comment by sbernhard** [comment]
```
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]: /usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext/output.rb:13:in `strict_err': Gem loading error: cannot load such file -- bigdecimal (RuntimeError)
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext/runtime.rb:46:in `rescue in block in system_require'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext/runtime.rb:39:in `block in system_require'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext/runtime.rb:37:in `each'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext/runtime.rb:37:in `system_require'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext.rb:19:in `block in system_require'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext.rb:14:in `each'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext.rb:14:in `system_require'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/foreman-proxy/lib/bundler_helper.rb:23:in `require_groups'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/foreman-proxy/lib/smart_proxy_main.rb:31:in `<top (required)>'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/foreman-proxy/bin/smart-proxy:5:in `<main>'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]: /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- bigdecimal (LoadError)
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/sequel-5.42.0/lib/sequel/core.rb:3:in `block in <top (required)>'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/sequel-5.42.0/lib/sequel/core.rb:3:in `each'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/sequel-5.42.0/lib/sequel/core.rb:3:in `<top (required)>'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/sequel-5.42.0/lib/sequel/model.rb:3:in `require_relative'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/sequel-5.42.0/lib/sequel/model.rb:3:in `<top (required)>'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/sequel-5.42.0/lib/sequel.rb:3:in `require_relative'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/sequel-5.42.0/lib/sequel.rb:3:in `<top (required)>'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/persistence_adapters/sequel.rb:2:in `<top (required)>'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/persistence_adapters.rb:5:in `<module:PersistenceAdapters>'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/persistence_adapters.rb:3:in `<module:Dynflow>'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/persistence_adapters.rb:2:in `<top (required)>'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/dynflow-1.6.4/lib/dynflow/persistence.rb:2:in `<top (required)>'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/dynflow-1.6.4/lib/dynflow.rb:56:in `<module:Dynflow>'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/dynflow-1.6.4/lib/dynflow.rb:20:in `<top (required)>'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/smart_proxy_dynflow-0.6.2/lib/smart_proxy_dynflow.rb:1:in `<top (required)>'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:159:in `require'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:159:in `rescue in require'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:147:in `require'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext/runtime.rb:41:in `block in system_require'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext/runtime.rb:37:in `each'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext/runtime.rb:37:in `system_require'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext.rb:19:in `block in system_require'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext.rb:14:in `each'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext.rb:14:in `system_require'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/foreman-proxy/lib/bundler_helper.rb:23:in `require_groups'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/foreman-proxy/lib/smart_proxy_main.rb:31:in `<top (required)>'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/foreman-proxy/bin/smart-proxy:5:in `<main>'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]: /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- smart_proxy_dynflow (LoadError)
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext/runtime.rb:41:in `block in system_require'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext/runtime.rb:37:in `each'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext/runtime.rb:37:in `system_require'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext.rb:19:in `block in system_require'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext.rb:14:in `each'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/gems/gems/bundler_ext-0.4.1/lib/bundler_ext.rb:14:in `system_require'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/foreman-proxy/lib/bundler_helper.rb:23:in `require_groups'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/foreman-proxy/lib/smart_proxy_main.rb:31:in `<top (required)>'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require'
Mär 09 12:25:34 bender-marvin.nr.eight smart-proxy[62416]:         from /usr/share/foreman-proxy/bin/smart-proxy:5:in `<main>'
```
(its from smart proxy for foreman 3.1)
In the end, its because of sequel. 

But if you grep for bigdecimal, its used in other libs, too:
json-2.3.0/lib/json/add/bigdecimal.rb:defined?(::BigDecimal) or require 'bigdecimal'
psych-3.1.0/lib/psych/visitors/to_ruby.rb:          require 'bigdecimal' unless defined? BigDecimal

My personal perspective is , rubygem-bigdecimal is about 100K size and it doesn't have other requirements. Before we fall in other issues related to bigdecimal, I would put it as a dependency on a higher live - like foreman-proxy itself.

**Comment by ekohl** [comment]
> In the end, its because of sequel.

Then I think we should submit a PR to sequel. Mostly because that also fixes it for non-RPM installations.

> json-2.3.0/lib/json/add/bigdecimal.rb:defined?(::BigDecimal) or require 'bigdecimal'

Yet I don't see where it explicitly where that file itself is included. I'm guessing it's optional, but I didn't dive into the JSON library itself.

> psych-3.1.0/lib/psych/visitors/to_ruby.rb: require 'bigdecimal' unless defined? BigDecimal

Note that this is only if the class is explicitly a BigDecimal object:
```ruby
when '!ruby/object:BigDecimal'
  require 'bigdecimal' unless defined? BigDecimal
  class_loader.big_decimal._load o.value
```

I think we rarely, if ever, explicitly serialize as a specific class.

**Pull request closed without merging**
