### PR TITLE
Release foreman-tasks 0.7.10 (DEB)

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by mmoll** [comment]
which Foreman versions is this compatible with?

**Comment by stbenjam** [comment]
Goes with 1.10 and develop, sorry forgot to say

**Comment by mmoll** [comment]
concurrent-ruby has to go from gem.list for develop, as the new sprockets (came in with patternfly) already depends on it, thus pulling it into the Debian package "foreman".

**Comment by stbenjam** [comment]
Updated

**Comment by mmoll** [comment]
this has to wait until the very newest foreman packages arrived on deb.tf.org (as opposed to stagingdeb)

**Comment by domcleal** [comment]
[test] as nightly repos are updating right now.

**Comment by domcleal** [comment]
Thanks @stbenjam, merged as 894bbae and building now.  Cherry picking to 1.10 too.

**Comment by domcleal** [comment]
Cherry picked as 3a48c7d to deb/1.10 and building now.

> concurrent-ruby has to go from gem.list for develop, as the new sprockets (came in with patternfly) already depends on it, thus pulling it into the Debian package "foreman".

I filed http://projects.theforeman.org/issues/13061 too, as the tight dependency on dynflow will cause issues on the next concurrent-ruby update, as the version in the "foreman" package will exceed the dependency in dynflow.

**Comment by domcleal** [comment]
Per https://github.com/theforeman/foreman-packaging/pull/955#issuecomment-169950154, the `rules` file should have been updated to include asset precompilation too - we'll need a new PR.

**Comment by mmoll** [comment]
for 1.10 concurrent-ruby is still needed, sorry for not mentioning that :crying_cat_face:

**Comment by domcleal** [comment]
@mmoll np, I removed that change when I cherry picked.

**Comment by mmoll** [comment]
oh, perfect :dizzy:

**Pull request closed without merging**
