### PR TITLE
Update rubygem-logging to 2.0.0

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
Figured I would go ahead and get this open for review. I am unfamiliar with debian packaging, but willing to attempt it to update this there as well.

**Comment by domcleal** [comment]
We can't do this, since our non-SCL version is used for Hammer and so needs 1.8 compatibility.

**Comment by domcleal** [comment]
Oh, and Debian packages for Foreman use bundler so a similar update wouldn't be required for Foreman core, they'd get the best version that bundler lets us use.

**Comment by ehelms** [comment]
Bummer,

**Pull request closed without merging**
