### PR TITLE
add foreman_vault plugin

### PR DESCRIPTION
**Pull request by timogoebel**
Please build for

* [x] Nightly
* [x] 1.21
* [x] 1.20

### CODE REVIEW

**Comment by timogoebel** [comment]
Updated.

**Comment by dgoetz** [comment]
Looks good now, but still requires https://github.com/theforeman/foreman-packaging/pull/3584 to be merged for 1.20.

**Comment by ekohl** [comment]
This now needs a rebase

**Comment by timogoebel** [comment]
@ekohl: Rebased.

**Pull request merged**
