### PR TITLE
Bump nodejs-patternfly to 3.58.0

### PR DESCRIPTION
**Pull request by xprazak2**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [ ] 1.20
* [ ] 1.19
* [ ] 1.18

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ekohl** [comment]
Like patternfly-react this was also unbundled to prevent some build issues

**Comment by xprazak2** [comment]
All green now.

**Comment by ekohl** [comment]
Added a small commit to fix the summary, other than that :+1:. Needs to be squashed on merge.

**Comment by mmoll** [comment]
core change went in

**Pull request merged**
