### PR TITLE
bump pulp-container to 1.4.2

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
2.1 backport

**Comment by tbrisker** [comment]
Looks like a couple of deps are missing in 2.1:
```
[2020-07-17T12:54:44.027Z]     package: python3-pulp-certguard-0.1.0-0.1.rc4.el8.noarch from el8-katello-pulpcore-3.16
[2020-07-17T12:54:44.027Z]       unresolved deps:
[2020-07-17T12:54:44.027Z]         python3-pyopenssl
[2020-07-17T12:54:44.027Z]     package: python3-pulp-container-1.4.2-1.el8.noarch from downloaded_rpms
[2020-07-17T12:54:44.027Z]       unresolved deps:
[2020-07-17T12:54:44.027Z]         python3-pulpcore >= 3.4
```

**Comment by jlsherrill** [comment]
@evgeni any ideas?  missed cherry pick?

**Comment by evgeni** [comment]
Certguard should be rc5. More on Monday if you send me a mail

**Comment by jlsherrill** [comment]
[test rpm]

**Comment by jlsherrill** [comment]
[test rpm]

**Comment by jlsherrill** [comment]
[test rpm]

**Comment by jlsherrill** [comment]
[test rpm]

404 from centos

**Comment by jlsherrill** [comment]
[test rpm]

**Comment by jlsherrill** [comment]
[test rpm]

**Pull request merged**
