### PR TITLE
Update rubygem-fog-ovirt to 2.0.0

### PR DESCRIPTION
**Pull request by shiramax**

### CODE REVIEW

**Comment by tbrisker** [comment]
[test rpm]

**Comment by evgeni** [comment]
Looks like it now rquires  ovirt-engine-sdk >= 4.3.1 , but this wasn't bumped in the RPM spec and not packaged.

**Comment by shiramax** [comment]
@evgeni in ovirt gemspec it does rquires ovirt-engine-sdk >= 4.3.1: 
https://github.com/fog/fog-ovirt/blob/master/fog-ovirt.gemspec#L27
what do I need to do in order for it to package properly?

**Comment by evgeni** [comment]
@shiramax you'd have to update the following line (seems this package isn't using the latest template, or bump_rpm would have done this for you):
https://github.com/theforeman/foreman-packaging/blob/3c5291579933db28090bc0953822751c15375dde/packages/foreman/rubygem-fog-ovirt/rubygem-fog-ovirt.spec#L22

And package the newer SDK :)

**Comment by evgeni** [comment]
@shiramax I took the liberty to regenerate the package based on recent template, which should make it easier to update it in the future, the result is in: https://github.com/theforeman/foreman-packaging/pull/6156

**Comment by shiramax** [comment]
thanks @evgeni, I will close this one.

**Pull request closed without merging**
