### PR TITLE
added foreman_datacenter

### PR DESCRIPTION
**Pull request by Zenya**

### CODE REVIEW

**Comment by Zenya** [comment]
@mmoll hi
can you please help me with releasing rpm package?
I got some errors and can't find out why it can't be builded

**Comment by mmoll** [comment]
I'm only doing DEB here...

**Comment by dgoetz** [comment]
The package tries to include apipie cache which seems to be not available. If this is correct because of the plugin not having an api, you can remove `%{foreman_apipie_cache_foreman}` and `%{foreman_apipie_cache_plugin}` from the spec file.

**Comment by zjhuntin** [comment]
[test rpm]

**Comment by evgeni** [comment]
[test rpm]

**Comment by evgeni** [comment]
Interesting, your plugin *does* have an API, but it only writes to `/usr/share/foreman/public/apipie-cache/plugin/foreman_datacenter` not `%{gem_instdir}/public/apipie-cache/plugin/foreman_datacenter`. I am not sure if that will work, but we can try :)

so instead of removing both apipie lines, you need to only have `%{foreman_apipie_cache_foreman}` in the `%files` section.

**Comment by evgeni** [comment]
oh, and I don't see a 2.0 release on https://github.com/theforeman/foreman_datacenter, and https://github.com/theforeman/foreman_datacenter/pull/35 ;)

**Comment by evgeni** [comment]
obsoleted by #5116

**Pull request closed without merging**
