### PR TITLE
Update rubygem-redhat_access to 2.1.5

### PR DESCRIPTION
**Pull request by ares**
For plugin updates, please indicate which repos this should be built into:

* [x] Nightly
* [x] 1.18
* [ ] 1.17
* [ ] 1.16

See Foreman's [plugin maintainer documentation](https://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Release-strategies) for more information.

---

### CODE REVIEW

**Comment by ekohl** [comment]
Build fails with `Sprockets::FileNotFound: couldn't find file 'angular-rails-templates' with type 'application/javascript'` and I'm not sure that's a packaging issue.

**Comment by ares** [comment]
@lphiri were there some dependency changes within this release?

**Comment by ares** [comment]
looking at the [commit](https://github.com/redhataccess/foreman-plugin/commit/57ec3bcaeb5775ce54a0b4ba3a94f6857a0d7cf8), it seems insights-frontend was bumped, perhaps some dependency of this dependency is missing?

**Comment by lphiri** [comment]
@ares there were no dependency changes in this PR.(in fact despite the large diff in the js file, the effective diff is a single line of javascript)
The gemspec was not touched and this line has been there from the beginning:
 s.add_dependency "angular-rails-templates", ">=0.0.4"
I believe this was required in the old katello build system. I have not kept up with the webpack changes and don't know if those are at play here.

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ehelms** [comment]
[test rpm]

**Comment by ares** [comment]
this now looks green

**Comment by dLobatog** [comment]
Both http://koji.katello.org/koji/taskinfo?taskID=104795 and http://koji.katello.org/koji/taskinfo?taskID=105165 are green so I'm going to go with merging

**Comment by dLobatog** [comment]
nightly - http://koji.katello.org/koji/taskinfo?taskID=105291
1.18 - http://koji.katello.org/koji/taskinfo?taskID=105293

@ares  Why is this under koji-katello in tito.props? Does this plugin not work without Katello?

**Pull request merged**
