### PR TITLE
Add libyaml-dev to Build-Depends for psych

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
Needed for https://github.com/theforeman/foreman/commit/fe77720302a6e81ff621ef071486ec123c9f74f7, bookworm is the only release using 3.1

**Review by ekohl — APPROVED** [review]
I thought it'd use the already included package :(

**Comment by evgeni** [comment]
> I thought it'd use the already included package :(

You mean `ruby-psych`?

**Comment by evgeni** [comment]
Well, today nothing pulls that in during build.
Also, I am not sure how I feel about mixing vendored and non-vendored things here.

**Comment by evgeni** [comment]
Or do you mean the "default" gem in `libruby3.1`?
`/usr/lib/ruby/gems/3.1.0/specifications/default/psych-4.0.3.gemspec`

:thinking:

**Comment by evgeni** [comment]
I'll merge this to unblock builds, we can still revisit afterwards.

**Comment by ekohl** [comment]
> Or do you mean the "default" gem in `libruby3.1`?

Yes, that's the one I meant. I suspect bundler wants to get the latest & greatest and upgrades it.

**Pull request merged**
