### PR TITLE
Bump Hammer Katello to version 0.24.premaster

### PR DESCRIPTION
**Pull request by chris1984**

### CODE REVIEW

**Comment by chris1984** [comment]
@jturel here is the hammer pr for nightly, will make another pr for the 2.2 branch

**Comment by jturel** [comment]
Looking at the changelog gives me the impression that we need to bump this to 0.24 and make that the new version here based on hammer-cli-katello-master, with a separate change for rpm/2.2 to bump the 0.23 version?

**Comment by chris1984** [comment]
> Looking at the changelog gives me the impression that we need to bump this to 0.24 and make that the new version here based on hammer-cli-katello-master, with a separate change for rpm/2.2 to bump the 0.23 version?

ok will update, pinged you on the 2.2 one

**Comment by chris1984** [comment]
@jturel updated

**Comment by chris1984** [comment]
@evgeni

**Comment by chris1984** [comment]
@tbrisker how does this look?

**Review by tbrisker — APPROVED** [review]
Thanks @chris1984 !

**Pull request merged**
